# Generated by Django 3.2 on 2022-04-22 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AuthBillet', '0003_tibilletuser_user_parent_pk'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminalPairingToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateField(auto_now_add=True)),
                ('token', models.SmallIntegerField(default=910337, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthBillet.termuser')),
            ],
        ),
    ]
