# Generated by Django 3.2 on 2022-04-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthBillet', '0004_terminalpairingtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='tibilletuser',
            name='local_ip_sended',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tibilletuser',
            name='mac_adress_sended',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='tibilletuser',
            name='terminal_uuid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='terminalpairingtoken',
            name='token',
            field=models.PositiveIntegerField(),
        ),
    ]
