# Generated by Django 3.2 on 2022-04-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthBillet', '0006_terminalpairingtoken_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminalpairingtoken',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
