# Generated by Django 3.2 on 2022-05-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthBillet', '0008_alter_terminalpairingtoken_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tibilletuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
