# Generated by Django 4.2.10 on 2024-02-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthBillet', '0009_alter_tibilletuser_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='RsaKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_pem', models.CharField(editable=False, max_length=2048)),
                ('public_pem', models.CharField(editable=False, max_length=512)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
