# Generated by Django 4.2.10 on 2024-02-15 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AuthBillet', '0011_tibilletuser_rsa_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tibilletuser',
            name='rsa_key',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='AuthBillet.rsakey'),
        ),
    ]
