# Generated by Django 4.2.10 on 2024-04-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthBillet', '0013_wallet_tibilletuser_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='tibilletuser',
            name='last_know_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tibilletuser',
            name='last_know_user_agent',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
