# Generated by Django 4.2.11 on 2024-05-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthBillet', '0014_tibilletuser_last_know_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tibilletuser',
            name='email_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tibilletuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
