# Generated by Django 4.2 on 2024-08-25 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthBillet', '0015_tibilletuser_email_valid_alter_tibilletuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tibilletuser',
            name='can_create_tenant',
        ),
    ]
