# Generated by Django 4.2.17 on 2025-02-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthBillet', '0017_alter_tibilletuser_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tibilletuser',
            name='email_error',
            field=models.BooleanField(default=False, help_text="L'email de confirmation a été distribué ?"),
        ),
        migrations.AlterField(
            model_name='tibilletuser',
            name='email_valid',
            field=models.BooleanField(default=False, help_text="L'email de confirmation OK ?"),
        ),
    ]
