# Generated by Django 4.2.17 on 2025-03-13 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0003_alter_client_categorie'),
        ('AuthBillet', '0018_alter_tibilletuser_email_error_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='humanuser',
            options={'verbose_name': 'User'},
        ),
        migrations.AlterModelOptions(
            name='superhumanuser',
            options={'verbose_name': 'Administrator'},
        ),
        migrations.AlterModelOptions(
            name='termuser',
            options={'verbose_name': 'Terminal', 'verbose_name_plural': 'Terminals'},
        ),
        migrations.AlterField(
            model_name='tibilletuser',
            name='accept_newsletter',
            field=models.BooleanField(default=True, verbose_name='I want to receive newsletters'),
        ),
        migrations.AlterField(
            model_name='tibilletuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='tibilletuser',
            name='client_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_principal', to='Customers.client', verbose_name='Registered from'),
        ),
        migrations.AlterField(
            model_name='tibilletuser',
            name='email_error',
            field=models.BooleanField(default=False, help_text='Confirmation email delivery failed'),
        ),
        migrations.AlterField(
            model_name='tibilletuser',
            name='email_valid',
            field=models.BooleanField(default=False, help_text='Email confirmed'),
        ),
        migrations.AlterField(
            model_name='tibilletuser',
            name='espece',
            field=models.CharField(choices=[('TE', 'Terminal'), ('AN', 'Android'), ('HU', 'Human')], default='HU', max_length=2),
        ),
        migrations.AlterField(
            model_name='tibilletuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='tibilletuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='tibilletuser',
            name='last_see',
            field=models.DateTimeField(auto_now=True, verbose_name='Last login'),
        ),
        migrations.AlterField(
            model_name='tibilletuser',
            name='offre',
            field=models.CharField(choices=[('PU', 'Public'), ('FR', 'Free'), ('PR', 'Premium'), ('EN', 'Entreprise'), ('CU', 'Custom')], default='PU', max_length=2),
        ),
        migrations.AlterField(
            model_name='tibilletuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='tibilletuser',
            name='postal_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Zip code'),
        ),
        migrations.AlterField(
            model_name='tibilletuser',
            name='user_parent_pk',
            field=models.UUIDField(blank=True, null=True, verbose_name='Parent user'),
        ),
    ]
