# Generated by Django 4.2.17 on 2025-04-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthBillet', '0019_alter_humanuser_options_alter_superhumanuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tibilletuser',
            name='email_error',
            field=models.BooleanField(default=False, help_text='Confirmation email delivery failed if true'),
        ),
    ]
