# Generated by Django 4.2.21 on 2025-06-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthBillet', '0020_alter_tibilletuser_email_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tibilletuser',
            name='offre',
            field=models.CharField(choices=[('PU', 'Public'), ('FR', 'Free price'), ('PR', 'Premium'), ('EN', 'Entreprise'), ('CU', 'Custom')], default='PU', max_length=2),
        ),
    ]
