# Generated by Django 4.2.24 on 2025-09-24 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0004_alter_client_categorie_alter_client_on_trial'),
        ('AuthBillet', '0021_alter_tibilletuser_offre'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='Customers.client'),
        ),
    ]
