# Generated by Django 4.2.24 on 2025-12-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0004_alter_client_categorie_alter_client_on_trial'),
        ('AuthBillet', '0022_wallet_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='tibilletuser',
            name='create_event',
            field=models.ManyToManyField(help_text='Can create event on agenda page', related_name='create_event', to='Customers.client', verbose_name='Can create event'),
        ),
        migrations.AddField(
            model_name='tibilletuser',
            name='initiate_payment',
            field=models.ManyToManyField(help_text='Can initiate payments on behalf of the location from My Account area', related_name='initiate_payment', to='Customers.client', verbose_name='Can initiate payments'),
        ),
        migrations.AddField(
            model_name='tibilletuser',
            name='manage_crowd',
            field=models.ManyToManyField(help_text='Can manage crowds initiative', related_name='manage_crowd', to='Customers.client', verbose_name='Can manage crodws'),
        ),
    ]
