# Generated by Django 4.2.28 on 2026-02-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthBillet', '0023_tibilletuser_create_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='name',
            field=models.CharField(blank=True, help_text='Nom du wallet (ex: nom du lieu, nom du user)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='public_pem',
            field=models.TextField(blank=True, help_text='Cle publique PEM pour audit cryptographique', null=True),
        ),
    ]
