# Generated by Django 4.2.30 on 2026-07-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthBillet', '0023_tibilletuser_create_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tibilletuser',
            name='terminal_role',
            field=models.CharField(blank=True, choices=[('LB', 'LaBoutik POS'), ('TI', 'Connected tap'), ('KI', 'Kiosk / self-service')], help_text='Only set for espece=TE. Drives permission checks.', max_length=2, null=True, verbose_name='Terminal role'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='name',
            field=models.CharField(blank=True, help_text='Nom du wallet (ex: nom du lieu, nom du user)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='public_pem',
            field=models.TextField(blank=True, help_text='Cle publique PEM pour audit cryptographique', null=True),
        ),
    ]
