# Generated by Django 4.2.28 on 2026-03-06 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthBillet', '0024_wallet_name_wallet_public_pem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='name',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='public_pem',
        ),
    ]
