# Generated by Django 4.2.30 on 2026-04-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthBillet', '0024_wallet_name_wallet_public_pem'),
    ]

    operations = [
        migrations.AddField(
            model_name='tibilletuser',
            name='terminal_role',
            field=models.CharField(blank=True, choices=[('LB', 'LaBoutik POS'), ('TI', 'Connected tap'), ('KI', 'Kiosk / self-service')], help_text='Only set for espece=TE. Drives permission checks.', max_length=2, null=True, verbose_name='Terminal role'),
        ),
    ]
