# Generated by Django 4.2.30 on 2026-09-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthBillet', '0024_tibilletuser_terminal_role_wallet_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tibilletuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Adresse e-mail'),
        ),
        migrations.AlterField(
            model_name='tibilletuser',
            name='email_valid',
            field=models.BooleanField(default=False, help_text='Email confirmed', verbose_name='Adresse e-mail confirmée'),
        ),
    ]
