# Generated by Django 3.2 on 2022-04-16 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BaseBillet', '0002_alter_ticket_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='user_commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
    ]
