# Generated by Django 3.2 on 2022-04-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0003_alter_reservation_user_commande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignearticle',
            name='status',
            field=models.CharField(choices=[('C', 'Annulée'), ('O', 'Non envoyé en paiement'), ('U', 'Non payée'), ('F', 'Reservation gratuite'), ('P', 'Payée'), ('V', 'Validée par serveur cashless')], default='O', max_length=3, verbose_name='Status de ligne article'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('C', 'Annulée'), ('R', 'Crée'), ('U', 'Non payée'), ('F', 'Mail non vérifié'), ('P', 'Payée'), ('PE', 'Payée mais mail non valide'), ('PN', 'Payée mais mail non envoyé'), ('V', 'Validée')], default='R', max_length=3, verbose_name='Status de la réservation'),
        ),
    ]
