# Generated by Django 3.2 on 2022-05-05 11:20

from django.db import migrations
import stdimage.models
import stdimage.validators


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0007_alter_configuration_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='img',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='images/', validators=[stdimage.validators.MinSizeValidator(720, 720)], verbose_name='Background'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='logo',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='images/', validators=[stdimage.validators.MaxSizeValidator(1920, 1920)], verbose_name='Logo'),
        ),
    ]
