# Generated by Django 3.2 on 2022-05-31 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0010_auto_20220531_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', to='BaseBillet.price'),
        ),
    ]
