# Generated by Django 3.2 on 2022-06-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0013_auto_20220602_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='terms_and_conditions_document',
            field=models.URLField(blank=True, null=True),
        ),
    ]
