# Generated by Django 3.2 on 2022-06-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0014_product_terms_and_conditions_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='subscription_type',
            field=models.CharField(choices=[('N', 'Non applicable'), ('Y', '365 Jours'), ('M', '30 Jours'), ('C', 'Fin decembre.')], default='N', max_length=1, verbose_name='Taux TVA'),
        ),
    ]
