# Generated by Django 3.2 on 2022-06-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0016_alter_membership_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='send_to_cashless',
            field=models.BooleanField(default=False),
        ),
    ]
