# Generated by Django 3.2 on 2022-06-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0017_product_send_to_cashless'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='jauge_max',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='Jauge maximale'),
        ),
        migrations.AlterField(
            model_name='price',
            name='subscription_type',
            field=models.CharField(choices=[('N', 'Non applicable'), ('Y', '365 Jours'), ('M', '30 Jours'), ('C', 'Civile')], default='N', max_length=1, verbose_name="durée d'abonnement"),
        ),
    ]
