# Generated by Django 3.2 on 2022-06-24 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0018_auto_20220608_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name': 'Adhésion', 'verbose_name_plural': 'Adhésions'},
        ),
        migrations.AddField(
            model_name='paiement_stripe',
            name='customer_stripe',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
