# Generated by Django 3.2 on 2022-06-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0019_auto_20220624_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='stripe_id_subscription',
            field=models.CharField(blank=True, max_length=28, null=True),
        ),
    ]
