# Generated by Django 3.2 on 2022-06-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0022_paiement_stripe_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='last_stripe_invoice',
            field=models.CharField(blank=True, max_length=278, null=True),
        ),
    ]
