# Generated by Django 3.2 on 2022-06-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0023_membership_last_stripe_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('O', 'Paiement unique'), ('A', 'Paiement automatique sur stripe'), ('C', 'Annulée')], default='O', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='paiement_stripe',
            name='source',
            field=models.CharField(choices=[('Q', 'Depuis scan QR-Code'), ('B', 'Depuis billetterie'), ('I', 'Depuis invoice')], default='B', max_length=1, verbose_name='Source de la commande'),
        ),
        migrations.AlterField(
            model_name='paiement_stripe',
            name='source_traitement',
            field=models.CharField(choices=[('N', 'Pas de traitement en cours'), ('W', 'Depuis webhook stripe'), ('G', 'Depuis Get'), ('I', 'Depuis webhook invoice')], default='N', max_length=1, verbose_name='Source de la commande'),
        ),
    ]
