# Generated by Django 3.2 on 2022-08-10 08:45

from django.db import migrations, models
import stdimage.models
import stdimage.validators


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0024_auto_20220626_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='img',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='images/', validators=[stdimage.validators.MinSizeValidator(720, 135)], variations={'fhd': (1920, 1920), 'hdr': (720, 720), 'med': (480, 480), 'thumbnail': (150, 90)}, verbose_name='Background'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('O', 'Paiement unique'), ('A', 'Renouvellement automatique'), ('C', 'Annulée')], default='O', max_length=1, verbose_name='Status'),
        ),
    ]
