# Generated by Django 3.2 on 2022-08-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0025_auto_20220810_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
