# Generated by Django 3.2 on 2022-08-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0027_product_poids'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuration',
            options={'verbose_name': 'Paramètres', 'verbose_name_plural': 'Paramètres'},
        ),
        migrations.AlterModelOptions(
            name='paiement_stripe',
            options={'verbose_name': 'Paiement Stripe', 'verbose_name_plural': 'Paiements Stripe'},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ('prix',), 'verbose_name': 'Tarif', 'verbose_name_plural': 'Tarifs'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('poids',), 'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Réservation', 'verbose_name_plural': 'Réservations'},
        ),
        migrations.AlterField(
            model_name='price',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Précisez le nom du Tarif'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categorie_article',
            field=models.CharField(choices=[('N', 'Selectionnez une catégorie'), ('B', 'Billet'), ('P', "Pack d'objets"), ('R', 'Recharge cashless'), ('T', 'Vetement'), ('M', 'Merchandasing'), ('A', 'Adhésions et abonnements'), ('D', 'Don'), ('F', 'Reservation gratuite')], default='N', max_length=3, verbose_name="Type d'article"),
        ),
        migrations.AlterField(
            model_name='product',
            name='long_description',
            field=models.TextField(blank=True, null=True, verbose_name='Description longue'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=500, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='product',
            name='poids',
            field=models.PositiveSmallIntegerField(default=0, help_text="Ordre d'apparition du plus leger au plus lourd", verbose_name='Poids'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Description courte'),
        ),
    ]
