# Generated by Django 3.2 on 2022-09-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0029_remove_configuration_activer_billetterie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement_stripe',
            name='source_traitement',
            field=models.CharField(choices=[('N', 'Pas de traitement en cours'), ('W', 'Depuis webhook stripe'), ('G', 'Depuis Get'), ('I', 'Depuis webhook invoice')], default='N', max_length=1, verbose_name='Source du traitement'),
        ),
        migrations.AlterField(
            model_name='product',
            name='send_to_cashless',
            field=models.BooleanField(default=False, help_text='Article qui doit être envoyé pour une comptabilité au cashless. Ex : Adhésions', verbose_name='Envoyer au cashless'),
        ),
    ]
