# Generated by Django 3.2 on 2022-09-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0034_apikey_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='auth',
            field=models.CharField(choices=[('N', 'Aucun acces'), ('event', "Creation d'évènements")], default='N', max_length=20, verbose_name='Authorisation'),
        ),
    ]
