# Generated by Django 3.2 on 2022-10-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0036_remove_apikey_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='event',
            field=models.BooleanField(default=False, verbose_name="Creation d'évènements"),
        ),
        migrations.AddField(
            model_name='apikey',
            name='tenant',
            field=models.BooleanField(default=False, verbose_name='Creation de nouvelles instances'),
        ),
    ]
