# Generated by Django 3.2 on 2022-10-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0037_auto_20221017_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='product',
            field=models.BooleanField(default=False, verbose_name='Creation de produits'),
        ),
    ]
