# Generated by Django 3.2 on 2022-10-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0040_apikey_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='reservation',
            field=models.BooleanField(default=False, verbose_name='Lister les reservations'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='ticket',
            field=models.BooleanField(default=False, verbose_name='Lister et valider les billets'),
        ),
    ]
