# Generated by Django 3.2 on 2022-10-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0044_webhook_last_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='categorie',
            field=models.CharField(choices=[('LIV', 'Concert'), ('FES', 'Festival'), ('REU', 'Réunion'), ('CON', 'Conférence'), ('RES', 'Restauration')], default='LIV', max_length=3, verbose_name="Catégorie d'évènement"),
        ),
    ]
