# Generated by Django 3.2 on 2022-11-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0046_alter_product_categorie_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='stripe_connect_account',
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='stripe_connect_account_test',
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
    ]
