# Generated by Django 3.2 on 2022-11-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0047_auto_20221121_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='stripe_payouts_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
