# Generated by Django 3.2 on 2022-11-25 14:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rest_framework_api_key', '0005_auto_20220110_1102'),
        ('BaseBillet', '0048_configuration_stripe_payouts_enabled'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApiKey',
            new_name='ExternalApiKey',
        ),
    ]
