# Generated by Django 3.2 on 2022-11-25 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0050_alter_externalapikey_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externalapikey',
            options={},
        ),
        migrations.RemoveField(
            model_name='externalapikey',
            name='key',
        ),
    ]
