# Generated by Django 3.2 on 2022-11-25 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_api_key', '0005_auto_20220110_1102'),
        ('BaseBillet', '0051_auto_20221125_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalapikey',
            name='key',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_key', to='rest_framework_api_key.apikey'),
        ),
    ]
