# Generated by Django 3.2 on 2022-11-25 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0052_externalapikey_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externalapikey',
            options={'verbose_name': 'Api key', 'verbose_name_plural': 'Api keys'},
        ),
    ]
