# Generated by Django 3.2 on 2022-12-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0054_price_recurring_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='pricesold',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
