# Generated by Django 3.2 on 2022-12-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0055_auto_20221215_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricesold',
            name='gift',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
