# Generated by Django 3.2 on 2023-04-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0059_event_cashless'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='minimum_cashless_required',
            field=models.SmallIntegerField(default=0, verbose_name='Montant obligatoire minimum de la recharge cashless'),
        ),
    ]
