# Generated by Django 3.2 on 2023-04-11 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0061_configuration_federated_cashless'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='mollie_api_key',
        ),
    ]
