# Generated by Django 3.2 on 2023-04-27 07:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0062_remove_configuration_mollie_api_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Nom du tag')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='option_generale_checkbox',
            field=models.ManyToManyField(blank=True, related_name='produits_checkbox', to='BaseBillet.OptionGenerale'),
        ),
        migrations.AddField(
            model_name='product',
            name='option_generale_radio',
            field=models.ManyToManyField(blank=True, related_name='produits_radio', to='BaseBillet.OptionGenerale'),
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='produit_tags', to='BaseBillet.Tag'),
        ),
    ]
