# Generated by Django 3.2 on 2023-04-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0065_auto_20230427_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='optiongenerale',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
