# Generated by Django 3.2 on 2023-04-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0066_optiongenerale_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='option_generale_checkbox',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='option_generale_radio',
        ),
        migrations.AddField(
            model_name='membership',
            name='option_generale',
            field=models.ManyToManyField(blank=True, related_name='membership_options', to='BaseBillet.OptionGenerale'),
        ),
    ]
