# Generated by Django 3.2 on 2023-05-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0070_alter_configuration_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='events', to='BaseBillet.Tag'),
        ),
    ]
