# Generated by Django 3.2 on 2023-05-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0076_auto_20230525_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_per_user',
            field=models.PositiveSmallIntegerField(default=10, help_text='ex : Un même email peut réserver plusieurs billets.', verbose_name='Nombre de reservation maximum par utilisateur'),
        ),
        migrations.AlterField(
            model_name='event',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Publier'),
        ),
    ]
