# Generated by Django 3.2 on 2023-06-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0077_auto_20230525_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_facebook_url',
            new_name='url_external',
        ),
        migrations.AddField(
            model_name='event',
            name='is_external',
            field=models.BooleanField(default=False, help_text="Si l'évènement est géré par une autre billetterie ou un autre site de réservation. Ex : Un event Facebook", verbose_name='Billetterie/Reservation externe'),
        ),
    ]
