# Generated by Django 3.2 on 2023-08-22 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0078_auto_20230602_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nominative',
            field=models.BooleanField(default=True, help_text='Nom/Prenom obligatoire lors de la réservation.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='send_to_cashless',
            field=models.BooleanField(default=False, help_text='Produit checké par le serveur cashless.', verbose_name='Envoyer au cashless'),
        ),
    ]
