# Generated by Django 3.2 on 2023-08-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0079_auto_20230822_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsold',
            name='categorie_article',
            field=models.CharField(choices=[('N', 'Selectionnez une catégorie'), ('B', 'Billet'), ('P', "Pack d'objets"), ('R', 'Recharge cashless'), ('S', 'Recharge suspendue'), ('T', 'Vetement'), ('M', 'Merchandasing'), ('A', 'Adhésions associative'), ('B', 'Abonnement'), ('D', 'Don'), ('F', 'Reservation gratuite')], default='N', max_length=3, verbose_name='Type de produit'),
        ),
    ]
