# Generated by Django 3.2 on 2023-08-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0080_productsold_categorie_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='key_fedow',
            field=models.CharField(blank=True, max_length=41, null=True, verbose_name="Clé d'API du serveur fedow"),
        ),
        migrations.AddField(
            model_name='configuration',
            name='server_fedow',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Adresse du serveur fedow'),
        ),
    ]
