# Generated by Django 3.2 on 2023-09-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0083_auto_20230906_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categorie_article',
            field=models.CharField(choices=[('N', 'Selectionnez une catégorie'), ('B', 'Billet payant'), ('P', "Pack d'objets"), ('R', 'Recharge cashless'), ('S', 'Recharge suspendue'), ('T', 'Vetement'), ('M', 'Merchandasing'), ('A', 'Abonnement et/ou adhésion associative'), ('D', 'Don'), ('F', 'Reservation gratuite'), ('V', 'Nécessite une validation manuelle')], default='N', max_length=3, verbose_name='Type de produit'),
        ),
        migrations.AlterField(
            model_name='productsold',
            name='categorie_article',
            field=models.CharField(choices=[('N', 'Selectionnez une catégorie'), ('B', 'Billet payant'), ('P', "Pack d'objets"), ('R', 'Recharge cashless'), ('S', 'Recharge suspendue'), ('T', 'Vetement'), ('M', 'Merchandasing'), ('A', 'Abonnement et/ou adhésion associative'), ('D', 'Don'), ('F', 'Reservation gratuite'), ('V', 'Nécessite une validation manuelle')], default='N', max_length=3, verbose_name='Type de produit'),
        ),
    ]
