# Generated by Django 3.2 on 2023-09-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0084_auto_20230906_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weekday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='booking',
            field=models.BooleanField(default=False, help_text="Si activé, l'évènement sera visible en haut de la page d'accueil, l'utilisateur pourra selectionner une date.", verbose_name='Mode restauration/booking'),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrent',
            field=models.ManyToManyField(blank=True, to='BaseBillet.Weekday'),
        ),
    ]
