# Generated by Django 4.2.11 on 2024-05-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0089_alter_price_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='laboutik_public_pem',
            field=models.CharField(blank=True, editable=False, max_length=512, null=True),
        ),
    ]
