# Generated by Django 4.2.11 on 2024-05-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0090_configuration_laboutik_public_pem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='subscription_type',
            field=models.CharField(choices=[('N', 'Non applicable'), ('Y', '365 Jours'), ('M', '30 Jours'), ('D', '1 Jour'), ('H', '1 Heure'), ('C', 'Civile')], default='N', max_length=1, verbose_name="durée d'abonnement"),
        ),
        migrations.AlterField(
            model_name='product',
            name='categorie_article',
            field=models.CharField(choices=[('N', 'Selectionnez une catégorie'), ('B', 'Billet payant'), ('P', "Pack d'objets"), ('R', 'Recharge cashless'), ('S', 'Recharge suspendue'), ('T', 'Vetement'), ('M', 'Merchandasing'), ('A', 'Abonnement et/ou adhésion associative'), ('G', 'Badgeuse'), ('D', 'Don'), ('F', 'Reservation gratuite'), ('V', 'Nécessite une validation manuelle')], default='N', max_length=3, verbose_name='Type de produit'),
        ),
        migrations.AlterField(
            model_name='productsold',
            name='categorie_article',
            field=models.CharField(choices=[('N', 'Selectionnez une catégorie'), ('B', 'Billet payant'), ('P', "Pack d'objets"), ('R', 'Recharge cashless'), ('S', 'Recharge suspendue'), ('T', 'Vetement'), ('M', 'Merchandasing'), ('A', 'Abonnement et/ou adhésion associative'), ('G', 'Badgeuse'), ('D', 'Don'), ('F', 'Reservation gratuite'), ('V', 'Nécessite une validation manuelle')], default='N', max_length=3, verbose_name='Type de produit'),
        ),
    ]
