# Generated by Django 4.2 on 2024-10-28 11:33

from django.db import migrations, models
from django_tenants.utils import tenant_context

from BaseBillet.models import Price


# def reset_id_stripe_product(apps, schema_editor):
#     Client = apps.get_model('Customers', 'Client')
#     for client in Client.objects.all().exclude(categorie='R'):
#         with tenant_context(client):
#             ProductSold = apps.get_model('BaseBillet', 'ProductSold')
#             PriceSold = apps.get_model('BaseBillet', 'PriceSold')
#             ProductSold.objects.all().update(id_product_stripe=None)
#             PriceSold.objects.all().update(id_price_stripe=None)
#
# def reverse(apps, schema_editor):
#     pass


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0097_price_free_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement_stripe',
            name='source',
            field=models.CharField(choices=[('Q', 'Depuis scan QR-Code'), ('B', 'Depuis API'), ('F', 'Depuis billetterie'), ('I', 'Depuis invoice')], default='B', max_length=1, verbose_name='Source de la commande'),
        ),
        migrations.AlterField(
            model_name='price',
            name='subscription_type',
            field=models.CharField(choices=[('N', 'Non applicable'), ('H', '1 Heure'), ('M', '30 Jours'), ('D', '1 Jour'), ('Y', '365 Jours'), ('C', 'Civile : 1er Janvier'), ('S', 'Scolaire : 1er septembre')], default='N', max_length=1, verbose_name="durée d'abonnement"),
        ),
        # migrations.RunPython(reset_id_stripe_product, reverse),
    ]
