# Generated by Django 4.2 on 2024-11-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0100_membership_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='need_name',
            field=models.BooleanField(default=True, verbose_name='Nom requis lors du scan qrcode'),
        ),
    ]
