# Generated by Django 4.2 on 2024-11-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0002_alter_client_categorie'),
        ('BaseBillet', '0101_configuration_need_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='federated_with',
            field=models.ManyToManyField(blank=True, help_text='Affiche les évènements et les adhésions des structures fédérées.', related_name='federated_with', to='Customers.client'),
        ),
    ]
