# Generated by Django 4.2 on 2024-11-28 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0102_configuration_federated_with'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostalAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.TextField(help_text='Le numéro de la rue, le nom de la rue, etc.', verbose_name='Adresse de la rue')),
                ('address_locality', models.CharField(help_text='La ville ou la localité.', max_length=255, verbose_name='Localité')),
                ('address_region', models.CharField(blank=True, help_text="L'état, la province ou la région.", max_length=255, null=True, verbose_name='Région')),
                ('postal_code', models.CharField(help_text='Le code postal ou code ZIP.', max_length=20, verbose_name='Code postal')),
                ('address_country', models.CharField(help_text="Le pays de l'adresse (en toutes lettres ou code ISO 3166-1 alpha-2).", max_length=255, verbose_name='Pays')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Coordonnée GPS : latitude.', max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Coordonnée GPS : longitude.', max_digits=9, null=True, verbose_name='Longitude')),
                ('comment', models.TextField(blank=True, help_text="Un commentaire sur l'adresse.", null=True, verbose_name='Commentaire')),
                ('is_main', models.BooleanField(default=False, verbose_name='Adresse principale')),
            ],
            options={
                'verbose_name': 'Adresse postale',
                'verbose_name_plural': 'Adresses postales',
            },
        ),
        migrations.AddField(
            model_name='configuration',
            name='postal_adress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BaseBillet.postaladdress'),
        ),
        migrations.AddField(
            model_name='event',
            name='postal_adress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BaseBillet.postaladdress'),
        ),
    ]
