# Generated by Django 4.2.17 on 2024-12-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0103_alter_optiongenerale_poids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='send_to_cashless',
        ),
        migrations.AlterField(
            model_name='product',
            name='archive',
            field=models.BooleanField(default=False, verbose_name='Archiver'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categorie_article',
            field=models.CharField(choices=[('N', 'Selectionnez une catégorie'), ('B', 'Ticket pour reservation payante'), ('A', 'Abonnement et/ou adhésion associative'), ('G', 'Badgeuse'), ('F', 'Reservation gratuite')], default='N', max_length=3, verbose_name='Type de produit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='legal_link',
            field=models.URLField(blank=True, help_text='Non obligatoire', null=True, verbose_name='Lien vers mentions légales'),
        ),
        migrations.AlterField(
            model_name='product',
            name='nominative',
            field=models.BooleanField(default=False, help_text='Nom/Prenom obligatoire par billet si plusieurs réservation.', verbose_name='Nominatif'),
        ),
        migrations.AlterField(
            model_name='product',
            name='option_generale_checkbox',
            field=models.ManyToManyField(blank=True, help_text='Peux choisir plusieurs options selectionnés.', related_name='produits_checkbox', to='BaseBillet.optiongenerale', verbose_name='Option choix multiple'),
        ),
        migrations.AlterField(
            model_name='product',
            name='option_generale_radio',
            field=models.ManyToManyField(blank=True, help_text='Peux choisir entre une seule des options selectionnés.', related_name='produits_radio', to='BaseBillet.optiongenerale', verbose_name='Option choix unique'),
        ),
        migrations.AlterField(
            model_name='product',
            name='publish',
            field=models.BooleanField(default=True, verbose_name='Publier'),
        ),
        migrations.AlterField(
            model_name='productsold',
            name='categorie_article',
            field=models.CharField(choices=[('N', 'Selectionnez une catégorie'), ('B', 'Ticket pour reservation payante'), ('A', 'Abonnement et/ou adhésion associative'), ('G', 'Badgeuse'), ('F', 'Reservation gratuite')], default='N', max_length=3, verbose_name='Type de produit'),
        ),
    ]
