# Generated by Django 4.2 on 2024-11-28 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0103_postaladdress_configuration_postal_adress_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuration',
            old_name='postal_adress',
            new_name='postal_address',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='postal_adress',
            new_name='postal_address',
        ),
    ]
