# Generated by Django 4.2 on 2024-11-29 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0104_rename_postal_adress_configuration_postal_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='url_external',
            new_name='full_url',
        ),
    ]
