# Generated by Django 4.2.17 on 2024-12-18 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0104_remove_product_send_to_cashless_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignearticle',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CB', 'Carte bancaire : TPE'), ('CS', 'Espèce'), ('ST', 'En ligne : Stripe'), ('CH', 'Cheque bancaire')], max_length=2, null=True, verbose_name='Moyen de paiement'),
        ),
        migrations.AlterField(
            model_name='lignearticle',
            name='pricesold',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseBillet.pricesold', verbose_name='Article vendu'),
        ),
        migrations.AlterField(
            model_name='lignearticle',
            name='status',
            field=models.CharField(choices=[('C', 'Annulée'), ('O', 'Non envoyé en paiement'), ('U', 'Non payée'), ('F', 'Reservation gratuite'), ('P', 'Payée'), ('V', 'Validée')], default='O', max_length=3, verbose_name='Status de ligne article'),
        ),
        migrations.AlterField(
            model_name='lignearticle',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='TVA'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='contribution_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Contribution'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='last_contribution',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='membership', to='BaseBillet.price', verbose_name='Produit/Prix'),
        ),
        migrations.AlterField(
            model_name='price',
            name='adhesion_obligatoire',
            field=models.ForeignKey(blank=True, help_text="Ce tarif n'est possible que si l'utilisateur.ices est adhérant.e à ", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adhesion_obligatoire', to='BaseBillet.product', verbose_name='Adhésion obligatoire'),
        ),
        migrations.AlterField(
            model_name='price',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='price',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='BaseBillet.product', verbose_name='Produit'),
        ),
        migrations.AlterField(
            model_name='price',
            name='publish',
            field=models.BooleanField(default=True, verbose_name='Publier'),
        ),
        migrations.AlterField(
            model_name='pricesold',
            name='productsold',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BaseBillet.productsold', verbose_name='Produit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categorie_article',
            field=models.CharField(choices=[('N', 'Selectionnez une catégorie'), ('B', 'Billet pour reservation payante'), ('A', 'Abonnement et/ou adhésion associative'), ('G', 'Badgeuse'), ('F', 'Reservation gratuite')], default='N', max_length=3, verbose_name='Type de produit'),
        ),
        migrations.AlterField(
            model_name='productsold',
            name='categorie_article',
            field=models.CharField(choices=[('N', 'Selectionnez une catégorie'), ('B', 'Billet pour reservation payante'), ('A', 'Abonnement et/ou adhésion associative'), ('G', 'Badgeuse'), ('F', 'Reservation gratuite')], default='N', max_length=3, verbose_name='Type de produit'),
        ),
    ]
