# Generated by Django 4.2 on 2024-11-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0105_rename_url_external_event_full_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.CharField(db_index=True, default='plouf', max_length=50, verbose_name='slug du tag'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nom du tag'),
        ),
    ]
