# Generated by Django 4.2.17 on 2024-12-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0106_lignearticle_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignearticle',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
