# Generated by Django 4.2.17 on 2025-02-08 12:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0107_ghostconfig_alter_ticket_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormbricksConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, max_length=200, null=True)),
                ('api_host', models.CharField(default='https://app.formbricks.com', max_length=220)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormbricksForms',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('environmentId', models.CharField(help_text="Id d'environnement du projet Formbricks", max_length=30)),
                ('trigger_name', models.CharField(help_text='Le nom du trigger qui va lancer le formulaire', max_length=30, unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formbricksform', to='BaseBillet.product')),
            ],
        ),
    ]
