# Generated by Django 4.2.17 on 2024-12-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0107_alter_lignearticle_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignearticle',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Montant'),
        ),
    ]
