# Generated by Django 4.2.17 on 2025-02-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0108_formbricksconfig_formbricksforms'),
    ]

    operations = [
        migrations.AddField(
            model_name='postaladdress',
            name='name',
            field=models.CharField(blank=True, help_text='Donnez un nom à cette adresse', max_length=400, null=True, verbose_name="Nom de l'adresse"),
        ),
        migrations.AlterField(
            model_name='postaladdress',
            name='address_country',
            field=models.CharField(help_text="Le pays de l'adresse (en toutes lettres ou code ISO.", max_length=255, verbose_name='Pays'),
        ),
    ]
