# Generated by Django 4.2.17 on 2024-12-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0108_alter_lignearticle_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Fin d'adhésion"),
        ),
    ]
