# Generated by Django 4.2.17 on 2024-12-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0109_membership_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignearticle',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('NA', 'Aucun : offert'), ('CB', 'Carte bancaire : TPE'), ('CS', 'Espèce'), ('CH', 'Cheque bancaire'), ('ST', 'En ligne : Stripe'), ('SR', 'Paiement récurent : Stripe')], max_length=2, null=True, verbose_name='Moyen de paiement'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='first_contribution',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='last_contribution',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
