# Generated by Django 4.2.17 on 2025-02-17 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0002_alter_client_categorie'),
        ('BaseBillet', '0111_alter_membership_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FederatedPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_exclude', models.ManyToManyField(blank=True, help_text='Ces tags sont exclus', related_name='excluded', to='BaseBillet.tag', verbose_name='Tags exclus')),
                ('tag_filter', models.ManyToManyField(blank=True, help_text='Si selectionnés, filtre uniquement ces tags', related_name='filtred', to='BaseBillet.tag', verbose_name='Filtre de tags')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Place', to='Customers.client')),
            ],
            options={
                'verbose_name': 'Espace fédéré',
                'verbose_name_plural': 'Espaces fédérés',
            },
        ),
    ]
