# Generated by Django 4.2.17 on 2024-12-20 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0111_membership_ligne_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='ligne_article',
        ),
        migrations.AddField(
            model_name='lignearticle',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lignearticles', to='BaseBillet.membership', verbose_name='Adhésion associée'),
        ),
    ]
