# Generated by Django 4.2.17 on 2024-12-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0112_remove_membership_ligne_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('NA', 'Aucun : offert'), ('CB', 'Carte bancaire : TPE'), ('CS', 'Espèce'), ('CH', 'Cheque bancaire'), ('ST', 'En ligne : Stripe'), ('SR', 'Paiement récurent : Stripe')], max_length=2, null=True, verbose_name='Moyen de paiement'),
        ),
    ]
