# Generated by Django 4.2.17 on 2025-02-18 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0112_federatedplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='easy_reservation',
            field=models.BooleanField(default=False, help_text='Mode réservation en un clic pour indiquer une intention de participation.', verbose_name='Réservation facile'),
        ),
        migrations.AlterField(
            model_name='event',
            name='categorie',
            field=models.CharField(choices=[('LIV', 'Concert'), ('FES', 'Festival'), ('REU', 'Réunion'), ('CON', 'Conférence'), ('RES', 'Restauration'), ('ACT', 'Action')], default='LIV', max_length=3, verbose_name="Catégorie d'évènement"),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_per_user',
            field=models.PositiveSmallIntegerField(default=10, help_text='ex : Un même email peut réserver plusieurs billets.', verbose_name='Nombre de reservation maximales par utilisateur·ices'),
        ),
        migrations.AlterField(
            model_name='price',
            name='adhesion_obligatoire',
            field=models.ForeignKey(blank=True, help_text="Ce tarif n'est possible que si l'utilisateur·ices est adhérant.e à ", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adhesion_obligatoire', to='BaseBillet.product', verbose_name='Adhésion obligatoire'),
        ),
    ]
