# Generated by Django 4.2.17 on 2024-12-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0113_membership_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('D', "Enregistré via l'administration"), ('O', 'Paiement unique en ligne'), ('A', 'Renouvellement automatique'), ('C', 'Annulée')], default='O', max_length=1, verbose_name='Status'),
        ),
    ]
