# Generated by Django 4.2.17 on 2025-02-18 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0114_alter_formbricksconfig_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='BaseBillet.event'),
        ),
    ]
