# Generated by Django 4.2.17 on 2024-12-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0114_alter_membership_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignearticle',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('NA', 'Aucun : offert'), ('CC', 'Carte bancaire : TPE'), ('CA', 'Espèce'), ('CH', 'Cheque bancaire'), ('SF', 'En ligne : Stripe fédéré'), ('SN', 'En ligne : Stripe account'), ('SR', 'Paiement récurent : Stripe account')], max_length=2, null=True, verbose_name='Moyen de paiement'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('NA', 'Aucun : offert'), ('CC', 'Carte bancaire : TPE'), ('CA', 'Espèce'), ('CH', 'Cheque bancaire'), ('SF', 'En ligne : Stripe fédéré'), ('SN', 'En ligne : Stripe account'), ('SR', 'Paiement récurent : Stripe account')], max_length=2, null=True, verbose_name='Moyen de paiement'),
        ),
    ]
