# Generated by Django 4.2.17 on 2025-01-07 10:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0002_alter_client_categorie'),
        ('BaseBillet', '0115_alter_lignearticle_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='federated_with',
            field=models.ManyToManyField(blank=True, help_text='Affiche les évènements et les adhésions des structures fédérées.', related_name='federated_with', to='Customers.client', verbose_name='Fédéré avec'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('D', "Enregistré via l'administration"), ('O', 'Paiement unique en ligne'), ('A', 'Renouvellement automatique'), ('C', 'Annulée')], default='O', max_length=1, verbose_name='Origine'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='event',
            field=models.CharField(choices=[('MB', 'Adhésion validée'), ('RV', 'Réservation validée')], default='RV', max_length=2, verbose_name='Évènement'),
        ),
    ]
