# Generated by Django 4.2.17 on 2025-02-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0115_event_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formbricksforms',
            name='trigger_name',
            field=models.CharField(help_text='Le nom du trigger qui va lancer le formulaire', max_length=30),
        ),
    ]
