# Generated by Django 4.2.17 on 2025-02-21 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0116_alter_formbricksforms_trigger_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='booking',
            field=models.BooleanField(default=False, help_text="Si activé, l'évènement sera visible en haut de la page d'accueil, l'utilisateur·ices pourra selectionner une date.", verbose_name='Mode restauration/booking'),
        ),
        migrations.AlterField(
            model_name='event',
            name='easy_reservation',
            field=models.BooleanField(default=False, help_text='Mode réservation en un clic si utilisateur·ices connecté·e.', verbose_name='Réservation facile'),
        ),
        migrations.AlterField(
            model_name='price',
            name='max_per_user',
            field=models.PositiveSmallIntegerField(default=10, help_text='ex : Un même email peut réserver plusieurs billets', verbose_name='Nombre de reservation maximum par utilisateur·ices'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='pricesold',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BaseBillet.pricesold'),
        ),
    ]
