# Generated by Django 4.2.17 on 2025-02-28 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models
import stdimage.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BaseBillet', '0117_alter_event_booking_alter_event_easy_reservation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name="Nom de l'image")),
                ('img', stdimage.models.StdImageField(force_min_size=False, upload_to='images/', validators=[stdimage.validators.MinSizeValidator(720, 135)], variations={'fhd': (1920, 1920), 'hdr': (720, 720), 'med': (480, 480)}, verbose_name='Fichier image')),
                ('on_event_list_page', models.BooleanField(default=True, verbose_name='Publier sur la page des évènements')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='img',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='images/', validators=[stdimage.validators.MaxSizeValidator(1920, 1920)], variations={'crop': (480, 270, True), 'crop_hdr': (960, 540, True), 'fhd': (1920, 1920), 'hdr': (1280, 1280), 'med': (480, 480), 'thumbnail': (150, 90)}, verbose_name='Image principale'),
        ),
        migrations.AlterField(
            model_name='externalapikey',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Utilisateur·ice qui a créé cette clé.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='membership',
            name='last_contribution',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date du paiement'),
        ),
        migrations.AddField(
            model_name='event',
            name='carrousel',
            field=models.ManyToManyField(blank=True, related_name='events', to='BaseBillet.carrousel', verbose_name="Carrousel d'images"),
        ),
    ]
