# Generated by Django 4.2.17 on 2025-01-07 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rest_framework_api_key', '0005_auto_20220110_1102'),
        ('BaseBillet', '0117_remove_externalapikey_revoquer_apikey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalapikey',
            name='ip',
            field=models.GenericIPAddressField(blank=True, help_text="Si non renseignée, la clé api fonctionnera depuis n'importe quelle ip.", null=True, verbose_name='Ip source'),
        ),
        migrations.AlterField(
            model_name='externalapikey',
            name='key',
            field=models.OneToOneField(blank=True, help_text="Validez l'enregistrement ou révoquez pour faire apparaitre la clé.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_key', to='rest_framework_api_key.apikey'),
        ),
        migrations.AlterField(
            model_name='externalapikey',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Utilisateur qui a créé cette clé.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
