# Generated by Django 4.2.17 on 2025-01-07 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_api_key', '0005_auto_20220110_1102'),
        ('BaseBillet', '0118_alter_externalapikey_ip_alter_externalapikey_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalapikey',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='externalapikey',
            name='place',
        ),
        migrations.AddField(
            model_name='externalapikey',
            name='read',
            field=models.BooleanField(default=True, verbose_name='Permission en lecture seulement'),
        ),
        migrations.AlterField(
            model_name='externalapikey',
            name='key',
            field=models.OneToOneField(blank=True, help_text="Validez l'enregistrement pour faire apparaitre la clé. Elle n'apparaitra qu'à la création.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_key', to='rest_framework_api_key.apikey'),
        ),
    ]
