# Generated by Django 4.2.17 on 2025-02-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0118_carrousel_alter_event_img_alter_externalapikey_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrousel',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='URL de lien'),
        ),
    ]
