# Generated by Django 4.2.17 on 2025-01-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0119_remove_externalapikey_artist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalapikey',
            name='wallet',
            field=models.BooleanField(default=False, verbose_name='Lister les wallets'),
        ),
        migrations.AlterField(
            model_name='externalapikey',
            name='read',
            field=models.BooleanField(default=True, verbose_name='Lecture'),
        ),
    ]
