# Generated by Django 4.2.17 on 2025-02-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0119_carrousel_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrousel',
            name='order',
            field=models.PositiveSmallIntegerField(default=1000, verbose_name="Ordre d'apparition"),
        ),
    ]
