# Generated by Django 4.2.17 on 2025-01-08 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BaseBillet', '0120_externalapikey_wallet_alter_externalapikey_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalapikey',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Utilisateur qui a créé cette clé.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
