# Generated by Django 4.2.17 on 2025-02-28 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AuthBillet', '0018_alter_tibilletuser_email_error_and_more'),
        ('BaseBillet', '0120_carrousel_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rsa_key',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='AuthBillet.rsakey'),
        ),
    ]
