# Generated by Django 4.2.17 on 2025-03-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0121_event_rsa_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='categorie',
            field=models.CharField(choices=[('LIV', 'Concert'), ('FES', 'Festival'), ('REU', 'Réunion'), ('CON', 'Conférence'), ('RES', 'Restauration'), ('ACT', 'Volontariat')], default='LIV', max_length=3, verbose_name="Catégorie d'évènement"),
        ),
    ]
