# Generated by Django 4.2.17 on 2025-01-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0121_alter_externalapikey_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalapikey',
            name='read',
        ),
        migrations.AlterField(
            model_name='externalapikey',
            name='event',
            field=models.BooleanField(default=False, verbose_name='Évènements'),
        ),
        migrations.AlterField(
            model_name='externalapikey',
            name='product',
            field=models.BooleanField(default=False, verbose_name='Produits'),
        ),
        migrations.AlterField(
            model_name='externalapikey',
            name='reservation',
            field=models.BooleanField(default=False, verbose_name='Reservations'),
        ),
        migrations.AlterField(
            model_name='externalapikey',
            name='ticket',
            field=models.BooleanField(default=False, verbose_name='Billets'),
        ),
        migrations.AlterField(
            model_name='externalapikey',
            name='wallet',
            field=models.BooleanField(default=False, verbose_name='Wallets'),
        ),
    ]
