# Generated by Django 4.2.17 on 2025-01-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0122_remove_externalapikey_read_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GhostConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ghost_url', models.URLField(blank=True, null=True)),
                ('ghost_key', models.CharField(blank=True, max_length=200, null=True)),
                ('ghost_last_log', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
