# Generated by Django 4.2.17 on 2025-03-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0123_remove_paiement_stripe_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='event_menu_name',
            field=models.CharField(default='Agenda', max_length=200, verbose_name='Nom du menu agenda'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='membership_menu_name',
            field=models.CharField(default='Adhésions', max_length=200, verbose_name='Nom du menu adhésion'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='jauge_max',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='Jauge maximale par defaut'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='vat_taxe',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tva par defaut', max_digits=4),
        ),
    ]
