# Generated by Django 4.2.17 on 2025-01-08 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0123_ghostconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='ghost_key',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='ghost_last_log',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='ghost_url',
        ),
    ]
