# Generated by Django 4.2.17 on 2025-01-08 15:28

from django.db import migrations, models
import stdimage.models
import stdimage.validators


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0124_remove_configuration_ghost_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_datetime',
            field=models.DateTimeField(blank=True, help_text='Non obligatoire', null=True, verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='event',
            name='datetime',
            field=models.DateTimeField(verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='event',
            name='img',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='images/', validators=[stdimage.validators.MaxSizeValidator(1920, 1920)], variations={'crop': (480, 270, True), 'crop_hdr': (960, 540, True), 'fhd': (1920, 1920), 'hdr': (1280, 1280), 'med': (480, 480), 'thumbnail': (150, 90)}, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='long_description',
            field=models.TextField(blank=True, null=True, verbose_name='Description longue'),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_per_user',
            field=models.PositiveSmallIntegerField(default=10, help_text='ex : Un même email peut réserver plusieurs billets.', verbose_name='Nombre de reservation maximales par utilisateur.ices'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=200, verbose_name="Nom de l'évènement"),
        ),
        migrations.AlterField(
            model_name='event',
            name='products',
            field=models.ManyToManyField(blank=True, to='BaseBillet.product', verbose_name='Produits'),
        ),
        migrations.AlterField(
            model_name='event',
            name='short_description',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Description courte'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='events', to='BaseBillet.tag', verbose_name='Tags'),
        ),
    ]
