# Generated by Django 4.2.17 on 2025-01-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0125_event_end_datetime_alter_event_datetime_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Billet', 'verbose_name_plural': 'Billets'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='recurrent',
        ),
        migrations.AddField(
            model_name='ticket',
            name='sale_origin',
            field=models.CharField(choices=[('LP', 'En ligne'), ('LB', 'Caisse'), ('AD', 'Administration'), ('EX', 'Extérieur')], default='LP', max_length=2, verbose_name='Origine du paiement'),
        ),
        migrations.AlterField(
            model_name='lignearticle',
            name='status',
            field=models.CharField(choices=[('C', 'Annulée'), ('O', 'Non envoyé en paiement'), ('U', 'Non payée'), ('F', 'Reservation gratuite'), ('P', 'Payée & non validée'), ('V', 'Validée')], default='O', max_length=3, verbose_name='Status de ligne article'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
