# Generated by Django 4.2.17 on 2025-03-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0126_brevoconfig_alter_configuration_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='categorie',
            field=models.CharField(choices=[('LIV', 'Concert'), ('FES', 'Festival'), ('REU', 'Meeting'), ('CON', 'Conference'), ('RES', 'Catering'), ('CHT', 'Workcamp'), ('ACT', 'Volunteering')], default='LIV', max_length=3, verbose_name='Event category'),
        ),
    ]
