# Generated by Django 4.2.17 on 2025-01-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0126_alter_ticket_options_remove_event_recurrent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('NA', 'Aucun : offert'), ('CC', 'Carte bancaire : TPE'), ('CA', 'Espèce'), ('CH', 'Cheque bancaire'), ('SF', 'En ligne : Stripe fédéré'), ('SN', 'En ligne : Stripe account'), ('SR', 'Paiement récurent : Stripe account')], max_length=2, null=True, verbose_name='Moyen de paiement'),
        ),
    ]
