# Generated by Django 4.2.17 on 2025-03-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0127_alter_event_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brevoconfig',
            name='api_key',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='legal_link',
            field=models.URLField(blank=True, help_text='Not required. If completed, displays a checkbox to validate the membership product.', null=True, verbose_name='Terms and conditions link'),
        ),
    ]
