# Generated by Django 4.2.17 on 2025-03-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0128_alter_brevoconfig_api_key_alter_product_legal_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ('order',), 'verbose_name': 'Rate', 'verbose_name_plural': 'Rates'},
        ),
        migrations.AddField(
            model_name='price',
            name='order',
            field=models.SmallIntegerField(default=100),
        ),
    ]
