# Generated by Django 4.2.17 on 2025-03-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0129_alter_price_options_price_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='first_input_label_membership',
            field=models.CharField(default='First name', max_length=200, verbose_name='Title of the first input on the membership form'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='second_input_label_membership',
            field=models.CharField(default='Last name or organization', max_length=200, verbose_name='Title of the second input on the membership form'),
        ),
    ]
