# Generated by Django 4.2.17 on 2025-03-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0131_alter_membership_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignearticle',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('NA', 'Offered'), ('CC', 'Credit card: POS terminal'), ('CA', 'Cash'), ('CH', 'Check'), ('TR', 'Bank transfer'), ('SF', 'Online: federated Stripe'), ('SN', 'Online: Stripe account'), ('SR', 'Recurring: Stripe account')], max_length=2, null=True, verbose_name='Payment method'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('NA', 'Offered'), ('CC', 'Credit card: POS terminal'), ('CA', 'Cash'), ('CH', 'Check'), ('TR', 'Bank transfer'), ('SF', 'Online: federated Stripe'), ('SN', 'Online: Stripe account'), ('SR', 'Recurring: Stripe account')], max_length=2, null=True, verbose_name='Payment method'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('D', 'Saved through the admin'), ('I', 'Import from file'), ('O', 'Single online stripe payment'), ('A', 'Automatic stripe renewal'), ('C', 'Cancelled'), ('L', 'LaBoutik')], default='O', max_length=1, verbose_name='Origin'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('NA', 'Offered'), ('CC', 'Credit card: POS terminal'), ('CA', 'Cash'), ('CH', 'Check'), ('TR', 'Bank transfer'), ('SF', 'Online: federated Stripe'), ('SN', 'Online: Stripe account'), ('SR', 'Recurring: Stripe account')], max_length=2, null=True, verbose_name='Payment method'),
        ),
    ]
