# Generated by Django 4.2.17 on 2025-04-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0132_alter_lignearticle_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignearticle',
            name='sended_to_laboutik',
            field=models.BooleanField(default=False),
        ),
    ]
