# Generated by Django 4.2.17 on 2025-04-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0133_lignearticle_sended_to_laboutik'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='description_membership_page',
            field=models.TextField(blank=True, help_text='Displayed above membership products.', verbose_name='Description on the membership page'),
        ),
        migrations.AlterField(
            model_name='lignearticle',
            name='sended_to_laboutik',
            field=models.BooleanField(default=False, verbose_name='Sended to LaBoutik'),
        ),
        migrations.AlterField(
            model_name='paiement_stripe',
            name='source',
            field=models.CharField(choices=[('Q', 'From QR code scan'), ('B', 'From API'), ('F', 'From ticketing app'), ('I', 'From invoice'), ('T', 'Stripe Transfert')], default='B', max_length=1, verbose_name='Order source'),
        ),
    ]
