# Generated by Django 4.2.17 on 2025-04-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0134_configuration_description_membership_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='additional_text_in_membership_mail',
            field=models.TextField(blank=True, help_text='You can add additional information that will be e-mailed to you when you sign up.', null=True, verbose_name='Additional text in membership mail'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='currency_code',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AlterField(
            model_name='price',
            name='prix',
            field=models.DecimalField(decimal_places=2, help_text='If the free price is activated, the amount is the minimum accepted rate.', max_digits=6, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='option_generale_checkbox',
            field=models.ManyToManyField(blank=True, help_text='Any number of choices can be selected at order time.', related_name='produits_checkbox', to='BaseBillet.optiongenerale', verbose_name='Multiple choice options'),
        ),
        migrations.AlterField(
            model_name='product',
            name='option_generale_radio',
            field=models.ManyToManyField(blank=True, help_text='Only one choice can be selected at order time.', related_name='produits_radio', to='BaseBillet.optiongenerale', verbose_name='Single choice options'),
        ),
    ]
