# Generated by Django 4.2.17 on 2025-04-11 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0135_configuration_additional_text_in_membership_mail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='private',
            field=models.BooleanField(default=False, help_text="Ne s'affichera pas sur les agendas partagés.", verbose_name='Évènement non fédérable'),
        ),
    ]
