# Generated by Django 4.2.17 on 2025-04-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0136_event_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='stripe_invoice',
            field=models.BooleanField(default=False, help_text='Send a stripe invoice to the customer', verbose_name='send a stripe invoice'),
        ),
    ]
