# Generated by Django 4.2.17 on 2025-04-16 07:21

from django.db import migrations, models
import stdimage.models
import stdimage.validators


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0137_configuration_stripe_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sticker_img',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, help_text='The small image displayed in the events list. If None, img will be displayed. 4x3 ratio.', null=True, upload_to='images/', validators=[stdimage.validators.MaxSizeValidator(1920, 1920)], variations={'crop': (480, 270, True), 'crop_hdr': (960, 540, True), 'fhd': (1920, 1920), 'hdr': (1280, 1280), 'med': (480, 480), 'thumbnail': (150, 90)}, verbose_name='Sticker image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='carrousel',
            field=models.ManyToManyField(blank=True, help_text='Images that will be displayed in the program section.', related_name='events', to='BaseBillet.carrousel', verbose_name='Carousel slides'),
        ),
        migrations.AlterField(
            model_name='event',
            name='img',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, help_text='The main image of the event, displayed in the head of the event page.', null=True, upload_to='images/', validators=[stdimage.validators.MaxSizeValidator(1920, 1920)], variations={'crop': (480, 270, True), 'crop_hdr': (960, 540, True), 'fhd': (1920, 1920), 'hdr': (1280, 1280), 'med': (480, 480), 'thumbnail': (150, 90)}, verbose_name='Main image'),
        ),
    ]
