# Generated by Django 4.2.17 on 2025-04-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0138_event_sticker_img_alter_event_carrousel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='validate_button_text',
            field=models.CharField(blank=True, help_text="'Subscribe' If empty", max_length=20, null=True, verbose_name='Validate button text for membership'),
        ),
    ]
