# Generated by Django 4.2.17 on 2025-04-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0139_product_validate_button_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='membership_menu_name',
            field=models.CharField(blank=True, help_text="'Subscriptions' If empty.", max_length=200, null=True, verbose_name='Subscription page name'),
        ),
    ]
