# Generated by Django 4.2.17 on 2025-04-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('BaseBillet', '0141_alter_configuration_event_menu_name_and_more'),
    ]

    def update_default_colors(apps, schema_editor):
        Tag = apps.get_model('BaseBillet', 'Tag')
        Tag.objects.filter(color='#000000').update(color='#0dcaf0')

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#0dcaf0', max_length=7, verbose_name='Tag color'),
        ),
        migrations.RunPython(update_default_colors, reverse_code=migrations.RunPython.noop),
    ]
