# Generated by Django 4.2.17 on 2025-04-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0142_alter_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='first_input_label_membership',
            field=models.CharField(blank=True, help_text="'First name' If empty.", max_length=200, null=True, verbose_name='Title of the first input on the membership form'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='second_input_label_membership',
            field=models.CharField(blank=True, help_text="'Last name or organization' If empty.", max_length=200, null=True, verbose_name='Title of the second input on the membership form'),
        ),
    ]
