# Generated by Django 4.2.17 on 2025-04-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0143_alter_configuration_first_input_label_membership_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='description_event_page',
            field=models.TextField(blank=True, help_text='Displayed above the search field.', verbose_name='Description on the event page'),
        ),
    ]
