# Generated by Django 4.2.17 on 2025-04-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0144_configuration_description_event_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='custom_confirmation_message',
            field=models.TextField(blank=True, help_text='Not required: You can add additional information to be sent by e-mail.', null=True, verbose_name='Personalized text in the booking confirmation e-mail.'),
        ),
    ]
