# Generated by Django 4.2.17 on 2025-05-14 15:56

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0146_alter_configuration_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='carte_restaurant',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='images/', variations={'fhd': (1920, 1920), 'hdr': (720, 720), 'med': (480, 480), 'thumbnail': (150, 90)}, verbose_name='Restaurant menu image'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='logo',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='images/', variations={'fhd': (1920, 1920), 'hdr': (720, 720), 'med': (480, 480), 'thumbnail': (300, 120)}, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='map_img',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='images/', variations={'fhd': (1920, 1920), 'hdr': (720, 720), 'med': (480, 480), 'thumbnail': (150, 90)}, verbose_name='Geographical map image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='img',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, help_text='The main image of the event, displayed in the head of the event page.', null=True, upload_to='images/', variations={'crop': (480, 270, True), 'crop_hdr': (960, 540, True), 'fhd': (1920, 1920), 'hdr': (1280, 1280), 'med': (480, 480), 'thumbnail': (150, 90)}, verbose_name='Main image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='sticker_img',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, help_text='The small image displayed in the events list. If None, img will be displayed. 4x3 ratio.', null=True, upload_to='images/', variations={'crop': (480, 270, True), 'crop_hdr': (960, 540, True), 'fhd': (1920, 1920), 'hdr': (1280, 1280), 'med': (480, 480), 'thumbnail': (150, 90)}, verbose_name='Sticker image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='images/', variations={'crop': (480, 270, True), 'crop_hdr': (960, 540, True), 'fhd': (1920, 1920), 'hdr': (720, 720), 'med': (480, 480), 'thumbnail': (150, 90)}, verbose_name='Product image'),
        ),
    ]
