# Generated by Django 4.2.17 on 2025-05-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0147_alter_configuration_carte_restaurant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='long_description',
            field=models.TextField(blank=True, help_text='Affiché uniquement pour les produits adhésions / abonnements.', null=True, verbose_name='Long description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, help_text='Affiché uniquement pour les produits adhésions / abonnements.', max_length=250, null=True, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('C', 'Created'), ('N', 'Inactive'), ('K', 'Valid and not scanned'), ('S', 'Valid and scanned')], default='C', max_length=1, verbose_name='Scanning status'),
        ),
    ]
