# Generated by Django 4.2.17 on 2025-05-27 15:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_api_key', '0005_auto_20220110_1102'),
        ('BaseBillet', '0149_alter_configuration_img_alter_event_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanApp',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('archive', models.BooleanField(default=False)),
                ('qrcode', models.CharField(blank=True, max_length=255, null=True)),
                ('claimed', models.BooleanField(default=False)),
                ('key', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scan_api_key', to='rest_framework_api_key.apikey')),
            ],
        ),
    ]
