# Generated by Django 4.2.17 on 2025-05-27 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0151_scannerapikey_alter_scanapp_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='scanned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='BaseBillet.scanapp'),
        ),
    ]
