# Generated by Django 4.2.21 on 2025-06-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0153_postaladdress_img_postaladdress_sticker_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='options_checkbox',
            field=models.ManyToManyField(blank=True, related_name='options_checkbox', to='BaseBillet.optiongenerale', verbose_name='Des cases à cocher pendant la reservation. Plusieurs choix possibles.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='options_radio',
            field=models.ManyToManyField(blank=True, help_text='Des cases à cocher pendant la reservation. Un seul choix possible.', related_name='options_radio', to='BaseBillet.optiongenerale', verbose_name='Single choice menu'),
        ),
    ]
