# Generated by Django 4.2.21 on 2025-06-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0154_alter_event_options_checkbox_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='federatedplace',
            name='membership_visible',
            field=models.BooleanField(default=False, help_text='Also display memberships and subscriptions for this site.', verbose_name='Federate memberships and subscriptions'),
        ),
        migrations.AlterField(
            model_name='ghostconfig',
            name='ghost_key',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Ghost Admin API key'),
        ),
        migrations.AlterField(
            model_name='ghostconfig',
            name='ghost_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ghost API URL'),
        ),
    ]
