# Generated by Django 4.2.21 on 2025-06-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0155_federatedplace_membership_visible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postaladdress',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=16, help_text='GPS coordinate: latitude.', max_digits=18, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='postaladdress',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=16, help_text='GPS coordinate: longitude.', max_digits=18, null=True, verbose_name='Longitude'),
        ),
    ]
