# Generated by Django 4.2.21 on 2025-07-16 06:24

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0156_alter_postaladdress_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='img',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, help_text='The main image of the event, displayed in the head of the event page and for social shares. If empty, the address image is displayed.', null=True, upload_to='images/', variations={'crop': (480, 270, True), 'crop_hdr': (960, 540, True), 'fhd': (1920, 1920), 'hdr': (1280, 1280), 'med': (480, 480), 'social_card': (1200, 630, True), 'thumbnail': (150, 90)}, verbose_name='Main image'),
        ),
        migrations.AlterField(
            model_name='postaladdress',
            name='sticker_img',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, help_text='The small image displayed in the events list if not img on event. If None, Main img will be displayed. 4x3 ratio.', null=True, upload_to='images/', variations={'crop': (480, 270, True), 'crop_hdr': (960, 540, True), 'fhd': (1920, 1920), 'hdr': (1280, 1280), 'med': (480, 480), 'thumbnail': (150, 90)}, verbose_name='Sticker image'),
        ),
    ]
