# Generated by Django 4.2.21 on 2025-08-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0157_alter_event_img_alter_postaladdress_sticker_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignearticle',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lignearticle',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('NA', 'Offered'), ('CC', 'Credit card: POS terminal'), ('CA', 'Cash'), ('CH', 'Check'), ('QR', 'QrCode on my account'), ('TR', 'Bank transfer'), ('SF', 'Online: federated Stripe'), ('SN', 'Online: Stripe account'), ('SR', 'Recurring: Stripe account')], max_length=2, null=True, verbose_name='Payment method'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('NA', 'Offered'), ('CC', 'Credit card: POS terminal'), ('CA', 'Cash'), ('CH', 'Check'), ('QR', 'QrCode on my account'), ('TR', 'Bank transfer'), ('SF', 'Online: federated Stripe'), ('SN', 'Online: Stripe account'), ('SR', 'Recurring: Stripe account')], max_length=2, null=True, verbose_name='Payment method'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categorie_article',
            field=models.CharField(choices=[('N', 'Select a category'), ('B', 'Ticket booking'), ('F', 'Free booking'), ('A', 'Subscription or membership'), ('G', 'Punchclock'), ('Q', 'QrCode paiement on my account')], default='N', max_length=3, verbose_name='Product type'),
        ),
        migrations.AlterField(
            model_name='productsold',
            name='categorie_article',
            field=models.CharField(choices=[('N', 'Select a category'), ('B', 'Ticket booking'), ('F', 'Free booking'), ('A', 'Subscription or membership'), ('G', 'Punchclock'), ('Q', 'QrCode paiement on my account')], default='N', max_length=3, verbose_name='Product type'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('NA', 'Offered'), ('CC', 'Credit card: POS terminal'), ('CA', 'Cash'), ('CH', 'Check'), ('QR', 'QrCode on my account'), ('TR', 'Bank transfer'), ('SF', 'Online: federated Stripe'), ('SN', 'Online: Stripe account'), ('SR', 'Recurring: Stripe account')], max_length=2, null=True, verbose_name='Payment method'),
        ),
    ]
