# Generated by Django 4.2.21 on 2025-08-09 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0158_lignearticle_metadata_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='price',
            unique_together=set(),
        ),
    ]
