# Generated by Django 4.2.21 on 2025-08-12 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AuthBillet', '0021_alter_tibilletuser_offre'),
        ('BaseBillet', '0159_alter_price_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignearticle',
            name='asset',
            field=models.UUIDField(blank=True, null=True, verbose_name='Asset'),
        ),
        migrations.AddField(
            model_name='lignearticle',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='AuthBillet.wallet', verbose_name='Wallet from'),
        ),
        migrations.AlterField(
            model_name='lignearticle',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('NA', 'Offered'), ('CC', 'Credit card: POS terminal'), ('CA', 'Cash'), ('CH', 'Check'), ('QR', 'QrCode on my account'), ('TR', 'Bank transfer'), ('SF', 'Online: federated Stripe'), ('SN', 'Online: Stripe account'), ('SR', 'Recurring: Stripe account'), ('LE', 'Asset local fiat'), ('LG', 'Asset local gift')], max_length=2, null=True, verbose_name='Payment method'),
        ),
        migrations.AlterField(
            model_name='lignearticle',
            name='qty',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name='membership',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('NA', 'Offered'), ('CC', 'Credit card: POS terminal'), ('CA', 'Cash'), ('CH', 'Check'), ('QR', 'QrCode on my account'), ('TR', 'Bank transfer'), ('SF', 'Online: federated Stripe'), ('SN', 'Online: Stripe account'), ('SR', 'Recurring: Stripe account'), ('LE', 'Asset local fiat'), ('LG', 'Asset local gift')], max_length=2, null=True, verbose_name='Payment method'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('NA', 'Offered'), ('CC', 'Credit card: POS terminal'), ('CA', 'Cash'), ('CH', 'Check'), ('QR', 'QrCode on my account'), ('TR', 'Bank transfer'), ('SF', 'Online: federated Stripe'), ('SN', 'Online: Stripe account'), ('SR', 'Recurring: Stripe account'), ('LE', 'Asset local fiat'), ('LG', 'Asset local gift')], max_length=2, null=True, verbose_name='Payment method'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sale_origin',
            field=models.CharField(choices=[('LP', 'Online platform'), ('LB', 'Cash register'), ('AD', 'Administration'), ('EX', 'External'), ('QR', 'QrCode on my account')], default='LP', max_length=2, verbose_name='Payment source'),
        ),
    ]
