# Generated by Django 4.2.21 on 2025-08-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0160_lignearticle_asset_lignearticle_wallet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='language',
            field=models.CharField(choices=[('fr', 'French'), ('en', 'English')], default='fr', max_length=2),
        ),
    ]
