# Generated by Django 4.2.23 on 2025-08-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0161_configuration_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='refund_deadline',
            field=models.PositiveSmallIntegerField(default=7, help_text='Number of days before the event to obtain a refund.', verbose_name='Refund deadline (days)'),
        ),
    ]
