# Generated by Django 4.2.23 on 2025-08-24 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fedow_connect', '0008_asset_asset_unique_stripe_primary_asset'),
        ('BaseBillet', '0162_event_refund_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fedow_reward_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Raw token amount.', max_digits=10, null=True, verbose_name='Token amount to send'),
        ),
        migrations.AddField(
            model_name='product',
            name='fedow_reward_asset',
            field=models.ForeignKey(blank=True, help_text='Asset to send from the place to the user wallet.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='fedow_connect.asset', verbose_name='Fedow Asset'),
        ),
        migrations.AddField(
            model_name='product',
            name='fedow_reward_enabled',
            field=models.BooleanField(default=False, help_text='If enabled, after a successful payment, the user wallet will receive tokens.', verbose_name='Top-up user wallet on payment (Fedow)'),
        ),
        migrations.AlterField(
            model_name='lignearticle',
            name='status',
            field=models.CharField(choices=[('C', 'Cancelled'), ('R', 'Refunded'), ('O', 'Not sent to payment'), ('U', 'Not paid'), ('F', 'Free booking'), ('P', 'Paid but not confirmed'), ('V', 'Confirmed')], default='O', max_length=3, verbose_name='Product entry status'),
        ),
        migrations.AlterField(
            model_name='paiement_stripe',
            name='status',
            field=models.CharField(choices=[('N', 'Payment link not generated'), ('O', 'Sent to Stripe'), ('W', 'Waiting for payment'), ('E', 'Expired'), ('P', 'Paid for'), ('V', 'Paid and confirmed'), ('S', 'Paid but issues with Stripe sync'), ('C', 'Cancelled'), ('R', 'Refunded')], default='N', max_length=1, verbose_name='Order status'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('C', 'Created'), ('N', 'Inactive'), ('K', 'Valid and not scanned'), ('S', 'Valid and scanned'), ('R', 'Canceled')], default='C', max_length=1, verbose_name='Scanning status'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='url',
            field=models.URLField(help_text="Astuce Dev' : pour tester un webhook, lancez un petit serveur HTTP qui affiche le contenu de la requete : https://gist.github.com/mdonkers/63e115cc0c79b4f6b8b3a6b797e485c7"),
        ),
    ]
