# Generated by Django 4.2.23 on 2025-09-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0163_price_fedow_reward_amount_price_fedow_reward_asset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='need_admin_validation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='state',
            field=models.CharField(choices=[('CA', 'Cancelled'), ('VA', 'Waiting for admin validation'), ('WA', 'Confirmed by admin'), ('AU', 'Confirmed by system')], default='AU', max_length=2, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='price',
            name='iteration',
            field=models.PositiveSmallIntegerField(blank=True, help_text='A rate with a monthly period and iterations=2 will last two months with two payments: one on day D and another the following month.', null=True, verbose_name='Max number of recurrences'),
        ),
        migrations.AlterField(
            model_name='price',
            name='recurring_payment',
            field=models.BooleanField(default=False, help_text='Monthly payment through Stripe, limited to one product at checkout.', verbose_name='Recurring payment'),
        ),
        migrations.AlterField(
            model_name='price',
            name='subscription_type',
            field=models.CharField(choices=[('N', 'Non applicable'), ('H', '1 hour'), ('D', '1 day'), ('W', '1 week'), ('M', '1 Month'), ('O', '1st of the month'), ('Y', '365 days'), ('C', 'Calendar year : 1st of January'), ('S', 'School year: 1st of September')], default='N', max_length=1, verbose_name='Subscription duration'),
        ),
    ]
