# Generated by Django 4.2.24 on 2025-09-17 18:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0164_membership_need_admin_validation_membership_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='custom_form',
            field=models.JSONField(blank=True, null=True, verbose_name='Custom Form'),
        ),
        migrations.CreateModel(
            name='ProductFormField',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.SlugField(help_text='Unique per product', max_length=64, verbose_name='Key')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('help_text', models.CharField(blank=True, max_length=500, null=True, verbose_name='Help text')),
                ('placeholder', models.CharField(blank=True, max_length=255, null=True, verbose_name='Placeholder')),
                ('field_type', models.CharField(choices=[('ST', 'Short text'), ('LT', 'Long text'), ('SS', 'Single select'), ('MS', 'Multiple select')], max_length=2, verbose_name='Field type')),
                ('required', models.BooleanField(default=False, verbose_name='Required')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Display order')),
                ('options', models.JSONField(blank=True, null=True, verbose_name='Options')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='BaseBillet.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Dynamic form field',
                'verbose_name_plural': 'Dynamic form fields',
                'ordering': ('order', 'uuid'),
            },
        ),
        migrations.AddConstraint(
            model_name='productformfield',
            constraint=models.UniqueConstraint(fields=('product', 'name'), name='uniq_product_formfield_key'),
        ),
    ]
