# Generated by Django 4.2.24 on 2025-09-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0165_membership_custom_form_productformfield_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='manual_validation',
            field=models.BooleanField(default=False, help_text='If selected, an administrator will have to manually approve the membership before sending the payment link by email. An email will be sent to the administration address.', verbose_name='Need manual validation'),
        ),
        migrations.AlterField(
            model_name='productformfield',
            name='name',
            field=models.SlugField(editable=False, help_text='Unique per product', max_length=64, verbose_name='Key'),
        ),
    ]
