# Generated by Django 4.2.24 on 2025-09-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0166_price_manual_validation_alter_productformfield_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='custom_form',
            field=models.JSONField(blank=True, null=True, verbose_name='Custom Form'),
        ),
    ]
