# Generated by Django 4.2.24 on 2025-09-19 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0167_reservation_custom_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productformfield',
            name='placeholder',
        ),
    ]
