# Generated by Django 4.2.24 on 2025-09-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0168_remove_productformfield_placeholder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='need_admin_validation',
        ),
        migrations.AlterField(
            model_name='membership',
            name='state',
            field=models.CharField(choices=[('CA', 'Cancelled'), ('WA', 'Waiting for admin validation'), ('VA', 'Confirmed by admin, waiting for payment'), ('PA', 'Paid by user'), ('AU', 'Confirmed by system')], default='AU', max_length=2, verbose_name='State'),
        ),
    ]
