# Generated by Django 4.2.24 on 2025-09-28 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0169_remove_membership_need_admin_validation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='fedow_reward_asset',
        ),
    ]
