# Generated by Django 4.2.24 on 2025-09-25 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fedow_public', '0001_initial'),
        ('BaseBillet', '0169_remove_membership_need_admin_validation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='fedow_reward_asset',
            field=models.ForeignKey(blank=True, help_text='Asset to send from the place to the user wallet.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='fedow_public.assetfedowpublic', verbose_name='Fedow Asset'),
        ),
    ]
