# Generated by Django 4.2.24 on 2025-09-28 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fedow_public', '0002_alter_assetfedowpublic_federated_with_and_more'),
        ('BaseBillet', '0170_remove_price_fedow_reward_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='fedow_reward_asset',
            field=models.ForeignKey(blank=True, help_text='Asset to send from the place to the user wallet.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='fedow_public.assetfedowpublic', verbose_name='Fedow Asset'),
        ),
    ]
