# Generated by Django 4.2.24 on 2025-10-04 11:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0171_price_fedow_reward_asset'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionalCode',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Descriptive name for the discount coupon.', max_length=200, verbose_name='Coupon name')),
                ('discount_rate', models.DecimalField(decimal_places=2, help_text='Discount percentage to apply (0-100).', max_digits=5, verbose_name='Discount rate (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Maximum number of times this code can be used. Leave empty for unlimited usage.', null=True, verbose_name='Usage limit')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Number of times this code has been used.', verbose_name='Usage count')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('product', models.ForeignKey(help_text='Product to which this discount coupon applies.', on_delete=django.db.models.deletion.CASCADE, related_name='promotional_codes', to='BaseBillet.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Promotional code',
                'verbose_name_plural': 'Promotional codes',
                'ordering': ('-date_created',),
            },
        ),
    ]
