# Generated by Django 4.2.24 on 2025-10-06 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0172_promotionalcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignearticle',
            name='promotional_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lignearticles', to='BaseBillet.promotionalcode', verbose_name='Promotional code'),
        ),
    ]
