# Generated by Django 4.2.24 on 2025-10-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0173_lignearticle_promotional_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionalcode',
            name='name',
            field=models.CharField(help_text='Descriptive name for the discount coupon.', max_length=200, unique=True, verbose_name='Coupon name'),
        ),
    ]
