# Generated by Django 4.2.24 on 2025-10-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0174_alter_promotionalcode_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='max_per_user',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Limit the quantity per user. Leave this field blank if the number is unlimited. if it is a recurring payment, the maximum is necessarily 1', null=True, verbose_name='Maximum per user'),
        ),
    ]
