# Generated by Django 4.2.24 on 2025-10-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0175_alter_price_max_per_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='stock',
            field=models.SmallIntegerField(blank=True, help_text='Number of valid subscriptions or memberships possible at the same time. Only works for membership or subscription-type products.', null=True, verbose_name='Simultaneous membership possible'),
        ),
    ]
