# Generated by Django 4.2.24 on 2025-10-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0176_alter_price_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productformfield',
            name='field_type',
            field=models.CharField(choices=[('ST', 'Short text'), ('LT', 'Long text'), ('SS', 'Single select (menu)'), ('SR', 'Single select (radio)'), ('MS', 'Multiple select'), ('BL', 'Switch on/off')], max_length=2, verbose_name='Field type'),
        ),
    ]
