# Generated by Django 4.2.24 on 2025-11-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0177_alter_productformfield_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_per_user',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Limit the quantity per user. Leave this field blank if the number is unlimited.', null=True, verbose_name='Maximum per user'),
        ),
    ]
