# Generated by Django 4.2.24 on 2025-11-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0178_product_max_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='show_gauge',
            field=models.BooleanField(default=False, verbose_name='Show gauge'),
        ),
        migrations.AlterField(
            model_name='price',
            name='max_per_user',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Limit the quantity per user. Leave this field blank if the number is unlimited.', null=True, verbose_name='Maximum per user'),
        ),
        migrations.AlterField(
            model_name='price',
            name='stock',
            field=models.SmallIntegerField(blank=True, help_text='Number of valid subscriptions or memberships possible simultaneously or maximum capacity for this price per event. Leave this field blank if the number is unlimited.', null=True, verbose_name='Maximum capacity'),
        ),
    ]
