# Generated by Django 4.2.24 on 2025-11-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0179_event_show_gauge_alter_price_max_per_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='reward_on_ticket_scanned',
            field=models.BooleanField(default=False, help_text='If enabled, after scanning a ticket, the user wallet will receive tokens.', verbose_name='Reward user wallet on ticket scanning'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Custom metadata', null=True, verbose_name='Metadata'),
        ),
    ]
