# Generated by Django 4.2.24 on 2025-11-14 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0181_event_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='current_iteration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='max_iteration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End of current subscription'),
        ),
        migrations.AlterField(
            model_name='price',
            name='adhesion_obligatoire',
            field=models.ForeignKey(blank=True, help_text='Rate available to suscribers only. Only works for reservation-type products. The rate will be visible if the user is logged in AND has paid their membership fees.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adhesion_obligatoire', to='BaseBillet.product', verbose_name='Subscription required'),
        ),
        migrations.AlterField(
            model_name='price',
            name='stock',
            field=models.SmallIntegerField(blank=True, help_text='Number of valid memberships possible simultaneously or maximum capacity for this price per event. Leave this field blank if the quantity is unlimited.', null=True, verbose_name='Maximum capacity'),
        ),
        migrations.AlterField(
            model_name='price',
            name='subscription_type',
            field=models.CharField(choices=[('N', 'Non applicable'), ('H', '1 hour'), ('D', '1 day'), ('W', '1 week'), ('M', '1 Month'), ('O', '1st of the month'), ('Y', '365 days'), ('C', 'Calendar year : 1st of January'), ('S', 'School year: 1st of September')], default='N', help_text='Valid membership period for each payment', max_length=1, verbose_name='Subscription duration'),
        ),
    ]
