# Generated by Django 4.2.24 on 2025-11-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0182_membership_current_iteration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='commitment',
            field=models.BooleanField(default=False, help_text='If checked, the user will not be able to cancel the automatic debit from their account. You will always be able to interrupt the automatic debit on the Stripe interface.', verbose_name='Commitment to the duration of the iteration.'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='state',
            field=models.CharField(choices=[('WP', 'Waiting for payment'), ('CA', 'Cancelled'), ('WA', 'Waiting for admin validation'), ('VA', 'Confirmed by admin, waiting for payment'), ('PA', 'Paid by user'), ('AU', 'Confirmed by system')], default='WP', max_length=2, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='paiement_stripe',
            name='status',
            field=models.CharField(choices=[('N', 'Payment link not generated'), ('O', 'Sent to Stripe'), ('W', 'Waiting for payment'), ('E', 'Expired'), ('P', 'Paid'), ('V', 'Paid and confirmed'), ('S', 'Paid but issues with LaBoutik sync'), ('C', 'Cancelled'), ('R', 'Refunded')], default='N', max_length=1, verbose_name='Order status'),
        ),
    ]
