# Generated by Django 4.2.24 on 2025-11-18 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0183_price_commitment_alter_membership_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='stripe_accept_sepa',
            field=models.BooleanField(default=False, help_text='SEPA direct debit is a deferred payment method. Please check the current rates on the Stripe website. Payment validation may take between 3 and 4 business days.', verbose_name='Accept SEPA payments'),
        ),
        migrations.AlterField(
            model_name='lignearticle',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('NA', 'Offered'), ('CC', 'Credit card: POS terminal'), ('CA', 'Cash'), ('CH', 'Check'), ('QR', 'QrCode or NFC'), ('TR', 'Bank transfer'), ('SF', 'Online: federated Stripe'), ('SN', 'Online: Stripe'), ('SR', 'Recurring: Stripe'), ('LE', 'Asset local fiat'), ('LG', 'Asset local gift')], max_length=2, null=True, verbose_name='Payment method'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('NA', 'Offered'), ('CC', 'Credit card: POS terminal'), ('CA', 'Cash'), ('CH', 'Check'), ('QR', 'QrCode or NFC'), ('TR', 'Bank transfer'), ('SF', 'Online: federated Stripe'), ('SN', 'Online: Stripe'), ('SR', 'Recurring: Stripe'), ('LE', 'Asset local fiat'), ('LG', 'Asset local gift')], max_length=2, null=True, verbose_name='Payment method'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('NA', 'Offered'), ('CC', 'Credit card: POS terminal'), ('CA', 'Cash'), ('CH', 'Check'), ('QR', 'QrCode or NFC'), ('TR', 'Bank transfer'), ('SF', 'Online: federated Stripe'), ('SN', 'Online: Stripe'), ('SR', 'Recurring: Stripe'), ('LE', 'Asset local fiat'), ('LG', 'Asset local gift')], max_length=2, null=True, verbose_name='Payment method'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sale_origin',
            field=models.CharField(choices=[('LP', 'Online platform'), ('LB', 'Cash register'), ('AD', 'Administration'), ('EX', 'External'), ('QR', 'QrCode or NFC')], default='LP', max_length=2, verbose_name='Payment source'),
        ),
    ]
