# Generated by Django 4.2.24 on 2025-11-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0184_configuration_stripe_accept_sepa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reservation_button_name',
            field=models.CharField(blank=True, help_text='If empty : I want to reserve one or more seats.', max_length=150, null=True, verbose_name='Button name for reservation'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='stripe_accept_sepa',
            field=models.BooleanField(default=False, help_text='SEPA Direct Debit is a deferred payment method. Please check the current rates on the Stripe website and activate it at https://dashboard.stripe.com/settings/payment_methods. Payment validation may take between 3 and 4 business days. Currently available only for subscriptions and memberships. Contact the team if you wish to extend this option.', verbose_name='Accept SEPA payments'),
        ),
        migrations.AlterField(
            model_name='lignearticle',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('NA', 'Offered'), ('CC', 'Credit card: POS terminal'), ('CA', 'Cash'), ('CH', 'Check'), ('QR', 'QrCode or NFC'), ('TR', 'Bank transfer'), ('SF', 'Online: federated Stripe'), ('SN', 'Online: Stripe CC'), ('SP', 'Online: Stripe SEPA'), ('SR', 'Recurring: Stripe'), ('LE', 'Asset local fiat'), ('LG', 'Asset local gift')], max_length=2, null=True, verbose_name='Payment method'),
        ),
        migrations.AlterField(
            model_name='lignearticle',
            name='status',
            field=models.CharField(choices=[('C', 'Cancelled'), ('R', 'Refunded'), ('O', 'Not sent to payment'), ('U', 'Not paid'), ('F', 'Free booking'), ('P', 'Paid but not confirmed'), ('V', 'Confirmed'), ('D', 'Failed')], default='O', max_length=3, verbose_name='Product entry status'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('NA', 'Offered'), ('CC', 'Credit card: POS terminal'), ('CA', 'Cash'), ('CH', 'Check'), ('QR', 'QrCode or NFC'), ('TR', 'Bank transfer'), ('SF', 'Online: federated Stripe'), ('SN', 'Online: Stripe CC'), ('SP', 'Online: Stripe SEPA'), ('SR', 'Recurring: Stripe'), ('LE', 'Asset local fiat'), ('LG', 'Asset local gift')], max_length=2, null=True, verbose_name='Payment method'),
        ),
        migrations.AlterField(
            model_name='paiement_stripe',
            name='status',
            field=models.CharField(choices=[('N', 'Payment link not generated'), ('O', 'Sent to Stripe'), ('W', 'Waiting for payment'), ('E', 'Expired'), ('F', 'Failed'), ('P', 'Paid'), ('V', 'Paid and confirmed'), ('S', 'Paid but issues with LaBoutik sync'), ('C', 'Cancelled'), ('R', 'Refunded')], default='N', max_length=1, verbose_name='Order status'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('NA', 'Offered'), ('CC', 'Credit card: POS terminal'), ('CA', 'Cash'), ('CH', 'Check'), ('QR', 'QrCode or NFC'), ('TR', 'Bank transfer'), ('SF', 'Online: federated Stripe'), ('SN', 'Online: Stripe CC'), ('SP', 'Online: Stripe SEPA'), ('SR', 'Recurring: Stripe'), ('LE', 'Asset local fiat'), ('LG', 'Asset local gift')], max_length=2, null=True, verbose_name='Payment method'),
        ),
    ]
