# Generated by Django 4.2.24 on 2025-11-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0185_event_reservation_button_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='subscription_type',
            field=models.CharField(choices=[('N', 'Non applicable'), ('H', '1 hour'), ('D', '1 day'), ('W', '1 week'), ('M', '1 Month'), ('O', '1st of the month'), ('Y', '365 days'), ('C', 'Calendar year : 1st of January'), ('S', 'School year: 1st of September'), ('L', 'valid for life')], default='N', help_text='Valid membership period for each payment', max_length=1, verbose_name='Subscription duration'),
        ),
    ]
