# Generated by Django 4.2.24 on 2025-12-08 09:17

from django.db import migrations, models
import django.db.models.deletion
import uuid
from decimal import Decimal


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0186_alter_price_subscription_type'),
    ]

    def create_default_tva_rates(apps, schema_editor):
        """
        Create standard VAT (TVA) rates for each schema.
        Idempotent: safe to re-run (e.g., after squash migrations).
        """
        Tva = apps.get_model('BaseBillet', 'Tva')

        # Standard FR rates + DOM rate added; 0 kept as "no VAT"
        rates = [
            Decimal('0.00'),
            Decimal('2.10'),
            Decimal('5.50'),
            Decimal('8.50'),
            Decimal('10.00'),
            Decimal('20.00'),
        ]

        for rate in rates:
            # tva_rate is unique, so get_or_create keeps it idempotent
            Tva.objects.get_or_create(tva_rate=rate)

    operations = [
        migrations.CreateModel(
            name='Tva',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tva_rate', models.DecimalField(decimal_places=2, max_digits=4, unique=True, verbose_name='TVA rate')),
            ],
            options={
                'verbose_name': 'TVA rate',
                'verbose_name_plural': 'TVA rate',
            },
        ),
        migrations.RunPython(create_default_tva_rates, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='federatedplace',
            name='membership_visible',
            field=models.BooleanField(default=False, help_text='Display memberships and subscriptions for this site.', verbose_name='Federate memberships and subscriptions'),
        ),
        migrations.AlterField(
            model_name='federatedplace',
            name='tag_exclude',
            field=models.ManyToManyField(blank=True, help_text='Exclude those tags.', related_name='excluded', to='BaseBillet.tag', verbose_name='Excluded tags'),
        ),
        migrations.AlterField(
            model_name='product',
            name='long_description',
            field=models.TextField(blank=True, help_text='Displayed only for membership/subscription products.', null=True, verbose_name='Long description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, help_text='Displayed only for membership/subscription products.', max_length=250, null=True, verbose_name='Short description'),
        ),
        migrations.AddField(
            model_name='product',
            name='tva',
            field=models.ForeignKey(blank=True, help_text='Leave if zero VAT', null=True, on_delete=django.db.models.deletion.PROTECT, to='BaseBillet.tva', verbose_name='TVA rate'),
        ),
    ]
