# Generated by Django 4.2.24 on 2025-12-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0187_tva_alter_federatedplace_membership_visible_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tva',
            options={'ordering': ['tva_rate'], 'verbose_name': 'TVA rate', 'verbose_name_plural': 'TVA rate'},
        ),
        migrations.AddField(
            model_name='externalapikey',
            name='sale',
            field=models.BooleanField(default=False, verbose_name='Sales'),
        ),
    ]
