# Generated by Django 4.2.24 on 2025-12-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0188_alter_tva_options_externalapikey_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='force_show_refill_button',
            field=models.BooleanField(default=False, verbose_name='Force show refill button'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='hide_refill_button',
            field=models.BooleanField(default=False, verbose_name='Hide refill button'),
        ),
    ]
