# Generated by Django 4.2.27 on 2025-12-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0189_configuration_force_show_refill_button_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='archiver',
            field=models.BooleanField(default=False),
        ),
    ]
