# Generated by Django 4.2.27 on 2025-12-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0190_membership_archiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('WP', 'En attente de paiement'), ('D', "Créé via l'administration"), ('I', 'Importé depuis un fichier'), ('L', 'Créé via la caisse'), ('AW', 'En attente de validation par un admin'), ('AV', 'Confirmé par un admin, en attente de paiement'), ('A', 'Payé en ligne'), ('O', 'Payé en ligne (récurrent)'), ('C', "Annulé par l'utilisateur"), ('AC', 'Annulé par un admin')], default='A', max_length=2, verbose_name='State'),
        ),
    ]
