# Generated by Django 4.2.27 on 2026-01-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0192_auto_20260116_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalapikey',
            name='membership',
            field=models.BooleanField(default=False, verbose_name='Memberships'),
        ),
    ]
