# Generated by Django 4.2.27 on 2026-02-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0193_externalapikey_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalapikey',
            name='crowd',
            field=models.BooleanField(default=False, verbose_name='Crowds'),
        ),
        migrations.AlterField(
            model_name='paiement_stripe',
            name='source',
            field=models.CharField(choices=[('Q', 'From QR code scan'), ('B', 'From API'), ('F', 'From ticketing app'), ('C', 'From Crowds app'), ('I', 'From invoice'), ('T', 'Stripe Transfert')], default='B', max_length=1, verbose_name='Order source'),
        ),
    ]
