# Generated by Django 4.2.27 on 2026-02-09 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0193_externalapikey_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='show_time',
            field=models.BooleanField(default=True),
        ),
    ]
