# Generated by Django 4.2.27 on 2026-02-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0194_externalapikey_crowd_alter_paiement_stripe_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='skin',
            field=models.CharField(choices=[('reunion', 'Réunion (thème par défaut)'), ('faire_festival', 'Faire Festival (thème brutaliste)')], default='reunion', help_text="Sélectionnez le thème visuel à utiliser pour l'affichage du site web.", max_length=50, verbose_name='Thème graphique du site'),
        ),
    ]
