# Generated by Django 4.2.27 on 2026-02-24 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0196_event_show_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='contribution_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Contribution'),
        ),
    ]
