# Generated by Django 4.2.28 on 2026-03-06 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0198_fix_free_lignearticle_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaBoutikAPIKey',
            fields=[
                ('id', models.CharField(editable=False, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('prefix', models.CharField(editable=False, max_length=8, unique=True)),
                ('hashed_key', models.CharField(editable=False, max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('name', models.CharField(default=None, help_text='A free-form name for the API key. Need not be unique. 50 characters max.', max_length=50)),
                ('revoked', models.BooleanField(blank=True, default=False, help_text='If the API key is revoked, clients cannot use it anymore. (This cannot be undone.)')),
                ('expiry_date', models.DateTimeField(blank=True, help_text='Once API key expires, clients cannot use it anymore.', null=True, verbose_name='Expires')),
            ],
            options={
                'verbose_name': 'LaBoutik API Key',
                'verbose_name_plural': 'LaBoutik API Keys',
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='event',
            name='thematique',
            field=models.ForeignKey(blank=True, help_text='Valide uniquement pour le thème graphique Faire Festival', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_thematique', to='BaseBillet.tag', verbose_name='Thématique'),
        ),
    ]
