# Generated by Django 4.2.27 on 2026-02-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0198_laboutikapikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='module_adhesion',
            field=models.BooleanField(default=False, verbose_name='Membership module'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='module_billetterie',
            field=models.BooleanField(default=True, verbose_name='Event ticketing module'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='module_caisse',
            field=models.BooleanField(default=False, verbose_name='POS & restaurant module'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='module_crowdfunding',
            field=models.BooleanField(default=False, verbose_name='Crowdfunding module'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='module_monnaie_locale',
            field=models.BooleanField(default=False, verbose_name='Local currency & cashless module'),
        ),
    ]
