# Generated by Django 4.2.28 on 2026-02-28 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0199_configuration_module_adhesion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Membership product',
                'verbose_name_plural': 'Membership products',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('BaseBillet.product',),
        ),
        migrations.CreateModel(
            name='TicketProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Ticket product',
                'verbose_name_plural': 'Ticket products',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('BaseBillet.product',),
        ),
    ]
