# Generated by Django 4.2.28 on 2026-03-06 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0199_credit_note_lignearticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignearticle',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lignearticles', to='BaseBillet.reservation', verbose_name='Reservation'),
        ),
    ]
