# Generated by Django 4.2.28 on 2026-03-04 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0198_fix_free_lignearticle_amount'),
        ('BaseBillet', '0200_membershipproduct_ticketproduct'),
    ]

    operations = [
    ]
