# Generated by Django 4.2.28 on 2026-03-06 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0201_backfill_lignearticle_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='adhesion_obligatoire',
        ),
        migrations.AddField(
            model_name='event',
            name='thematique',
            field=models.ForeignKey(blank=True, help_text='Valide uniquement pour le thème graphique Faire Festival', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_thematique', to='BaseBillet.tag', verbose_name='Thématique'),
        ),
        migrations.AddField(
            model_name='price',
            name='adhesions_obligatoires',
            field=models.ManyToManyField(blank=True, help_text='Rate available to subscribers only (OR logic: having at least one of the selected subscriptions is enough). Only works for reservation-type products. The rate will be visible if the user is logged in AND has paid at least one of these membership fees.', related_name='adhesions_obligatoires', to='BaseBillet.product', verbose_name='Subscriptions required'),
        ),
    ]
