# Generated by Django 4.2.28 on 2026-03-06 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0199_laboutikapikey_event_thematique'),
        ('BaseBillet', '0202_price_adhesion_fk_to_m2m'),
    ]

    operations = [
    ]
