# Generated by Django 4.2.28 on 2026-03-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0202_remove_price_adhesion_obligatoire_event_thematique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formbricksconfig',
            name='api_host',
            field=models.CharField(blank=True, default='', max_length=220),
        ),
    ]
