# Generated by Django 4.2.29 on 2026-04-06 08:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0203_formbricks_api_host_default_empty'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieProduct',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Category name displayed on the POS interface.', max_length=200, verbose_name='Name')),
                ('icon', models.CharField(blank=True, help_text='Icon name (e.g. Bootstrap Icons class).', max_length=50, null=True, verbose_name='Icon')),
                ('couleur_texte', models.CharField(blank=True, help_text='Hexadecimal color code for text (e.g. #FFFFFF).', max_length=7, null=True, verbose_name='Text color')),
                ('couleur_fond', models.CharField(blank=True, help_text='Hexadecimal color code for background (e.g. #000000).', max_length=7, null=True, verbose_name='Background color')),
                ('poid_liste', models.SmallIntegerField(default=0, help_text='Lower values are displayed first.', verbose_name='Display order')),
                ('cashless', models.BooleanField(default=False, help_text='Check if this category is for cashless token items.', verbose_name='Cashless')),
            ],
            options={
                'verbose_name': 'Product category',
                'verbose_name_plural': 'Product categories',
                'ordering': ('poid_liste', 'name'),
            },
        ),
        migrations.CreateModel(
            name='FutProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Keg product',
                'verbose_name_plural': 'Keg products',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('BaseBillet.product',),
        ),
        migrations.CreateModel(
            name='MembershipProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Membership product',
                'verbose_name_plural': 'Membership products',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('BaseBillet.product',),
        ),
        migrations.CreateModel(
            name='POSProduct',
            fields=[
            ],
            options={
                'verbose_name': 'POS product',
                'verbose_name_plural': 'POS products',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('BaseBillet.product',),
        ),
        migrations.CreateModel(
            name='TicketProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Ticket product',
                'verbose_name_plural': 'Ticket products',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('BaseBillet.product',),
        ),
        migrations.AddField(
            model_name='configuration',
            name='module_adhesion',
            field=models.BooleanField(default=False, verbose_name='Membership module'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='module_billetterie',
            field=models.BooleanField(default=True, verbose_name='Event ticketing module'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='module_caisse',
            field=models.BooleanField(default=False, verbose_name='POS & restaurant module'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='module_crowdfunding',
            field=models.BooleanField(default=False, verbose_name='Crowdfunding module'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='module_inventaire',
            field=models.BooleanField(default=False, help_text='Enable stock management for POS products.', verbose_name='Inventory module'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='module_monnaie_locale',
            field=models.BooleanField(default=False, verbose_name='Local currency & cashless module'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='module_tireuse',
            field=models.BooleanField(default=False, help_text='Enable connected beer tap management (controlvanne).', verbose_name='Connected tap module'),
        ),
        migrations.AddField(
            model_name='lignearticle',
            name='hmac_hash',
            field=models.CharField(blank=True, default='', help_text='HMAC-SHA256 de cette ligne, chainee avec la precedente. / HMAC-SHA256 of this line, chained with the previous one.', max_length=64, verbose_name='HMAC hash'),
        ),
    ]
