# Generated by Django 4.2.28 on 2026-03-12 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fedow_core', '0001_initial'),
        ('BaseBillet', '0203_categorieproduct_membershipproduct_posproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='asset',
            field=models.ForeignKey(blank=True, help_text='If set, the price is in asset units (tokens). If empty, the price is in euros.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prices', to='fedow_core.asset', verbose_name='Asset'),
        ),
        migrations.AddField(
            model_name='product',
            name='besoin_tag_id',
            field=models.BooleanField(default=False, help_text='An NFC card must be scanned before this product can be added to the cart.', verbose_name='Requires NFC tag'),
        ),
        migrations.AddField(
            model_name='product',
            name='couleur_fond_pos',
            field=models.CharField(blank=True, help_text='Hexadecimal color for the product button background (e.g. #3B82F6).', max_length=7, null=True, verbose_name='POS background color'),
        ),
        migrations.AddField(
            model_name='product',
            name='couleur_texte_pos',
            field=models.CharField(blank=True, help_text='Hexadecimal color for the product button text (e.g. #FFFFFF).', max_length=7, null=True, verbose_name='POS text color'),
        ),
        migrations.AddField(
            model_name='product',
            name='fractionne',
            field=models.BooleanField(default=False, help_text='Allow partial/split payment for this product at the POS.', verbose_name='Split payment allowed'),
        ),
        migrations.AddField(
            model_name='product',
            name='groupe_pos',
            field=models.CharField(blank=True, help_text='Group name to cluster buttons together on the POS interface.', max_length=50, null=True, verbose_name='POS button group'),
        ),
        migrations.AddField(
            model_name='product',
            name='icon_pos',
            field=models.CharField(blank=True, help_text='Icon name for the POS button (e.g. Bootstrap Icons class).', max_length=50, null=True, verbose_name='POS icon'),
        ),
        migrations.AddField(
            model_name='product',
            name='methode_caisse',
            field=models.CharField(blank=True, choices=[('VT', 'Sale'), ('RE', 'Euro top-up'), ('RC', 'Gift top-up'), ('TM', 'Time top-up'), ('AD', 'Membership'), ('CR', 'Deposit return'), ('VC', 'Empty card'), ('FR', 'Split payment'), ('BI', 'Ticket'), ('FD', 'Loyalty')], help_text='Payment/action method at the cash register. Leave empty if this product is not sold at the POS.', max_length=2, null=True, verbose_name='POS method'),
        ),
        migrations.AddField(
            model_name='categorieproduct',
            name='tva',
            field=models.ForeignKey(blank=True, help_text='Default VAT rate applied to products in this category.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='BaseBillet.tva', verbose_name='Default VAT rate'),
        ),
        migrations.AddField(
            model_name='product',
            name='categorie_pos',
            field=models.ForeignKey(blank=True, help_text='Display category on the POS interface.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_pos', to='BaseBillet.categorieproduct', verbose_name='POS category'),
        ),
    ]
