# Generated by Django 4.2.30 on 2026-05-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0203_formbricks_api_host_default_empty'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='module_adhesion',
            field=models.BooleanField(default=True, verbose_name='Membership module'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='module_billetterie',
            field=models.BooleanField(default=True, verbose_name='Event ticketing module'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='module_booking',
            field=models.BooleanField(default=False, help_text='Enable resource booking (rooms, equipment, coworking desks).', verbose_name='Booking module'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='module_caisse',
            field=models.BooleanField(default=False, verbose_name='POS & restaurant module'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='module_crowdfunding',
            field=models.BooleanField(default=True, verbose_name='Crowdfunding module'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='module_federation',
            field=models.BooleanField(default=True, verbose_name='Federation module'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='module_inventaire',
            field=models.BooleanField(default=False, help_text='Enable stock management for POS products.', verbose_name='Inventory module'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='module_monnaie_locale',
            field=models.BooleanField(default=False, verbose_name='Local currency & cashless module'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='module_tireuse',
            field=models.BooleanField(default=False, help_text='Enable connected beer tap management (controlvanne).', verbose_name='Connected tap module'),
        ),
    ]
