# Generated by Django 4.2.28 on 2026-03-17 08:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fedow_core', '0001_initial'),
        ('BaseBillet', '0203_formbricks_api_host_default_empty'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Membership product',
                'verbose_name_plural': 'Membership products',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('BaseBillet.product',),
        ),
        migrations.CreateModel(
            name='POSProduct',
            fields=[
            ],
            options={
                'verbose_name': 'POS product',
                'verbose_name_plural': 'POS products',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('BaseBillet.product',),
        ),
        migrations.CreateModel(
            name='TicketProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Ticket product',
                'verbose_name_plural': 'Ticket products',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('BaseBillet.product',),
        ),
        migrations.AddField(
            model_name='configuration',
            name='module_adhesion',
            field=models.BooleanField(default=False, verbose_name='Membership module'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='module_billetterie',
            field=models.BooleanField(default=True, verbose_name='Event ticketing module'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='module_caisse',
            field=models.BooleanField(default=False, verbose_name='POS & restaurant module'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='module_crowdfunding',
            field=models.BooleanField(default=False, verbose_name='Crowdfunding module'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='module_monnaie_locale',
            field=models.BooleanField(default=False, verbose_name='Local currency & cashless module'),
        ),
        migrations.AddField(
            model_name='price',
            name='asset',
            field=models.ForeignKey(blank=True, help_text='If set, the price is in asset units (tokens). If empty, the price is in euros.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prices', to='fedow_core.asset', verbose_name='Asset'),
        ),
        migrations.AddField(
            model_name='product',
            name='besoin_tag_id',
            field=models.BooleanField(default=False, help_text='An NFC card must be scanned before this product can be added to the cart.', verbose_name='Requires NFC tag'),
        ),
        migrations.AddField(
            model_name='product',
            name='couleur_fond_pos',
            field=models.CharField(blank=True, help_text='Hexadecimal color for the product button background (e.g. #3B82F6).', max_length=7, null=True, verbose_name='POS background color'),
        ),
        migrations.AddField(
            model_name='product',
            name='couleur_texte_pos',
            field=models.CharField(blank=True, help_text='Hexadecimal color for the product button text (e.g. #FFFFFF).', max_length=7, null=True, verbose_name='POS text color'),
        ),
        migrations.AddField(
            model_name='product',
            name='fractionne',
            field=models.BooleanField(default=False, help_text='Allow partial/split payment for this product at the POS.', verbose_name='Split payment allowed'),
        ),
        migrations.AddField(
            model_name='product',
            name='groupe_pos',
            field=models.CharField(blank=True, help_text='Group name to cluster buttons together on the POS interface.', max_length=50, null=True, verbose_name='POS button group'),
        ),
        migrations.AddField(
            model_name='product',
            name='icon_pos',
            field=models.CharField(blank=True, help_text='Icon name for the POS button (e.g. Bootstrap Icons class).', max_length=50, null=True, verbose_name='POS icon'),
        ),
        migrations.AddField(
            model_name='product',
            name='methode_caisse',
            field=models.CharField(blank=True, choices=[('VT', 'Sale'), ('RE', 'Euro top-up'), ('RC', 'Gift top-up'), ('TM', 'Time top-up'), ('AD', 'Membership'), ('CR', 'Deposit return'), ('VC', 'Empty card'), ('FR', 'Split payment'), ('BI', 'Ticket'), ('FD', 'Loyalty')], help_text='Payment/action method at the cash register. Leave empty if this product is not sold at the POS.', max_length=2, null=True, verbose_name='POS method'),
        ),
        migrations.CreateModel(
            name='CategorieProduct',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Category name displayed on the POS interface.', max_length=200, verbose_name='Name')),
                ('icon', models.CharField(blank=True, help_text='Icon name (e.g. Bootstrap Icons class).', max_length=50, null=True, verbose_name='Icon')),
                ('couleur_texte', models.CharField(blank=True, help_text='Hexadecimal color code for text (e.g. #FFFFFF).', max_length=7, null=True, verbose_name='Text color')),
                ('couleur_fond', models.CharField(blank=True, help_text='Hexadecimal color code for background (e.g. #000000).', max_length=7, null=True, verbose_name='Background color')),
                ('poid_liste', models.SmallIntegerField(default=0, help_text='Lower values are displayed first.', verbose_name='Display order')),
                ('cashless', models.BooleanField(default=False, help_text='Check if this category is for cashless token items.', verbose_name='Cashless')),
                ('tva', models.ForeignKey(blank=True, help_text='Default VAT rate applied to products in this category.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='BaseBillet.tva', verbose_name='Default VAT rate')),
            ],
            options={
                'verbose_name': 'Product category',
                'verbose_name_plural': 'Product categories',
                'ordering': ('poid_liste', 'name'),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='categorie_pos',
            field=models.ForeignKey(blank=True, help_text='Display category on the POS interface.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_pos', to='BaseBillet.categorieproduct', verbose_name='POS category'),
        ),
    ]
