# Generated by Django 4.2.30 on 2026-05-12 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0204_configuration_module_adhesion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FutProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Keg product',
                'verbose_name_plural': 'Keg products',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('BaseBillet.product',),
        ),
        migrations.CreateModel(
            name='MembershipProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Membership product',
                'verbose_name_plural': 'Membership products',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('BaseBillet.product',),
        ),
        migrations.CreateModel(
            name='POSProduct',
            fields=[
            ],
            options={
                'verbose_name': 'POS product',
                'verbose_name_plural': 'POS products',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('BaseBillet.product',),
        ),
        migrations.CreateModel(
            name='TicketProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Ticket product',
                'verbose_name_plural': 'Ticket products',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('BaseBillet.product',),
        ),
    ]
