# Generated by Django 4.2.29 on 2026-04-06 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0204_categorieproduct_futproduct_membershipproduct_and_more'),
        ('laboutik', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignearticle',
            name='point_de_vente',
            field=models.ForeignKey(blank=True, help_text='Point de vente ou cette vente a ete realisee. / Point of sale where this sale was made.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_articles', to='laboutik.pointdevente', verbose_name='Point of sale'),
        ),
        migrations.AddField(
            model_name='lignearticle',
            name='previous_hmac',
            field=models.CharField(blank=True, default='', help_text='HMAC de la LigneArticle precedente dans la chaine. / HMAC of the previous LigneArticle in the chain.', max_length=64, verbose_name='Previous HMAC'),
        ),
        migrations.AddField(
            model_name='lignearticle',
            name='total_ht',
            field=models.IntegerField(default=0, help_text='Total hors taxes en centimes. Calcule : TTC / (1 + taux_tva/100). / Total excluding tax in cents. Computed: TTC / (1 + vat_rate/100).', verbose_name='Total HT (cents)'),
        ),
        migrations.AddField(
            model_name='lignearticle',
            name='uuid_transaction',
            field=models.UUIDField(blank=True, db_index=True, help_text='Groups all lines from the same payment for reprinting.', null=True, verbose_name='Transaction ID'),
        ),
        migrations.AddField(
            model_name='lignearticle',
            name='weight_quantity',
            field=models.IntegerField(blank=True, help_text='Amount entered by cashier in stock unit (g or cl). Null for standard sales.', null=True, verbose_name='Quantity by weight/volume'),
        ),
    ]
