# Generated by Django 4.2.30 on 2026-05-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0204_configuration_module_adhesion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='module_federation',
            field=models.BooleanField(default=False, verbose_name='Federation module'),
        ),
    ]
