# Generated by Django 4.2.28 on 2026-03-18 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0204_membershipproduct_posproduct_ticketproduct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='groupe_pos',
        ),
    ]
