# Generated by Django 4.2.30 on 2026-05-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0205_futproduct_membershipproduct_posproduct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='poids',
            field=models.PositiveSmallIntegerField(default=0, help_text='Smallest appears first.', verbose_name='Display order'),
        ),
    ]
