# Generated by Django 4.2.28 on 2026-03-24 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboutik', '0006_printer_laboutikconfiguration_sunmi_app_id_and_more'),
        ('BaseBillet', '0205_remove_groupe_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorieproduct',
            name='printer',
            field=models.ForeignKey(blank=True, help_text='Printer for order tickets (kitchen, bar). When an order contains products from this category, the ticket is sent to this printer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories_produit', to='laboutik.printer', verbose_name='Order printer'),
        ),
    ]
