# Generated by Django 4.2.28 on 2026-03-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0206_categorieproduct_printer'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignearticle',
            name='uuid_transaction',
            field=models.UUIDField(blank=True, db_index=True, help_text='Groups all lines from the same payment for reprinting.', null=True, verbose_name='Transaction ID'),
        ),
    ]
