# Generated by Django 4.2.30 on 2026-05-17 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0206_alter_product_poids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postaladdress',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS coordinate: latitude.', max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='postaladdress',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS coordinate: longitude.', max_digits=9, null=True, verbose_name='Longitude'),
        ),
    ]
