# Generated by Django 4.2.29 on 2026-05-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0206_alter_product_poids'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='rapport_emails',
            field=models.TextField(blank=True, default='', help_text='Comma-separated emails. Leave empty to disable automatic sending.', verbose_name='Recipient emails for closure reports'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='rapport_periodicite',
            field=models.CharField(choices=[('NONE', 'No email'), ('J', 'Daily'), ('H', 'Weekly'), ('M', 'Monthly'), ('A', 'Yearly')], default='NONE', max_length=4, verbose_name='Closure report sending frequency'),
        ),
    ]
