# Generated by Django 4.2.29 on 2026-04-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0206_price_asset_price_contenance_price_poids_mesure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='contenance',
            field=models.PositiveIntegerField(blank=True, help_text="Stock quantity consumed per unit sold (in stock unit). Use this when selling by unit but decrementing stock by weight/volume. E.g.: pint=50 (cl), half=25 (cl), portion=150 (g). Empty = 1 unit. Incompatible with 'Sale by weight/volume' (where the cashier enters the exact quantity).", null=True, verbose_name='Contenance'),
        ),
        migrations.AlterField(
            model_name='price',
            name='poids_mesure',
            field=models.BooleanField(default=False, help_text='If checked, the cashier enters the weight or volume at each sale. The price is per kg (grams) or per liter (centiliters). Stock is decremented by the exact quantity entered.', verbose_name='Sale by weight/volume'),
        ),
    ]
