# Generated by Django 4.2.30 on 2026-05-18 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0207_configuration_rapport_emails_and_more'),
        ('BaseBillet', '0207_fix_postaladdress_latlng_precision'),
    ]

    operations = [
    ]
