# Generated by Django 4.2.28 on 2026-03-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0207_lignearticle_uuid_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignearticle',
            name='hmac_hash',
            field=models.CharField(blank=True, default='', help_text='HMAC-SHA256 de cette ligne, chainee avec la precedente. / HMAC-SHA256 of this line, chained with the previous one.', max_length=64, verbose_name='HMAC hash'),
        ),
        migrations.AddField(
            model_name='lignearticle',
            name='previous_hmac',
            field=models.CharField(blank=True, default='', help_text='HMAC de la LigneArticle precedente dans la chaine. / HMAC of the previous LigneArticle in the chain.', max_length=64, verbose_name='Previous HMAC'),
        ),
        migrations.AddField(
            model_name='lignearticle',
            name='total_ht',
            field=models.IntegerField(default=0, help_text='Total hors taxes en centimes. Calcule : TTC / (1 + taux_tva/100). / Total excluding tax in cents. Computed: TTC / (1 + vat_rate/100).', verbose_name='Total HT (cents)'),
        ),
    ]
