# Generated by Django 4.2.29 on 2026-04-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0207_update_help_texts_poids_contenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='module_booking',
            field=models.BooleanField(default=False, help_text='Enable resource booking (rooms, equipment, coworking desks).', verbose_name='Booking module'),
        ),
    ]
