# Generated by Django 4.2.29 on 2026-04-08 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fedow_core', '0001_initial'),
        ('BaseBillet', '0207_update_help_texts_poids_contenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='asset',
            field=models.ForeignKey(blank=True, help_text='Asset fedow lie a ce produit de recharge. / Fedow asset linked to this top-up product.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='fedow_core.asset', verbose_name='Asset'),
        ),
    ]
