# Generated by Django 4.2.29 on 2026-04-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0208_product_asset_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='non_fiduciaire',
            field=models.BooleanField(default=False, help_text='If checked, the price is in tokens (time, loyalty, etc.) instead of euros. You must select the asset below.', verbose_name='Non-fiduciary price'),
        ),
    ]
