# Generated by Django 4.2.30 on 2026-05-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0208_configuration_rapport_emails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_proposal',
            field=models.BooleanField(default=False, help_text='Event submitted via the public proposal wizard, awaiting admin validation.', verbose_name='Public proposal'),
        ),
    ]
