# Generated by Django 4.2.28 on 2026-03-30 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboutik', '0009_add_hmac_and_report_config'),
        ('BaseBillet', '0208_add_hmac_and_total_ht_on_lignearticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignearticle',
            name='point_de_vente',
            field=models.ForeignKey(blank=True, help_text='Point de vente ou cette vente a ete realisee. / Point of sale where this sale was made.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_articles', to='laboutik.pointdevente', verbose_name='Point of sale'),
        ),
    ]
