# Generated by Django 4.2.30 on 2026-05-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0209_event_is_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='module_agenda_participatif',
            field=models.BooleanField(default=False, verbose_name='Participatory agenda module'),
        ),
    ]
