# Generated by Django 4.2.29 on 2026-04-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0209_price_non_fiduciaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignearticle',
            name='sale_origin',
            field=models.CharField(choices=[('LP', 'Online platform'), ('LB', 'Cash register'), ('LT', 'LaBoutik (test mode)'), ('AD', 'Administration'), ('EX', 'External'), ('QR', 'QrCode online'), ('NF', 'NFC online'), ('AP', 'API'), ('WK', 'Webhook Stripe'), ('TI', 'Connected tap')], default='LP', max_length=2, verbose_name='Payment source'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sale_origin',
            field=models.CharField(choices=[('LP', 'Online platform'), ('LB', 'Cash register'), ('LT', 'LaBoutik (test mode)'), ('AD', 'Administration'), ('EX', 'External'), ('QR', 'QrCode online'), ('NF', 'NFC online'), ('AP', 'API'), ('WK', 'Webhook Stripe'), ('TI', 'Connected tap')], default='LP', max_length=2, verbose_name='Payment source'),
        ),
    ]
