# Generated by Django 4.2.29 on 2026-03-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0209_add_point_de_vente_on_lignearticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prix_achat',
            field=models.IntegerField(default=0, help_text="Prix d'achat unitaire en centimes. Utilise pour le calcul du benefice estime. / Unit purchase price in cents. Used for estimated profit calculation.", verbose_name='Purchase price (cents)'),
        ),
        migrations.AlterField(
            model_name='lignearticle',
            name='sale_origin',
            field=models.CharField(choices=[('LP', 'Online platform'), ('LB', 'Cash register'), ('LT', 'LaBoutik (test mode)'), ('AD', 'Administration'), ('EX', 'External'), ('QR', 'QrCode online'), ('NF', 'NFC online'), ('AP', 'API'), ('WK', 'Webhook Stripe')], default='LP', max_length=2, verbose_name='Payment source'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sale_origin',
            field=models.CharField(choices=[('LP', 'Online platform'), ('LB', 'Cash register'), ('LT', 'LaBoutik (test mode)'), ('AD', 'Administration'), ('EX', 'External'), ('QR', 'QrCode online'), ('NF', 'NFC online'), ('AP', 'API'), ('WK', 'Webhook Stripe')], default='LP', max_length=2, verbose_name='Payment source'),
        ),
    ]
