# Generated by Django 4.2.29 on 2026-04-02 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboutik', '0018_comptecomptable_mappingmoyendepaiement'),
        ('BaseBillet', '0210_prix_achat_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorieproduct',
            name='compte_comptable',
            field=models.ForeignKey(blank=True, help_text="Compte comptable de vente associe a cette categorie. Utilise pour l'export FEC et CSV comptable. / Sales accounting code for this category. Used for FEC and CSV accounting export.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories_produit', to='laboutik.comptecomptable', verbose_name='Accounting code'),
        ),
    ]
