# Generated by Django 4.2.30 on 2026-04-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0210_alter_lignearticle_sale_origin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='methode_caisse',
            field=models.CharField(blank=True, choices=[('VT', 'Sale'), ('RE', 'Euro top-up'), ('RC', 'Gift top-up'), ('TM', 'Time top-up'), ('AD', 'Membership'), ('CR', 'Deposit return'), ('VC', 'Empty card'), ('FR', 'Split payment'), ('BI', 'Ticket'), ('FD', 'Loyalty'), ('VR', 'Bank transfer received')], help_text='Payment/action method at the cash register. Leave empty if this product is not sold at the POS.', max_length=2, null=True, verbose_name='POS method'),
        ),
    ]
