# Generated by Django 4.2.30 on 2026-05-21 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fedow_public', '0003_assetfedowpublic_archive'),
        ('BaseBillet', '0210_configuration_module_agenda_participatif'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalapikey',
            name='gift_asset',
            field=models.ForeignKey(blank=True, help_text='If set, this key can top-up this gift asset via /api/v2/wallet-refills/.', limit_choices_to={'category': 'TNF'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_keys_gift_refill', to='fedow_public.assetfedowpublic', verbose_name='Gift token refill (asset)'),
        ),
    ]
