# Generated by Django 4.2.30 on 2026-05-21 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fedow_public', '0003_assetfedowpublic_archive'),
        ('BaseBillet', '0211_externalapikey_gift_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalapikey',
            name='gift_asset',
            field=models.ForeignKey(blank=True, help_text='If set, this key can top-up this asset (gift, time, loyalty or badge — non-fiat) via /api/v2/wallet-refills/.', limit_choices_to={'category__in': ['TNF', 'TIM', 'FID', 'BDG']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_keys_gift_refill', to='fedow_public.assetfedowpublic', verbose_name='Wallet refill (asset)'),
        ),
    ]
