# Generated by Django 4.2.29 on 2026-04-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0211_categorieproduct_compte_comptable'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='scanned_at',
            field=models.DateTimeField(blank=True, help_text='Date et heure du scan / Date and time of scan', null=True),
        ),
    ]
