# Generated by Django 4.2.30 on 2026-04-15 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BaseBillet', '0211_alter_product_methode_caisse'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboutikapikey',
            name='user',
            field=models.OneToOneField(blank=True, help_text='TermUser linked (V2 bridge flow). Null for legacy V1 keys.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laboutik_api_key', to=settings.AUTH_USER_MODEL, verbose_name='Terminal user'),
        ),
    ]
