# Generated by Django 4.2.30 on 2026-05-24 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0212_alter_externalapikey_gift_asset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name': 'Adhésion / Abonnement / Pass', 'verbose_name_plural': 'Adhésion / Abonnement / Pass'},
        ),
    ]
