# Generated by Django 4.2.30 on 2026-04-17 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BaseBillet', '0212_laboutikapikey_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email_acheteur', models.EmailField(max_length=254, verbose_name='Buyer email')),
                ('first_name', models.CharField(max_length=200, verbose_name='First name')),
                ('last_name', models.CharField(max_length=200, verbose_name='Last name')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending payment'), ('PAID', 'Paid'), ('CANCELED', 'Canceled'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=10, verbose_name='Order status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid at')),
                ('paiement_stripe', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commande_obj', to='BaseBillet.paiement_stripe', verbose_name='Stripe payment')),
                ('promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='BaseBillet.promotionalcode', verbose_name='Promotional code')),
                ('user', models.ForeignKey(help_text='Utilisateur acheteur (résolu par email au checkout). / Buyer user (resolved by email at checkout).', on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to=settings.AUTH_USER_MODEL, verbose_name='Buyer')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='membership',
            name='commande',
            field=models.ForeignKey(blank=True, help_text="Renseignée uniquement si l'adhésion a été créée via un panier multi-items. / Only set if the membership was created via a multi-item cart.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships_commande', to='BaseBillet.commande', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='commande',
            field=models.ForeignKey(blank=True, help_text='Renseignée uniquement si la reservation a été créée via un panier multi-items. / Only set if the reservation was created via a multi-item cart.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='BaseBillet.commande', verbose_name='Order'),
        ),
    ]
