# Generated by Django 4.2.29 on 2026-04-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0212_ticket_scanned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='module_inventaire',
            field=models.BooleanField(default=False, help_text='Enable stock management for POS products.', verbose_name='Inventory module'),
        ),
        migrations.AddField(
            model_name='price',
            name='contenance',
            field=models.PositiveIntegerField(blank=True, help_text="Quantity consumed per unit sold, in the stock's base unit. E.g.: pint=50 (cl), half=25 (cl), portion=150 (g). Empty = 1 unit by default.", null=True, verbose_name='Serving size'),
        ),
    ]
