# Generated by Django 4.2.29 on 2026-04-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0213_configuration_module_inventaire_price_contenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignearticle',
            name='weight_quantity',
            field=models.IntegerField(blank=True, help_text='Amount entered by cashier in stock unit (g or cl). Null for standard sales.', null=True, verbose_name='Quantity by weight/volume'),
        ),
        migrations.AddField(
            model_name='price',
            name='poids_mesure',
            field=models.BooleanField(default=False, help_text='If checked, the cashier enters the weight or volume at each sale. The price is per kg (for grams) or per liter (for centiliters).', verbose_name='Sale by weight/volume'),
        ),
        migrations.AlterField(
            model_name='price',
            name='contenance',
            field=models.PositiveIntegerField(blank=True, help_text="Quantité consommée par unité vendue, dans l'unité du stock. Ex : pinte=50 (cl), demi=25 (cl), portion=150 (g). Vide = 1 unité par défaut.", null=True, verbose_name='Contenance'),
        ),
    ]
