# Generated by Django 4.2.30 on 2026-06-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0213_alter_membership_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='newsletter',
            field=models.BooleanField(default=False, verbose_name="I want to receive the collective's newsletter."),
        ),
    ]
