# Generated by Django 4.2.30 on 2026-04-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0213_commande_and_fks'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement_stripe',
            name='checkout_session_url',
            field=models.URLField(blank=True, help_text="URL Stripe Checkout persistée après création — permet de rediriger l'utilisateur vers le paiement sans rappeler Stripe. / Stripe Checkout URL persisted after creation — allows redirecting the user to payment without recalling Stripe.", max_length=500, null=True, verbose_name='Stripe checkout URL'),
        ),
    ]
