# Generated by Django 4.2.29 on 2026-04-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0214_price_poids_mesure'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='module_tireuse',
            field=models.BooleanField(default=False, help_text='Enable connected beer tap management (controlvanne).', verbose_name='Connected tap module'),
        ),
    ]
