# Generated by Django 4.2.30 on 2026-06-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0214_alter_membership_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='FederationConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afficher_lieux_sans_adresse', models.BooleanField(default=True, help_text="Si activé, la liste inclut aussi les lieux du réseau sans adresse géolocalisée (ils n'apparaissent pas sur la carte). [Effectif après la Phase B — modification du JS.]", verbose_name='Afficher les lieux sans adresse')),
                ('afficher_seulement_lieux_avec_event', models.BooleanField(default=False, help_text='Si activé, seuls les lieux ayant au moins un événement publié à venir sont affichés.', verbose_name='Afficher seulement les lieux avec un événement à venir')),
                ('afficher_lieux_entrants', models.BooleanField(default=True, help_text="Si activé, affiche aussi les lieux qui m'ont ajouté à leur réseau, même si je ne les ai pas ajoutés au mien.", verbose_name='Afficher les lieux qui me fédèrent')),
                ('texte_introduction', models.TextField(blank=True, help_text='Texte affiché en haut de la page Réseau local.', null=True, verbose_name="Texte d'introduction")),
                ('tri_des_lieux', models.CharField(choices=[('alpha', 'Alphabétique'), ('events', 'Par prochain événement')], default='alpha', help_text="Ordre d'affichage de la liste des lieux.", max_length=10, verbose_name='Tri des lieux')),
            ],
            options={
                'verbose_name': 'Options de fédération',
                'verbose_name_plural': 'Options de fédération',
            },
        ),
    ]
