# Generated by Django 4.2.30 on 2026-04-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0214_paiement_stripe_checkout_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement_stripe',
            name='source',
            field=models.CharField(choices=[('Q', 'From QR code scan'), ('B', 'From API'), ('F', 'From ticketing app'), ('C', 'From Crowds app'), ('I', 'From invoice'), ('T', 'Stripe Transfert'), ('R', 'Cashless refill')], default='B', max_length=1, verbose_name='Order source'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categorie_article',
            field=models.CharField(choices=[('N', 'Select a category'), ('B', 'Ticket booking'), ('F', 'Free booking'), ('A', 'Subscription or membership'), ('G', 'Punchclock'), ('E', 'FED cashless refill'), ('Q', 'QrCode paiement on my account'), ('U', 'Keg (connected tap)')], default='N', max_length=3, verbose_name='Product type'),
        ),
        migrations.AlterField(
            model_name='productsold',
            name='categorie_article',
            field=models.CharField(choices=[('N', 'Select a category'), ('B', 'Ticket booking'), ('F', 'Free booking'), ('A', 'Subscription or membership'), ('G', 'Punchclock'), ('E', 'FED cashless refill'), ('Q', 'QrCode paiement on my account'), ('U', 'Keg (connected tap)')], default='N', max_length=3, verbose_name='Product type'),
        ),
    ]
