# Generated by Django 4.2.30 on 2026-04-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0215_alter_paiement_stripe_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement_stripe',
            name='checkout_session_url',
            field=models.URLField(blank=True, help_text="URL Stripe Checkout persistée après création — permet de rediriger l'utilisateur vers le paiement sans rappeler Stripe. / Stripe Checkout URL persisted after creation — allows redirecting the user to payment without recalling Stripe.", max_length=1024, null=True, verbose_name='Stripe checkout URL'),
        ),
    ]
