# Generated by Django 4.2.30 on 2026-06-01 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0215_federationconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='proposition_anonyme_autorisee',
            field=models.BooleanField(default=False, help_text='Si activé, les visiteurs non connectés peuvent proposer des évènements (nécessite le module Agenda participatif).', verbose_name='Autoriser les propositions anonymes'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='tag_auto_proposition',
            field=models.ForeignKey(blank=True, help_text="Tag ajouté automatiquement aux évènements proposés via l'agenda participatif.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_tag_auto_proposition', to='BaseBillet.tag', verbose_name='Tag automatique des évènements proposés'),
        ),
        migrations.AlterField(
            model_name='federationconfiguration',
            name='afficher_lieux_sans_adresse',
            field=models.BooleanField(default=True, help_text='Si activé, la liste inclut aussi les lieux du réseau sans adresse géolocalisée (ils apparaissent dans la liste mais pas sur la carte).', verbose_name='Afficher les lieux sans adresse'),
        ),
    ]
