# Generated by Django 4.2.29 on 2026-04-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0215_add_module_tireuse'),
    ]

    operations = [
        migrations.CreateModel(
            name='FutProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Keg product',
                'verbose_name_plural': 'Keg products',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('BaseBillet.product',),
        ),
        migrations.AlterField(
            model_name='product',
            name='categorie_article',
            field=models.CharField(choices=[('N', 'Select a category'), ('B', 'Ticket booking'), ('F', 'Free booking'), ('A', 'Subscription or membership'), ('G', 'Punchclock'), ('Q', 'QrCode paiement on my account'), ('U', 'Keg (connected tap)')], default='N', max_length=3, verbose_name='Product type'),
        ),
        migrations.AlterField(
            model_name='productsold',
            name='categorie_article',
            field=models.CharField(choices=[('N', 'Select a category'), ('B', 'Ticket booking'), ('F', 'Free booking'), ('A', 'Subscription or membership'), ('G', 'Punchclock'), ('Q', 'QrCode paiement on my account'), ('U', 'Keg (connected tap)')], default='N', max_length=3, verbose_name='Product type'),
        ),
    ]
