# Generated by Django 4.2.30 on 2026-06-02 06:09

from django.db import connection, migrations, models
import django.db.models.deletion


def copier_reglages_agenda_vers_federation(apps, schema_editor):
    """
    Recopie les reglages d'agenda participatif depuis Configuration vers
    FederationConfiguration, pour le tenant courant.
    / Copy participatory-agenda settings from Configuration to
    FederationConfiguration, for the current tenant.

    IMPORTANT : Configuration et FederationConfiguration sont des TENANT_APPS.
    Leurs tables n'existent pas dans le schema public. On sort immediatement
    si on tourne dans public.
    / IMPORTANT: both models are TENANT_APPS. Their tables don't exist in the
    public schema. Return immediately when running in public.

    A ce stade de la migration : les champs existent ENCORE sur Configuration
    (RemoveField n'est pas encore passe) et DEJA sur FederationConfiguration
    (AddField vient de passer).
    / At this point: fields still exist on Configuration (RemoveField not yet
    applied) and already exist on FederationConfiguration (AddField applied).
    """
    schema_courant = connection.schema_name
    if schema_courant == "public":
        return

    Configuration = apps.get_model("BaseBillet", "Configuration")
    FederationConfiguration = apps.get_model("BaseBillet", "FederationConfiguration")

    config = Configuration.objects.first()
    if config is None:
        # Pas de configuration sur ce tenant : rien a recopier.
        # / No configuration on this tenant: nothing to copy.
        return

    # Singleton : on reutilise l'instance existante, sinon on la cree avec pk=1
    # (DEFAULT_SINGLETON_INSTANCE_ID de django-solo).
    # / Singleton: reuse existing row, otherwise create it with pk=1.
    fed_config = FederationConfiguration.objects.first()
    if fed_config is None:
        fed_config = FederationConfiguration(pk=1)

    fed_config.module_agenda_participatif = config.module_agenda_participatif
    fed_config.proposition_anonyme_autorisee = config.proposition_anonyme_autorisee
    fed_config.tag_auto_proposition_id = config.tag_auto_proposition_id
    fed_config.save()

    print(
        f"  -> [{schema_courant}] reglages agenda participatif recopies "
        f"vers FederationConfiguration "
        f"(actif={fed_config.module_agenda_participatif})"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0216_configuration_proposition_anonyme_autorisee_and_more'),
    ]

    operations = [
        # 1) On ajoute les champs sur FederationConfiguration.
        # / 1) Add the fields on FederationConfiguration.
        migrations.AddField(
            model_name='federationconfiguration',
            name='module_agenda_participatif',
            field=models.BooleanField(default=False, help_text="Affiche un formulaire sur la page agenda pour que le public propose des évènements. Les propositions sont à valider dans l'admin.", verbose_name="Activer l'agenda participatif"),
        ),
        migrations.AddField(
            model_name='federationconfiguration',
            name='proposition_anonyme_autorisee',
            field=models.BooleanField(default=False, help_text="Si activé, les visiteurs non connectés peuvent proposer des évènements (nécessite l'agenda participatif).", verbose_name='Autoriser les propositions anonymes'),
        ),
        migrations.AddField(
            model_name='federationconfiguration',
            name='tag_auto_proposition',
            field=models.ForeignKey(blank=True, help_text="Tag ajouté automatiquement aux évènements proposés via l'agenda participatif.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_tag_auto_proposition', to='BaseBillet.tag', verbose_name='Tag automatique des évènements proposés'),
        ),
        # 2) On recopie les valeurs existantes (par tenant) AVANT de supprimer.
        # / 2) Copy existing values (per tenant) BEFORE removing them.
        migrations.RunPython(
            copier_reglages_agenda_vers_federation,
            reverse_code=migrations.RunPython.noop,
        ),
        # 3) On supprime les champs de Configuration.
        # / 3) Remove the fields from Configuration.
        migrations.RemoveField(
            model_name='configuration',
            name='module_agenda_participatif',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='proposition_anonyme_autorisee',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='tag_auto_proposition',
        ),
    ]
