# Generated by Django 4.2.30 on 2026-05-04 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0208_module_booking'),
        ('BaseBillet', '0216_alter_paiement_stripe_checkout_session_url'),
    ]

    operations = [
    ]
