# Generated by Django 4.2.30 on 2026-06-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0217_remove_configuration_module_agenda_participatif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='federationconfiguration',
            name='tags_federation',
            field=models.ManyToManyField(blank=True, help_text='Affiche dans votre agenda et votre carte les évènements de tout le réseau TiBillet portant un de ces tags, en plus de votre fédération habituelle. Laisser vide pour ne rien ajouter.', related_name='federation_configs_auto', to='BaseBillet.tag', verbose_name='Fédérer automatiquement tous les évènements avec ces tags'),
        ),
    ]
