# Generated by Django 4.2.30 on 2026-06-20 12:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fedow_core', '0003_unique_fed_asset'),
        ('BaseBillet', '0219_alter_membership_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieProduct',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Category name displayed on the POS interface.', max_length=200, verbose_name='Name')),
                ('icon', models.CharField(blank=True, help_text='Icon name (e.g. Bootstrap Icons class).', max_length=50, null=True, verbose_name='Icon')),
                ('couleur_texte', models.CharField(blank=True, help_text='Hexadecimal color code for text (e.g. #FFFFFF).', max_length=7, null=True, verbose_name='Text color')),
                ('couleur_fond', models.CharField(blank=True, help_text='Hexadecimal color code for background (e.g. #000000).', max_length=7, null=True, verbose_name='Background color')),
                ('poid_liste', models.SmallIntegerField(default=0, help_text='Lower values are displayed first.', verbose_name='Display order')),
                ('cashless', models.BooleanField(default=False, help_text='Check if this category is for cashless token items.', verbose_name='Cashless')),
            ],
            options={
                'verbose_name': 'Product category',
                'verbose_name_plural': 'Product categories',
                'ordering': ('poid_liste', 'name'),
            },
        ),
        migrations.AddField(
            model_name='price',
            name='asset',
            field=models.ForeignKey(blank=True, help_text='If set, the price is in asset units (tokens). If empty, the price is in euros.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prices', to='fedow_core.asset', verbose_name='Asset'),
        ),
        migrations.AddField(
            model_name='price',
            name='contenance',
            field=models.PositiveIntegerField(blank=True, help_text="Stock quantity consumed per unit sold (in stock unit). Use this when selling by unit but decrementing stock by weight/volume. E.g.: pint=50 (cl), half=25 (cl), portion=150 (g). Empty = 1 unit. Incompatible with 'Sale by weight/volume' (where the cashier enters the exact quantity).", null=True, verbose_name='Contenance'),
        ),
        migrations.AddField(
            model_name='price',
            name='non_fiduciaire',
            field=models.BooleanField(default=False, help_text='If checked, the price is in tokens (time, loyalty, etc.) instead of euros. You must select the asset below.', verbose_name='Non-fiduciary price'),
        ),
        migrations.AddField(
            model_name='price',
            name='poids_mesure',
            field=models.BooleanField(default=False, help_text='If checked, the cashier enters the weight or volume at each sale. The price is per kg (grams) or per liter (centiliters). Stock is decremented by the exact quantity entered.', verbose_name='Sale by weight/volume'),
        ),
        migrations.AddField(
            model_name='product',
            name='asset',
            field=models.ForeignKey(blank=True, help_text='Asset fedow lie a ce produit de recharge. / Fedow asset linked to this top-up product.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='fedow_core.asset', verbose_name='Asset'),
        ),
        migrations.AddField(
            model_name='product',
            name='besoin_tag_id',
            field=models.BooleanField(default=False, help_text='An NFC card must be scanned before this product can be added to the cart.', verbose_name='Requires NFC tag'),
        ),
        migrations.AddField(
            model_name='product',
            name='couleur_fond_pos',
            field=models.CharField(blank=True, help_text='Hexadecimal color for the product button background (e.g. #3B82F6).', max_length=7, null=True, verbose_name='POS background color'),
        ),
        migrations.AddField(
            model_name='product',
            name='couleur_texte_pos',
            field=models.CharField(blank=True, help_text='Hexadecimal color for the product button text (e.g. #FFFFFF).', max_length=7, null=True, verbose_name='POS text color'),
        ),
        migrations.AddField(
            model_name='product',
            name='fractionne',
            field=models.BooleanField(default=False, help_text='Allow partial/split payment for this product at the POS.', verbose_name='Split payment allowed'),
        ),
        migrations.AddField(
            model_name='product',
            name='icon_pos',
            field=models.CharField(blank=True, help_text='Icon name for the POS button (e.g. Bootstrap Icons class).', max_length=50, null=True, verbose_name='POS icon'),
        ),
        migrations.AddField(
            model_name='product',
            name='methode_caisse',
            field=models.CharField(blank=True, choices=[('VT', 'Sale'), ('RE', 'Euro top-up'), ('RC', 'Gift top-up'), ('TM', 'Time top-up'), ('AD', 'Membership'), ('CR', 'Deposit return'), ('VC', 'Empty card'), ('FR', 'Split payment'), ('BI', 'Ticket'), ('FD', 'Loyalty'), ('VR', 'Bank transfer received')], help_text='Payment/action method at the cash register. Leave empty if this product is not sold at the POS.', max_length=2, null=True, verbose_name='POS method'),
        ),
        migrations.AddField(
            model_name='product',
            name='prix_achat',
            field=models.IntegerField(default=0, help_text="Prix d'achat unitaire en centimes. Utilise pour le calcul du benefice estime. / Unit purchase price in cents. Used for estimated profit calculation.", verbose_name='Purchase price (cents)'),
        ),
    ]
