# Generated by Django 4.2.30 on 2026-06-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0219_alter_membership_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='module_pages',
            field=models.BooleanField(default=True, verbose_name='Module pages / site web'),
        ),
    ]
