# Generated by Django 4.2.30 on 2026-06-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0219_paiement_stripe_checkout_session_url_commande_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Resource product',
                'verbose_name_plural': 'Resources products',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('BaseBillet.product',),
        ),
        migrations.AlterField(
            model_name='product',
            name='categorie_article',
            field=models.CharField(choices=[('N', 'Select a category'), ('B', 'Ticket booking'), ('F', 'Free booking'), ('A', 'Subscription or membership'), ('G', 'Punchclock'), ('Q', 'QrCode paiement on my account'), ('C', 'Ressource')], default='N', max_length=3, verbose_name='Product type'),
        ),
        migrations.AlterField(
            model_name='productsold',
            name='categorie_article',
            field=models.CharField(choices=[('N', 'Select a category'), ('B', 'Ticket booking'), ('F', 'Free booking'), ('A', 'Subscription or membership'), ('G', 'Punchclock'), ('Q', 'QrCode paiement on my account'), ('C', 'Ressource')], default='N', max_length=3, verbose_name='Product type'),
        ),
    ]
