# Generated by Django 4.2.30 on 2026-06-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0219_alter_membership_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignearticle',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Idempotency key'),
        ),
        migrations.AddConstraint(
            model_name='lignearticle',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('idempotency_key',), name='unique_lignearticle_idempotency_key'),
        ),
    ]
