# Generated by Django 4.2.30 on 2026-06-30 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_resource_options_remove_resource_product_and_more'),
        ('BaseBillet', '0220_resourceproduct_alter_product_categorie_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignearticle',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lignearticles', to='booking.booking', verbose_name='Resources reservation'),
        ),
    ]
