# Generated by Django 4.2.30 on 2026-07-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0220_lignearticle_idempotency_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='module_newsletter',
            field=models.BooleanField(default=False, verbose_name='Newsletter module'),
        ),
    ]
