# Generated by Django 4.2.30 on 2026-06-20 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboutik', '0001_initial'),
        ('BaseBillet', '0220_categorieproduct_price_asset_price_contenance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorieproduct',
            name='compte_comptable',
            field=models.ForeignKey(blank=True, help_text="Compte comptable de vente associe a cette categorie. Utilise pour l'export FEC et CSV comptable. / Sales accounting code for this category. Used for FEC and CSV accounting export.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories_produit', to='laboutik.comptecomptable', verbose_name='Accounting code'),
        ),
        migrations.AddField(
            model_name='categorieproduct',
            name='printer',
            field=models.ForeignKey(blank=True, help_text='Printer for order tickets (kitchen, bar). When an order contains products from this category, the ticket is sent to this printer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories_produit', to='laboutik.printer', verbose_name='Order printer'),
        ),
        migrations.AddField(
            model_name='categorieproduct',
            name='tva',
            field=models.ForeignKey(blank=True, help_text='Default VAT rate applied to products in this category.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='BaseBillet.tva', verbose_name='Default VAT rate'),
        ),
        migrations.AddField(
            model_name='product',
            name='categorie_pos',
            field=models.ForeignKey(blank=True, help_text='Display category on the POS interface.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_pos', to='BaseBillet.categorieproduct', verbose_name='POS category'),
        ),
    ]
