# Generated by Django 4.2.30 on 2026-06-28 14:23
# Edite a la main : copie skin -> pages.ConfigurationSite avant de retirer le champ.
# / Hand-edited: copy skin -> pages.ConfigurationSite before removing the field.

from django.db import connection, migrations


def copier_skin_vers_configuration_site(apps, schema_editor):
    """
    Copie Configuration.skin vers le singleton pages.ConfigurationSite.
    / Copies Configuration.skin into the pages.ConfigurationSite singleton.

    Cette migration BaseBillet ne s'execute que sur les schemas tenant
    (BaseBillet est en TENANT_APPS uniquement), donc Configuration et
    ConfigurationSite existent toutes deux ici. On garde tout de meme un garde
    sur le schema public par securite.
    / This BaseBillet migration only runs on tenant schemas (BaseBillet is in
    TENANT_APPS only), so both Configuration and ConfigurationSite exist here.
    We still guard against the public schema for safety.
    """
    if connection.schema_name == "public":
        return

    Configuration = apps.get_model("BaseBillet", "Configuration")
    ConfigurationSite = apps.get_model("pages", "ConfigurationSite")

    configuration = Configuration.objects.first()
    if configuration is None:
        return

    skin_actuel = getattr(configuration, "skin", None)

    # Defensif : si le champ skin n'existe plus (re-execution apres RemoveField),
    # on NE TOUCHE PAS au singleton, sinon on l'ecraserait avec une valeur par
    # defaut et on perdrait le skin reel du tenant.
    # / Defensive: if the skin field is gone (re-run after RemoveField), DO NOT
    # touch the singleton, otherwise we'd overwrite it with a default and lose
    # the tenant's real skin.
    if not skin_actuel:
        return

    # Le singleton django-solo utilise l'id 1. On cree ou met a jour la ligne.
    # / The django-solo singleton uses id 1. We create or update the row.
    ConfigurationSite.objects.update_or_create(
        id=1,
        defaults={"skin": skin_actuel},
    )
    print(f"  -> [{connection.schema_name}] skin '{skin_actuel}' copie vers ConfigurationSite")


def restaurer_skin_sur_configuration(apps, schema_editor):
    """
    Operation inverse : recopie le skin du singleton vers Configuration.
    / Reverse operation: copies the skin from the singleton back to Configuration.

    Note : le champ Configuration.skin est recree par le reverse de RemoveField
    avant que cette fonction ne s'execute (operations inversees dans l'ordre).
    / Note: the Configuration.skin field is recreated by RemoveField's reverse
    before this function runs (operations reversed in order).
    """
    if connection.schema_name == "public":
        return

    Configuration = apps.get_model("BaseBillet", "Configuration")
    ConfigurationSite = apps.get_model("pages", "ConfigurationSite")

    site = ConfigurationSite.objects.first()
    configuration = Configuration.objects.first()
    if site is None or configuration is None:
        return

    configuration.skin = site.skin or "reunion"
    configuration.save(update_fields=["skin"])


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0220_configuration_module_pages'),
        # Le singleton ConfigurationSite doit exister avant la copie.
        # / The ConfigurationSite singleton must exist before the copy.
        ('pages', '0003_configurationsite'),
    ]

    operations = [
        # 1) On copie d'abord le skin existant vers le nouveau singleton.
        # / 1) First copy the existing skin into the new singleton.
        migrations.RunPython(
            copier_skin_vers_configuration_site,
            reverse_code=restaurer_skin_sur_configuration,
        ),
        # 2) Puis on retire le champ skin de Configuration.
        # / 2) Then remove the skin field from Configuration.
        migrations.RemoveField(
            model_name='configuration',
            name='skin',
        ),
    ]
