# Generated by Django 4.2.30 on 2026-07-02 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0221_lignearticle_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement_stripe',
            name='commande',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='BaseBillet.commande'),
        ),
    ]
