# Generated by Django 4.2.30 on 2026-07-18 19:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0221_configuration_module_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email_acheteur', models.EmailField(max_length=254, verbose_name='Buyer email')),
                ('first_name', models.CharField(max_length=200, verbose_name='First name')),
                ('last_name', models.CharField(max_length=200, verbose_name='Last name')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending payment'), ('PAID', 'Paid'), ('CANCELED', 'Canceled'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=10, verbose_name='Order status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid at')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ResourceProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Resource product',
                'verbose_name_plural': 'Resources products',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('BaseBillet.product',),
        ),
    ]
