# Generated by Django 4.2.30 on 2026-10-05 15:59
# Édité à la main : le `RemoveField` du champ `Configuration.skin` est retiré de
# cette migration. Il est dans 0226, après la copie des données (0225).
# / Hand-edited: the `RemoveField` of `Configuration.skin` is taken out of this
# migration. It lives in 0226, after the data copy (0225).

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BaseBillet', '0221_configuration_module_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieProduct',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Category name displayed on the POS interface.', max_length=200, verbose_name='Name')),
                ('icon', models.CharField(blank=True, help_text='Icon name (e.g. Bootstrap Icons class).', max_length=50, null=True, verbose_name='Icon')),
                ('couleur_texte', models.CharField(blank=True, help_text='Hexadecimal color code for text (e.g. #FFFFFF).', max_length=7, null=True, verbose_name='Text color')),
                ('couleur_fond', models.CharField(blank=True, help_text='Hexadecimal color code for background (e.g. #000000).', max_length=7, null=True, verbose_name='Background color')),
                ('poid_liste', models.SmallIntegerField(default=0, help_text='Lower values are displayed first.', verbose_name='Display order')),
                ('cashless', models.BooleanField(default=False, help_text='Check if this category is for cashless token items.', verbose_name='Cashless')),
            ],
            options={
                'verbose_name': 'Product category',
                'verbose_name_plural': 'Product categories',
                'ordering': ('poid_liste', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email_acheteur', models.EmailField(max_length=254, verbose_name='Buyer email')),
                ('first_name', models.CharField(max_length=200, verbose_name='First name')),
                ('last_name', models.CharField(max_length=200, verbose_name='Last name')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending payment'), ('PAID', 'Paid'), ('CANCELED', 'Canceled'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=10, verbose_name='Order status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid at')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Reglement',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('moyen', models.CharField(choices=[('UK', 'Unknown'), ('NA', 'Offered'), ('CC', 'Credit card: POS terminal'), ('CA', 'Cash'), ('CH', 'Check'), ('QR', 'QrCode or NFC'), ('TR', 'Bank transfer'), ('SF', 'Online: federated Stripe'), ('SN', 'Online: Stripe CC'), ('SP', 'Online: Stripe SEPA'), ('SR', 'Recurring: Stripe'), ('LE', 'Asset local fiat'), ('LG', 'Asset local gift'), ('NM', 'Points ou temps (non monétaire)')], max_length=2, verbose_name='Moyen de paiement')),
                ('montant', models.IntegerField(verbose_name='Montant (centimes)')),
                ('asset', models.UUIDField(blank=True, null=True, verbose_name='Monnaie')),
                ('fedow_transaction_uuid', models.UUIDField(blank=True, null=True, verbose_name='Transaction Fedow')),
                ('reference_externe', models.CharField(blank=True, default='', max_length=255, verbose_name='Référence externe')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Règlement',
                'verbose_name_plural': 'Règlements',
                'ordering': ('datetime',),
            },
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Numéro')),
                ('nature', models.CharField(choices=[('VENTE', 'Vente'), ('AVOIR', 'Avoir'), ('VIDAGE_CARTE', 'Vidage de carte'), ('CORRECTION', 'Correction de moyen de paiement')], max_length=20, verbose_name='Nature')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('REGLEE', 'Réglée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('origine', models.CharField(choices=[('LP', 'Online platform'), ('LB', 'Cash register'), ('AD', 'Administration'), ('EX', 'External'), ('QR', 'QrCode online'), ('NF', 'NFC online'), ('AP', 'API'), ('WK', 'Webhook Stripe'), ('TI', 'Connected tap')], max_length=2, verbose_name='Origine')),
                ('unite', models.CharField(default='EUR', max_length=36, verbose_name='Unité')),
                ('total_catalogue', models.IntegerField(default=0, verbose_name='Total catalogue')),
                ('total_offert', models.IntegerField(default=0, verbose_name='Total offert')),
                ('total_ttc', models.IntegerField(default=0, verbose_name='Total net vendu (TTC)')),
                ('total_ht', models.IntegerField(default=0, verbose_name='Total HT')),
                ('total_tva', models.IntegerField(default=0, verbose_name='Total TVA')),
                ('datetime_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('datetime_encaissement', models.DateTimeField(blank=True, null=True, verbose_name="Date d'encaissement")),
                ('hmac_hash', models.CharField(blank=True, default='', max_length=64, verbose_name='Empreinte')),
                ('previous_hmac', models.CharField(blank=True, default='', max_length=64, verbose_name='Empreinte précédente')),
                ('raison', models.TextField(blank=True, default='', help_text="Raison écrite par le caissier lors d'une correction de moyen de paiement.", verbose_name='Raison')),
                ('idempotency_key', models.CharField(blank=True, max_length=255, null=True, verbose_name="Clé d'idempotence")),
            ],
            options={
                'verbose_name': 'Vente',
                'verbose_name_plural': 'Ventes',
                'ordering': ('-datetime_creation',),
            },
        ),
        migrations.CreateModel(
            name='ResourceProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Resource product',
                'verbose_name_plural': 'Resources products',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('BaseBillet.product',),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
        # Le champ `skin` n'est PAS retiré ici : la migration de données 0225 le copie
        # d'abord vers `pages.ConfigurationSite`, puis la migration 0226 le retire.
        # / The `skin` field is NOT removed here: data migration 0225 copies it first
        # to `pages.ConfigurationSite`, then migration 0226 removes it.
        migrations.AddField(
            model_name='configuration',
            name='heure_de_fermeture',
            field=models.TimeField(default=datetime.time(2, 0), help_text="Heure locale de fermeture du lieu. Si personne n'a fait la clôture de la journée, elle est faite automatiquement deux heures après.", verbose_name='Heure de fermeture'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='module_kiosk',
            field=models.BooleanField(default=False, help_text='Active les bornes de paiement en libre-service (Stripe Terminal).', verbose_name='Module kiosk / borne libre-service'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='module_pages',
            field=models.BooleanField(default=True, verbose_name='Module pages / site web'),
        ),
        migrations.AddField(
            model_name='externalapikey',
            name='page',
            field=models.BooleanField(default=False, verbose_name='Pages / Site web'),
        ),
        migrations.AddField(
            model_name='laboutikapikey',
            name='user',
            field=models.OneToOneField(blank=True, help_text='TermUser linked (V2 bridge flow). Null for legacy V1 keys.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laboutik_api_key', to=settings.AUTH_USER_MODEL, verbose_name='Terminal user'),
        ),
    ]
