# Generated by Django 4.2.30 on 2026-07-02 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0222_paiement_stripe_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignearticle',
            name='commande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lignes_articles', to='BaseBillet.commande'),
        ),
        migrations.AlterField(
            model_name='paiement_stripe',
            name='commande',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paiement', to='BaseBillet.commande'),
        ),
    ]
