# Generated by Django 4.2.30 on 2026-06-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0222_creer_page_accueil'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalapikey',
            name='page',
            field=models.BooleanField(default=False, verbose_name='Pages / Site web'),
        ),
    ]
