# Generated by Django 4.2.30 on 2026-07-18 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0222_commande_resourceproduct'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignearticle',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lignearticles', to='booking.booking', verbose_name='Resources reservation'),
        ),
        migrations.AddField(
            model_name='paiement_stripe',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='booking.booking'),
        ),
        migrations.AddField(
            model_name='paiement_stripe',
            name='checkout_session_url',
            field=models.URLField(blank=True, help_text="URL Stripe Checkout persistée après création — permet de rediriger l'utilisateur vers le paiement sans rappeler Stripe. / Stripe Checkout URL persisted after creation — allows redirecting the user to payment without recalling Stripe.", max_length=1024, null=True, verbose_name='Stripe checkout URL'),
        ),
        migrations.AlterField(
            model_name='paiement_stripe',
            name='status',
            field=models.CharField(choices=[('N', 'Payment link not generated'), ('O', 'Sent to Stripe'), ('W', 'Waiting for payment'), ('E', 'Expired'), ('F', 'Failed'), ('P', 'Paid'), ('V', 'Paid and confirmed'), ('S', 'Paid but issues with LaBoutik sync'), ('C', 'Cancelled'), ('R', 'Refunded'), ('H', 'Partiellement remboursé')], default='N', max_length=1, verbose_name='Order status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categorie_article',
            field=models.CharField(choices=[('N', 'Select a category'), ('B', 'Ticket booking'), ('F', 'Free booking'), ('A', 'Subscription or membership'), ('G', 'Punchclock'), ('Q', 'QrCode paiement on my account'), ('C', 'Ressource')], default='N', max_length=3, verbose_name='Product type'),
        ),
        migrations.AlterField(
            model_name='productsold',
            name='categorie_article',
            field=models.CharField(choices=[('N', 'Select a category'), ('B', 'Ticket booking'), ('F', 'Free booking'), ('A', 'Subscription or membership'), ('G', 'Punchclock'), ('Q', 'QrCode paiement on my account'), ('C', 'Ressource')], default='N', max_length=3, verbose_name='Product type'),
        ),
        migrations.AddField(
            model_name='commande',
            name='paiement_stripe',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commande_obj', to='BaseBillet.paiement_stripe', verbose_name='Stripe payment'),
        ),
        migrations.AddField(
            model_name='commande',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='BaseBillet.promotionalcode', verbose_name='Promotional code'),
        ),
        migrations.AddField(
            model_name='commande',
            name='user',
            field=models.ForeignKey(help_text='Utilisateur acheteur (résolu par email au checkout). / Buyer user (resolved by email at checkout).', on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to=settings.AUTH_USER_MODEL, verbose_name='Buyer'),
        ),
        migrations.AddField(
            model_name='membership',
            name='commande',
            field=models.ForeignKey(blank=True, help_text="Renseignée uniquement si l'adhésion a été créée via un panier multi-items. / Only set if the membership was created via a multi-item cart.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships_commande', to='BaseBillet.commande', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='commande',
            field=models.ForeignKey(blank=True, help_text='Renseignée uniquement si la reservation a été créée via un panier multi-items. / Only set if the reservation was created via a multi-item cart.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='BaseBillet.commande', verbose_name='Order'),
        ),
    ]
