# Generated by Django 4.2.30 on 2026-10-05 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0222_ventes_reglements_commandes_et_categories'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignearticle',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lignearticles', to='booking.booking', verbose_name='Resources reservation'),
        ),
        migrations.AddField(
            model_name='lignearticle',
            name='cout_achat',
            field=models.IntegerField(blank=True, null=True, verbose_name="Coût d'achat (centimes)"),
        ),
        migrations.AddField(
            model_name='lignearticle',
            name='hmac_hash',
            field=models.CharField(blank=True, default='', help_text='HMAC-SHA256 de cette ligne, chainee avec la precedente. / HMAC-SHA256 of this line, chained with the previous one.', max_length=64, verbose_name='HMAC hash'),
        ),
        migrations.AddField(
            model_name='lignearticle',
            name='hors_chiffre_affaires',
            field=models.BooleanField(default=False, verbose_name="Hors chiffre d'affaires"),
        ),
        migrations.AddField(
            model_name='lignearticle',
            name='part_en_jetons',
            field=models.IntegerField(default=0, help_text="Centimes du net vendu payés en jetons cadeau. Cette part est vendue hors TVA ; la TVA de l'article porte sur le reste.", verbose_name='Part payée en jetons (centimes)'),
        ),
        migrations.AddField(
            model_name='lignearticle',
            name='part_offerte',
            field=models.IntegerField(default=0, verbose_name='Part offerte (centimes)'),
        ),
    ]
