# Generated by Django 4.2.30 on 2026-07-21 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboutik', '0001_initial'),
        ('BaseBillet', '0223_lignearticle_point_de_vente_and_more'),
        ('fedow_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='asset',
            field=models.ForeignKey(blank=True, help_text='If set, the price is in asset units (tokens). If empty, the price is in euros.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prices', to='fedow_core.asset', verbose_name='Asset'),
        ),
        migrations.AddField(
            model_name='price',
            name='contenance',
            field=models.PositiveIntegerField(blank=True, help_text="Stock quantity consumed per unit sold (in stock unit). Use this when selling by unit but decrementing stock by weight/volume. E.g.: pint=50 (cl), half=25 (cl), portion=150 (g). Empty = 1 unit. Incompatible with 'Sale by weight/volume' (where the cashier enters the exact quantity).", null=True, verbose_name='Contenance'),
        ),
        migrations.AddField(
            model_name='price',
            name='non_fiduciaire',
            field=models.BooleanField(default=False, help_text='If checked, the price is in tokens (time, loyalty, etc.) instead of euros. You must select the asset below.', verbose_name='Non-fiduciary price'),
        ),
        migrations.AddField(
            model_name='price',
            name='poids_mesure',
            field=models.BooleanField(default=False, help_text='If checked, the cashier enters the weight or volume at each sale. The price is per kg (grams) or per liter (centiliters). Stock is decremented by the exact quantity entered.', verbose_name='Sale by weight/volume'),
        ),
        migrations.AddField(
            model_name='product',
            name='asset',
            field=models.ForeignKey(blank=True, help_text='Asset fedow lie a ce produit de recharge. / Fedow asset linked to this top-up product.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='fedow_core.asset', verbose_name='Asset'),
        ),
        migrations.AddField(
            model_name='product',
            name='besoin_tag_id',
            field=models.BooleanField(default=False, help_text='An NFC card must be scanned before this product can be added to the cart.', verbose_name='Requires NFC tag'),
        ),
        migrations.AddField(
            model_name='product',
            name='couleur_fond_pos',
            field=models.CharField(blank=True, help_text='Hexadecimal color for the product button background (e.g. #3B82F6).', max_length=7, null=True, verbose_name='POS background color'),
        ),
        migrations.AddField(
            model_name='product',
            name='couleur_texte_pos',
            field=models.CharField(blank=True, help_text='Hexadecimal color for the product button text (e.g. #FFFFFF).', max_length=7, null=True, verbose_name='POS text color'),
        ),
        migrations.AddField(
            model_name='product',
            name='fractionne',
            field=models.BooleanField(default=False, help_text='Allow partial/split payment for this product at the POS.', verbose_name='Split payment allowed'),
        ),
        migrations.AddField(
            model_name='product',
            name='icon_pos',
            field=models.CharField(blank=True, help_text='Icon name for the POS button (e.g. Bootstrap Icons class).', max_length=50, null=True, verbose_name='POS icon'),
        ),
        migrations.AddField(
            model_name='product',
            name='methode_caisse',
            field=models.CharField(blank=True, choices=[('VT', 'Sale'), ('RE', 'Euro top-up'), ('RC', 'Gift top-up'), ('TM', 'Time top-up'), ('AD', 'Membership'), ('CR', 'Deposit return'), ('VC', 'Empty card'), ('FR', 'Split payment'), ('BI', 'Ticket'), ('FD', 'Loyalty'), ('VR', 'Bank transfer received')], help_text='Payment/action method at the cash register. Leave empty if this product is not sold at the POS.', max_length=2, null=True, verbose_name='POS method'),
        ),
        migrations.AddField(
            model_name='product',
            name='prix_achat',
            field=models.IntegerField(default=0, help_text="Prix d'achat unitaire en centimes. Utilise pour le calcul du benefice estime. / Unit purchase price in cents. Used for estimated profit calculation.", verbose_name='Purchase price (cents)'),
        ),
        migrations.AlterField(
            model_name='lignearticle',
            name='sale_origin',
            field=models.CharField(choices=[('LP', 'Online platform'), ('LB', 'Cash register'), ('AD', 'Administration'), ('EX', 'External'), ('QR', 'QrCode online'), ('NF', 'NFC online'), ('AP', 'API'), ('WK', 'Webhook Stripe'), ('TI', 'Connected tap')], default='LP', max_length=2, verbose_name='Payment source'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categorie_article',
            field=models.CharField(choices=[('N', 'Select a category'), ('B', 'Ticket booking'), ('F', 'Free booking'), ('A', 'Subscription or membership'), ('G', 'Punchclock'), ('Q', 'QrCode paiement on my account'), ('U', 'Keg (connected tap)')], default='N', max_length=3, verbose_name='Product type'),
        ),
        migrations.AlterField(
            model_name='productsold',
            name='categorie_article',
            field=models.CharField(choices=[('N', 'Select a category'), ('B', 'Ticket booking'), ('F', 'Free booking'), ('A', 'Subscription or membership'), ('G', 'Punchclock'), ('Q', 'QrCode paiement on my account'), ('U', 'Keg (connected tap)')], default='N', max_length=3, verbose_name='Product type'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sale_origin',
            field=models.CharField(choices=[('LP', 'Online platform'), ('LB', 'Cash register'), ('AD', 'Administration'), ('EX', 'External'), ('QR', 'QrCode online'), ('NF', 'NFC online'), ('AP', 'API'), ('WK', 'Webhook Stripe'), ('TI', 'Connected tap')], default='LP', max_length=2, verbose_name='Payment source'),
        ),
        migrations.AddField(
            model_name='categorieproduct',
            name='compte_comptable',
            field=models.ForeignKey(blank=True, help_text="Compte comptable de vente associe a cette categorie. Utilise pour l'export FEC et CSV comptable. / Sales accounting code for this category. Used for FEC and CSV accounting export.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories_produit', to='laboutik.comptecomptable', verbose_name='Accounting code'),
        ),
        migrations.AddField(
            model_name='categorieproduct',
            name='printer',
            field=models.ForeignKey(blank=True, help_text='Printer for order tickets (kitchen, bar). When an order contains products from this category, the ticket is sent to this printer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories_produit', to='laboutik.printer', verbose_name='Order printer'),
        ),
        migrations.AddField(
            model_name='categorieproduct',
            name='tva',
            field=models.ForeignKey(blank=True, help_text='Default VAT rate applied to products in this category.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='BaseBillet.tva', verbose_name='Default VAT rate'),
        ),
        migrations.AddField(
            model_name='product',
            name='categorie_pos',
            field=models.ForeignKey(blank=True, help_text='Display category on the POS interface.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_pos', to='BaseBillet.categorieproduct', verbose_name='POS category'),
        ),
    ]
