# Generated by Django 4.2.30 on 2026-10-05 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('laboutik', '0001_initial'),
        ('AuthBillet', '0024_role_de_terminal_et_portefeuille'),
        ('QrcodeCashless', '0021_portefeuille_ephemere_de_la_carte'),
        ('Customers', '0005_libelles_fr_du_lieu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0001_initial'),
        ('rest_framework_api_key', '0005_auto_20220110_1102'),
        ('fedow_core', '0001_initial'),
        ('BaseBillet', '0223_ligne_article_reservation_couts_et_jetons'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignearticle',
            name='point_de_vente',
            field=models.ForeignKey(blank=True, help_text='Point de vente ou cette vente a ete realisee. / Point of sale where this sale was made.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_articles', to='laboutik.pointdevente', verbose_name='Point of sale'),
        ),
        migrations.AddField(
            model_name='lignearticle',
            name='previous_hmac',
            field=models.CharField(blank=True, default='', help_text='HMAC de la LigneArticle precedente dans la chaine. / HMAC of the previous LigneArticle in the chain.', max_length=64, verbose_name='Previous HMAC'),
        ),
        migrations.AddField(
            model_name='lignearticle',
            name='source_offert',
            field=models.CharField(blank=True, choices=[('OFFRIR', 'Offert par le lieu'), ('JETONS', 'Jetons cadeau')], default='', max_length=10, verbose_name="Source de l'offert"),
        ),
        migrations.AddField(
            model_name='lignearticle',
            name='total_catalogue',
            field=models.IntegerField(default=0, verbose_name='Total catalogue (centimes)'),
        ),
        migrations.AddField(
            model_name='lignearticle',
            name='total_ht',
            field=models.IntegerField(default=0, help_text='Total hors taxes en centimes. Calcule : TTC / (1 + taux_tva/100). / Total excluding tax in cents. Computed: TTC / (1 + vat_rate/100).', verbose_name='Total HT (cents)'),
        ),
        migrations.AddField(
            model_name='lignearticle',
            name='total_ttc',
            field=models.IntegerField(default=0, verbose_name='Net vendu TTC (centimes)'),
        ),
        migrations.AddField(
            model_name='lignearticle',
            name='total_tva',
            field=models.IntegerField(default=0, verbose_name='Total TVA (centimes)'),
        ),
        migrations.AddField(
            model_name='lignearticle',
            name='uuid_transaction',
            field=models.UUIDField(blank=True, db_index=True, help_text='Groups all lines from the same payment for reprinting.', null=True, verbose_name='Transaction ID'),
        ),
        migrations.AddField(
            model_name='lignearticle',
            name='weight_quantity',
            field=models.IntegerField(blank=True, help_text='Amount entered by cashier in stock unit (g or cl). Null for standard sales.', null=True, verbose_name='Quantity by weight/volume'),
        ),
        migrations.AddField(
            model_name='paiement_stripe',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='booking.booking'),
        ),
        migrations.AddField(
            model_name='paiement_stripe',
            name='checkout_session_url',
            field=models.URLField(blank=True, help_text="URL Stripe Checkout persistée après création — permet de rediriger l'utilisateur vers le paiement sans rappeler Stripe. / Stripe Checkout URL persisted after creation — allows redirecting the user to payment without recalling Stripe.", max_length=1024, null=True, verbose_name='Stripe checkout URL'),
        ),
        migrations.AddField(
            model_name='paiement_stripe',
            name='montant_encaisse',
            field=models.IntegerField(blank=True, null=True, verbose_name='Montant encaissé (centimes)'),
        ),
        migrations.AddField(
            model_name='paiement_stripe',
            name='moyen',
            field=models.CharField(blank=True, choices=[('SN', 'Online: Stripe CC'), ('SP', 'Online: Stripe SEPA'), ('SR', 'Recurring: Stripe')], max_length=2, null=True, verbose_name='Moyen de paiement Stripe'),
        ),
        migrations.AddField(
            model_name='price',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
        migrations.AddField(
            model_name='price',
            name='asset',
            field=models.ForeignKey(blank=True, help_text='If set, the price is in asset units (tokens). If empty, the price is in euros.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prices', to='fedow_core.asset', verbose_name='Asset'),
        ),
        migrations.AddField(
            model_name='price',
            name='contenance',
            field=models.PositiveIntegerField(blank=True, help_text="Stock quantity consumed per unit sold (in stock unit). Use this when selling by unit but decrementing stock by weight/volume. E.g.: pint=50 (cl), half=25 (cl), portion=150 (g). Empty = 1 unit. Incompatible with 'Sale by weight/volume' (where the cashier enters the exact quantity).", null=True, verbose_name='Contenance'),
        ),
        migrations.AddField(
            model_name='price',
            name='non_fiduciaire',
            field=models.BooleanField(default=False, help_text='If checked, the price is in tokens (time, loyalty, etc.) instead of euros. You must select the asset below.', verbose_name='Non-fiduciary price'),
        ),
        migrations.AddField(
            model_name='price',
            name='poids_mesure',
            field=models.BooleanField(default=False, help_text='If checked, the cashier enters the weight or volume at each sale. The price is per kg (grams) or per liter (centiliters). Stock is decremented by the exact quantity entered.', verbose_name='Sale by weight/volume'),
        ),
        migrations.AddField(
            model_name='product',
            name='asset',
            field=models.ForeignKey(blank=True, help_text='Asset fedow lie a ce produit de recharge. / Fedow asset linked to this top-up product.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='fedow_core.asset', verbose_name='Asset'),
        ),
        migrations.AddField(
            model_name='product',
            name='besoin_tag_id',
            field=models.BooleanField(default=False, help_text='An NFC card must be scanned before this product can be added to the cart.', verbose_name='Requires NFC tag'),
        ),
        migrations.AddField(
            model_name='product',
            name='consigne_remboursee',
            field=models.ForeignKey(blank=True, help_text='Le produit consigne (par exemple le gobelet) que ce retour rembourse. La caisse rend son prix, avec son taux de TVA.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retours_de_consigne', to='BaseBillet.product', verbose_name='Rembourse la consigne'),
        ),
        migrations.AddField(
            model_name='product',
            name='couleur_fond_pos',
            field=models.CharField(blank=True, help_text='Hexadecimal color for the product button background (e.g. #3B82F6).', max_length=7, null=True, verbose_name='POS background color'),
        ),
        migrations.AddField(
            model_name='product',
            name='couleur_texte_pos',
            field=models.CharField(blank=True, help_text='Hexadecimal color for the product button text (e.g. #FFFFFF).', max_length=7, null=True, verbose_name='POS text color'),
        ),
        migrations.AddField(
            model_name='product',
            name='fractionne',
            field=models.BooleanField(default=False, help_text='Allow partial/split payment for this product at the POS.', verbose_name='Split payment allowed'),
        ),
        migrations.AddField(
            model_name='product',
            name='icon_pos',
            field=models.CharField(blank=True, help_text='Icon name for the POS button (e.g. Bootstrap Icons class).', max_length=50, null=True, verbose_name='POS icon'),
        ),
        migrations.AddField(
            model_name='product',
            name='methode_caisse',
            field=models.CharField(blank=True, choices=[('VT', 'Sale'), ('RE', 'Euro top-up'), ('RC', 'Gift top-up'), ('TM', 'Time top-up'), ('AD', 'Membership'), ('CR', 'Deposit return'), ('VC', 'Empty card'), ('FR', 'Split payment'), ('BI', 'Ticket'), ('FD', 'Loyalty'), ('VR', 'Bank transfer received')], help_text='Payment/action method at the cash register. Leave empty if this product is not sold at the POS.', max_length=2, null=True, verbose_name='POS method'),
        ),
        migrations.AddField(
            model_name='product',
            name='prix_achat',
            field=models.IntegerField(default=0, help_text="Prix d'achat en centimes, par unité de vente (kg, litre, pièce) ; 0 = inconnu.", verbose_name='Purchase price (cents)'),
        ),
        migrations.AlterField(
            model_name='brevoconfig',
            name='last_log',
            field=models.TextField(blank=True, null=True, verbose_name='Dernier journal'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='currency_code',
            field=models.CharField(default='EUR', max_length=3, verbose_name='Code devise'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Adresse e-mail'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='fuseau_horaire',
            field=models.CharField(choices=[('Africa/Abidjan', 'Africa/Abidjan'), ('Africa/Accra', 'Africa/Accra'), ('Africa/Addis_Ababa', 'Africa/Addis_Ababa'), ('Africa/Algiers', 'Africa/Algiers'), ('Africa/Asmara', 'Africa/Asmara'), ('Africa/Asmera', 'Africa/Asmera'), ('Africa/Bamako', 'Africa/Bamako'), ('Africa/Bangui', 'Africa/Bangui'), ('Africa/Banjul', 'Africa/Banjul'), ('Africa/Bissau', 'Africa/Bissau'), ('Africa/Blantyre', 'Africa/Blantyre'), ('Africa/Brazzaville', 'Africa/Brazzaville'), ('Africa/Bujumbura', 'Africa/Bujumbura'), ('Africa/Cairo', 'Africa/Cairo'), ('Africa/Casablanca', 'Africa/Casablanca'), ('Africa/Ceuta', 'Africa/Ceuta'), ('Africa/Conakry', 'Africa/Conakry'), ('Africa/Dakar', 'Africa/Dakar'), ('Africa/Dar_es_Salaam', 'Africa/Dar_es_Salaam'), ('Africa/Djibouti', 'Africa/Djibouti'), ('Africa/Douala', 'Africa/Douala'), ('Africa/El_Aaiun', 'Africa/El_Aaiun'), ('Africa/Freetown', 'Africa/Freetown'), ('Africa/Gaborone', 'Africa/Gaborone'), ('Africa/Harare', 'Africa/Harare'), ('Africa/Johannesburg', 'Africa/Johannesburg'), ('Africa/Juba', 'Africa/Juba'), ('Africa/Kampala', 'Africa/Kampala'), ('Africa/Khartoum', 'Africa/Khartoum'), ('Africa/Kigali', 'Africa/Kigali'), ('Africa/Kinshasa', 'Africa/Kinshasa'), ('Africa/Lagos', 'Africa/Lagos'), ('Africa/Libreville', 'Africa/Libreville'), ('Africa/Lome', 'Africa/Lome'), ('Africa/Luanda', 'Africa/Luanda'), ('Africa/Lubumbashi', 'Africa/Lubumbashi'), ('Africa/Lusaka', 'Africa/Lusaka'), ('Africa/Malabo', 'Africa/Malabo'), ('Africa/Maputo', 'Africa/Maputo'), ('Africa/Maseru', 'Africa/Maseru'), ('Africa/Mbabane', 'Africa/Mbabane'), ('Africa/Mogadishu', 'Africa/Mogadishu'), ('Africa/Monrovia', 'Africa/Monrovia'), ('Africa/Nairobi', 'Africa/Nairobi'), ('Africa/Ndjamena', 'Africa/Ndjamena'), ('Africa/Niamey', 'Africa/Niamey'), ('Africa/Nouakchott', 'Africa/Nouakchott'), ('Africa/Ouagadougou', 'Africa/Ouagadougou'), ('Africa/Porto-Novo', 'Africa/Porto-Novo'), ('Africa/Sao_Tome', 'Africa/Sao_Tome'), ('Africa/Timbuktu', 'Africa/Timbuktu'), ('Africa/Tripoli', 'Africa/Tripoli'), ('Africa/Tunis', 'Africa/Tunis'), ('Africa/Windhoek', 'Africa/Windhoek'), ('America/Adak', 'America/Adak'), ('America/Anchorage', 'America/Anchorage'), ('America/Anguilla', 'America/Anguilla'), ('America/Antigua', 'America/Antigua'), ('America/Araguaina', 'America/Araguaina'), ('America/Argentina/Buenos_Aires', 'America/Argentina/Buenos_Aires'), ('America/Argentina/Catamarca', 'America/Argentina/Catamarca'), ('America/Argentina/ComodRivadavia', 'America/Argentina/ComodRivadavia'), ('America/Argentina/Cordoba', 'America/Argentina/Cordoba'), ('America/Argentina/Jujuy', 'America/Argentina/Jujuy'), ('America/Argentina/La_Rioja', 'America/Argentina/La_Rioja'), ('America/Argentina/Mendoza', 'America/Argentina/Mendoza'), ('America/Argentina/Rio_Gallegos', 'America/Argentina/Rio_Gallegos'), ('America/Argentina/Salta', 'America/Argentina/Salta'), ('America/Argentina/San_Juan', 'America/Argentina/San_Juan'), ('America/Argentina/San_Luis', 'America/Argentina/San_Luis'), ('America/Argentina/Tucuman', 'America/Argentina/Tucuman'), ('America/Argentina/Ushuaia', 'America/Argentina/Ushuaia'), ('America/Aruba', 'America/Aruba'), ('America/Asuncion', 'America/Asuncion'), ('America/Atikokan', 'America/Atikokan'), ('America/Atka', 'America/Atka'), ('America/Bahia', 'America/Bahia'), ('America/Bahia_Banderas', 'America/Bahia_Banderas'), ('America/Barbados', 'America/Barbados'), ('America/Belem', 'America/Belem'), ('America/Belize', 'America/Belize'), ('America/Blanc-Sablon', 'America/Blanc-Sablon'), ('America/Boa_Vista', 'America/Boa_Vista'), ('America/Bogota', 'America/Bogota'), ('America/Boise', 'America/Boise'), ('America/Buenos_Aires', 'America/Buenos_Aires'), ('America/Cambridge_Bay', 'America/Cambridge_Bay'), ('America/Campo_Grande', 'America/Campo_Grande'), ('America/Cancun', 'America/Cancun'), ('America/Caracas', 'America/Caracas'), ('America/Catamarca', 'America/Catamarca'), ('America/Cayenne', 'America/Cayenne'), ('America/Cayman', 'America/Cayman'), ('America/Chicago', 'America/Chicago'), ('America/Chihuahua', 'America/Chihuahua'), ('America/Ciudad_Juarez', 'America/Ciudad_Juarez'), ('America/Coral_Harbour', 'America/Coral_Harbour'), ('America/Cordoba', 'America/Cordoba'), ('America/Costa_Rica', 'America/Costa_Rica'), ('America/Coyhaique', 'America/Coyhaique'), ('America/Creston', 'America/Creston'), ('America/Cuiaba', 'America/Cuiaba'), ('America/Curacao', 'America/Curacao'), ('America/Danmarkshavn', 'America/Danmarkshavn'), ('America/Dawson', 'America/Dawson'), ('America/Dawson_Creek', 'America/Dawson_Creek'), ('America/Denver', 'America/Denver'), ('America/Detroit', 'America/Detroit'), ('America/Dominica', 'America/Dominica'), ('America/Edmonton', 'America/Edmonton'), ('America/Eirunepe', 'America/Eirunepe'), ('America/El_Salvador', 'America/El_Salvador'), ('America/Ensenada', 'America/Ensenada'), ('America/Fort_Nelson', 'America/Fort_Nelson'), ('America/Fort_Wayne', 'America/Fort_Wayne'), ('America/Fortaleza', 'America/Fortaleza'), ('America/Glace_Bay', 'America/Glace_Bay'), ('America/Godthab', 'America/Godthab'), ('America/Goose_Bay', 'America/Goose_Bay'), ('America/Grand_Turk', 'America/Grand_Turk'), ('America/Grenada', 'America/Grenada'), ('America/Guadeloupe', 'America/Guadeloupe'), ('America/Guatemala', 'America/Guatemala'), ('America/Guayaquil', 'America/Guayaquil'), ('America/Guyana', 'America/Guyana'), ('America/Halifax', 'America/Halifax'), ('America/Havana', 'America/Havana'), ('America/Hermosillo', 'America/Hermosillo'), ('America/Indiana/Indianapolis', 'America/Indiana/Indianapolis'), ('America/Indiana/Knox', 'America/Indiana/Knox'), ('America/Indiana/Marengo', 'America/Indiana/Marengo'), ('America/Indiana/Petersburg', 'America/Indiana/Petersburg'), ('America/Indiana/Tell_City', 'America/Indiana/Tell_City'), ('America/Indiana/Vevay', 'America/Indiana/Vevay'), ('America/Indiana/Vincennes', 'America/Indiana/Vincennes'), ('America/Indiana/Winamac', 'America/Indiana/Winamac'), ('America/Indianapolis', 'America/Indianapolis'), ('America/Inuvik', 'America/Inuvik'), ('America/Iqaluit', 'America/Iqaluit'), ('America/Jamaica', 'America/Jamaica'), ('America/Jujuy', 'America/Jujuy'), ('America/Juneau', 'America/Juneau'), ('America/Kentucky/Louisville', 'America/Kentucky/Louisville'), ('America/Kentucky/Monticello', 'America/Kentucky/Monticello'), ('America/Knox_IN', 'America/Knox_IN'), ('America/Kralendijk', 'America/Kralendijk'), ('America/La_Paz', 'America/La_Paz'), ('America/Lima', 'America/Lima'), ('America/Los_Angeles', 'America/Los_Angeles'), ('America/Louisville', 'America/Louisville'), ('America/Lower_Princes', 'America/Lower_Princes'), ('America/Maceio', 'America/Maceio'), ('America/Managua', 'America/Managua'), ('America/Manaus', 'America/Manaus'), ('America/Marigot', 'America/Marigot'), ('America/Martinique', 'America/Martinique'), ('America/Matamoros', 'America/Matamoros'), ('America/Mazatlan', 'America/Mazatlan'), ('America/Mendoza', 'America/Mendoza'), ('America/Menominee', 'America/Menominee'), ('America/Merida', 'America/Merida'), ('America/Metlakatla', 'America/Metlakatla'), ('America/Mexico_City', 'America/Mexico_City'), ('America/Miquelon', 'America/Miquelon'), ('America/Moncton', 'America/Moncton'), ('America/Monterrey', 'America/Monterrey'), ('America/Montevideo', 'America/Montevideo'), ('America/Montreal', 'America/Montreal'), ('America/Montserrat', 'America/Montserrat'), ('America/Nassau', 'America/Nassau'), ('America/New_York', 'America/New_York'), ('America/Nipigon', 'America/Nipigon'), ('America/Nome', 'America/Nome'), ('America/Noronha', 'America/Noronha'), ('America/North_Dakota/Beulah', 'America/North_Dakota/Beulah'), ('America/North_Dakota/Center', 'America/North_Dakota/Center'), ('America/North_Dakota/New_Salem', 'America/North_Dakota/New_Salem'), ('America/Nuuk', 'America/Nuuk'), ('America/Ojinaga', 'America/Ojinaga'), ('America/Panama', 'America/Panama'), ('America/Pangnirtung', 'America/Pangnirtung'), ('America/Paramaribo', 'America/Paramaribo'), ('America/Phoenix', 'America/Phoenix'), ('America/Port-au-Prince', 'America/Port-au-Prince'), ('America/Port_of_Spain', 'America/Port_of_Spain'), ('America/Porto_Acre', 'America/Porto_Acre'), ('America/Porto_Velho', 'America/Porto_Velho'), ('America/Puerto_Rico', 'America/Puerto_Rico'), ('America/Punta_Arenas', 'America/Punta_Arenas'), ('America/Rainy_River', 'America/Rainy_River'), ('America/Rankin_Inlet', 'America/Rankin_Inlet'), ('America/Recife', 'America/Recife'), ('America/Regina', 'America/Regina'), ('America/Resolute', 'America/Resolute'), ('America/Rio_Branco', 'America/Rio_Branco'), ('America/Rosario', 'America/Rosario'), ('America/Santa_Isabel', 'America/Santa_Isabel'), ('America/Santarem', 'America/Santarem'), ('America/Santiago', 'America/Santiago'), ('America/Santo_Domingo', 'America/Santo_Domingo'), ('America/Sao_Paulo', 'America/Sao_Paulo'), ('America/Scoresbysund', 'America/Scoresbysund'), ('America/Shiprock', 'America/Shiprock'), ('America/Sitka', 'America/Sitka'), ('America/St_Barthelemy', 'America/St_Barthelemy'), ('America/St_Johns', 'America/St_Johns'), ('America/St_Kitts', 'America/St_Kitts'), ('America/St_Lucia', 'America/St_Lucia'), ('America/St_Thomas', 'America/St_Thomas'), ('America/St_Vincent', 'America/St_Vincent'), ('America/Swift_Current', 'America/Swift_Current'), ('America/Tegucigalpa', 'America/Tegucigalpa'), ('America/Thule', 'America/Thule'), ('America/Thunder_Bay', 'America/Thunder_Bay'), ('America/Tijuana', 'America/Tijuana'), ('America/Toronto', 'America/Toronto'), ('America/Tortola', 'America/Tortola'), ('America/Vancouver', 'America/Vancouver'), ('America/Virgin', 'America/Virgin'), ('America/Whitehorse', 'America/Whitehorse'), ('America/Winnipeg', 'America/Winnipeg'), ('America/Yakutat', 'America/Yakutat'), ('America/Yellowknife', 'America/Yellowknife'), ('Antarctica/Casey', 'Antarctica/Casey'), ('Antarctica/Davis', 'Antarctica/Davis'), ('Antarctica/DumontDUrville', 'Antarctica/DumontDUrville'), ('Antarctica/Macquarie', 'Antarctica/Macquarie'), ('Antarctica/Mawson', 'Antarctica/Mawson'), ('Antarctica/McMurdo', 'Antarctica/McMurdo'), ('Antarctica/Palmer', 'Antarctica/Palmer'), ('Antarctica/Rothera', 'Antarctica/Rothera'), ('Antarctica/South_Pole', 'Antarctica/South_Pole'), ('Antarctica/Syowa', 'Antarctica/Syowa'), ('Antarctica/Troll', 'Antarctica/Troll'), ('Antarctica/Vostok', 'Antarctica/Vostok'), ('Arctic/Longyearbyen', 'Arctic/Longyearbyen'), ('Asia/Aden', 'Asia/Aden'), ('Asia/Almaty', 'Asia/Almaty'), ('Asia/Amman', 'Asia/Amman'), ('Asia/Anadyr', 'Asia/Anadyr'), ('Asia/Aqtau', 'Asia/Aqtau'), ('Asia/Aqtobe', 'Asia/Aqtobe'), ('Asia/Ashgabat', 'Asia/Ashgabat'), ('Asia/Ashkhabad', 'Asia/Ashkhabad'), ('Asia/Atyrau', 'Asia/Atyrau'), ('Asia/Baghdad', 'Asia/Baghdad'), ('Asia/Bahrain', 'Asia/Bahrain'), ('Asia/Baku', 'Asia/Baku'), ('Asia/Bangkok', 'Asia/Bangkok'), ('Asia/Barnaul', 'Asia/Barnaul'), ('Asia/Beirut', 'Asia/Beirut'), ('Asia/Bishkek', 'Asia/Bishkek'), ('Asia/Brunei', 'Asia/Brunei'), ('Asia/Calcutta', 'Asia/Calcutta'), ('Asia/Chita', 'Asia/Chita'), ('Asia/Choibalsan', 'Asia/Choibalsan'), ('Asia/Chongqing', 'Asia/Chongqing'), ('Asia/Chungking', 'Asia/Chungking'), ('Asia/Colombo', 'Asia/Colombo'), ('Asia/Dacca', 'Asia/Dacca'), ('Asia/Damascus', 'Asia/Damascus'), ('Asia/Dhaka', 'Asia/Dhaka'), ('Asia/Dili', 'Asia/Dili'), ('Asia/Dubai', 'Asia/Dubai'), ('Asia/Dushanbe', 'Asia/Dushanbe'), ('Asia/Famagusta', 'Asia/Famagusta'), ('Asia/Gaza', 'Asia/Gaza'), ('Asia/Harbin', 'Asia/Harbin'), ('Asia/Hebron', 'Asia/Hebron'), ('Asia/Ho_Chi_Minh', 'Asia/Ho_Chi_Minh'), ('Asia/Hong_Kong', 'Asia/Hong_Kong'), ('Asia/Hovd', 'Asia/Hovd'), ('Asia/Irkutsk', 'Asia/Irkutsk'), ('Asia/Istanbul', 'Asia/Istanbul'), ('Asia/Jakarta', 'Asia/Jakarta'), ('Asia/Jayapura', 'Asia/Jayapura'), ('Asia/Jerusalem', 'Asia/Jerusalem'), ('Asia/Kabul', 'Asia/Kabul'), ('Asia/Kamchatka', 'Asia/Kamchatka'), ('Asia/Karachi', 'Asia/Karachi'), ('Asia/Kashgar', 'Asia/Kashgar'), ('Asia/Kathmandu', 'Asia/Kathmandu'), ('Asia/Katmandu', 'Asia/Katmandu'), ('Asia/Khandyga', 'Asia/Khandyga'), ('Asia/Kolkata', 'Asia/Kolkata'), ('Asia/Krasnoyarsk', 'Asia/Krasnoyarsk'), ('Asia/Kuala_Lumpur', 'Asia/Kuala_Lumpur'), ('Asia/Kuching', 'Asia/Kuching'), ('Asia/Kuwait', 'Asia/Kuwait'), ('Asia/Macao', 'Asia/Macao'), ('Asia/Macau', 'Asia/Macau'), ('Asia/Magadan', 'Asia/Magadan'), ('Asia/Makassar', 'Asia/Makassar'), ('Asia/Manila', 'Asia/Manila'), ('Asia/Muscat', 'Asia/Muscat'), ('Asia/Nicosia', 'Asia/Nicosia'), ('Asia/Novokuznetsk', 'Asia/Novokuznetsk'), ('Asia/Novosibirsk', 'Asia/Novosibirsk'), ('Asia/Omsk', 'Asia/Omsk'), ('Asia/Oral', 'Asia/Oral'), ('Asia/Phnom_Penh', 'Asia/Phnom_Penh'), ('Asia/Pontianak', 'Asia/Pontianak'), ('Asia/Pyongyang', 'Asia/Pyongyang'), ('Asia/Qatar', 'Asia/Qatar'), ('Asia/Qostanay', 'Asia/Qostanay'), ('Asia/Qyzylorda', 'Asia/Qyzylorda'), ('Asia/Rangoon', 'Asia/Rangoon'), ('Asia/Riyadh', 'Asia/Riyadh'), ('Asia/Saigon', 'Asia/Saigon'), ('Asia/Sakhalin', 'Asia/Sakhalin'), ('Asia/Samarkand', 'Asia/Samarkand'), ('Asia/Seoul', 'Asia/Seoul'), ('Asia/Shanghai', 'Asia/Shanghai'), ('Asia/Singapore', 'Asia/Singapore'), ('Asia/Srednekolymsk', 'Asia/Srednekolymsk'), ('Asia/Taipei', 'Asia/Taipei'), ('Asia/Tashkent', 'Asia/Tashkent'), ('Asia/Tbilisi', 'Asia/Tbilisi'), ('Asia/Tehran', 'Asia/Tehran'), ('Asia/Tel_Aviv', 'Asia/Tel_Aviv'), ('Asia/Thimbu', 'Asia/Thimbu'), ('Asia/Thimphu', 'Asia/Thimphu'), ('Asia/Tokyo', 'Asia/Tokyo'), ('Asia/Tomsk', 'Asia/Tomsk'), ('Asia/Ujung_Pandang', 'Asia/Ujung_Pandang'), ('Asia/Ulaanbaatar', 'Asia/Ulaanbaatar'), ('Asia/Ulan_Bator', 'Asia/Ulan_Bator'), ('Asia/Urumqi', 'Asia/Urumqi'), ('Asia/Ust-Nera', 'Asia/Ust-Nera'), ('Asia/Vientiane', 'Asia/Vientiane'), ('Asia/Vladivostok', 'Asia/Vladivostok'), ('Asia/Yakutsk', 'Asia/Yakutsk'), ('Asia/Yangon', 'Asia/Yangon'), ('Asia/Yekaterinburg', 'Asia/Yekaterinburg'), ('Asia/Yerevan', 'Asia/Yerevan'), ('Atlantic/Azores', 'Atlantic/Azores'), ('Atlantic/Bermuda', 'Atlantic/Bermuda'), ('Atlantic/Canary', 'Atlantic/Canary'), ('Atlantic/Cape_Verde', 'Atlantic/Cape_Verde'), ('Atlantic/Faeroe', 'Atlantic/Faeroe'), ('Atlantic/Faroe', 'Atlantic/Faroe'), ('Atlantic/Jan_Mayen', 'Atlantic/Jan_Mayen'), ('Atlantic/Madeira', 'Atlantic/Madeira'), ('Atlantic/Reykjavik', 'Atlantic/Reykjavik'), ('Atlantic/South_Georgia', 'Atlantic/South_Georgia'), ('Atlantic/St_Helena', 'Atlantic/St_Helena'), ('Atlantic/Stanley', 'Atlantic/Stanley'), ('Australia/ACT', 'Australia/ACT'), ('Australia/Adelaide', 'Australia/Adelaide'), ('Australia/Brisbane', 'Australia/Brisbane'), ('Australia/Broken_Hill', 'Australia/Broken_Hill'), ('Australia/Canberra', 'Australia/Canberra'), ('Australia/Currie', 'Australia/Currie'), ('Australia/Darwin', 'Australia/Darwin'), ('Australia/Eucla', 'Australia/Eucla'), ('Australia/Hobart', 'Australia/Hobart'), ('Australia/LHI', 'Australia/LHI'), ('Australia/Lindeman', 'Australia/Lindeman'), ('Australia/Lord_Howe', 'Australia/Lord_Howe'), ('Australia/Melbourne', 'Australia/Melbourne'), ('Australia/NSW', 'Australia/NSW'), ('Australia/North', 'Australia/North'), ('Australia/Perth', 'Australia/Perth'), ('Australia/Queensland', 'Australia/Queensland'), ('Australia/South', 'Australia/South'), ('Australia/Sydney', 'Australia/Sydney'), ('Australia/Tasmania', 'Australia/Tasmania'), ('Australia/Victoria', 'Australia/Victoria'), ('Australia/West', 'Australia/West'), ('Australia/Yancowinna', 'Australia/Yancowinna'), ('Brazil/Acre', 'Brazil/Acre'), ('Brazil/DeNoronha', 'Brazil/DeNoronha'), ('Brazil/East', 'Brazil/East'), ('Brazil/West', 'Brazil/West'), ('CET', 'CET'), ('CST6CDT', 'CST6CDT'), ('Canada/Atlantic', 'Canada/Atlantic'), ('Canada/Central', 'Canada/Central'), ('Canada/Eastern', 'Canada/Eastern'), ('Canada/Mountain', 'Canada/Mountain'), ('Canada/Newfoundland', 'Canada/Newfoundland'), ('Canada/Pacific', 'Canada/Pacific'), ('Canada/Saskatchewan', 'Canada/Saskatchewan'), ('Canada/Yukon', 'Canada/Yukon'), ('Chile/Continental', 'Chile/Continental'), ('Chile/EasterIsland', 'Chile/EasterIsland'), ('Cuba', 'Cuba'), ('EET', 'EET'), ('EST', 'EST'), ('EST5EDT', 'EST5EDT'), ('Egypt', 'Egypt'), ('Eire', 'Eire'), ('Etc/GMT', 'Etc/GMT'), ('Etc/GMT+0', 'Etc/GMT+0'), ('Etc/GMT+1', 'Etc/GMT+1'), ('Etc/GMT+10', 'Etc/GMT+10'), ('Etc/GMT+11', 'Etc/GMT+11'), ('Etc/GMT+12', 'Etc/GMT+12'), ('Etc/GMT+2', 'Etc/GMT+2'), ('Etc/GMT+3', 'Etc/GMT+3'), ('Etc/GMT+4', 'Etc/GMT+4'), ('Etc/GMT+5', 'Etc/GMT+5'), ('Etc/GMT+6', 'Etc/GMT+6'), ('Etc/GMT+7', 'Etc/GMT+7'), ('Etc/GMT+8', 'Etc/GMT+8'), ('Etc/GMT+9', 'Etc/GMT+9'), ('Etc/GMT-0', 'Etc/GMT-0'), ('Etc/GMT-1', 'Etc/GMT-1'), ('Etc/GMT-10', 'Etc/GMT-10'), ('Etc/GMT-11', 'Etc/GMT-11'), ('Etc/GMT-12', 'Etc/GMT-12'), ('Etc/GMT-13', 'Etc/GMT-13'), ('Etc/GMT-14', 'Etc/GMT-14'), ('Etc/GMT-2', 'Etc/GMT-2'), ('Etc/GMT-3', 'Etc/GMT-3'), ('Etc/GMT-4', 'Etc/GMT-4'), ('Etc/GMT-5', 'Etc/GMT-5'), ('Etc/GMT-6', 'Etc/GMT-6'), ('Etc/GMT-7', 'Etc/GMT-7'), ('Etc/GMT-8', 'Etc/GMT-8'), ('Etc/GMT-9', 'Etc/GMT-9'), ('Etc/GMT0', 'Etc/GMT0'), ('Etc/Greenwich', 'Etc/Greenwich'), ('Etc/UCT', 'Etc/UCT'), ('Etc/UTC', 'Etc/UTC'), ('Etc/Universal', 'Etc/Universal'), ('Etc/Zulu', 'Etc/Zulu'), ('Europe/Amsterdam', 'Europe/Amsterdam'), ('Europe/Andorra', 'Europe/Andorra'), ('Europe/Astrakhan', 'Europe/Astrakhan'), ('Europe/Athens', 'Europe/Athens'), ('Europe/Belfast', 'Europe/Belfast'), ('Europe/Belgrade', 'Europe/Belgrade'), ('Europe/Berlin', 'Europe/Berlin'), ('Europe/Bratislava', 'Europe/Bratislava'), ('Europe/Brussels', 'Europe/Brussels'), ('Europe/Bucharest', 'Europe/Bucharest'), ('Europe/Budapest', 'Europe/Budapest'), ('Europe/Busingen', 'Europe/Busingen'), ('Europe/Chisinau', 'Europe/Chisinau'), ('Europe/Copenhagen', 'Europe/Copenhagen'), ('Europe/Dublin', 'Europe/Dublin'), ('Europe/Gibraltar', 'Europe/Gibraltar'), ('Europe/Guernsey', 'Europe/Guernsey'), ('Europe/Helsinki', 'Europe/Helsinki'), ('Europe/Isle_of_Man', 'Europe/Isle_of_Man'), ('Europe/Istanbul', 'Europe/Istanbul'), ('Europe/Jersey', 'Europe/Jersey'), ('Europe/Kaliningrad', 'Europe/Kaliningrad'), ('Europe/Kiev', 'Europe/Kiev'), ('Europe/Kirov', 'Europe/Kirov'), ('Europe/Kyiv', 'Europe/Kyiv'), ('Europe/Lisbon', 'Europe/Lisbon'), ('Europe/Ljubljana', 'Europe/Ljubljana'), ('Europe/London', 'Europe/London'), ('Europe/Luxembourg', 'Europe/Luxembourg'), ('Europe/Madrid', 'Europe/Madrid'), ('Europe/Malta', 'Europe/Malta'), ('Europe/Mariehamn', 'Europe/Mariehamn'), ('Europe/Minsk', 'Europe/Minsk'), ('Europe/Monaco', 'Europe/Monaco'), ('Europe/Moscow', 'Europe/Moscow'), ('Europe/Nicosia', 'Europe/Nicosia'), ('Europe/Oslo', 'Europe/Oslo'), ('Europe/Paris', 'Europe/Paris'), ('Europe/Podgorica', 'Europe/Podgorica'), ('Europe/Prague', 'Europe/Prague'), ('Europe/Riga', 'Europe/Riga'), ('Europe/Rome', 'Europe/Rome'), ('Europe/Samara', 'Europe/Samara'), ('Europe/San_Marino', 'Europe/San_Marino'), ('Europe/Sarajevo', 'Europe/Sarajevo'), ('Europe/Saratov', 'Europe/Saratov'), ('Europe/Simferopol', 'Europe/Simferopol'), ('Europe/Skopje', 'Europe/Skopje'), ('Europe/Sofia', 'Europe/Sofia'), ('Europe/Stockholm', 'Europe/Stockholm'), ('Europe/Tallinn', 'Europe/Tallinn'), ('Europe/Tirane', 'Europe/Tirane'), ('Europe/Tiraspol', 'Europe/Tiraspol'), ('Europe/Ulyanovsk', 'Europe/Ulyanovsk'), ('Europe/Uzhgorod', 'Europe/Uzhgorod'), ('Europe/Vaduz', 'Europe/Vaduz'), ('Europe/Vatican', 'Europe/Vatican'), ('Europe/Vienna', 'Europe/Vienna'), ('Europe/Vilnius', 'Europe/Vilnius'), ('Europe/Volgograd', 'Europe/Volgograd'), ('Europe/Warsaw', 'Europe/Warsaw'), ('Europe/Zagreb', 'Europe/Zagreb'), ('Europe/Zaporozhye', 'Europe/Zaporozhye'), ('Europe/Zurich', 'Europe/Zurich'), ('Factory', 'Factory'), ('GB', 'GB'), ('GB-Eire', 'GB-Eire'), ('GMT', 'GMT'), ('GMT+0', 'GMT+0'), ('GMT-0', 'GMT-0'), ('GMT0', 'GMT0'), ('Greenwich', 'Greenwich'), ('HST', 'HST'), ('Hongkong', 'Hongkong'), ('Iceland', 'Iceland'), ('Indian/Antananarivo', 'Indian/Antananarivo'), ('Indian/Chagos', 'Indian/Chagos'), ('Indian/Christmas', 'Indian/Christmas'), ('Indian/Cocos', 'Indian/Cocos'), ('Indian/Comoro', 'Indian/Comoro'), ('Indian/Kerguelen', 'Indian/Kerguelen'), ('Indian/Mahe', 'Indian/Mahe'), ('Indian/Maldives', 'Indian/Maldives'), ('Indian/Mauritius', 'Indian/Mauritius'), ('Indian/Mayotte', 'Indian/Mayotte'), ('Indian/Reunion', 'Indian/Reunion'), ('Iran', 'Iran'), ('Israel', 'Israel'), ('Jamaica', 'Jamaica'), ('Japan', 'Japan'), ('Kwajalein', 'Kwajalein'), ('Libya', 'Libya'), ('MET', 'MET'), ('MST', 'MST'), ('MST7MDT', 'MST7MDT'), ('Mexico/BajaNorte', 'Mexico/BajaNorte'), ('Mexico/BajaSur', 'Mexico/BajaSur'), ('Mexico/General', 'Mexico/General'), ('NZ', 'NZ'), ('NZ-CHAT', 'NZ-CHAT'), ('Navajo', 'Navajo'), ('PRC', 'PRC'), ('PST8PDT', 'PST8PDT'), ('Pacific/Apia', 'Pacific/Apia'), ('Pacific/Auckland', 'Pacific/Auckland'), ('Pacific/Bougainville', 'Pacific/Bougainville'), ('Pacific/Chatham', 'Pacific/Chatham'), ('Pacific/Chuuk', 'Pacific/Chuuk'), ('Pacific/Easter', 'Pacific/Easter'), ('Pacific/Efate', 'Pacific/Efate'), ('Pacific/Enderbury', 'Pacific/Enderbury'), ('Pacific/Fakaofo', 'Pacific/Fakaofo'), ('Pacific/Fiji', 'Pacific/Fiji'), ('Pacific/Funafuti', 'Pacific/Funafuti'), ('Pacific/Galapagos', 'Pacific/Galapagos'), ('Pacific/Gambier', 'Pacific/Gambier'), ('Pacific/Guadalcanal', 'Pacific/Guadalcanal'), ('Pacific/Guam', 'Pacific/Guam'), ('Pacific/Honolulu', 'Pacific/Honolulu'), ('Pacific/Johnston', 'Pacific/Johnston'), ('Pacific/Kanton', 'Pacific/Kanton'), ('Pacific/Kiritimati', 'Pacific/Kiritimati'), ('Pacific/Kosrae', 'Pacific/Kosrae'), ('Pacific/Kwajalein', 'Pacific/Kwajalein'), ('Pacific/Majuro', 'Pacific/Majuro'), ('Pacific/Marquesas', 'Pacific/Marquesas'), ('Pacific/Midway', 'Pacific/Midway'), ('Pacific/Nauru', 'Pacific/Nauru'), ('Pacific/Niue', 'Pacific/Niue'), ('Pacific/Norfolk', 'Pacific/Norfolk'), ('Pacific/Noumea', 'Pacific/Noumea'), ('Pacific/Pago_Pago', 'Pacific/Pago_Pago'), ('Pacific/Palau', 'Pacific/Palau'), ('Pacific/Pitcairn', 'Pacific/Pitcairn'), ('Pacific/Pohnpei', 'Pacific/Pohnpei'), ('Pacific/Ponape', 'Pacific/Ponape'), ('Pacific/Port_Moresby', 'Pacific/Port_Moresby'), ('Pacific/Rarotonga', 'Pacific/Rarotonga'), ('Pacific/Saipan', 'Pacific/Saipan'), ('Pacific/Samoa', 'Pacific/Samoa'), ('Pacific/Tahiti', 'Pacific/Tahiti'), ('Pacific/Tarawa', 'Pacific/Tarawa'), ('Pacific/Tongatapu', 'Pacific/Tongatapu'), ('Pacific/Truk', 'Pacific/Truk'), ('Pacific/Wake', 'Pacific/Wake'), ('Pacific/Wallis', 'Pacific/Wallis'), ('Pacific/Yap', 'Pacific/Yap'), ('Poland', 'Poland'), ('Portugal', 'Portugal'), ('ROC', 'ROC'), ('ROK', 'ROK'), ('Singapore', 'Singapore'), ('Turkey', 'Turkey'), ('UCT', 'UCT'), ('US/Alaska', 'US/Alaska'), ('US/Aleutian', 'US/Aleutian'), ('US/Arizona', 'US/Arizona'), ('US/Central', 'US/Central'), ('US/East-Indiana', 'US/East-Indiana'), ('US/Eastern', 'US/Eastern'), ('US/Hawaii', 'US/Hawaii'), ('US/Indiana-Starke', 'US/Indiana-Starke'), ('US/Michigan', 'US/Michigan'), ('US/Mountain', 'US/Mountain'), ('US/Pacific', 'US/Pacific'), ('US/Samoa', 'US/Samoa'), ('UTC', 'UTC'), ('Universal', 'Universal'), ('W-SU', 'W-SU'), ('WET', 'WET'), ('Zulu', 'Zulu'), ('localtime', 'localtime')], default='Europe/Paris', max_length=50, verbose_name='Timezone'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='language',
            field=models.CharField(choices=[('fr', 'French'), ('en', 'English')], default='fr', max_length=2, verbose_name='Langue'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='postal_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BaseBillet.postaladdress', verbose_name='Adresse postale'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='site_web',
            field=models.URLField(blank=True, null=True, verbose_name='Site web'),
        ),
        migrations.AlterField(
            model_name='event',
            name='postal_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BaseBillet.postaladdress', verbose_name='Adresse postale'),
        ),
        migrations.AlterField(
            model_name='event',
            name='products',
            field=models.ManyToManyField(blank=True, limit_choices_to={'categorie_article__in': ['B', 'F']}, to='BaseBillet.product', verbose_name='Products'),
        ),
        migrations.AlterField(
            model_name='externalapikey',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
        migrations.AlterField(
            model_name='externalapikey',
            name='key',
            field=models.OneToOneField(blank=True, help_text='Confirm to generate key. It will not appear before.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_key', to='rest_framework_api_key.apikey', verbose_name='Clé'),
        ),
        migrations.AlterField(
            model_name='externalapikey',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nom de la clé'),
        ),
        migrations.AlterField(
            model_name='externalapikey',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who created this key.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur·ice'),
        ),
        migrations.AlterField(
            model_name='federatedplace',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Collective', to='Customers.client', verbose_name='Lieu'),
        ),
        migrations.AlterField(
            model_name='formbricksforms',
            name='environmentId',
            field=models.CharField(help_text='Formbricks environment ID', max_length=30, verbose_name="Identifiant d'environnement"),
        ),
        migrations.AlterField(
            model_name='formbricksforms',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formbricksform', to='BaseBillet.product', verbose_name='Produit'),
        ),
        migrations.AlterField(
            model_name='ghostconfig',
            name='ghost_last_log',
            field=models.TextField(blank=True, null=True, verbose_name='Dernier journal Ghost'),
        ),
        migrations.AlterField(
            model_name='lignearticle',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date et heure'),
        ),
        migrations.AlterField(
            model_name='lignearticle',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('UK', 'Unknown'), ('NA', 'Offered'), ('CC', 'Credit card: POS terminal'), ('CA', 'Cash'), ('CH', 'Check'), ('QR', 'QrCode or NFC'), ('TR', 'Bank transfer'), ('SF', 'Online: federated Stripe'), ('SN', 'Online: Stripe CC'), ('SP', 'Online: Stripe SEPA'), ('SR', 'Recurring: Stripe'), ('LE', 'Asset local fiat'), ('LG', 'Asset local gift'), ('NM', 'Points ou temps (non monétaire)')], max_length=2, null=True, verbose_name='Payment method'),
        ),
        migrations.AlterField(
            model_name='lignearticle',
            name='sale_origin',
            field=models.CharField(choices=[('LP', 'Online platform'), ('LB', 'Cash register'), ('AD', 'Administration'), ('EX', 'External'), ('QR', 'QrCode online'), ('NF', 'NFC online'), ('AP', 'API'), ('WK', 'Webhook Stripe'), ('TI', 'Connected tap')], default='LP', max_length=2, verbose_name='Payment source'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Numéro de carte'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('UK', 'Unknown'), ('NA', 'Offered'), ('CC', 'Credit card: POS terminal'), ('CA', 'Cash'), ('CH', 'Check'), ('QR', 'QrCode or NFC'), ('TR', 'Bank transfer'), ('SF', 'Online: federated Stripe'), ('SN', 'Online: Stripe CC'), ('SP', 'Online: Stripe SEPA'), ('SR', 'Recurring: Stripe'), ('LE', 'Asset local fiat'), ('LG', 'Asset local gift'), ('NM', 'Points ou temps (non monétaire)')], max_length=2, null=True, verbose_name='Payment method'),
        ),
        migrations.AlterField(
            model_name='paiement_stripe',
            name='status',
            field=models.CharField(choices=[('N', 'Payment link not generated'), ('O', 'Sent to Stripe'), ('W', 'Waiting for payment'), ('E', 'Expired'), ('F', 'Failed'), ('P', 'Paid'), ('V', 'Paid and confirmed'), ('S', 'Paid but issues with LaBoutik sync'), ('C', 'Cancelled'), ('R', 'Refunded'), ('H', 'Partiellement remboursé')], default='N', max_length=1, verbose_name='Order status'),
        ),
        migrations.AlterField(
            model_name='paiement_stripe',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur·ice'),
        ),
        migrations.AlterField(
            model_name='price',
            name='adhesions_obligatoires',
            field=models.ManyToManyField(blank=True, help_text='Rate available to subscribers only (OR logic: having at least one of the selected subscriptions is enough). Only works for reservation-type products. The rate will be visible if the user is logged in AND has paid at least one of these membership fees.', limit_choices_to={'categorie_article': 'A'}, related_name='adhesions_obligatoires', to='BaseBillet.product', verbose_name='Subscriptions required'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categorie_article',
            field=models.CharField(choices=[('N', 'Select a category'), ('B', 'Ticket booking'), ('F', 'Free booking'), ('A', 'Subscription or membership'), ('G', 'Punchclock'), ('Q', 'QrCode paiement on my account'), ('C', 'Ressource'), ('U', 'Keg (connected tap)')], default='N', max_length=3, verbose_name='Product type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='validate_button_text',
            field=models.CharField(blank=True, help_text="'Subscribe' If empty. Only useful for membership or subscription products.", max_length=30, null=True, verbose_name='Validate button text for membership'),
        ),
        migrations.AlterField(
            model_name='productsold',
            name='categorie_article',
            field=models.CharField(choices=[('N', 'Select a category'), ('B', 'Ticket booking'), ('F', 'Free booking'), ('A', 'Subscription or membership'), ('G', 'Punchclock'), ('Q', 'QrCode paiement on my account'), ('C', 'Ressource'), ('U', 'Keg (connected tap)')], default='N', max_length=3, verbose_name='Product type'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Date et heure'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation', to='BaseBillet.event', verbose_name='Évènement'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user_commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Personne qui réserve'),
        ),
        migrations.AlterField(
            model_name='scanapp',
            name='archive',
            field=models.BooleanField(default=False, verbose_name='Archivée'),
        ),
        migrations.AlterField(
            model_name='scanapp',
            name='claimed',
            field=models.BooleanField(default=False, verbose_name='Appairée'),
        ),
        migrations.AlterField(
            model_name='scanapp',
            name='name',
            field=models.CharField(max_length=30, verbose_name="Nom de l'application"),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('UK', 'Unknown'), ('NA', 'Offered'), ('CC', 'Credit card: POS terminal'), ('CA', 'Cash'), ('CH', 'Check'), ('QR', 'QrCode or NFC'), ('TR', 'Bank transfer'), ('SF', 'Online: federated Stripe'), ('SN', 'Online: Stripe CC'), ('SP', 'Online: Stripe SEPA'), ('SR', 'Recurring: Stripe'), ('LE', 'Asset local fiat'), ('LG', 'Asset local gift'), ('NM', 'Points ou temps (non monétaire)')], max_length=2, null=True, verbose_name='Payment method'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sale_origin',
            field=models.CharField(choices=[('LP', 'Online platform'), ('LB', 'Cash register'), ('AD', 'Administration'), ('EX', 'External'), ('QR', 'QrCode online'), ('NF', 'NFC online'), ('AP', 'API'), ('WK', 'Webhook Stripe'), ('TI', 'Connected tap')], default='LP', max_length=2, verbose_name='Payment source'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='last_response',
            field=models.TextField(blank=True, null=True, verbose_name='Dernière réponse'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='url',
            field=models.URLField(help_text="Astuce Dev' : pour tester un webhook, lancez un petit serveur HTTP qui affiche le contenu de la requete : https://gist.github.com/mdonkers/63e115cc0c79b4f6b8b3a6b797e485c7", verbose_name='URL de destination'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('archive', False)), fields=('categorie_article', 'name'), name='unique_product_non_archive_par_categorie_et_nom', violation_error_message='Un produit avec ce nom existe déjà. Choisissez un autre nom, ou archivez le produit existant.'),
        ),
        migrations.AddField(
            model_name='vente',
            name='carte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes', to='QrcodeCashless.cartecashless', verbose_name='Carte'),
        ),
        migrations.AddField(
            model_name='vente',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes_achetees', to=settings.AUTH_USER_MODEL, verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='vente',
            name='operateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes_operees', to=settings.AUTH_USER_MODEL, verbose_name='Opérateur'),
        ),
        migrations.AddField(
            model_name='vente',
            name='point_de_vente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to='laboutik.pointdevente', verbose_name='Point de vente'),
        ),
        migrations.AddField(
            model_name='vente',
            name='vente_liee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventes_derivees', to='BaseBillet.vente', verbose_name='Vente liée'),
        ),
        migrations.AddField(
            model_name='reglement',
            name='carte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reglements', to='QrcodeCashless.cartecashless', verbose_name='Carte'),
        ),
        migrations.AddField(
            model_name='reglement',
            name='paiement_stripe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reglements', to='BaseBillet.paiement_stripe', verbose_name='Paiement Stripe'),
        ),
        migrations.AddField(
            model_name='reglement',
            name='vente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reglements', to='BaseBillet.vente', verbose_name='Vente'),
        ),
        migrations.AddField(
            model_name='reglement',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reglements', to='AuthBillet.wallet', verbose_name='Portefeuille'),
        ),
        migrations.AddField(
            model_name='commande',
            name='paiement_stripe',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commande_obj', to='BaseBillet.paiement_stripe', verbose_name='Stripe payment'),
        ),
        migrations.AddField(
            model_name='commande',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='BaseBillet.promotionalcode', verbose_name='Promotional code'),
        ),
        migrations.AddField(
            model_name='commande',
            name='user',
            field=models.ForeignKey(help_text='Utilisateur acheteur (résolu par email au checkout). / Buyer user (resolved by email at checkout).', on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to=settings.AUTH_USER_MODEL, verbose_name='Buyer'),
        ),
        migrations.AddField(
            model_name='commande',
            name='vente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='BaseBillet.vente', verbose_name='Vente'),
        ),
        migrations.AddField(
            model_name='categorieproduct',
            name='compte_comptable',
            field=models.ForeignKey(blank=True, help_text="Compte comptable de vente associe a cette categorie. Utilise pour l'export FEC et CSV comptable. / Sales accounting code for this category. Used for FEC and CSV accounting export.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories_produit', to='laboutik.comptecomptable', verbose_name='Accounting code'),
        ),
        migrations.AddField(
            model_name='categorieproduct',
            name='printer',
            field=models.ForeignKey(blank=True, help_text='Printer for order tickets (kitchen, bar). When an order contains products from this category, the ticket is sent to this printer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories_produit', to='laboutik.printer', verbose_name='Order printer'),
        ),
        migrations.AddField(
            model_name='categorieproduct',
            name='tva',
            field=models.ForeignKey(blank=True, help_text='Default VAT rate applied to products in this category.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='BaseBillet.tva', verbose_name='Default VAT rate'),
        ),
        migrations.AddField(
            model_name='lignearticle',
            name='vente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='BaseBillet.vente', verbose_name='Vente'),
        ),
        migrations.AddField(
            model_name='membership',
            name='commande',
            field=models.ForeignKey(blank=True, help_text="Renseignée uniquement si l'adhésion a été créée via un panier multi-items. / Only set if the membership was created via a multi-item cart.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships_commande', to='BaseBillet.commande', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='paiement_stripe',
            name='vente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paiements_stripe', to='BaseBillet.vente', verbose_name="Vente d'origine"),
        ),
        migrations.AddField(
            model_name='product',
            name='categorie_pos',
            field=models.ForeignKey(blank=True, help_text='Display category on the POS interface.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_pos', to='BaseBillet.categorieproduct', verbose_name='POS category'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='commande',
            field=models.ForeignKey(blank=True, help_text='Renseignée uniquement si la reservation a été créée via un panier multi-items. / Only set if the reservation was created via a multi-item cart.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='BaseBillet.commande', verbose_name='Order'),
        ),
        migrations.AddIndex(
            model_name='vente',
            index=models.Index(fields=['statut', 'datetime_encaissement'], name='vente_statut_encaissement'),
        ),
        migrations.AddConstraint(
            model_name='vente',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('idempotency_key',), name='unique_vente_idempotency_key'),
        ),
        migrations.AddConstraint(
            model_name='reglement',
            constraint=models.CheckConstraint(check=models.Q(('montant', 0), _negated=True), name='reglement_montant_non_nul'),
        ),
        # Déplacées ici à la main : ces contraintes citent `vente`, ajouté plus haut.
        # / Moved here by hand: these constraints use `vente`, added above.
        migrations.AddConstraint(
            model_name='lignearticle',
            constraint=models.CheckConstraint(check=models.Q(('total_ttc', django.db.models.expressions.CombinedExpression(models.F('total_catalogue'), '-', models.F('part_offerte')))), name='lignearticle_ttc_egal_catalogue_moins_offert'),
        ),
        migrations.AddConstraint(
            model_name='lignearticle',
            constraint=models.CheckConstraint(check=models.Q(('vente__isnull', True), ('total_ttc', django.db.models.expressions.CombinedExpression(models.F('total_ht'), '+', models.F('total_tva'))), _connector='OR'), name='lignearticle_ht_plus_tva_egal_ttc_si_vente'),
        ),
        migrations.AddConstraint(
            model_name='lignearticle',
            constraint=models.CheckConstraint(check=models.Q(models.Q(models.Q(('total_ttc__gte', 0), ('part_en_jetons__gte', 0), ('part_en_jetons__lte', models.F('total_ttc'))), models.Q(('total_ttc__lt', 0), ('part_en_jetons__lte', 0), ('part_en_jetons__gte', models.F('total_ttc'))), _connector='OR'), models.Q(('hors_chiffre_affaires', False), ('part_en_jetons', 0), _connector='OR')), name='lignearticle_part_en_jetons_entre_zero_et_le_net'),
        ),
    ]
