# Generated by Django 4.2.30 on 2026-07-02 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0223_lignearticle_commande_alter_paiement_stripe_commande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lignearticle',
            name='commande',
        ),
        migrations.RemoveField(
            model_name='paiement_stripe',
            name='commande',
        ),
    ]
