# Generated by Django 4.2.30 on 2026-07-03 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0220_lignearticle_idempotency_key_and_more'),
        ('BaseBillet', '0223_externalapikey_page'),
    ]

    operations = [
    ]
