# Generated by Django 4.2.30 on 2026-07-02 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_booking_commande_alter_booking_status'),
        ('BaseBillet', '0224_remove_lignearticle_commande_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement_stripe',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='booking.booking'),
        ),
    ]
