# Generated by Django 4.2.30 on 2026-07-06 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0221_remove_configuration_skin_configuration_module_pages_and_more'),
        ('BaseBillet', '0224_merge_20260630_0900'),
    ]

    operations = [
    ]
