# Generated by Django 4.2.30 on 2026-08-27 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0223_lignearticle_booking_paiement_stripe_booking_and_more'),
        ('BaseBillet', '0225_fuseau_horaire_choix_zoneinfo'),
    ]

    operations = [
    ]
