# Generated by Django 4.2.30 on 2026-07-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0225_paiement_stripe_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement_stripe',
            name='status',
            field=models.CharField(choices=[('N', 'Payment link not generated'), ('O', 'Sent to Stripe'), ('W', 'Waiting for payment'), ('E', 'Expired'), ('F', 'Failed'), ('P', 'Paid'), ('V', 'Paid and confirmed'), ('S', 'Paid but issues with LaBoutik sync'), ('C', 'Cancelled'), ('R', 'Refunded'), ('H', 'Partiellement remboursé')], default='N', max_length=1, verbose_name='Order status'),
        ),
    ]
