# Generated by Django 4.2.30 on 2026-07-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0225_merge_20260706_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignearticle',
            name='sale_origin',
            field=models.CharField(choices=[('LP', 'Online platform'), ('LB', 'Cash register'), ('AD', 'Administration'), ('EX', 'External'), ('QR', 'QrCode online'), ('NF', 'NFC online'), ('AP', 'API'), ('WK', 'Webhook Stripe'), ('TI', 'Connected tap')], default='LP', max_length=2, verbose_name='Payment source'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sale_origin',
            field=models.CharField(choices=[('LP', 'Online platform'), ('LB', 'Cash register'), ('AD', 'Administration'), ('EX', 'External'), ('QR', 'QrCode online'), ('NF', 'NFC online'), ('AP', 'API'), ('WK', 'Webhook Stripe'), ('TI', 'Connected tap')], default='LP', max_length=2, verbose_name='Payment source'),
        ),
    ]
