# Generated by Django 4.2.30 on 2026-07-06 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0226_alter_lignearticle_sale_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='module_kiosk',
            field=models.BooleanField(default=False, help_text='Active les bornes de paiement en libre-service (Stripe Terminal).', verbose_name='Module kiosk / borne libre-service'),
        ),
    ]
