# Generated by Django 4.2.30 on 2026-08-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0226_merge_20260827_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categorie_article',
            field=models.CharField(choices=[('N', 'Select a category'), ('B', 'Ticket booking'), ('F', 'Free booking'), ('A', 'Subscription or membership'), ('G', 'Punchclock'), ('Q', 'QrCode paiement on my account'), ('C', 'Ressource'), ('U', 'Keg (connected tap)')], default='N', max_length=3, verbose_name='Product type'),
        ),
        migrations.AlterField(
            model_name='productsold',
            name='categorie_article',
            field=models.CharField(choices=[('N', 'Select a category'), ('B', 'Ticket booking'), ('F', 'Free booking'), ('A', 'Subscription or membership'), ('G', 'Punchclock'), ('Q', 'QrCode paiement on my account'), ('C', 'Ressource'), ('U', 'Keg (connected tap)')], default='N', max_length=3, verbose_name='Product type'),
        ),
    ]
