# Generated by Django 4.2.30 on 2026-10-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0227_moteur_v2_si_un_module_v2_est_actif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='federationconfiguration',
            name='texte_introduction',
            field=models.TextField(blank=True, help_text='Texte affiché en haut de la page Autour de nous.', null=True, verbose_name="Texte d'introduction"),
        ),
    ]
