# Generated by Django 4.2.30 on 2026-07-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0227_configuration_module_kiosk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categorie_article',
            field=models.CharField(choices=[('N', 'Select a category'), ('B', 'Ticket booking'), ('F', 'Free booking'), ('A', 'Subscription or membership'), ('G', 'Punchclock'), ('Q', 'QrCode paiement on my account'), ('U', 'Keg (connected tap)')], default='N', max_length=3, verbose_name='Product type'),
        ),
        migrations.AlterField(
            model_name='productsold',
            name='categorie_article',
            field=models.CharField(choices=[('N', 'Select a category'), ('B', 'Ticket booking'), ('F', 'Free booking'), ('A', 'Subscription or membership'), ('G', 'Punchclock'), ('Q', 'QrCode paiement on my account'), ('U', 'Keg (connected tap)')], default='N', max_length=3, verbose_name='Product type'),
        ),
    ]
