# Generated by Django 4.2.30 on 2026-09-10 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Customers', '0005_verbose_name_fr'),
        ('rest_framework_api_key', '0005_auto_20220110_1102'),
        ('BaseBillet', '0227_alter_product_categorie_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brevoconfig',
            name='last_log',
            field=models.TextField(blank=True, null=True, verbose_name='Dernier journal'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='currency_code',
            field=models.CharField(default='EUR', max_length=3, verbose_name='Code devise'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Adresse e-mail'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='language',
            field=models.CharField(choices=[('fr', 'French'), ('en', 'English')], default='fr', max_length=2, verbose_name='Langue'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='postal_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BaseBillet.postaladdress', verbose_name='Adresse postale'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='site_web',
            field=models.URLField(blank=True, null=True, verbose_name='Site web'),
        ),
        migrations.AlterField(
            model_name='event',
            name='postal_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BaseBillet.postaladdress', verbose_name='Adresse postale'),
        ),
        migrations.AlterField(
            model_name='externalapikey',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
        migrations.AlterField(
            model_name='externalapikey',
            name='key',
            field=models.OneToOneField(blank=True, help_text='Confirm to generate key. It will not appear before.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_key', to='rest_framework_api_key.apikey', verbose_name='Clé'),
        ),
        migrations.AlterField(
            model_name='externalapikey',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nom de la clé'),
        ),
        migrations.AlterField(
            model_name='externalapikey',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who created this key.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur·ice'),
        ),
        migrations.AlterField(
            model_name='federatedplace',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Collective', to='Customers.client', verbose_name='Lieu'),
        ),
        migrations.AlterField(
            model_name='formbricksforms',
            name='environmentId',
            field=models.CharField(help_text='Formbricks environment ID', max_length=30, verbose_name="Identifiant d'environnement"),
        ),
        migrations.AlterField(
            model_name='formbricksforms',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formbricksform', to='BaseBillet.product', verbose_name='Produit'),
        ),
        migrations.AlterField(
            model_name='ghostconfig',
            name='ghost_last_log',
            field=models.TextField(blank=True, null=True, verbose_name='Dernier journal Ghost'),
        ),
        migrations.AlterField(
            model_name='lignearticle',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date et heure'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Numéro de carte'),
        ),
        migrations.AlterField(
            model_name='paiement_stripe',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur·ice'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Date et heure'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation', to='BaseBillet.event', verbose_name='Évènement'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user_commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Personne qui réserve'),
        ),
        migrations.AlterField(
            model_name='scanapp',
            name='archive',
            field=models.BooleanField(default=False, verbose_name='Archivée'),
        ),
        migrations.AlterField(
            model_name='scanapp',
            name='claimed',
            field=models.BooleanField(default=False, verbose_name='Appairée'),
        ),
        migrations.AlterField(
            model_name='scanapp',
            name='name',
            field=models.CharField(max_length=30, verbose_name="Nom de l'application"),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='last_response',
            field=models.TextField(blank=True, null=True, verbose_name='Dernière réponse'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='url',
            field=models.URLField(help_text="Astuce Dev' : pour tester un webhook, lancez un petit serveur HTTP qui affiche le contenu de la requete : https://gist.github.com/mdonkers/63e115cc0c79b4f6b8b3a6b797e485c7", verbose_name='URL de destination'),
        ),
    ]
