# Generated by Django 4.2.30 on 2026-07-28 16:25

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0227_configuration_module_kiosk'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageBibliotheque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name used to reference this image in import files (img column).', max_length=200, unique=True, verbose_name='Image name')),
                ('img', stdimage.models.StdImageField(force_min_size=False, upload_to='images/', variations={'med': (480, 480), 'thumbnail': (150, 90, True)}, verbose_name='Image')),
                ('tags', models.ManyToManyField(blank=True, help_text='Optional, to organise the library.', to='BaseBillet.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Library image',
                'verbose_name_plural': 'Image library',
            },
        ),
    ]
