# Generated by Django 4.2.30 on 2026-09-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0227_alter_product_categorie_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanapp',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
