# Generated by Django 4.2.30 on 2026-09-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0228_alter_brevoconfig_last_log_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignearticle',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('UK', 'Unknown'), ('NA', 'Offered'), ('CC', 'Credit card: POS terminal'), ('CA', 'Cash'), ('CH', 'Check'), ('QR', 'QrCode or NFC'), ('TR', 'Bank transfer'), ('SF', 'Online: federated Stripe'), ('SN', 'Online: Stripe CC'), ('SP', 'Online: Stripe SEPA'), ('SR', 'Recurring: Stripe'), ('LE', 'Asset local fiat'), ('LG', 'Asset local gift'), ('NM', 'Points ou temps (non monétaire)')], max_length=2, null=True, verbose_name='Payment method'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('UK', 'Unknown'), ('NA', 'Offered'), ('CC', 'Credit card: POS terminal'), ('CA', 'Cash'), ('CH', 'Check'), ('QR', 'QrCode or NFC'), ('TR', 'Bank transfer'), ('SF', 'Online: federated Stripe'), ('SN', 'Online: Stripe CC'), ('SP', 'Online: Stripe SEPA'), ('SR', 'Recurring: Stripe'), ('LE', 'Asset local fiat'), ('LG', 'Asset local gift'), ('NM', 'Points ou temps (non monétaire)')], max_length=2, null=True, verbose_name='Payment method'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('UK', 'Unknown'), ('NA', 'Offered'), ('CC', 'Credit card: POS terminal'), ('CA', 'Cash'), ('CH', 'Check'), ('QR', 'QrCode or NFC'), ('TR', 'Bank transfer'), ('SF', 'Online: federated Stripe'), ('SN', 'Online: Stripe CC'), ('SP', 'Online: Stripe SEPA'), ('SR', 'Recurring: Stripe'), ('LE', 'Asset local fiat'), ('LG', 'Asset local gift'), ('NM', 'Points ou temps (non monétaire)')], max_length=2, null=True, verbose_name='Payment method'),
        ),
    ]
