# Generated by Django 4.2.30 on 2026-07-28 19:25

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0228_imagebibliotheque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagebibliotheque',
            name='img',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to='images/', variations={'crop': (480, 270, True), 'crop_hdr': (960, 540, True), 'fhd': (1920, 1920), 'hdr': (1280, 1280), 'med': (480, 480), 'social_card': (1200, 630, True), 'thumbnail': (150, 90)}, verbose_name='Image'),
        ),
    ]
