# Generated by Django 4.2.30 on 2026-07-14 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0221_configuration_module_newsletter'),
        ('BaseBillet', '0228_alter_product_categorie_article_and_more'),
    ]

    operations = [
    ]
