# Generated by Django 4.2.30 on 2026-07-29 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0229_alter_imagebibliotheque_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagebibliotheque',
            options={'verbose_name': 'Vignette image', 'verbose_name_plural': 'Image vignette'},
        ),
    ]
