# Generated by Django 4.2.30 on 2026-09-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0229_verbose_name_fr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalapikey',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
    ]
