# Generated by Django 4.2.30 on 2026-09-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0229_paymentmethod_non_monetaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='products',
            field=models.ManyToManyField(blank=True, limit_choices_to={'categorie_article__in': ['B', 'F']}, to='BaseBillet.product', verbose_name='Products'),
        ),
        migrations.AlterField(
            model_name='price',
            name='adhesions_obligatoires',
            field=models.ManyToManyField(blank=True, help_text='Rate available to subscribers only (OR logic: having at least one of the selected subscriptions is enough). Only works for reservation-type products. The rate will be visible if the user is logged in AND has paid at least one of these membership fees.', limit_choices_to={'categorie_article': 'A'}, related_name='adhesions_obligatoires', to='BaseBillet.product', verbose_name='Subscriptions required'),
        ),
    ]
