# Generated by Django 4.2.30 on 2026-09-29 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('laboutik', '0006_icones_fontawesome_vers_material'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('QrcodeCashless', '0022_verbose_name_fr'),
        ('AuthBillet', '0025_verbose_name_fr'),
        ('BaseBillet', '0229_paymentmethod_non_monetaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reglement',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('moyen', models.CharField(choices=[('UK', 'Unknown'), ('NA', 'Offered'), ('CC', 'Credit card: POS terminal'), ('CA', 'Cash'), ('CH', 'Check'), ('QR', 'QrCode or NFC'), ('TR', 'Bank transfer'), ('SF', 'Online: federated Stripe'), ('SN', 'Online: Stripe CC'), ('SP', 'Online: Stripe SEPA'), ('SR', 'Recurring: Stripe'), ('LE', 'Asset local fiat'), ('LG', 'Asset local gift'), ('NM', 'Points ou temps (non monétaire)')], max_length=2, verbose_name='Moyen de paiement')),
                ('montant', models.IntegerField(verbose_name='Montant (centimes)')),
                ('asset', models.UUIDField(blank=True, null=True, verbose_name='Monnaie')),
                ('fedow_transaction_uuid', models.UUIDField(blank=True, null=True, verbose_name='Transaction Fedow')),
                ('reference_externe', models.CharField(blank=True, default='', max_length=255, verbose_name='Référence externe')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Règlement',
                'verbose_name_plural': 'Règlements',
                'ordering': ('datetime',),
            },
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Numéro')),
                ('nature', models.CharField(choices=[('VENTE', 'Vente'), ('AVOIR', 'Avoir'), ('VIDAGE_CARTE', 'Vidage de carte'), ('CORRECTION', 'Correction de moyen de paiement')], max_length=20, verbose_name='Nature')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('REGLEE', 'Réglée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('origine', models.CharField(choices=[('LP', 'Online platform'), ('LB', 'Cash register'), ('AD', 'Administration'), ('EX', 'External'), ('QR', 'QrCode online'), ('NF', 'NFC online'), ('AP', 'API'), ('WK', 'Webhook Stripe'), ('TI', 'Connected tap')], max_length=2, verbose_name='Origine')),
                ('unite', models.CharField(default='EUR', max_length=36, verbose_name='Unité')),
                ('total_catalogue', models.IntegerField(default=0, verbose_name='Total catalogue')),
                ('total_offert', models.IntegerField(default=0, verbose_name='Total offert')),
                ('total_ttc', models.IntegerField(default=0, verbose_name='Total net vendu (TTC)')),
                ('total_ht', models.IntegerField(default=0, verbose_name='Total HT')),
                ('total_tva', models.IntegerField(default=0, verbose_name='Total TVA')),
                ('datetime_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('datetime_encaissement', models.DateTimeField(blank=True, null=True, verbose_name="Date d'encaissement")),
                ('hmac_hash', models.CharField(blank=True, default='', max_length=64, verbose_name='Empreinte')),
                ('previous_hmac', models.CharField(blank=True, default='', max_length=64, verbose_name='Empreinte précédente')),
                ('idempotency_key', models.CharField(blank=True, max_length=255, null=True, verbose_name="Clé d'idempotence")),
            ],
            options={
                'verbose_name': 'Vente',
                'verbose_name_plural': 'Ventes',
                'ordering': ('-datetime_creation',),
            },
        ),
        migrations.AddField(
            model_name='lignearticle',
            name='cout_achat',
            field=models.IntegerField(blank=True, null=True, verbose_name="Coût d'achat (centimes)"),
        ),
        migrations.AddField(
            model_name='lignearticle',
            name='hors_chiffre_affaires',
            field=models.BooleanField(default=False, verbose_name="Hors chiffre d'affaires"),
        ),
        migrations.AddField(
            model_name='lignearticle',
            name='part_offerte',
            field=models.IntegerField(default=0, verbose_name='Part offerte (centimes)'),
        ),
        migrations.AddField(
            model_name='lignearticle',
            name='source_offert',
            field=models.CharField(blank=True, choices=[('OFFRIR', 'Offert par le lieu'), ('JETONS', 'Jetons cadeau')], default='', max_length=10, verbose_name="Source de l'offert"),
        ),
        migrations.AddField(
            model_name='lignearticle',
            name='total_catalogue',
            field=models.IntegerField(default=0, verbose_name='Total catalogue (centimes)'),
        ),
        migrations.AddField(
            model_name='lignearticle',
            name='total_ttc',
            field=models.IntegerField(default=0, verbose_name='Net vendu TTC (centimes)'),
        ),
        migrations.AddField(
            model_name='lignearticle',
            name='total_tva',
            field=models.IntegerField(default=0, verbose_name='Total TVA (centimes)'),
        ),
        migrations.AddField(
            model_name='paiement_stripe',
            name='montant_encaisse',
            field=models.IntegerField(blank=True, null=True, verbose_name='Montant encaissé (centimes)'),
        ),
        migrations.AddField(
            model_name='paiement_stripe',
            name='moyen',
            field=models.CharField(blank=True, choices=[('SN', 'Online: Stripe CC'), ('SP', 'Online: Stripe SEPA'), ('SR', 'Recurring: Stripe')], max_length=2, null=True, verbose_name='Moyen de paiement Stripe'),
        ),
        migrations.AddField(
            model_name='vente',
            name='carte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes', to='QrcodeCashless.cartecashless', verbose_name='Carte'),
        ),
        migrations.AddField(
            model_name='vente',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes_achetees', to=settings.AUTH_USER_MODEL, verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='vente',
            name='operateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes_operees', to=settings.AUTH_USER_MODEL, verbose_name='Opérateur'),
        ),
        migrations.AddField(
            model_name='vente',
            name='point_de_vente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to='laboutik.pointdevente', verbose_name='Point de vente'),
        ),
        migrations.AddField(
            model_name='vente',
            name='vente_liee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventes_derivees', to='BaseBillet.vente', verbose_name='Vente liée'),
        ),
        migrations.AddField(
            model_name='reglement',
            name='carte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reglements', to='QrcodeCashless.cartecashless', verbose_name='Carte'),
        ),
        migrations.AddField(
            model_name='reglement',
            name='paiement_stripe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reglements', to='BaseBillet.paiement_stripe', verbose_name='Paiement Stripe'),
        ),
        migrations.AddField(
            model_name='reglement',
            name='vente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reglements', to='BaseBillet.vente', verbose_name='Vente'),
        ),
        migrations.AddField(
            model_name='reglement',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reglements', to='AuthBillet.wallet', verbose_name='Portefeuille'),
        ),
        migrations.AddField(
            model_name='commande',
            name='vente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='BaseBillet.vente', verbose_name='Vente'),
        ),
        migrations.AddField(
            model_name='lignearticle',
            name='vente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='BaseBillet.vente', verbose_name='Vente'),
        ),
        migrations.AddField(
            model_name='paiement_stripe',
            name='vente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paiements_stripe', to='BaseBillet.vente', verbose_name="Vente d'origine"),
        ),
        migrations.AddConstraint(
            model_name='vente',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('idempotency_key',), name='unique_vente_idempotency_key'),
        ),
        migrations.AddConstraint(
            model_name='reglement',
            constraint=models.CheckConstraint(check=models.Q(('montant', 0), _negated=True), name='reglement_montant_non_nul'),
        ),
        # Les deux contraintes de LigneArticle viennent EN DERNIER : la seconde lit la
        # colonne `vente_id`, créée par l'AddField `lignearticle.vente` plus haut.
        # Les lignes existantes ont total_catalogue = part_offerte = total_ttc = 0 (vrai
        # pour la 1re) et vente vide (2e non appliquée).
        # / Both LigneArticle constraints come LAST: the second reads `vente_id`.
        migrations.AddConstraint(
            model_name='lignearticle',
            constraint=models.CheckConstraint(check=models.Q(('total_ttc', django.db.models.expressions.CombinedExpression(models.F('total_catalogue'), '-', models.F('part_offerte')))), name='lignearticle_ttc_egal_catalogue_moins_offert'),
        ),
        migrations.AddConstraint(
            model_name='lignearticle',
            constraint=models.CheckConstraint(check=models.Q(('vente__isnull', True), ('total_ttc', django.db.models.expressions.CombinedExpression(models.F('total_ht'), '+', models.F('total_tva'))), _connector='OR'), name='lignearticle_ht_plus_tva_egal_ttc_si_vente'),
        ),
    ]
