# Generated by Django 4.2.30 on 2026-09-29 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0230_vente_reglement_montants_entiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='consigne_remboursee',
            field=models.ForeignKey(blank=True, help_text='Le produit consigne (par exemple le gobelet) que ce retour rembourse. La caisse rend son prix, avec son taux de TVA.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retours_de_consigne', to='BaseBillet.product', verbose_name='Rembourse la consigne'),
        ),
    ]
