# Generated by Django 4.2.30 on 2026-09-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0230_alter_event_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
    ]
