# Generated by Django 4.2.30 on 2026-07-29 14:56

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0230_alter_imagebibliotheque_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='default_event_img',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, help_text='Used whenever an event has no image of its own.', null=True, upload_to='images/', variations={'crop_hdr': (960, 540, True), 'hdr': (720, 720), 'med': (480, 480), 'thumbnail': (150, 90)}, verbose_name='Default event image'),
        ),
    ]
