# Generated by Django 4.2.30 on 2026-09-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0231_price_archived'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('archive', False)), fields=('categorie_article', 'name'), name='unique_product_non_archive_par_categorie_et_nom'),
        ),
    ]
