# Generated by Django 4.2.30 on 2026-10-03 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0232_alter_product_prix_achat'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='heure_de_fermeture',
            field=models.TimeField(default=datetime.time(2, 0), help_text="Heure locale de fermeture du lieu. Si personne n'a fait la clôture de la journée, elle est faite automatiquement deux heures après.", verbose_name='Heure de fermeture'),
        ),
        migrations.AddIndex(
            model_name='vente',
            index=models.Index(fields=['statut', 'datetime_encaissement'], name='vente_statut_encaissement'),
        ),
    ]
