# Generated by Django 4.2.30 on 2026-10-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0232_product_nom_unique_si_non_archive'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_product_non_archive_par_categorie_et_nom',
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('archive', False)), fields=('categorie_article', 'name'), name='unique_product_non_archive_par_categorie_et_nom', violation_error_message='Un produit avec ce nom existe déjà. Choisissez un autre nom, ou archivez le produit existant.'),
        ),
    ]
