# Generated by Django 4.2.30 on 2026-10-04 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0233_heure_de_fermeture_et_index_vente'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='raison',
            field=models.TextField(blank=True, default='', help_text="Raison écrite par le caissier lors d'une correction de moyen de paiement.", verbose_name='Raison'),
        ),
    ]
