# Generated by Django 4.2.30 on 2026-10-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0233_remove_product_unique_product_non_archive_par_categorie_et_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='validate_button_text',
            field=models.CharField(blank=True, help_text="'Subscribe' If empty. Only useful for membership or subscription products.", max_length=30, null=True, verbose_name='Validate button text for membership'),
        ),
    ]
