# Generated by Django 4.2.30 on 2026-10-05 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0234_vente_raison'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignearticle',
            name='part_en_jetons',
            field=models.IntegerField(default=0, help_text="Centimes du net vendu payés en jetons cadeau. Cette part est vendue hors TVA ; la TVA de l'article porte sur le reste.", verbose_name='Part payée en jetons (centimes)'),
        ),
        migrations.AddConstraint(
            model_name='lignearticle',
            constraint=models.CheckConstraint(check=models.Q(models.Q(models.Q(('total_ttc__gte', 0), ('part_en_jetons__gte', 0), ('part_en_jetons__lte', models.F('total_ttc'))), models.Q(('total_ttc__lt', 0), ('part_en_jetons__lte', 0), ('part_en_jetons__gte', models.F('total_ttc'))), _connector='OR'), models.Q(('hors_chiffre_affaires', False), ('part_en_jetons', 0), _connector='OR')), name='lignearticle_part_en_jetons_entre_zero_et_le_net'),
        ),
    ]
