# Generated by Django 3.2 on 2022-06-02 06:13

from django.db import migrations
import stdimage.models
import stdimage.validators


class Migration(migrations.Migration):

    dependencies = [
        ('QrcodeCashless', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='img',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='images/', validators=[stdimage.validators.MaxSizeValidator(1920, 1920)], variations={'med': (480, 480), 'thumbnail': (150, 90)}, verbose_name='Recto de la carte'),
        ),
    ]
