# Generated by Django 2.2 on 2021-09-25 08:08

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('QrcodeCashless', '0002_auto_20210925_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', stdimage.models.StdImageField(blank=True, null=True, upload_to='images/', verbose_name='Recto de la carte')),
            ],
        ),
        migrations.AddField(
            model_name='cartecashless',
            name='detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='QrcodeCashless.Detail'),
        ),
    ]
