# Generated by Django 2.2 on 2021-09-25 08:24

from django.db import migrations
import stdimage.models
import stdimage.validators


class Migration(migrations.Migration):

    dependencies = [
        ('QrcodeCashless', '0003_auto_20210925_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='img',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='images/', validators=[stdimage.validators.MaxSizeValidator(1920, 1920)], verbose_name='Recto de la carte'),
        ),
    ]
