# Generated by Django 3.2 on 2022-12-05 10:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('QrcodeCashless', '0003_auto_20221101_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
