# Generated by Django 2.2 on 2021-09-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QrcodeCashless', '0004_auto_20210925_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='base_url',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
