# Generated by Django 2.2 on 2021-09-25 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QrcodeCashless', '0005_detail_base_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartecashless',
            name='origine',
        ),
    ]
