# Generated by Django 2.2 on 2021-09-25 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0003_auto_20210623_1351'),
        ('QrcodeCashless', '0006_remove_cartecashless_origine'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='origine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Customers.Client'),
        ),
    ]
