# Generated by Django 2.2 on 2021-09-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QrcodeCashless', '0007_detail_origine'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='img_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
