# Generated by Django 2.2 on 2021-09-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QrcodeCashless', '0008_detail_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='generation',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
