FROM node:lts-alpine

RUN npm install -g @vue/cli

# EXPOSE 8080
# CMD [ "http-server", "dist" ]

# PROD :
# build stage

# FROM node:lts-alpine as build-stage
# WORKDIR /app
# COPY package*.json ./
# RUN npm install
# COPY . .
# RUN npm run build

# production stage
#
# FROM nginx:stable-alpine as production-stage
# COPY --from=build-stage /app/dist /usr/share/nginx/html
# EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]