# Generated by Django 4.2.10 on 2024-03-20 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fedow_connect', '0002_remove_fedowconfig_rsa_key_delete_rsakey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fedowconfig',
            name='fedow_place_wallet_public_pem',
        ),
    ]
