# Generated by Django 4.2.10 on 2024-03-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fedow_connect', '0003_remove_fedowconfig_fedow_place_wallet_public_pem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fedowconfig',
            name='fedow_place_admin_apikey',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
    ]
