# Generated by Django 2.2 on 2021-06-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(max_length=50)),
                ('short_description', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
