# Generated by Django 2.2 on 2021-10-29 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement_stripe',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='BaseBillet.Reservation'),
        ),
    ]
