# Generated by Django 3.2 on 2022-02-14 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='optiongenerale',
            options={'ordering': ('poids',), 'verbose_name': 'Option Ticket', 'verbose_name_plural': 'Options Tickets'},
        ),
        migrations.AlterField(
            model_name='optiongenerale',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
