# Generated by Django 3.2 on 2022-02-07 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0001_initial'),
        ('BaseBillet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='short_description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='artist_on_events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Customers.client')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseBillet.event')),
            ],
        ),
    ]
