# Generated by Django 3.2 on 2022-02-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement_stripe',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
