# Generated by Django 3.2 on 2022-01-31 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='city',
            field=models.CharField(default='Saint Jo', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuration',
            name='postal_code',
            field=models.IntegerField(default=97480),
            preserve_default=False,
        ),
    ]
