# Generated by Django 2.2 on 2021-06-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
