# Generated by Django 2.2 on 2021-09-27 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lignearticle',
            name='reste',
        ),
    ]
