# Generated by Django 3.2 on 2022-02-14 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0002_auto_20220214_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='options',
            field=models.ManyToManyField(blank=True, to='BaseBillet.OptionGenerale'),
        ),
    ]
