# Generated by Django 2.2 on 2021-10-31 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0002_paiement_stripe_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement_stripe',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='BaseBillet.Reservation'),
        ),
    ]
