# Generated by Django 3.2 on 2022-02-09 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0002_paiement_stripe_payment_intent_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paiement_stripe',
            old_name='id_stripe',
            new_name='checkout_session_id_stripe',
        ),
    ]
