# Generated by Django 2.2 on 2021-09-27 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0002_remove_lignearticle_reste'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TarifsAdhesion',
        ),
    ]
