# Generated by Django 2.2 on 2021-10-24 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0002_auto_20211024_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='tarifs',
        ),
    ]
