# Generated by Django 3.2 on 2022-02-14 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0003_event_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='options',
        ),
        migrations.AddField(
            model_name='event',
            name='options_checkbox',
            field=models.ManyToManyField(blank=True, related_name='options_checkbox', to='BaseBillet.OptionGenerale'),
        ),
        migrations.AddField(
            model_name='event',
            name='options_radio',
            field=models.ManyToManyField(blank=True, related_name='options_radio', to='BaseBillet.OptionGenerale'),
        ),
    ]
