# Generated by Django 2.2 on 2021-06-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0003_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('datetime',), 'verbose_name': 'Evenement', 'verbose_name_plural': 'Evenements'},
        ),
        migrations.AddField(
            model_name='configuration',
            name='adresse',
            field=models.CharField(default='route de la joie', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuration',
            name='email',
            field=models.EmailField(default='demo@demo.demo', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuration',
            name='phone',
            field=models.CharField(default='-262 6 121212', max_length=20),
            preserve_default=False,
        ),
    ]
