# Generated by Django 2.2 on 2021-10-31 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0003_auto_20211031_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='mail_send',
            field=models.BooleanField(default=False),
        ),
    ]
