# Generated by Django 2.2 on 2021-09-30 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QrcodeCashless', '0002_cartecashless_user'),
        ('BaseBillet', '0003_delete_tarifsadhesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignearticle',
            name='carte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='QrcodeCashless.CarteCashless'),
        ),
    ]
