# Generated by Django 3.2 on 2022-02-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0003_rename_id_stripe_paiement_stripe_checkout_session_id_stripe'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement_stripe',
            name='source_traitement',
            field=models.CharField(choices=[('N', 'Pas de traitement en cours'), ('W', 'Depuis webhook post stripe'), ('G', 'Depuis Get')], default='N', max_length=1, verbose_name='Source de la commande'),
        ),
    ]
