# Generated by Django 2.2 on 2021-06-29 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0004_auto_20210629_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignearticle',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BaseBillet.Reservation'),
        ),
        migrations.AlterField(
            model_name='lignearticle',
            name='uuid',
            field=models.UUIDField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='uuid',
            field=models.UUIDField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
