# Generated by Django 2.2 on 2021-06-21 17:19

from django.db import migrations
import stdimage.models
import stdimage.validators


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0004_auto_20210621_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='img',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='images/', validators=[stdimage.validators.MaxSizeValidator(1920, 1920)]),
        ),
        migrations.AddField(
            model_name='event',
            name='img',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='images/', validators=[stdimage.validators.MaxSizeValidator(1920, 1920)]),
        ),
    ]
