# Generated by Django 3.2 on 2022-02-14 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0004_auto_20220214_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='options_checkbox',
            field=models.ManyToManyField(blank=True, related_name='options_checkbox', to='BaseBillet.OptionGenerale', verbose_name='Option choix multiple'),
        ),
        migrations.AlterField(
            model_name='event',
            name='options_radio',
            field=models.ManyToManyField(blank=True, related_name='options_radio', to='BaseBillet.OptionGenerale', verbose_name='Option choix unique'),
        ),
    ]
