# Generated by Django 2.2 on 2021-10-24 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0004_remove_lignearticle_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignearticle',
            name='price',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BaseBillet.Price'),
            preserve_default=False,
        ),
    ]
