# Generated by Django 2.2 on 2021-06-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0005_auto_20210621_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='mollie_api_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='reservation_max',
            field=models.PositiveSmallIntegerField(default=6),
        ),
    ]
