# Generated by Django 3.2 on 2022-02-14 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0005_auto_20220214_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='options_checkbox',
            field=models.ManyToManyField(blank=True, related_name='options_checkbox', to='BaseBillet.OptionGenerale', verbose_name='Options choix multiple'),
        ),
    ]
