# Generated by Django 2.2 on 2021-11-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0005_auto_20211101_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignearticle',
            name='status',
            field=models.CharField(choices=[('C', 'Annulée'), ('O', 'Non envoyé en paiement'), ('N', 'Non payée'), ('P', 'Payée'), ('V', 'Validée par serveur cashless')], default='O', max_length=3, verbose_name='Status de ligne article'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('C', 'Crée'), ('N', 'Non actif'), ('K', 'Non scanné'), ('S', 'scanné')], default='C', max_length=1, verbose_name='Status du scan'),
        ),
    ]
