# Generated by Django 2.2 on 2021-06-29 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0006_auto_20210629_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='options',
            field=models.ManyToManyField(to='BaseBillet.OptionGenerale'),
        ),
        migrations.AlterField(
            model_name='lignearticle',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BaseBillet.Reservation'),
        ),
    ]
