# Generated by Django 3.2 on 2022-02-20 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Customers', '0001_initial'),
        ('BaseBillet', '0006_alter_event_options_checkbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('first_contribution', models.DateField(blank=True, null=True)),
                ('last_contribution', models.DateField(blank=True, null=True)),
                ('contribution_value', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Nom')),
                ('prenom', models.CharField(blank=True, max_length=50, null=True, verbose_name='Prénom')),
                ('pseudo', models.CharField(blank=True, max_length=50, null=True)),
                ('demarchage', models.BooleanField(default=True, verbose_name="J'accepte de recevoir la newsletter")),
                ('code_postal', models.IntegerField(blank=True, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('tel', models.CharField(blank=True, max_length=15, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_inscription', models.DateField(blank=True, null=True)),
                ('date_derniere_cotisation', models.DateField(blank=True, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('last_action', models.DateTimeField(auto_now=True, verbose_name='Présence')),
                ('cotisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='BaseBillet.pricesold')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Customers.client')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='membership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
