# Generated by Django 2.2 on 2021-11-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0006_auto_20211101_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='mail_error',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lignearticle',
            name='status',
            field=models.CharField(choices=[('C', 'Annulée'), ('O', 'Non envoyé en paiement'), ('U', 'Non payée'), ('P', 'Payée'), ('V', 'Validée par serveur cashless')], default='O', max_length=3, verbose_name='Status de ligne article'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('C', 'Annulée'), ('R', 'Crée'), ('U', 'Non payée'), ('P', 'Payée'), ('V', 'Validée')], default='R', max_length=3, verbose_name='Status de la réservation'),
        ),
    ]
