# Generated by Django 2.2 on 2021-06-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0006_auto_20210622_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuration',
            old_name='reservation_max',
            new_name='reservation_par_user_max',
        ),
        migrations.AddField(
            model_name='configuration',
            name='jauge_max',
            field=models.PositiveSmallIntegerField(default=50),
            preserve_default=False,
        ),
    ]
