# Generated by Django 2.2 on 2021-10-25 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0007_auto_20211025_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='name_required_for_ticket',
            field=models.BooleanField(default=False),
        ),
    ]
