# Generated by Django 2.2 on 2021-06-29 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0007_auto_20210629_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='billets',
            field=models.ManyToManyField(to='BaseBillet.Billet'),
        ),
        migrations.AlterField(
            model_name='event',
            name='articles',
            field=models.ManyToManyField(to='BaseBillet.Article'),
        ),
        migrations.AlterField(
            model_name='lignearticle',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BaseBillet.Reservation'),
        ),
    ]
