# Generated by Django 3.2 on 2022-02-20 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0007_membership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='tenant',
        ),
    ]
