# Generated by Django 2.2 on 2021-11-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0007_auto_20211109_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('C', 'Annulée'), ('R', 'Crée'), ('U', 'Non payée'), ('P', 'Payée'), ('PE', 'Payée'), ('V', 'Validée')], default='R', max_length=3, verbose_name='Status de la réservation'),
        ),
    ]
