# Generated by Django 2.2 on 2021-06-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0007_auto_20210622_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reservations',
            field=models.PositiveSmallIntegerField(default=6),
        ),
    ]
