# Generated by Django 3.2 on 2022-02-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0008_remove_membership_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='name',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='prenom',
        ),
        migrations.AddField(
            model_name='membership',
            name='first_name',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='membership',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='demarchage',
            field=models.BooleanField(default=True, verbose_name="J'accepte de recevoir la newsletter de l'association"),
        ),
    ]
