# Generated by Django 2.2 on 2021-10-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0008_configuration_name_required_for_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
