# Generated by Django 2.2 on 2021-11-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0009_auto_20211109_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='long_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
