# Generated by Django 3.2 on 2022-02-20 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0009_auto_20220220_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='date_naissance',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='tel',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='code_postal',
            new_name='postal_code',
        ),
    ]
