# Generated by Django 2.2 on 2021-06-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0009_auto_20210622_1139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='optiongenerale',
            options={'ordering': ('poids',), 'verbose_name': 'Options Generales', 'verbose_name_plural': 'Options Generales'},
        ),
        migrations.AddField(
            model_name='optiongenerale',
            name='poids',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Poids'),
        ),
    ]
