# Generated by Django 2.2 on 2021-06-29 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0010_auto_20210629_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='reservation_par_user_max',
        ),
        migrations.AddField(
            model_name='article',
            name='reservation_par_user_max',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='lignearticle',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BaseBillet.Reservation'),
        ),
    ]
