# Generated by Django 2.2 on 2021-11-10 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0010_configuration_long_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='button_adhesion',
            field=models.BooleanField(default=False),
        ),
    ]
