# Generated by Django 3.2 on 2022-02-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0010_auto_20220220_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='demarchage',
            new_name='newsletter',
        ),
        migrations.AlterField(
            model_name='membership',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
