# Generated by Django 2.2 on 2021-06-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0011_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='jauge_max',
            field=models.PositiveSmallIntegerField(default=50),
        ),
    ]
