# Generated by Django 2.2 on 2021-10-26 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PaiementStripe', '0001_initial'),
        ('BaseBillet', '0011_auto_20211026_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='paiement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservation', to='PaiementStripe.Paiement_stripe'),
        ),
    ]
