# Generated by Django 3.2 on 2022-02-23 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0012_alter_membership_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='cotisation',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='date_ajout',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='date_derniere_cotisation',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='date_inscription',
        ),
    ]
