# Generated by Django 2.2 on 2021-11-10 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0012_configuration_map'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuration',
            old_name='map',
            new_name='map_img',
        ),
    ]
