# Generated by Django 2.2 on 2021-06-29 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0013_auto_20210629_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignearticle',
            name='articles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BaseBillet.Article', verbose_name='lignes_article'),
        ),
        migrations.AlterField(
            model_name='lignearticle',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BaseBillet.Reservation'),
        ),
    ]
