# Generated by Django 2.2 on 2021-10-27 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0013_lignearticle_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lignearticle',
            options={'ordering': ('-datetime',)},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ('-datetime',)},
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='scan_status',
            new_name='status',
        ),
    ]
