# Generated by Django 3.2 on 2022-04-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0013_auto_20220223_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='fuseau_horaire',
            field=models.CharField(choices=[('Indian/Reunion', 'Indian/Reunion'), ('Europe/Paris', 'Europe/Paris')], default='Indian/Reunion', max_length=50),
        ),
        migrations.AlterField(
            model_name='membership',
            name='first_name',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categorie_article',
            field=models.CharField(choices=[('B', 'Billet'), ('P', "Pack d'objets"), ('R', 'Recharge cashless'), ('T', 'Vetement'), ('M', 'Merchandasing'), ('A', 'Adhésion'), ('D', 'Don'), ('F', 'Reservation gratuite')], default='B', max_length=3, verbose_name="Type d'article"),
        ),
    ]
