# Generated by Django 3.2 on 2022-04-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0014_auto_20220406_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='to_mail',
            field=models.BooleanField(default=True),
        ),
    ]
