# Generated by Django 2.2 on 2021-10-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0015_auto_20211027_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='options',
            field=models.ManyToManyField(blank=True, to='BaseBillet.OptionGenerale'),
        ),
    ]
