# Generated by Django 2.2 on 2021-11-10 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0015_auto_20211110_0930'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('name', 'datetime')},
        ),
    ]
