# Generated by Django 2.2 on 2021-11-11 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0017_event_event_facebook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_facebook',
            new_name='event_facebook_url',
        ),
    ]
