# Generated by Django 2.2 on 2021-11-11 06:17

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0018_auto_20211111_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='logo',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='images/', verbose_name='Background'),
        ),
    ]
