# Generated by Django 2.2 on 2021-11-11 08:19

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0019_configuration_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='logo',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='images/', verbose_name='Logo'),
        ),
    ]
