# Generated by Django 2.2 on 2021-12-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0020_auto_20211111_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='template_billetterie',
            field=models.CharField(blank=True, choices=[('html5up-massively', 'html5up-massively'), ('arnaud_mvc', 'arnaud_mvc'), ('original_arnaud', 'original_arnaud')], max_length=250, null=True, verbose_name='Template'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='template_meta',
            field=models.CharField(blank=True, choices=[('html5up-massively', 'html5up-massively'), ('arnaud_mvc', 'arnaud_mvc'), ('original_arnaud', 'original_arnaud')], max_length=250, null=True, verbose_name='Template'),
        ),
    ]
