# Generated by Django 3.2 on 2022-06-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0021_paiement_stripe_invoice_stripe'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement_stripe',
            name='subscription',
            field=models.CharField(blank=True, max_length=28, null=True),
        ),
    ]
