# Generated by Django 2.2 on 2021-12-21 13:23

from django.db import migrations, models
import stdimage.models
import stdimage.validators


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0021_auto_20211206_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='template_billetterie',
            field=models.CharField(blank=True, choices=[('html5up-massively', 'html5up-massively'), ('arnaud_mvc', 'arnaud_mvc'), ('original_arnaud', 'original_arnaud')], max_length=250, null=True, verbose_name='Template Billetterie'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='template_meta',
            field=models.CharField(blank=True, choices=[('html5up-story', 'html5up-story'), ('blk-mit', 'blk-mit')], max_length=250, null=True, verbose_name='Template Meta'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='images/', validators=[stdimage.validators.MaxSizeValidator(1920, 1920)], verbose_name='Image du produit'),
        ),
    ]
