# Generated by Django 2.2 on 2021-09-23 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PaiementStripe', '0002_auto_20210923_1338'),
        ('BaseBillet', '0022_auto_20210629_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignearticle',
            name='paiement_stripe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='PaiementStripe.Paiement_stripe'),
        ),
        migrations.AlterField(
            model_name='lignearticle',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BaseBillet.Reservation'),
        ),
    ]
