# Generated by Django 3.2 on 2022-01-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0023_auto_20220114_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement_stripe',
            name='metadata_stripe',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
