# Generated by Django 3.2 on 2022-01-14 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0024_alter_paiement_stripe_metadata_stripe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='reservations',
        ),
    ]
