# Generated by Django 2.2 on 2021-09-23 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0024_auto_20210923_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='key_cashless',
            field=models.CharField(blank=True, max_length=41, null=True, verbose_name="Clé d'API du serveur cashless"),
        ),
        migrations.AddField(
            model_name='configuration',
            name='server_cashless',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Adresse du serveur Cashless'),
        ),
        migrations.AlterField(
            model_name='lignearticle',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BaseBillet.Reservation'),
        ),
    ]
