# Generated by Django 3.2 on 2022-01-17 07:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0026_alter_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSold',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('id_product_stripe', models.CharField(blank=True, max_length=30, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BaseBillet.event')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BaseBillet.product')),
            ],
        ),
        migrations.CreateModel(
            name='PricesSold',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('id_price_stripe', models.CharField(blank=True, max_length=30, null=True)),
                ('qty', models.SmallIntegerField()),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BaseBillet.price')),
                ('productsold', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BaseBillet.productsold')),
            ],
        ),
    ]
