# Generated by Django 3.2 on 2022-01-17 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0027_pricessold_productsold'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignearticle',
            name='pricesold',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BaseBillet.pricessold'),
        ),
    ]
