# Generated by Django 3.2 on 2022-01-17 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0028_lignearticle_pricesold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignearticle',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BaseBillet.price'),
        ),
    ]
