# Generated by Django 3.2 on 2022-01-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0029_alter_lignearticle_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricessold',
            name='qty',
            field=models.SmallIntegerField(default=0),
        ),
    ]
