# Generated by Django 3.2 on 2022-01-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0030_alter_pricessold_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricessold',
            name='prix',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
