# Generated by Django 3.2 on 2022-01-22 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0031_pricessold_prix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='id_price_stripe',
        ),
        migrations.RemoveField(
            model_name='product',
            name='id_product_stripe',
        ),
    ]
