# Generated by Django 3.2 on 2022-01-22 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0032_auto_20220122_1259'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PricesSold',
            new_name='PriceSold',
        ),
    ]
