# Generated by Django 3.2 on 2022-01-22 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0035_rename_qty_pricesold_qty_solded'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='pricesold',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BaseBillet.pricesold'),
        ),
    ]
