# Generated by Django 3.2 on 2022-01-22 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0036_ticket_pricesold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsold',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='BaseBillet.event'),
        ),
    ]
