# Generated by Django 3.2 on 2022-10-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0038_apikey_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikey',
            name='tenant',
        ),
        migrations.AddField(
            model_name='apikey',
            name='artist',
            field=models.BooleanField(default=False, verbose_name='Creation de nouvelles instances artiste'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='place',
            field=models.BooleanField(default=False, verbose_name='Creation de nouvelles instances lieux'),
        ),
    ]
