# Generated by Django 3.2 on 2022-10-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0043_webhook_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='last_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
