# Generated by Django 3.2 on 2022-10-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0045_auto_20221021_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recharge_cashless',
            field=models.BooleanField(default=False),
        ),
    ]
