# Generated by Django 2.2 on 2021-09-26 11:31

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models
import stdimage.validators


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0047_auto_20210926_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='activer_billetterie',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='carte_restaurant',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='images/', validators=[stdimage.validators.MaxSizeValidator(1920, 1920)], verbose_name='Carte du restaurant'),
        ),
        migrations.AlterField(
            model_name='lignearticle',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BaseBillet.Reservation'),
        ),
    ]
