# Generated by Django 2.2 on 2021-09-27 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0048_auto_20210926_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifsAdhesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('tarif', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='configuration',
            name='adhesion_obligatoire',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lignearticle',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BaseBillet.Reservation'),
        ),
    ]
