# Generated by Django 2.2 on 2021-09-27 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0049_auto_20210927_1047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarifsadhesion',
            options={'ordering': ('-tarif',)},
        ),
        migrations.AddField(
            model_name='configuration',
            name='cadeau_adhesion',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='lignearticle',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BaseBillet.Reservation'),
        ),
    ]
