# Generated by Django 3.2 on 2022-12-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0053_alter_externalapikey_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='recurring_payment',
            field=models.BooleanField(default=False, help_text='Paiement récurrent avec Stripe, ne peux être utilisé avec un autre article dans le panier', verbose_name='Paiement récurrent'),
        ),
    ]
