# Generated by Django 2.2 on 2021-09-27 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0054_auto_20210927_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='id_stripe',
            new_name='id_price_stripe',
        ),
        migrations.AlterField(
            model_name='article',
            name='categorie_article',
            field=models.CharField(choices=[('B', 'Billet'), ('P', "Pack d'objets"), ('R', 'Recharge cashless'), ('T', 'Vetement'), ('M', 'Merchandasing'), ('A', 'Adhésion')], default='B', max_length=3, verbose_name="Type d'article"),
        ),
        migrations.AlterField(
            model_name='lignearticle',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BaseBillet.Reservation'),
        ),
    ]
