# Generated by Django 3.2 on 2023-04-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0060_event_minimum_cashless_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='federated_cashless',
            field=models.BooleanField(default=False),
        ),
    ]
