# Generated by Django 3.2 on 2023-04-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0064_auto_20230427_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='option_generale_checkbox',
            field=models.ManyToManyField(blank=True, related_name='membership_checkbox', to='BaseBillet.OptionGenerale'),
        ),
        migrations.AddField(
            model_name='membership',
            name='option_generale_radio',
            field=models.ManyToManyField(blank=True, related_name='membership_radio', to='BaseBillet.OptionGenerale'),
        ),
    ]
