# Generated by Django 3.2 on 2023-04-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0067_auto_20230427_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='ghost_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='ghost_last_log',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='ghost_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
