# Generated by Django 3.2 on 2023-05-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0069_alter_optiongenerale_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='short_description',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Description courte'),
        ),
    ]
