# Generated by Django 3.2 on 2023-05-24 13:06

from django.db import migrations
import stdimage.models
import stdimage.validators


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0074_auto_20230523_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='img',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='images/', validators=[stdimage.validators.MinSizeValidator(720, 135)], variations={'crop': (480, 270, True), 'crop_hdr': (960, 540, True), 'fhd': (1920, 1920), 'hdr': (720, 720), 'med': (480, 480), 'thumbnail': (150, 90)}, verbose_name='Background'),
        ),
        migrations.AlterField(
            model_name='event',
            name='img',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='images/', validators=[stdimage.validators.MaxSizeValidator(1920, 1920)], variations={'crop': (480, 270, True), 'crop_hdr': (960, 540, True), 'fhd': (1920, 1920), 'hdr': (1280, 1280), 'med': (480, 480), 'thumbnail': (150, 90)}),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='images/', validators=[stdimage.validators.MaxSizeValidator(1920, 1920)], variations={'crop': (480, 270, True), 'crop_hdr': (960, 540, True), 'fhd': (1920, 1920), 'hdr': (720, 720), 'med': (480, 480), 'thumbnail': (150, 90)}, verbose_name='Image du produit'),
        ),
    ]
