# Generated by Django 3.2 on 2023-05-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0075_auto_20230524_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='max_per_user',
            field=models.PositiveSmallIntegerField(default=10, help_text='ex : Un même email peut réserver plusieurs billets', verbose_name='Nombre de reservation maximum par utilisateur'),
        ),
        migrations.AlterField(
            model_name='price',
            name='recurring_payment',
            field=models.BooleanField(default=False, help_text='Paiement récurrent avec Stripe, Ne peux être utilisé avec un autre article dans le même panier', verbose_name='Paiement récurrent'),
        ),
    ]
