# Generated by Django 3.2 on 2023-09-08 10:10

from django.db import migrations

def create_days(apps, schema_editor):
    Weekday = apps.get_model('BaseBillet', 'Weekday')
    Weekday.objects.bulk_create([
        Weekday(day=0),
        Weekday(day=1),
        Weekday(day=2),
        Weekday(day=3),
        Weekday(day=4),
        Weekday(day=5),
        Weekday(day=6),
    ])

def reverse_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0085_auto_20230908_1409'),
    ]

    operations = [
        migrations.RunPython(create_days, reverse_func),
    ]
