# Generated by Django 4.2.10 on 2024-03-29 06:37

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models
import stdimage.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0087_alter_event_recurrent'),
    ]

    operations = [
        migrations.CreateModel(
            name='FedowTransaction',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='activate_mailjet',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='email_confirm_template',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='template_billetterie',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='template_meta',
        ),
        migrations.AddField(
            model_name='configuration',
            name='siren',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de SIREN'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='tva_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de TVA'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='vat_taxe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='lignearticle',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='membership',
            name='stripe_paiement',
            field=models.ManyToManyField(blank=True, related_name='membership', to='BaseBillet.paiement_stripe'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='img',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='images/', validators=[stdimage.validators.MinSizeValidator(720, 135)], variations={'crop': (480, 270, True), 'crop_hdr': (960, 540, True), 'fhd': (1920, 1920), 'hdr': (720, 720), 'med': (480, 480), 'thumbnail': (150, 90)}, verbose_name='Background image'),
        ),
        migrations.AlterField(
            model_name='lignearticle',
            name='paiement_stripe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lignearticles', to='BaseBillet.paiement_stripe'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='contribution_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='fedow_transactions',
            field=models.ManyToManyField(blank=True, related_name='membership', to='BaseBillet.fedowtransaction'),
        ),
        migrations.AddField(
            model_name='paiement_stripe',
            name='fedow_transactions',
            field=models.ManyToManyField(blank=True, related_name='paiement_stripe', to='BaseBillet.fedowtransaction'),
        ),
    ]
