# Generated by Django 4.2.24 on 2025-09-24 15:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AuthBillet', '0022_wallet_origin'),
        ('Customers', '0004_alter_client_categorie_alter_client_on_trial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetFedowPublic',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('currency_code', models.CharField(max_length=3)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('fedow_place_origin_uuid', models.UUIDField()),
                ('category', models.CharField(choices=[('TLF', 'Fiduciaire'), ('TNF', 'Cadeau'), ('FED', 'Fiduciaire fédérée'), ('TIM', 'Monnaie temps'), ('FID', 'Points de fidélité'), ('BDG', 'Badgeuse/Pointeuse'), ('SUB', 'Adhésion ou abonnement')], max_length=3)),
                ('federated_with', models.ManyToManyField(blank=True, related_name='federated_assets_fedow_public', to='Customers.client')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets_fedow_public', to='Customers.client')),
                ('pending_invitations', models.ManyToManyField(blank=True, related_name='pending_invitations_fedow_public', to='Customers.client')),
                ('wallet_origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets_fedow_public', to='AuthBillet.wallet')),
            ],
        ),
        migrations.AddConstraint(
            model_name='assetfedowpublic',
            constraint=models.UniqueConstraint(condition=models.Q(('category', 'FED')), fields=('category',), name='unique_primary_asset'),
        ),
    ]
