# Generated by Django 4.2.24 on 2025-09-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0004_alter_client_categorie_alter_client_on_trial'),
        ('fedow_public', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetfedowpublic',
            name='federated_with',
            field=models.ManyToManyField(blank=True, help_text='Lieux fédérés', related_name='federated_assets_fedow_public', to='Customers.client', verbose_name='Lieux fédérés'),
        ),
        migrations.AlterField(
            model_name='assetfedowpublic',
            name='pending_invitations',
            field=models.ManyToManyField(blank=True, help_text="Invitez une organisation à partager cet actif, il recevra un mail de confirmation. Une fois validé, l'actif disparaitra de cette liste pour aller dans celle ci dessous", related_name='pending_invitations_fedow_public', to='Customers.client', verbose_name='Partager cet actif'),
        ),
    ]
