# Generated by Django 4.2.24 on 2025-10-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fedow_public', '0002_alter_assetfedowpublic_federated_with_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetfedowpublic',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
