# Generated by Django 4.2.30 on 2026-09-09 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0005_verbose_name_fr'),
        ('AuthBillet', '0025_verbose_name_fr'),
        ('fedow_public', '0003_assetfedowpublic_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetfedowpublic',
            name='category',
            field=models.CharField(choices=[('TLF', 'Fiduciaire'), ('TNF', 'Cadeau'), ('FED', 'Fiduciaire fédérée'), ('TIM', 'Monnaie temps'), ('FID', 'Points de fidélité'), ('BDG', 'Badgeuse/Pointeuse'), ('SUB', 'Adhésion ou abonnement')], max_length=3, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='assetfedowpublic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='assetfedowpublic',
            name='currency_code',
            field=models.CharField(max_length=3, verbose_name='Code devise'),
        ),
        migrations.AlterField(
            model_name='assetfedowpublic',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name="Nom de l'asset"),
        ),
        migrations.AlterField(
            model_name='assetfedowpublic',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets_fedow_public', to='Customers.client', verbose_name='Origine'),
        ),
        migrations.AlterField(
            model_name='assetfedowpublic',
            name='wallet_origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets_fedow_public', to='AuthBillet.wallet', verbose_name="Portefeuille d'origine"),
        ),
    ]
