# Generated by Django 2.2 on 2021-09-23 08:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement_stripe',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('id_stripe', models.CharField(blank=True, max_length=20, null=True)),
                ('order_date', models.DateTimeField(auto_now=True, verbose_name='Date')),
                ('status', models.CharField(choices=[('O', 'Envoyée a Stripe'), ('W', 'En attente de paiement'), ('P', 'Payée'), ('V', 'Payée et validée'), ('C', 'Annulée')], default='O', max_length=1, verbose_name='Statut de la commande')),
                ('email_billet', models.CharField(blank=True, max_length=30, verbose_name='Email de récéption des billets')),
            ],
        ),
    ]
