# Generated by Django 2.2 on 2021-09-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaiementStripe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement_stripe',
            name='status',
            field=models.CharField(choices=[('N', 'Lien de paiement non crée'), ('O', 'Envoyée a Stripe'), ('W', 'En attente de paiement'), ('P', 'Payée'), ('V', 'Payée et validée'), ('C', 'Annulée')], default='N', max_length=1, verbose_name='Statut de la commande'),
        ),
    ]
