# Generated by Django 2.2 on 2021-10-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaiementStripe', '0002_auto_20211026_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement_stripe',
            name='source',
            field=models.CharField(choices=[('Q', 'Depuis scan QR-Code'), ('B', 'Depuis billetterie')], default='B', max_length=1, verbose_name='Statut de la commande'),
        ),
    ]
