# Generated by Django 2.2 on 2021-09-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaiementStripe', '0003_auto_20210924_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement_stripe',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
