# Generated by Django 2.2 on 2021-09-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaiementStripe', '0004_paiement_stripe_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration_stripe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_api_key', models.CharField(blank=True, max_length=110, null=True)),
                ('api_key', models.CharField(blank=True, max_length=110, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='paiement_stripe',
            name='email_billet',
        ),
    ]
