# Generated by Django 2.2 on 2021-09-26 07:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PaiementStripe', '0007_auto_20210925_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement_stripe',
            name='metadata_stripe',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
