services:
  cordova:
    build: CordovaDockerFile
    container_name: cordova
    network_mode: host
    ports:
      - 5037:5037
    privileged: true
    volumes:
      - ../cordova_local_plugins:/cordova_local_plugins
      - ../mobile-app:/mobile-app
      - ../mobile-app/res:/mobile-app/res
      - /dev/bus/usb:/dev/bus/usb
      - ./.bashrc:/root/.bashrc
    tty: true
    command: "/bin/bash"
