# Generated by Django 4.2.30 on 2026-07-05 10:10

from django.db import migrations, models
import django.db.models.deletion
import pages.models
import stdimage.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloc',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('type_bloc', models.CharField(choices=[('HERO', "Hero (banniere d'ouverture)"), ('PARAGRAPHE', 'Paragraphe riche'), ('IMAGE_TEXTE', 'Image + texte'), ('CTA', "Appel a l'action (CTA)"), ('TEMOIGNAGE', 'Temoignage'), ('VIDEO_TEXTE', 'Video + texte'), ('CARTE', 'Carte (regroupee en grille si plusieurs a la suite)'), ('IMAGE', 'Image seule'), ('CARTE_LEAFLET', 'Carte Leaflet (points GPS)'), ('INFOS', "Infos structurees (badges, horaires, transports) - a cote d'une carte"), ('FAQ', 'Question / reponse (regroupee en 2 colonnes si plusieurs a la suite)'), ('EVENEMENTS', "Prochains evenements (liste automatique depuis l'agenda)"), ('GALERIE', "Galerie d'images (plusieurs photos en grille)"), ('EMBED', 'Contenu integre (video YouTube/Vimeo/PeerTube, carte OSM)')], help_text="Choisit le gabarit du bloc. Les champs s'adaptent automatiquement.", max_length=20, verbose_name='Type de bloc')),
                ('position', models.PositiveIntegerField(default=0, help_text='Ordre du bloc dans la page (croissant).', verbose_name='Position')),
                ('titre', models.CharField(blank=True, help_text='Titre principal du bloc.', max_length=200, verbose_name='Titre')),
                ('sous_titre', models.CharField(blank=True, help_text='Texte secondaire sous le titre (Hero et CTA).', max_length=300, verbose_name='Sous-titre')),
                ('surtitre', models.CharField(blank=True, help_text="Petit titre en haut d'une carte (ex. « JOUR 01 »).", max_length=120, verbose_name='Sur-titre (carte)')),
                ('badge', models.CharField(blank=True, help_text='Petite pastille sur la carte (ex. « gratuit »).', max_length=60, verbose_name='Badge (carte)')),
                ('texte', models.TextField(blank=True, help_text='Contenu riche (paragraphe, description, citation).', verbose_name='Texte')),
                ('image', stdimage.models.StdImageField(blank=True, force_min_size=False, help_text='Image du bloc (fond du Hero ou illustration laterale).', upload_to='images/pages/', validators=[pages.models.valider_taille_image], variations={'crop': (480, 270, True), 'crop_hdr': (960, 540, True), 'fhd': (1920, 1920), 'hdr': (1280, 1280), 'med': (480, 480), 'social_card': (1200, 630, True), 'thumbnail': (150, 90)}, verbose_name='Image')),
                ('image_secondaire', stdimage.models.StdImageField(blank=True, force_min_size=False, help_text="Image secondaire (ex. badge date, logo a cote d'une carte).", upload_to='images/pages/', validators=[pages.models.valider_taille_image], variations={'crop': (480, 270, True), 'crop_hdr': (960, 540, True), 'fhd': (1920, 1920), 'hdr': (1280, 1280), 'med': (480, 480), 'social_card': (1200, 630, True), 'thumbnail': (150, 90)}, verbose_name='Seconde image')),
                ('video', models.FileField(blank=True, help_text='Fichier video (mp4/webm) pour le bloc Video + texte.', upload_to='videos/pages/', verbose_name='Video')),
                ('points_gps', models.JSONField(blank=True, default=list, help_text='Liste de marqueurs : [{"lat": 43.55, "lng": 1.48, "label": "La Cité"}].', verbose_name='Points GPS (carte Leaflet)')),
                ('contenu', models.JSONField(blank=True, default=list, help_text='Items typés (texte seulement) : [{"type": "transport", "titre": "BUS", "lignes": ["..."]}].', verbose_name='Contenu structure (colonne gauche)')),
                ('nombre_max', models.PositiveSmallIntegerField(default=6, help_text="Nombre maximum d'évènements à venir affichés (bloc Prochains évènements).", verbose_name="Nombre d'évènements")),
                ('repliable', models.BooleanField(default=False, help_text="Si coché, les réponses de la FAQ sont repliées et s'ouvrent au clic.", verbose_name='FAQ repliable (accordéon)')),
                ('embed_url', models.URLField(blank=True, help_text='Lien YouTube, Vimeo ou PeerTube (instance autorisée). Les autres hôtes sont ignorés (sécurité).', max_length=500, verbose_name='URL à intégrer (embed)')),
                ('image_position', models.CharField(blank=True, choices=[('GAUCHE', 'Image a gauche'), ('DROITE', 'Image a droite')], default='GAUCHE', help_text="Cote ou afficher l'image (bloc Image + texte).", max_length=10, verbose_name="Position de l'image")),
                ('bouton_label', models.CharField(blank=True, help_text='Texte du bouton principal.', max_length=80, verbose_name='Libelle du bouton')),
                ('bouton_url', models.CharField(blank=True, help_text='Lien interne (/event/) ou externe (https://...).', max_length=500, verbose_name='Lien du bouton')),
                ('bouton2_label', models.CharField(blank=True, help_text='Texte du bouton secondaire (optionnel).', max_length=80, verbose_name='Libelle du second bouton')),
                ('bouton2_url', models.CharField(blank=True, help_text='Lien du bouton secondaire (optionnel).', max_length=500, verbose_name='Lien du second bouton')),
                ('auteur_nom', models.CharField(blank=True, help_text='Personne qui temoigne.', max_length=120, verbose_name="Nom de l'auteur")),
                ('auteur_role', models.CharField(blank=True, help_text='Fonction ou statut (ex: adherente, benevole).', max_length=160, verbose_name="Role de l'auteur")),
                ('auteur_photo', stdimage.models.StdImageField(blank=True, force_min_size=False, help_text='Portrait de la personne qui temoigne (optionnel).', upload_to='images/pages/auteurs/', validators=[pages.models.valider_taille_image], variations={'med': (480, 480), 'thumbnail': (150, 150, True)}, verbose_name="Photo de l'auteur")),
            ],
            options={
                'verbose_name': 'Bloc',
                'verbose_name_plural': 'Blocs',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ConfigurationSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin', models.CharField(choices=[('reunion', 'Réunion (thème par défaut)'), ('faire_festival', 'Faire Festival (thème brutaliste)')], default='reunion', help_text="Sélectionnez le thème visuel à utiliser pour l'affichage du site web.", max_length=50, verbose_name='Thème graphique du site')),
            ],
            options={
                'verbose_name': 'Configuration du site',
                'verbose_name_plural': 'Configuration du site',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('titre', models.CharField(help_text='Titre de la page, affiche dans la navigation.', max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(help_text='Adresse de la page : /<slug>/. Genere depuis le titre, modifiable.', max_length=200, unique=True, validators=[pages.models.valider_slug_non_reserve], verbose_name='Slug (URL)')),
                ('position', models.PositiveIntegerField(default=0, help_text="Ordre d'apparition dans la navigation (croissant).", verbose_name='Position')),
                ('publie', models.BooleanField(default=False, help_text='Si decoche, la page reste un brouillon (invisible du public).', verbose_name='Publiee')),
                ('est_accueil', models.BooleanField(default=False, help_text='Si coche, cette page est servie sur la racine du site (/). Une seule a la fois.', verbose_name="Page d'accueil")),
                ('meta_description', models.CharField(blank=True, help_text='Resume court affiche par les moteurs de recherche.', max_length=255, verbose_name='Meta description (SEO)')),
                ('meta_title', models.CharField(blank=True, help_text='Titre pour les moteurs/onglets. Si vide : reprend le titre de la page.', max_length=70, verbose_name='Titre SEO')),
                ('image', stdimage.models.StdImageField(blank=True, force_min_size=False, help_text="Aperu lors d'un partage sur les reseaux (1200x630 conseille). Si vide : image du site par defaut.", upload_to='images/pages/seo/', validators=[pages.models.valider_taille_image], variations={'med': (480, 480), 'social_card': (1200, 630, True)}, verbose_name='Image de partage (reseaux sociaux)')),
                ('noindex', models.BooleanField(default=False, help_text="Si coche : la page n'est pas indexee et reste hors du sitemap.", verbose_name='Masquer des moteurs (noindex)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifie le')),
                ('parent', models.ForeignKey(blank=True, help_text='Si renseignée, cette page apparaît dans un menu déroulant sous la page parente. Un seul niveau de profondeur.', limit_choices_to={'est_accueil': False, 'parent__isnull': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enfants', to='pages.page', verbose_name='Page parente (sous-menu)')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['position', 'titre'],
            },
        ),
        migrations.CreateModel(
            name='ImageGalerie',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image', stdimage.models.StdImageField(blank=True, force_min_size=False, help_text='Une photo de la galerie.', upload_to='images/pages/galerie/', validators=[pages.models.valider_taille_image], variations={'med': (480, 480), 'social_card': (1200, 630, True)}, verbose_name='Image')),
                ('legende', models.CharField(blank=True, help_text="Texte alternatif et légende de l'image (optionnel).", max_length=200, verbose_name='Légende')),
                ('position', models.PositiveIntegerField(default=0, help_text="Ordre de l'image dans la galerie (croissant).", verbose_name='Position')),
                ('bloc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_galerie', to='pages.bloc', verbose_name='Bloc galerie')),
            ],
            options={
                'verbose_name': 'Image de galerie',
                'verbose_name_plural': 'Images de galerie',
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='bloc',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocs', to='pages.page', verbose_name='Page'),
        ),
    ]
