# Generated by Django 4.2.30 on 2026-06-28 13:06

from django.db import migrations, models
import django.db.models.deletion
import pages.models
import stdimage.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('titre', models.CharField(help_text='Titre de la page, affiche dans la navigation.', max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(help_text='Adresse de la page : /<slug>/. Genere depuis le titre, modifiable.', max_length=200, unique=True, validators=[pages.models.valider_slug_non_reserve], verbose_name='Slug (URL)')),
                ('position', models.PositiveIntegerField(default=0, help_text="Ordre d'apparition dans la navigation (croissant).", verbose_name='Position')),
                ('publie', models.BooleanField(default=False, help_text='Si decoche, la page reste un brouillon (invisible du public).', verbose_name='Publiee')),
                ('meta_description', models.CharField(blank=True, help_text='Resume court affiche par les moteurs de recherche.', max_length=255, verbose_name='Meta description (SEO)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifie le')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['position', 'titre'],
            },
        ),
        migrations.CreateModel(
            name='Bloc',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('type_bloc', models.CharField(choices=[('HERO', "Hero (banniere d'ouverture)"), ('PARAGRAPHE', 'Paragraphe riche'), ('IMAGE_TEXTE', 'Image + texte'), ('CTA', "Appel a l'action (CTA)"), ('TEMOIGNAGE', 'Temoignage')], help_text="Choisit le gabarit du bloc. Les champs s'adaptent automatiquement.", max_length=20, verbose_name='Type de bloc')),
                ('position', models.PositiveIntegerField(default=0, help_text='Ordre du bloc dans la page (croissant).', verbose_name='Position')),
                ('titre', models.CharField(blank=True, help_text='Titre principal du bloc.', max_length=200, verbose_name='Titre')),
                ('sous_titre', models.CharField(blank=True, help_text='Texte secondaire sous le titre (Hero et CTA).', max_length=300, verbose_name='Sous-titre')),
                ('texte', models.TextField(blank=True, help_text='Contenu riche (paragraphe, description, citation).', verbose_name='Texte')),
                ('image', stdimage.models.StdImageField(blank=True, force_min_size=False, help_text='Image du bloc (fond du Hero ou illustration laterale).', null=True, upload_to='images/pages/', variations={'crop': (480, 270, True), 'crop_hdr': (960, 540, True), 'fhd': (1920, 1920), 'hdr': (1280, 1280), 'med': (480, 480), 'social_card': (1200, 630, True), 'thumbnail': (150, 90)}, verbose_name='Image')),
                ('image_position', models.CharField(blank=True, choices=[('GAUCHE', 'Image a gauche'), ('DROITE', 'Image a droite')], default='GAUCHE', help_text="Cote ou afficher l'image (bloc Image + texte).", max_length=10, verbose_name="Position de l'image")),
                ('bouton_label', models.CharField(blank=True, help_text='Texte du bouton principal.', max_length=80, verbose_name='Libelle du bouton')),
                ('bouton_url', models.CharField(blank=True, help_text='Lien interne (/event/) ou externe (https://...).', max_length=500, verbose_name='Lien du bouton')),
                ('bouton2_label', models.CharField(blank=True, help_text='Texte du bouton secondaire (optionnel).', max_length=80, verbose_name='Libelle du second bouton')),
                ('bouton2_url', models.CharField(blank=True, help_text='Lien du bouton secondaire (optionnel).', max_length=500, verbose_name='Lien du second bouton')),
                ('auteur_nom', models.CharField(blank=True, help_text='Personne qui temoigne.', max_length=120, verbose_name="Nom de l'auteur")),
                ('auteur_role', models.CharField(blank=True, help_text='Fonction ou statut (ex: adherente, benevole).', max_length=160, verbose_name="Role de l'auteur")),
                ('auteur_photo', stdimage.models.StdImageField(blank=True, force_min_size=False, help_text='Portrait de la personne qui temoigne (optionnel).', null=True, upload_to='images/pages/auteurs/', variations={'med': (480, 480), 'thumbnail': (150, 150, True)}, verbose_name="Photo de l'auteur")),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocs', to='pages.page', verbose_name='Page')),
            ],
            options={
                'verbose_name': 'Bloc',
                'verbose_name_plural': 'Blocs',
                'ordering': ['position'],
            },
        ),
    ]
