# Generated by Django 4.2.30 on 2026-06-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='est_accueil',
            field=models.BooleanField(default=False, help_text='Si coche, cette page est servie sur la racine du site (/). Une seule a la fois.', verbose_name="Page d'accueil"),
        ),
    ]
