# Generated by Django 4.2.30 on 2026-07-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationsite',
            name='skin',
            field=models.CharField(choices=[('reunion', 'Réunion (thème par défaut)'), ('faire_festival', 'Faire Festival (thème brutaliste)'), ('bar', 'Bar')], default='reunion', help_text="Sélectionnez le thème visuel à utiliser pour l'affichage du site web.", max_length=50, verbose_name='Thème graphique du site'),
        ),
    ]
