# Generated by Django 4.2.30 on 2026-07-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_iframe_partenaires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloc',
            name='embed_url',
            field=models.URLField(blank=True, help_text="Lien du contenu a integrer. EMBED : video YouTube/Vimeo/PeerTube. IFRAME : formulaire/widget (hote autorise par le ROOT). NEWSLETTER : adresse de l'instance Ghost (ex. https://ghost.exemple.coop/).", max_length=500, verbose_name='URL à intégrer (embed)'),
        ),
        migrations.AlterField(
            model_name='bloc',
            name='type_bloc',
            field=models.CharField(choices=[('HERO', "Hero (banniere d'ouverture)"), ('PARAGRAPHE', 'Paragraphe riche'), ('IMAGE_TEXTE', 'Image + texte'), ('CTA', "Appel a l'action (CTA)"), ('TEMOIGNAGE', 'Temoignage'), ('VIDEO_TEXTE', 'Video + texte'), ('CARTE', 'Carte (regroupee en grille si plusieurs a la suite)'), ('IMAGE', 'Image seule'), ('CARTE_LEAFLET', 'Carte Leaflet (points GPS)'), ('INFOS', "Infos structurees (badges, horaires, transports) - a cote d'une carte"), ('FAQ', 'Question / reponse (regroupee en 2 colonnes si plusieurs a la suite)'), ('EVENEMENTS', "Prochains evenements (liste automatique depuis l'agenda)"), ('GALERIE', "Galerie d'images (plusieurs photos en grille)"), ('EMBED', 'Contenu integre (video YouTube/Vimeo/PeerTube, carte OSM)'), ('MARKDOWN', 'Markdown (texte long : article, page de blog)'), ('LISTE_SOUS_PAGES', 'Liste des sous-pages (cartes - index de blog)'), ('IFRAME', 'Contenu integre libre (formulaire, widget — domaines autorises par le ROOT)'), ('PARTENAIRES', 'Partenaires (bande de logos cliquables)'), ('NEWSLETTER', 'Inscription newsletter (formulaire Ghost)')], help_text="Choisit le gabarit du bloc. Les champs s'adaptent automatiquement.", max_length=20, verbose_name='Type de bloc'),
        ),
    ]
