# Generated by Django 4.2.30 on 2026-09-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_configurationsite_skin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloc',
            name='affichage',
            field=models.CharField(blank=True, choices=[('BANNIERE', "Bannière d'ouverture"), ('TEXTE_IMAGE_GAUCHE', 'Texte avec image à gauche'), ('TEXTE_IMAGE_DROITE', 'Texte avec image à droite'), ('TEXTE_VIDEO', 'Texte avec vidéo (fichier déposé)'), ('MEDIA_ET_CARTES', 'Média + texte + sous-cartes (section composée)'), ('CARTE', 'Carte (se range en grille avec les cartes voisines)'), ('APPEL_ACTION', "Appel à l'action (boutons mis en avant)"), ('CITATION', 'Citation / témoignage signé'), ('EQUIPE', 'Équipe (personnes et rôles)'), ('FRISE', 'Frise chronologique (dates et étapes)'), ('RESSOURCES', 'Ressources (documents et liens)'), ('PLEINE_LARGEUR', 'Photo pleine largeur'), ('VIGNETTE_TITRE', 'Vignette centrée (image-titre dessinée)'), ('GRILLE', 'Galerie en grille'), ('BANDE_LOGOS', 'Bande de logos cliquables'), ('VIDEO', 'Vidéo en ligne (YouTube / Vimeo / PeerTube)'), ('WIDGET', 'Formulaire ou widget (hôte autorisé par le ROOT)'), ('NEWSLETTER', 'Inscription newsletter (Ghost)')], help_text="Comment ce bloc s'affiche. Les choix dépendent du type de bloc.", max_length=20, verbose_name='Affichage'),
        ),
    ]
