# Generated by Django 4.2.30 on 2026-06-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_page_est_accueil'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin', models.CharField(choices=[('reunion', 'Réunion (thème par défaut)'), ('faire_festival', 'Faire Festival (thème brutaliste)')], default='reunion', help_text="Sélectionnez le thème visuel à utiliser pour l'affichage du site web.", max_length=50, verbose_name='Thème graphique du site')),
            ],
            options={
                'verbose_name': 'Configuration du site',
                'verbose_name_plural': 'Configuration du site',
            },
        ),
    ]
