# Generated by Django 4.2.30 on 2026-06-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_configurationsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloc',
            name='badge',
            field=models.CharField(blank=True, help_text='Petite pastille sur la carte (ex. « gratuit »).', max_length=60, verbose_name='Badge (carte)'),
        ),
        migrations.AddField(
            model_name='bloc',
            name='image_secondaire_statique',
            field=models.CharField(blank=True, help_text="Chemin static d'une seconde image (ex. badge date du Hero).", max_length=300, verbose_name='2e image (chemin static)'),
        ),
        migrations.AddField(
            model_name='bloc',
            name='image_statique',
            field=models.CharField(blank=True, help_text="Chemin d'une image static du skin (ex. faire_festival/image/logopage.webp).", max_length=300, verbose_name='Image (chemin static)'),
        ),
        migrations.AddField(
            model_name='bloc',
            name='surtitre',
            field=models.CharField(blank=True, help_text="Petit titre en haut d'une carte (ex. « JOUR 01 »).", max_length=120, verbose_name='Sur-titre (carte)'),
        ),
        migrations.AddField(
            model_name='bloc',
            name='video_statique',
            field=models.CharField(blank=True, help_text="Chemin static d'une video (ex. faire_festival/image/motion-table.mp4).", max_length=300, verbose_name='Video (chemin static)'),
        ),
        migrations.AlterField(
            model_name='bloc',
            name='type_bloc',
            field=models.CharField(choices=[('HERO', "Hero (banniere d'ouverture)"), ('PARAGRAPHE', 'Paragraphe riche'), ('IMAGE_TEXTE', 'Image + texte'), ('CTA', "Appel a l'action (CTA)"), ('TEMOIGNAGE', 'Temoignage'), ('VIDEO_TEXTE', 'Video + texte'), ('CARTE', 'Carte (regroupee en grille si plusieurs a la suite)'), ('IMAGE', 'Image seule')], help_text="Choisit le gabarit du bloc. Les champs s'adaptent automatiquement.", max_length=20, verbose_name='Type de bloc'),
        ),
    ]
