# Generated by Django 4.2.30 on 2026-07-16 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_bloc_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationsite',
            name='skin',
            field=models.CharField(choices=[('reunion', 'Réunion (thème par défaut)'), ('faire_festival', 'Faire Festival (thème brutaliste)'), ('la_filature', 'La Filature (tiers-lieu)'), ('miete', 'La MIETE (tiers-lieu)')], default='reunion', help_text="Sélectionnez le thème visuel à utiliser pour l'affichage du site web.", max_length=50, verbose_name='Thème graphique du site'),
        ),
    ]
