# Generated by Django 4.2.30 on 2026-06-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_bloc_badge_bloc_image_secondaire_statique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloc',
            name='points_gps',
            field=models.JSONField(blank=True, default=list, help_text='Liste de marqueurs : [{"lat": 43.55, "lng": 1.48, "label": "La Cité"}].', verbose_name='Points GPS (carte Leaflet)'),
        ),
        migrations.AlterField(
            model_name='bloc',
            name='type_bloc',
            field=models.CharField(choices=[('HERO', "Hero (banniere d'ouverture)"), ('PARAGRAPHE', 'Paragraphe riche'), ('IMAGE_TEXTE', 'Image + texte'), ('CTA', "Appel a l'action (CTA)"), ('TEMOIGNAGE', 'Temoignage'), ('VIDEO_TEXTE', 'Video + texte'), ('CARTE', 'Carte (regroupee en grille si plusieurs a la suite)'), ('IMAGE', 'Image seule'), ('CARTE_LEAFLET', 'Texte + carte Leaflet (points GPS)')], help_text="Choisit le gabarit du bloc. Les champs s'adaptent automatiquement.", max_length=20, verbose_name='Type de bloc'),
        ),
    ]
