# Generated by Django 4.2.30 on 2026-06-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_bloc_points_gps_alter_bloc_type_bloc'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloc',
            name='contenu',
            field=models.JSONField(blank=True, default=list, help_text='Items typés (texte seulement) : [{"type": "transport", "titre": "BUS", "lignes": ["..."]}].', verbose_name='Contenu structure (colonne gauche)'),
        ),
        migrations.AlterField(
            model_name='bloc',
            name='type_bloc',
            field=models.CharField(choices=[('HERO', "Hero (banniere d'ouverture)"), ('PARAGRAPHE', 'Paragraphe riche'), ('IMAGE_TEXTE', 'Image + texte'), ('CTA', "Appel a l'action (CTA)"), ('TEMOIGNAGE', 'Temoignage'), ('VIDEO_TEXTE', 'Video + texte'), ('CARTE', 'Carte (regroupee en grille si plusieurs a la suite)'), ('IMAGE', 'Image seule'), ('CARTE_LEAFLET', 'Texte + carte Leaflet (points GPS)'), ('FAQ', 'Question / reponse (regroupee en 2 colonnes si plusieurs a la suite)')], help_text="Choisit le gabarit du bloc. Les champs s'adaptent automatiquement.", max_length=20, verbose_name='Type de bloc'),
        ),
    ]
