# Generated by Django 4.2.30 on 2026-07-18 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_bloc_affichage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='est_blog',
        ),
    ]
