# Generated by Django 4.2.30 on 2026-07-18 19:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import pages.models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_remove_page_est_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloc',
            name='embed_url',
            field=models.URLField(blank=True, help_text="Lien du contenu a integrer, selon l'affichage choisi. Video : YouTube / Vimeo / PeerTube. Formulaire ou widget : hote autorise par le ROOT. Newsletter : adresse de l'instance Ghost (ex. https://ghost.exemple.coop/).", max_length=500, verbose_name='URL à intégrer (embed)'),
        ),
        migrations.AlterField(
            model_name='bloc',
            name='hauteur_px',
            field=models.PositiveIntegerField(default=600, help_text='Hauteur du cadre integre, en pixels (affichage Formulaire ou widget).', validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(4000)], verbose_name="Hauteur de l'iframe (pixels)"),
        ),
        migrations.AlterField(
            model_name='bloc',
            name='image',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, help_text="Image du bloc : illustration laterale, visuel de carte, logo d'un lieu.", upload_to='images/pages/', validators=[pages.models.valider_taille_image], variations={'crop': (480, 270, True), 'crop_hdr': (960, 540, True), 'fhd': (1920, 1920), 'hdr': (1280, 1280), 'med': (480, 480), 'social_card': (1200, 630, True), 'thumbnail': (150, 90)}, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='bloc',
            name='sous_titre',
            field=models.CharField(blank=True, help_text='Texte secondaire sous le titre. Sert aussi de sur-titre sur une carte.', max_length=300, verbose_name='Sous-titre'),
        ),
        migrations.AlterField(
            model_name='bloc',
            name='video',
            field=models.FileField(blank=True, help_text='Fichier video (mp4/webm) depose. Pour une video en ligne, utiliser un bloc Contenu integre.', upload_to='videos/pages/', verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='page',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Si renseignée, cette page apparaît dans un menu déroulant sous la page parente. Un seul niveau de profondeur.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enfants', to='pages.page', verbose_name='Page parente (sous-menu)'),
        ),
    ]
