# Generated by Django 4.2.30 on 2026-06-28 18:32

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_bloc_type_bloc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloc',
            name='image_secondaire_statique',
        ),
        migrations.RemoveField(
            model_name='bloc',
            name='image_statique',
        ),
        migrations.RemoveField(
            model_name='bloc',
            name='video_statique',
        ),
        migrations.AddField(
            model_name='bloc',
            name='image_secondaire',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, help_text="Image secondaire (ex. badge date, logo a cote d'une carte).", null=True, upload_to='images/pages/', variations={'crop': (480, 270, True), 'crop_hdr': (960, 540, True), 'fhd': (1920, 1920), 'hdr': (1280, 1280), 'med': (480, 480), 'social_card': (1200, 630, True), 'thumbnail': (150, 90)}, verbose_name='Seconde image'),
        ),
        migrations.AddField(
            model_name='bloc',
            name='video',
            field=models.FileField(blank=True, help_text='Fichier video (mp4/webm) pour le bloc Video + texte.', null=True, upload_to='videos/pages/', verbose_name='Video'),
        ),
    ]
