# Generated by Django 4.2.30 on 2026-07-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_bloc_embed_url_alter_bloc_hauteur_px_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='affichage_nav',
            field=models.CharField(choices=[('NAVBAR', 'Barre de navigation'), ('SIDEBAR', 'Menu latéral (documentation)'), ('AUCUN', 'Hors navigation')], default='NAVBAR', help_text="Barre de navigation : la page y figure, avec ses sous-pages en menu déroulant. Menu latéral : la page ouvre un menu de documentation à gauche, où tout son arbre se déplie. Hors navigation : la page reste accessible par son adresse et par un bloc Liste, mais n'apparaît dans aucun menu.", max_length=20, verbose_name='Place dans la navigation'),
        ),
    ]
