# Generated by Django 4.2.30 on 2026-06-29 21:06

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_bloc_fichiers_non_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='image',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, help_text="Aperu lors d'un partage sur les reseaux (1200x630 conseille). Si vide : image du site par defaut.", upload_to='images/pages/seo/', variations={'med': (480, 480), 'social_card': (1200, 630, True)}, verbose_name='Image de partage (reseaux sociaux)'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Titre pour les moteurs/onglets. Si vide : reprend le titre de la page.', max_length=70, verbose_name='Titre SEO'),
        ),
        migrations.AddField(
            model_name='page',
            name='noindex',
            field=models.BooleanField(default=False, help_text="Si coche : la page n'est pas indexee et reste hors du sitemap.", verbose_name='Masquer des moteurs (noindex)'),
        ),
    ]
