# Generated by Django 4.2.30 on 2026-07-19 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_page_affichage_nav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='parent',
            field=models.ForeignKey(blank=True, help_text="Si renseignée, cette page est rangée sous la page parente : elle hérite de son fil d'Ariane et peut être listée automatiquement. Six niveaux de profondeur au maximum.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enfants', to='pages.page', verbose_name='Page parente (sous-menu)'),
        ),
    ]
