# Generated by Django 4.2.30 on 2026-07-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_page_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='afficher_sommaire',
            field=models.BooleanField(default=True, help_text="Si decoche : la page n'affiche pas sa table des matieres. Le sommaire reste masque quand la page a moins de deux titres.", verbose_name='Afficher le sommaire'),
        ),
    ]
