# Generated by Django 4.2.30 on 2026-06-30 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_page_image_page_meta_title_page_noindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloc',
            name='nombre_max',
            field=models.PositiveSmallIntegerField(default=6, help_text="Nombre maximum d'évènements à venir affichés (bloc Prochains évènements).", verbose_name="Nombre d'évènements"),
        ),
        migrations.AlterField(
            model_name='bloc',
            name='type_bloc',
            field=models.CharField(choices=[('HERO', "Hero (banniere d'ouverture)"), ('PARAGRAPHE', 'Paragraphe riche'), ('IMAGE_TEXTE', 'Image + texte'), ('CTA', "Appel a l'action (CTA)"), ('TEMOIGNAGE', 'Temoignage'), ('VIDEO_TEXTE', 'Video + texte'), ('CARTE', 'Carte (regroupee en grille si plusieurs a la suite)'), ('IMAGE', 'Image seule'), ('CARTE_LEAFLET', 'Carte Leaflet (points GPS)'), ('INFOS', "Infos structurees (badges, horaires, transports) - a cote d'une carte"), ('FAQ', 'Question / reponse (regroupee en 2 colonnes si plusieurs a la suite)'), ('EVENEMENTS', "Prochains evenements (liste automatique depuis l'agenda)")], help_text="Choisit le gabarit du bloc. Les champs s'adaptent automatiquement.", max_length=20, verbose_name='Type de bloc'),
        ),
    ]
