# Generated by Django 4.2.30 on 2026-06-30 04:21

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_bloc_nombre_max_alter_bloc_type_bloc'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloc',
            name='embed_url',
            field=models.URLField(blank=True, help_text='Lien YouTube, Vimeo, PeerTube ou OpenStreetMap. Les autres hôtes sont ignorés.', max_length=500, verbose_name='URL à intégrer (embed)'),
        ),
        migrations.AddField(
            model_name='bloc',
            name='repliable',
            field=models.BooleanField(default=False, help_text="Si coché, les réponses de la FAQ sont repliées et s'ouvrent au clic.", verbose_name='FAQ repliable (accordéon)'),
        ),
        migrations.AlterField(
            model_name='bloc',
            name='type_bloc',
            field=models.CharField(choices=[('HERO', "Hero (banniere d'ouverture)"), ('PARAGRAPHE', 'Paragraphe riche'), ('IMAGE_TEXTE', 'Image + texte'), ('CTA', "Appel a l'action (CTA)"), ('TEMOIGNAGE', 'Temoignage'), ('VIDEO_TEXTE', 'Video + texte'), ('CARTE', 'Carte (regroupee en grille si plusieurs a la suite)'), ('IMAGE', 'Image seule'), ('CARTE_LEAFLET', 'Carte Leaflet (points GPS)'), ('INFOS', "Infos structurees (badges, horaires, transports) - a cote d'une carte"), ('FAQ', 'Question / reponse (regroupee en 2 colonnes si plusieurs a la suite)'), ('EVENEMENTS', "Prochains evenements (liste automatique depuis l'agenda)"), ('GALERIE', "Galerie d'images (plusieurs photos en grille)"), ('EMBED', 'Contenu integre (video YouTube/Vimeo/PeerTube, carte OSM)')], help_text="Choisit le gabarit du bloc. Les champs s'adaptent automatiquement.", max_length=20, verbose_name='Type de bloc'),
        ),
        migrations.CreateModel(
            name='ImageGalerie',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image', stdimage.models.StdImageField(blank=True, force_min_size=False, help_text='Une photo de la galerie.', upload_to='images/pages/galerie/', variations={'med': (480, 480), 'social_card': (1200, 630, True)}, verbose_name='Image')),
                ('legende', models.CharField(blank=True, help_text="Texte alternatif et légende de l'image (optionnel).", max_length=200, verbose_name='Légende')),
                ('position', models.PositiveIntegerField(default=0, help_text="Ordre de l'image dans la galerie (croissant).", verbose_name='Position')),
                ('bloc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_galerie', to='pages.bloc', verbose_name='Bloc galerie')),
            ],
            options={
                'verbose_name': 'Image de galerie',
                'verbose_name_plural': 'Images de galerie',
                'ordering': ['position'],
            },
        ),
    ]
