# Generated by Django 4.2.30 on 2026-07-20 19:55

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_page_afficher_sommaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloc',
            name='video',
            field=models.FileField(blank=True, help_text='Fichier video (mp4/webm) depose. Pour une video en ligne, utiliser un bloc Contenu integre.', upload_to='videos/pages/', validators=[pages.models.valider_extension_video], verbose_name='Video'),
        ),
    ]
