# Generated by Django 4.2.30 on 2026-06-30 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_bloc_embed_url_bloc_repliable_alter_bloc_type_bloc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Si renseignée, cette page apparaît dans un menu déroulant sous la page parente. Un seul niveau de profondeur.', limit_choices_to={'est_accueil': False, 'parent__isnull': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enfants', to='pages.page', verbose_name='Page parente (sous-menu)'),
        ),
        migrations.AlterField(
            model_name='bloc',
            name='embed_url',
            field=models.URLField(blank=True, help_text='Lien YouTube, Vimeo ou PeerTube (instance autorisée). Les autres hôtes sont ignorés (sécurité).', max_length=500, verbose_name='URL à intégrer (embed)'),
        ),
    ]
