"""
Django settings for TiBillet project.

Generated by 'django-admin startproject' using Django 3.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
from datetime import timedelta
from pathlib import Path

from django.db import connection
from django.utils.translation import gettext_lazy as _
from django.templatetags.static import static
from django.urls import reverse_lazy
from faker.utils.text import slugify

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve(strict=True).parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET')
FERNET_KEY = os.environ.get('FERNET_KEY')

# Cle MapTiler pour les tuiles de la carte explorer (cf. seo/static/seo/explorer.js).
# Exposee cote client (URL des tuiles) -> a restreindre par domaine dans le dashboard
# MapTiler. Si vide, la carte retombe sur les tuiles HOT / OpenStreetMap France.
# / MapTiler key for the explorer map tiles. Client-exposed -> restrict by domain.
# Empty -> the map falls back to HOT / OpenStreetMap France tiles.
MAPTILER_KEY = os.environ.get('MAPTILER_KEY', '')

FEDOW = True

# Autorise ou non la creation d'un asset local de categorie FED (fedow_core).
# La monnaie federee du reseau est servie par le Fedow distant : un asset FED
# local serait debite par la cascade de paiement du point de vente et rendu en
# billets par le remboursement en especes de la caisse, qui filtrent tous deux
# sur la categorie sans distinguer les deux moteurs. La garde vit dans
# Asset.save() (fedow_core/models.py) et leve AssetFedLocalInterdit.
# Seuls les tests qui couvrent volontairement le code d'apres-migration
# passent ce reglage a True, le temps de leur fixture.
# / Whether a local FED asset (fedow_core) may be created. The network's
# federated currency is served by the remote Fedow; a local one would be spent
# by the POS payment cascade and refunded in cash by the register. Guard lives
# in Asset.save() and raises AssetFedLocalInterdit.
FEDOW_AUTORISER_ASSET_FED_LOCAL = False

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG') == '1'

TEST = os.environ.get('TEST') == '1'

# Age of cookie, in seconds (default: 2 weeks).
SESSION_COOKIE_AGE = 60 * 60 * 24 * 7 * 12  # 12 weeks (3 month)
SESSION_SAVE_EVERY_REQUEST = True

# ----------------------------------------------------------------------
# COOKIES — attribut Secure
#
# `Secure` interdit au navigateur d'envoyer le cookie sur une connexion en
# clair. Sans lui, un reseau wifi hostile peut provoquer une seule requete
# HTTP vers le domaine et recuperer le cookie de session au passage.
#
# POURQUOI CONDITIONNE A `not DEBUG` PLUTOT QU'A `True` EN DUR :
# le client de test Django et les tests Playwright parlent en HTTP. Un
# cookie `Secure` ne serait tout simplement pas pose, et toute la suite
# authentifiee tomberait, avec un symptome trompeur (« utilisateur non
# connecte ») a des kilometres de la cause.
# / Conditioned on `not DEBUG` because the Django test client and Playwright
# speak HTTP: a Secure cookie would never be set and every authenticated
# test would fail with a misleading "not logged in" symptom.
#
# SANS RISQUE POUR LE MULTI-TENANT : `SESSION_COOKIE_DOMAIN` est desactive
# (voir juste en dessous), donc le cookie est deja host-only. Il n'y a
# aucun partage de session entre sous-domaines a preserver.
# / Safe for multi-tenancy: SESSION_COOKIE_DOMAIN is off, the cookie is
# already host-only, there is no cross-subdomain session to preserve.
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG

# `SameSite` decide si le cookie part quand la requete vient d'un AUTRE site.
#
# On reste en `Lax` (qui est deja la valeur par defaut de Django) et on
# l'ecrit explicitement pour que ce choix soit visible et documente.
#
# /!\ NE PAS PASSER EN `Strict`. Ca casserait deux parcours essentiels :
#   - le retour depuis Stripe apres un paiement (l'utilisateur reviendrait
#     deconnecte, et la reservation semblerait perdue) ;
#   - les liens de connexion envoyes par e-mail, qui sont ouverts depuis un
#     client mail, donc vus comme une navigation cross-site.
# / Do NOT switch to Strict: it breaks the Stripe payment return and the
# magic-link login e-mails (both are cross-site navigations).
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

# TODO montrer ça à Sham
# Mecanisme qui permet d'etre loggue sur toute les instances tibillet multi tenant
# SECURITY WARNING: This setting is only safe if all subdomains are fully trusted and controlled by you
# Otherwise it could enable session hijacking attacks across subdomains
# SESSION_COOKIE_DOMAIN = f'.{os.environ["DOMAIN"]}'
# Store CSRF data in session instead of cookie
# This is safer since session is signed and secure against tampering
# CSRF_USE_SESSIONS = True

# Sentry
if not DEBUG and os.environ.get('SENTRY_DNS'):
    import sentry_sdk

    sentry_sdk.init(
        dsn=os.environ.get('SENTRY_DNS'),
        # Tracing DESACTIVE (0.0) : le volume festival (4000 users + taches Celery)
        # saturait le budget de spans Sentry. Les events d'erreur (issues) restent
        # captures normalement ; seul le performance monitoring (spans/transactions)
        # est coupe. Remonter PRUDEMMENT (ex. 0.01-0.05) si besoin de perf, en
        # surveillant le budget spans.
        # / Tracing DISABLED (0.0): festival volume exhausted the Sentry spans budget.
        # Error events are still captured; only performance monitoring is off.
        traces_sample_rate=0.0,
        profiles_sample_rate=0.0,
    )

DATETIME_INPUT_FORMATS = ['%Y-%m-%d %H:%M:%S', '%Y-%m-%d %H:%M:%S.%f', '%Y-%m-%d %H:%M', '%d/%m/%Y %H:%M:%S', '%d/%m/%Y %H:%M:%S.%f', '%d/%m/%Y %H:%M', '%d/%m/%y %H:%M:%S', '%d/%m/%y %H:%M:%S.%f', '%d/%m/%y %H:%M']

ALLOWED_HOSTS = [
    f'{os.environ["DOMAIN"]}',
    f'.{os.environ["DOMAIN"]}',
    f'www.{os.environ["DOMAIN"]}',
    f'{os.environ["SUB"]}.{os.environ["DOMAIN"]}',
    f'{os.environ["META"]}.{os.environ["DOMAIN"]}',
]


CSRF_TRUSTED_ORIGINS = [
    f'https://{os.environ.get("DOMAIN")}',
    f'https://.{os.environ.get("DOMAIN")}',
    f'https://*.{os.environ.get("DOMAIN")}',
    f'https://www.{os.environ["DOMAIN"]}',
    f'https://{os.environ["SUB"]}.{os.environ["DOMAIN"]}',
    f'https://{os.environ["META"]}.{os.environ["DOMAIN"]}',
]

if DEBUG: # pour l'inspecteur chrome sur android
    ALLOWED_HOSTS += ['lespass.tibillet.localhost:8080', ]
    CSRF_TRUSTED_ORIGINS += ['https://lespass.tibillet.localhost:8080', ]

if os.environ.get('ADDITIONAL_DOMAINS'):
    for domain in os.environ.get('ADDITIONAL_DOMAINS').split(','):
        ALLOWED_HOSTS.append(f'{domain}')
        ALLOWED_HOSTS.append(f'.{domain}')
        CSRF_TRUSTED_ORIGINS.append(f'https://{domain}')
        CSRF_TRUSTED_ORIGINS.append(f'https://*.{domain}')

# ----------------------------------------------------------------------
# CORS — ETAT REEL : LE PARTAGE CROSS-ORIGIN EST DESACTIVE
#
# Ce bloc trompe la lecture, d'ou cet avertissement. DEUX raisons cumulees
# font qu'aucun reglage CORS n'est actif aujourd'hui :
#
# 1. `CORS_ORIGIN_WHITELIST` ci-dessous ne veut plus rien dire. Ce nom a ete
#    remplace par `CORS_ALLOWED_ORIGINS` dans django-cors-headers 3.0, puis
#    SUPPRIME en 4.0. Le projet est en 4.9 : ce reglage est ignore, en
#    silence. Il n'autorise donc rien. (Accessoirement, les entrees a
#    caractere joker comme `https://*.domaine` n'auraient de toute facon
#    jamais fonctionne : CORS_ALLOWED_ORIGINS n'accepte que des origines
#    exactes, les motifs passent par CORS_ALLOWED_ORIGIN_REGEXES.)
#
# 2. Le bloc qui suit est encadre par des triples guillemets. Ce n'est pas
#    du code : c'est une CHAINE DE CARACTERES que Python evalue et jette.
#    `CORS_ALLOW_ALL_ORIGINS = True` n'est donc PAS applique — ce qui est
#    une bonne nouvelle, car combine a `CORS_ALLOW_CREDENTIALS = True` il
#    aurait laisse n'importe quel site lire des reponses authentifiees.
#
# Verification, si un doute subsiste :
#   manage.py shell -c "from django.conf import settings; \
#       print(getattr(settings, 'CORS_ALLOW_ALL_ORIGINS', 'ABSENT'))"
#
# CONSEQUENCE PRATIQUE : le site ne repond a aucune requete cross-origin.
# C'est la position la plus sure, et elle convient tant que tout est servi
# depuis la meme origine (rendu serveur + HTMX). Si un client externe doit
# un jour appeler l'API depuis un autre domaine, il faudra ecrire un vrai
# `CORS_ALLOWED_ORIGINS` — ne PAS se contenter de sortir le bloc ci-dessous
# de ses guillemets, il ouvrirait tout.
# / CORS is fully OFF: `CORS_ORIGIN_WHITELIST` was removed in
# django-cors-headers 4.0 (project runs 4.9) and the block below is a
# string literal, not code. Safest position; keep it unless an external
# origin genuinely needs the API — and then write CORS_ALLOWED_ORIGINS
# properly rather than un-quoting the block.
# ----------------------------------------------------------------------
CORS_ORIGIN_WHITELIST = CSRF_TRUSTED_ORIGINS + ['http://localhost', ]
"""
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_EXPOSE_HEADERS = ['Content-Type', 'X-CSRFToken', 'Authorization']
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]
"""

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# Application definition
SHARED_APPS = (
    'django_tenants',  # mandatory
    "daphne",
    'Customers',  # you must list the app where your tenant model resides in

    "unfold",  # before django.contrib.admin
    "unfold.contrib.import_export",  # optional, if django-import-export package is used
    "unfold.contrib.filters",  # optional, if special filters are needed
    "unfold.contrib.forms",  # optional, if special form elements are needed
    "unfold.contrib.inlines",  # optional, if special inlines are needed
    # "unfold.contrib.guardian",  # optional, if django-guardian package is used
    # "unfold.contrib.simple_history",  # optional, if django-simple-history package is used

    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.admin',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',

    # 'channels',
    'AuthBillet',
    'QrcodeCashless',
    'Administration',
    'MetaBillet',
    'root_billet',
    'wsocket',
    'fedow_public',
    'fedow_core',
    'discovery',
    'seo',
    'onboard',

    # App pages : dual-list (SHARED + TENANT) pour exister dans le schema public
    # ET dans chaque schema tenant, chaque schema gardant ses propres pages isolees.
    # / pages app: dual-list so the table lives in the public schema AND in each
    # tenant schema, each schema keeping its own isolated pages.
    'pages',

    'django_extensions',
    'solo',
    'stdimage',
    'corsheaders',
    'django_htmx',
    'import_export',
    'django_cotton',
)

if DEBUG and not TEST :
    SHARED_APPS += ('django_browser_reload',)

# CodeLogin_app/settings.py
TENANT_COLOR_ADMIN_APPS = False

TENANT_APPS = (
    # The following Django contrib apps must be in TENANT_APPS
    'django.contrib.contenttypes',
    'django.contrib.staticfiles',

    'rest_framework_api_key',
    # your tenant-specific apps
    'BaseBillet',
    'ApiBillet',
    'api_v2',
    'PaiementStripe',
    'wsocket',
    'tibrss',
    'fedow_connect',
    'crowds',
    'booking',
    'comptabilite',
    'laboutik',
    'kiosk',
    'inventaire',
    # Tireuses connectées (controlvanne) — paiement NFC via fedow_core local.
    # / Connected beer taps (controlvanne) — NFC payment via local fedow_core.
    'controlvanne',
    # Voir SHARED_APPS : 'pages' est en dual-list (isolation par schema, public inclus).
    # / See SHARED_APPS: 'pages' is dual-listed (per-schema isolation, public included).
    'pages',
    # Newsletter : pilote une instance Ghost auto-hebergee depuis TiBillet.
    # / Newsletter: drives a self-hosted Ghost instance from TiBillet.
    'newsletter',
)

INSTALLED_APPS = list(SHARED_APPS) + [app for app in TENANT_APPS if app not in SHARED_APPS]
TENANT_MODEL = "Customers.Client"  # app.Model
TENANT_DOMAIN_MODEL = "Customers.Domain"  # app.Model
ROOT_URLCONF = 'TiBillet.urls_tenants'
PUBLIC_SCHEMA_URLCONF = 'TiBillet.urls_public'
SITE_ID = 1
AUTH_USER_MODEL = 'AuthBillet.TibilletUser'

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.PyMemcacheCache',
        'LOCATION': 'memcached:11211',
        'KEY_FUNCTION': 'django_tenants.cache.make_key',
        'REVERSE_KEY_FUNCTION': 'django_tenants.cache.reverse_key',
    }
}
SOLO_CACHE = 'default'
TENANT_LIMIT_SET_CALLS = True

MIDDLEWARE = [
    'django_tenants.middleware.main.TenantMainMiddleware',
    # Redirige (301) vers le domaine principal du tenant si on arrive sur un
    # domaine secondaire (ex : tibillet.org -> tibillet.coop). Doit rester juste
    # apres TenantMainMiddleware (besoin de connection.tenant).
    # / Redirect (301) to the tenant's primary domain. Must stay right after
    # TenantMainMiddleware (needs connection.tenant).
    'Customers.middleware.CanonicalDomainRedirectMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
    # Garde central des sessions terminal : un terminal (espece=TE, authentifié via
    # le bridge) est restreint à son interface (kiosk/laboutik/controlvanne) et ne
    # peut pas atteindre les vues humaines. Après Authentication + Htmx (lit user + htmx).
    # / Central terminal-session guard: restricts TE sessions to their interface.
    'AuthBillet.middleware.TerminalSessionGuardMiddleware',
    # Vary: HX-Request + Cache-Control par défaut : indispensable en prod, les
    # vues rendent 2 corps différents (shell/fragment) sur la même URL selon
    # HX-Request. Doit être APRÈS AuthenticationMiddleware (lit request.user).
    # / Vary: HX-Request + default Cache-Control: required in prod, views render
    # 2 different bodies (shell/fragment) on the same URL depending on
    # HX-Request. Must come AFTER AuthenticationMiddleware (reads request.user).
    'BaseBillet.middleware.ProtectionCacheHtmxMiddleware',
    'Customers.views.TimezoneMiddleware',
]

if DEBUG and not TEST :
    MIDDLEWARE += ['django_browser_reload.middleware.BrowserReloadMiddleware', ]

# Detection HTTPS derriere proxy (Traefik termine TLS et forwarde HTTP au container).
# Sans ce reglage, request.scheme = 'http' → canonical URLs et JSON-LD contiennent
# http://... au lieu de https://... ce qui penalise le SEO.
# Le header X-Forwarded-Proto doit etre setting cote Traefik (par defaut dans
# le mode HTTPS auto, mais a verifier). En dev local, le browser accepte http
# meme si on tape https:// donc le canonical http:// reste cosmetique.
# / HTTPS detection behind proxy (Traefik terminates TLS, forwards HTTP to container).
# Without this, request.scheme = 'http' → canonical URLs and JSON-LD contain
# http://... instead of https://... which hurts SEO.
# The X-Forwarded-Proto header must be set on Traefik side (default in
# HTTPS auto mode, but worth checking). In local dev, browsers accept http
# even if typed as https://, so http:// canonical stays cosmetic.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 'DIRS': [],
        'DIRS': [
            BASE_DIR / "Administration/templates",  # Pour le dashboard d'admin unfold
            BASE_DIR / "templates",  # Templates réutilisables projet (widgets, etc.)
        ],
        # APP_DIRS doit etre False quand on utilise des loaders explicites (django-cotton).
        # app_directories.Loader conserve la decouverte des templates d'apps.
        # / APP_DIRS must be False with explicit loaders (django-cotton). app_directories.Loader
        # keeps app template discovery working.
        'APP_DIRS': False,

        'OPTIONS': {
            'loaders': [
                'django_cotton.cotton_loader.Loader',
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
            ],
            'builtins': [
                'django_cotton.templatetags.cotton',
            ],
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Expose `noindex_seo: bool` aux bases templates pour
                # le rendu de <meta name="robots">. Voir
                # TiBillet/seo_indexing.py et SESSIONS/SEO/CHANTIER-01.
                # / Expose `noindex_seo: bool` to base templates.
                'TiBillet.seo_indexing.noindex_context',
                'BaseBillet.context_processors.panier_context',
                # Expose `maptiler_key: str` a tous les gabarits qui rendent une
                # carte (blocs, geoloc, explorer, widget d'adresse). Voir
                # TiBillet/maptiler.py et static/cartes/tb_fond_de_carte.js.
                # / Expose `maptiler_key: str` to every template rendering a map.
                'TiBillet.maptiler.maptiler_context',
            ],
        },
    }
]

WSGI_APPLICATION = 'TiBillet.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django_tenants.postgresql_backend',  # Add 'postgresql', 'mysql', 'sqlite3' or 'oracle'.
        'NAME': os.environ.get('POSTGRES_DB'),
        'USER': os.environ.get('POSTGRES_USER'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD'),
        'HOST': os.environ.get('POSTGRES_HOST', 'postgres'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
    }
}

DATABASE_ROUTERS = (
    'django_tenants.routers.TenantSyncRouter',
)

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    # 'DEFAULT_THROTTLE_CLASSES': [
    #     'rest_framework.throttling.AnonRateThrottle',
    #     'rest_framework.throttling.UserRateThrottle'
    #     # 'rest_framework.throttling.ScopedRateThrottle',
    # ],
    # 'DEFAULT_THROTTLE_RATES': {
    #     'smallanon': '10/day',
    #     'anon': '1000/day',
    #     'user': '100000/day'
    # },
    # INDISPENSABLE : sans ce reglage, la limitation de debit est CONTOURNABLE.
    #
    # Pour identifier qui appelle, DRF lit l'en-tete X-Forwarded-For. Quand NUM_PROXIES
    # n'est pas defini, il prend cet en-tete EN ENTIER — or il est fourni par le client,
    # donc falsifiable. Il suffit d'envoyer une valeur differente a chaque requete pour
    # obtenir une identite neuve a chaque fois, et la limite ne s'applique plus jamais.
    #
    # Notre nginx AJOUTE l'adresse reelle en fin d'en-tete ($proxy_add_x_forwarded_for).
    # Avec NUM_PROXIES = 1, DRF prend la DERNIERE adresse de la liste : celle que nginx
    # vient d'ajouter. C'est la seule que le client ne peut pas falsifier.
    #
    # Ce que ca protege concretement : l'appairage d'un terminal se reclame avec un code
    # a 6 chiffres, sur une route publique. Sans limite de debit reelle, les 900 000 codes
    # possibles se balaient en quelques minutes.
    # / MANDATORY: without this, rate limiting is BYPASSABLE. DRF would trust the whole
    # client-supplied X-Forwarded-For header as the caller's identity.
    'NUM_PROXIES': 1,

    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
        "rest_framework_api_key.permissions.HasAPIKey",
    ),
    # "DEFAULT_AUTHENTICATION_CLASSES": (
    #     "rest_framework_simplejwt.authentication.JWTAuthentication",
    # ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}

#
# SIMPLE_JWT = {
#     'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
#     'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
#     #     'REFRESH_TOKEN_LIFETIME': timedelta(seconds=30),
#     'ROTATE_REFRESH_TOKENS': False,
#     'BLACKLIST_AFTER_ROTATION': False,
#     'UPDATE_LAST_LOGIN': False,
#
#     'ALGORITHM': 'HS256',
#     'SIGNING_KEY': SECRET_KEY,
#     'VERIFYING_KEY': None,
#     'AUDIENCE': None,
#     'ISSUER': None,
#     'JWK_URL': None,
#     'LEEWAY': 0,
#
#     'AUTH_HEADER_TYPES': ('Bearer',),
#     'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
#     'USER_ID_FIELD': 'id',
#     'USER_ID_CLAIM': 'user_id',
#     'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
#
#     'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
#     'TOKEN_TYPE_CLAIM': 'token_type',
#     'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',
#
#     'JTI_CLAIM': 'jti',
#
#     'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
#     'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
#     'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
# }

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = os.environ.get('LANGUAGE_CODE', 'fr')

TIME_ZONE = os.environ.get('TIME_ZONE', 'UTC')

USE_I18N = True
USE_L10N = True
USE_TZ = True
LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, "www", "static")
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    'BaseBillet/static',
    'MetaBillet/static',
    BASE_DIR / "static",  # Fichiers statiques projet (widgets, etc.)
]

MEDIA_ROOT = os.path.join(BASE_DIR, "www", "media")
MEDIA_URL = '/media/'

# --- Limites d'upload / Upload limits ---
# Borne la taille des donnees POST NON-fichier gardees en memoire (formulaires,
# JSON de l'API). Ne compte PAS les fichiers uploades (exclus par Django). Aligne
# sur la limite nginx (client_max_body_size). / Caps in-memory NON-file POST data
# (forms, API JSON). Does NOT count uploaded files. Aligned with the nginx limit.
DATA_UPLOAD_MAX_MEMORY_SIZE = 12 * 1024 * 1024  # 12 Mo

# Seuil au-dela duquel un fichier uploade est ecrit sur disque (temp) au lieu de
# rester en RAM. Protege la memoire lors des uploads. / Threshold above which an
# uploaded file is streamed to a temp file on disk instead of RAM.
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024  # 5 Mo

# EMAIL
EMAIL_HOST = os.environ.get('EMAIL_HOST')
EMAIL_PORT = os.environ.get('EMAIL_PORT')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', False)
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', True)

# Celery Configuration Options
CELERY_TIMEZONE = os.environ.get('TIME_ZONE', 'UTC')
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60
BROKER_URL = os.environ.get('CELERY_BROKER', 'redis://redis:6379/0')
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER', 'redis://redis:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_BACKEND', 'redis://redis:6379/0')

# Fenetre pendant laquelle Redis attend l'ack d'une tache avant de la redelivrer.
# Avec un broker Redis, une tache dont le countdown (retry, eta) depasse cette
# valeur est consideree comme perdue et redelivree en boucle (meme task_id),
# ce qui provoque une duplication exponentielle des taches et sature la RAM.
# REGLE : MAX_RETRY_TIME des taches *_to_laboutik (BaseBillet/tasks.py) doit
# rester strictement sous cette valeur.
# / Redis re-delivers any task whose countdown exceeds this timeout. Keep task
# retry countdowns strictly below it to avoid exponential task duplication.
CELERY_BROKER_TRANSPORT_OPTIONS = {'visibility_timeout': 3600}  # 1 h
# DJANGO_CELERY_BEAT_TZ_AWARE=False

# CHANNELS
ASGI_APPLICATION = "TiBillet.asgi.application"
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('redis', 6379)],
        },
    },
}

# -------------------------------------/
# COMMUNECTER SSO oauth2 — RETIRÉ (plus utilisé) / REMOVED (no longer used)
# -------------------------------------/

# -------------------------------------/
# LOGGING
# -------------------------------------/

LOGGING_LVL = 'DEBUG' if DEBUG else 'INFO'
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'tenant_context': {
            '()': 'django_tenants.log.TenantContextFilter'
        },
    },
    'formatters': {
        'simple': {
            'format': '%(levelname)s %(message)s',
            'datefmt': '%y %b %d, %H:%M:%S',
        },
        'tenant_context': {
            'format': '[%(schema_name)s:%(domain_url)s] '
                      '%(levelname)-7s %(asctime)s %(message)s',
        },
    },
    'handlers': {
        'console': {
            'level': LOGGING_LVL,
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
            'filters': ['tenant_context'],
        },
        'logfile': {
            'level': LOGGING_LVL,
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': f"{BASE_DIR}/logs/Djangologfile",
            'formatter': 'simple',
            'maxBytes': 1024 * 1024 * 100,  # 100 mb
            'filters': ['tenant_context'],
        },
        'weasyprint': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': f"{BASE_DIR}/logs/weasyprint",
            'formatter': 'simple',
            'maxBytes': 1024 * 1024 * 100,  # 100 mb
            'filters': ['tenant_context'],
        },
    },
    "import_export": {
        "handlers": ["console", "logfile"],
        "level": "INFO",
    },
    'root': {
        'level': 'INFO',
        # 'handlers': ['console', 'logfile', 'weasyprint']
        'handlers': ['console']
    },
}

UNFOLD = {
    "ENVIRONMENT": "Administration.admin_tenant.environment_callback",  # environment name in header
    "DASHBOARD_CALLBACK": "Administration.admin_tenant.dashboard_callback",
    "SHOW_HISTORY": False,  # show/hide "History" button, default: True
    "SITE_TITLE": "TiBillet",
    "THEME": "light",  # Force theme disable theme switcher
    # En haut du rail : le nom du lieu, puis une ligne de contexte.
    # SITE_HEADER accepte un chemin pointe vers un callable, comme
    # SIDEBAR.navigation — c'est ce qui permet d'afficher le nom du lieu
    # courant plutot qu'une chaine fixe. Utile des qu'on gere plusieurs lieux.
    # / SITE_HEADER accepts a dotted path to a callable, so the sidebar can
    #   show the current venue's name instead of a fixed string.
    "SITE_HEADER": "Administration.admin_tenant.nom_du_lieu",
    "SITE_SUBHEADER": _("Votre espace TiBillet"),
    # Le glyphe de la pastille, quand aucun logo n'est fourni.
    # / The tile glyph, when no logo is configured.
    "SITE_SYMBOL": "confirmation_number",
    # Le menu qui s'ouvre sous le nom du lieu, en haut du rail.
    # / The menu that opens under the venue name, at the top of the rail.
    "SITE_DROPDOWN": [
        {
            # Retour au site public du lieu. C'est la racine de SON domaine :
            # un lien relatif suffit, et il reste juste pour tous les lieux
            # sans avoir a fabriquer d'URL absolue.
            # / Back to the venue's public site: the root of its own domain,
            #   so a relative link is correct for every tenant.
            "icon": "home",
            "title": _("Voir mon site"),
            "link": "/",
        },
        {
            # Raccourci vers la page de configuration du lieu. La maquette en
            # fait un crayon epingle au nom ; le mettre ici evite de forker
            # unfold/helpers/navigation_header.html, qui n'offre aucun point
            # d'insertion (element_classes n'injecte que des classes).
            # / Shortcut to the venue's settings page. The mockup pins a pencil
            #   next to the name; putting it here avoids forking Unfold's
            #   navigation header, which offers no insertion point.
            #
            # reverse_lazy plutot qu'un chemin ecrit a la main : si ce
            # ModelAdmin est un jour desenregistre, on le saura au demarrage
            # plutot que par un lien mort.
            # / reverse_lazy rather than a hand-written path: a missing admin
            #   fails at startup instead of leaving a dead link.
            "icon": "edit",
            "title": _("Modifier l'identité de mon lieu"),
            "link": reverse_lazy("staff_admin:BaseBillet_configuration_changelist"),
        },
        {
            "icon": "diamond",
            "title": _("TiBillet"),
            "link": "https://tibillet.coop",
        },
    ],
    # Barres d'onglets, construites depuis la meme source que la sidebar.
    #
    # POURQUOI UN CALLABLE : depuis le passage aux domaines, la sidebar
    # n'affiche plus qu'UN lien par module. Les autres pages du module ne
    # sont atteignables QUE par ces onglets — ils ne sont donc pas un
    # confort, mais la seconde moitie de la navigation.
    # get_tabs() les derive des memes sections que get_sidebar_navigation(),
    # ce qui garantit qu'une page ajoutee a un module apparait aux deux
    # endroits sans double saisie. Les deux barres historiques (Formbricks,
    # Parametres/Cles API/Webhooks) y sont conservees telles quelles.
    # / Tabs are derived from the same sections as the sidebar. Since the
    #   sidebar now shows one link per module, these tabs are the only way
    #   to reach a module's other pages.
    "TABS": "Administration.admin_tenant.get_tabs",
    "SIDEBAR": {
        "show_search": True, #  Search in applications and models names
        "show_all_applications": False, # Dropdown with all applications and models
        "navigation": "Administration.admin_tenant.get_sidebar_navigation",
    },
    # --- Peau TiBillet : palette de l'admin Unfold ---------------------------
    # Jetons repris de la maquette (TEMP-tibillet-admin-main/style.css),
    # convertis en OKLCH puis etales sur les 11 paliers attendus par Unfold.
    # Unfold injecte chaque entree en variable CSS --color-{nom}-{poids}
    # (voir unfold/templates/unfold/layouts/skeleton.html).
    # / TiBillet admin skin: warm paper + brand green, from the mockup tokens.
    "COLORS": {
        # Neutres chauds (teinte 93) : remplacent le gris-bleu froid d'Unfold.
        # base-50 sert de fond de page, base-200 de couleur de bordure globale.
        # / Warm neutrals (hue 93) replacing Unfold's cool blue-grey.
        "base": {
            "50": "oklch(96.5% 0.008 93)",  # #f5f3ee  papier / paper
            "100": "oklch(94.9% 0.010 93)",  # #f0eee7  --line-soft
            "200": "oklch(91.9% 0.012 93)",  # #e7e4db  --line
            "300": "oklch(86.5% 0.012 93)",  # #d5d3ca
            "400": "oklch(67.9% 0.010 93)",  # #9a9891  --ink-mut
            "500": "oklch(56.0% 0.008 93)",  # #76746f
            "600": "oklch(48.2% 0.006 93)",  # #5f5e5a  --ink-soft
            "700": "oklch(38.0% 0.008 93)",  # #44423e
            "800": "oklch(30.0% 0.010 93)",  # #2f2e28
            "900": "oklch(21.0% 0.012 93)",  # #1a1812  fond du mode sombre
            "950": "oklch(16.0% 0.012 93)",  # #0f0d08
        },
        # Vert de marque (teinte 166), ancre sur #1D9E75 au palier 600.
        # Pilote les boutons, les liens, le lien de sidebar actif, le focus.
        # / Brand green anchored on #1D9E75 at step 600.
        "primary": {
            "50": "oklch(95.2% 0.021 166)",  # #e3f4ec  --brand-soft
            "100": "oklch(91.5% 0.040 166)",  # #cbecdd
            "200": "oklch(85.5% 0.065 166)",  # #a7dec6
            "300": "oklch(78.0% 0.090 166)",  # #7dcaaa
            "400": "oklch(70.5% 0.108 166)",  # #54b590
            "500": "oklch(66.0% 0.118 166)",  # #37a981
            "600": "oklch(62.3% 0.123 165.5)",  # #1d9e75  --brand
            "700": "oklch(54.0% 0.107 170)",  # #008265
            "800": "oklch(48.1% 0.091 170)",  # #0f6e56  --brand-txt
            "900": "oklch(40.0% 0.075 170)",  # #0b5441
            "950": "oklch(27.0% 0.050 170)",  # #042e23
        },
        # Les trois tons d'encre de la maquette, montes sur les jetons Unfold.
        # Les variantes sombres restent des renvois a la rampe base : le mode
        # sombre herite de la chaleur sans travail supplementaire.
        # / The mockup's three ink tones mapped onto Unfold's font tokens.
        "font": {
            "subtle-light": "oklch(67.9% 0.010 93)",  # #9a9891  --ink-mut
            "subtle-dark": "var(--color-base-400)",
            "default-light": "oklch(48.2% 0.006 93)",  # #5f5e5a  --ink-soft
            "default-dark": "var(--color-base-300)",
            "important-light": "oklch(26.3% 0.011 99.3)",  # #26251f  --ink
            "important-dark": "var(--color-base-100)",
        },
        # --- Rampes semantiques ---
        # Unfold ne les met PAS dans COLORS par defaut : elles ne vivent que
        # dans son @layer theme. Les declarer ici les fait passer par le bloc
        # <style> du <body>, qui gagne sur le layer. C'est ce qui recolore
        # d'un coup tous les badges @display(label=...), les messages, les
        # booleens et l'interrupteur, sans une seule ligne de CSS.
        # / Declaring these recolors every badge, message, boolean and switch.
        "green": {  # succes / success  ->  --brand-soft / --brand-txt
            "100": "#e3f4ec",
            "400": "#4bbc93",
            "500": "#1D9E75",
            "600": "#1a8a66",
            "700": "#0f6e56",
        },
        "orange": {  # avertissement / warning  ->  --warm-soft / --warm-txt
            "100": "#fbeed7",
            "400": "#f0b45c",
            "500": "#EF9F27",
            "600": "#d98a17",
            "700": "#8a5310",
        },
        "blue": {  # information / info  ->  --blue-soft / --blue-txt
            "100": "#e6f1fb",
            "400": "#6aa9e6",
            "500": "#378ADD",
            "600": "#2a72bd",
            "700": "#185fa5",
        },
        "red": {  # danger  ->  ton .u-danger de la maquette
            "100": "#fbe4e0",
            "400": "#e88b7d",
            "500": "#e0483d",
            "600": "#c4432f",
            "700": "#9c3524",
        },
        # Unfold ne definit que yellow-200 et yellow-500. Or
        # Administration/templates/admin/dashboard.html:46 utilise
        # bg-yellow-100 / text-yellow-800 / dark:bg-yellow-900 : le badge
        # « V1 » s'affiche donc aujourd'hui SANS couleur. Declarer la rampe
        # complete corrige ce bug preexistant au passage.
        # / Fixes a pre-existing bug: the V1 badge uses undefined yellow steps.
        "yellow": {
            "100": "#fbeed7",
            "200": "#f6dcae",
            "400": "#f0b45c",
            "500": "#EF9F27",
            "600": "#d98a17",
            "800": "#8a5310",
            "900": "#5c3709",
        },
    },
    # Arrondis de la maquette : controles 8-10px, cartes 10-14px. 10px est le
    # meilleur compromis unique. Alimente la classe `rounded-default` utilisee
    # par tous les widgets Unfold (voir unfold/widgets.py).
    # / Mockup radius; feeds Unfold's `rounded-default` class.
    "BORDER_RADIUS": "10px",
    # Feuille de finition de la peau TiBillet.
    # Unfold l'insere dans le <head> AVANT son propre styles.css. L'ordre
    # source jouerait donc contre nous, mais le CSS d'Unfold est du Tailwind
    # v4 range dans des @layer : une regle SANS layer gagne toujours. Voir
    # l'en-tete du fichier CSS pour les deux regles d'ecriture a respecter.
    # / Skin finishing sheet. Unfold injects it before its own styles.css,
    #   but unlayered CSS always beats Unfold's layered Tailwind.
    "STYLES": [
        lambda request: static("css/tibillet-admin.css"),
    ],
    "SCRIPTS": [
        lambda request: static("js/autofocus_select2.js"),
    ],
}

if DEBUG:
    SHELL_PLUS = "ipython"

    SHELL_PLUS_POST_IMPORTS = [  # extra things to import in notebook
        ("django.template.loader", ("get_template", "render_to_string")),
        ("IPython.lib.pretty", ("pretty")),
        ("root_billet.utils", ("pp")),
        ("datetime", ("datetime", "timedelta")),
        ("json"),
        ("requests"),
        ("fedow_connect.fedow_api", ("FedowAPI",)),
        ("fedow_connect.utils", ("rsa_generator", "sign_message", "verify_signature",
                                 "sign_utf8_string", "get_public_key", "get_private_key",
                                 "hash_hexdigest", "rsa_encrypt_string", "rsa_decrypt_string")),
        (("cryptography.hazmat.primitives"), ("serialization",)),
        (("BaseBillet.tasks"), ("test_logger",)),
        (("ApiBillet.serializers"), ("get_or_create_price_sold",)),
        (("fedow_connect.fedow_api"), ("FedowAPI",)),
        (("django.db"), ("connection",)),

        #     ("module2.submodule", ("func1", "func2", "class1", "etc"))
        #
    ]
    os.environ["DJANGO_ALLOW_ASYNC_UNSAFE"] = "true"  # only use in development




# --- Mode demonstration POS (simulateur de scan NFC) — portage S6 ---
# DEMO active le simulateur de carte du POS (boutons cartes demo + saisie manuelle).
# Defaut : True en dev (DEBUG), False en prod ; override via la variable d'env DEMO.
# / DEMO enables the POS NFC card simulator. Defaults to True in dev (DEBUG), False in prod.
DEMO = os.environ.get("DEMO", "1" if DEBUG else "0") == "1"

# --- Cartes NFC de demonstration (fixtures POS laboutik) — portage S6 ---
# / Demo NFC cards for laboutik POS fixtures
DEMO_TAGID_CM = os.environ.get('DEMO_TAGID_CM', 'A49E8E2A').strip().upper()
DEMO_TAGID_CLIENT1 = os.environ.get('DEMO_TAGID_CLIENT1', '41726643').strip().upper()
DEMO_TAGID_CLIENT2 = os.environ.get('DEMO_TAGID_CLIENT2', '52be6543').strip().upper()
DEMO_TAGID_CLIENT3 = os.environ.get('DEMO_TAGID_CLIENT3', '33BC1DC3').strip().upper()
DEMO_TAGID_CLIENT4 = os.environ.get('DEMO_TAGID_CLIENT4', 'E85C2C6E').strip().upper()
DEMO_EMAIL_CLIENT1 = os.environ.get('DEMO_EMAIL_CLIENT1', 'client1@test.loc')
DEMO_EMAIL_CLIENT2 = os.environ.get('DEMO_EMAIL_CLIENT2', 'client2@test.loc')
DEMO_EMAIL_CLIENT3 = os.environ.get('DEMO_EMAIL_CLIENT3', 'client3@test.loc')
