# Generated by Django 4.2.11 on 2024-04-18 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models
import stdimage.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('img', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='images/', validators=[stdimage.validators.MaxSizeValidator(1920, 1920)], variations={'med': (480, 480), 'thumbnail': (150, 90)}, verbose_name='Recto de la carte')),
                ('img_url', models.URLField(blank=True, null=True)),
                ('base_url', models.CharField(blank=True, max_length=60, null=True)),
                ('generation', models.SmallIntegerField()),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('origine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='origine', to='Customers.client')),
            ],
        ),
        migrations.CreateModel(
            name='CarteCashless',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.CharField(db_index=True, editable=False, max_length=8, unique=True)),
                ('uuid', models.UUIDField(blank=True, db_index=True, editable=False, null=True, unique=True, verbose_name='Uuid')),
                ('number', models.CharField(db_index=True, editable=False, max_length=8, unique=True)),
                ('detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='QrcodeCashless.detail')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
