# Generated by Django 3.2 on 2023-01-03 10:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('QrcodeCashless', '0006_alter_wallet_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together={('asset', 'user')},
        ),
    ]
