# Generated by Django 3.2 on 2023-01-10 12:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0002_alter_client_categorie'),
        ('QrcodeCashless', '0008_alter_cartecashless_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncFederatedLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('etat_client_sync', models.JSONField(blank=True, null=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='QrcodeCashless.asset')),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='QrcodeCashless.cartecashless')),
                ('client_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Customers.client')),
            ],
        ),
        migrations.CreateModel(
            name='FederatedCashless',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('server_cashless', models.URLField(blank=True, null=True)),
                ('key_cashless', models.CharField(blank=True, max_length=50, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='QrcodeCashless.asset')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Customers.client')),
            ],
        ),
    ]
