# Generated by Django 3.2 on 2023-01-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QrcodeCashless', '0010_auto_20230111_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncfederatedlog',
            name='new_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='syncfederatedlog',
            name='old_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
