# Generated by Django 3.2 on 2023-01-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QrcodeCashless', '0011_auto_20230125_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncfederatedlog',
            name='categorie',
            field=models.CharField(choices=[('N', '?'), ('S', 'Recharge fédérée depuis stripe'), ('V', "Vente d'article depuis cashless")], default='N', max_length=3, verbose_name='Why?'),
        ),
    ]
