# Generated by Django 3.2 on 2023-01-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QrcodeCashless', '0013_auto_20230125_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='categorie',
            field=models.CharField(choices=[('LE', 'Token local €'), ('LG', 'Token local cadeau'), ('FR', 'Fractionné'), ('AR', 'Ardoise'), ('SF', 'Token Federated Stripe'), ('SN', 'Stripe no federated'), ('CA', 'Espèces'), ('CC', 'Carte bancaire TPE'), ('OC', 'Oceco')], default='SF', max_length=2),
            preserve_default=False,
        ),
    ]
