# Generated by Django 3.2 on 2023-01-26 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0002_alter_client_categorie'),
        ('QrcodeCashless', '0014_asset_categorie'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('origin', 'categorie'), ('origin', 'name')},
        ),
    ]
