# Generated by Django 3.2 on 2023-04-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QrcodeCashless', '0015_alter_asset_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
