# Generated by Django 4.2.10 on 2024-02-15 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QrcodeCashless', '0016_detail_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SyncFederatedLog',
        ),
    ]
