# Generated by Django 4.2.10 on 2024-02-15 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QrcodeCashless', '0018_delete_federatedcashless'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
