# Generated by Django 4.2.10 on 2024-02-15 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QrcodeCashless', '0019_delete_wallet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asset',
        ),
    ]
