# Generated by Django 4.2.30 on 2026-07-21 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AuthBillet', '0024_tibilletuser_terminal_role_wallet_name_and_more'),
        ('QrcodeCashless', '0020_delete_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartecashless',
            name='wallet_ephemere',
            field=models.OneToOneField(blank=True, help_text='Wallet temporaire pour carte anonyme (avant identification user)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carte_ephemere', to='AuthBillet.wallet'),
        ),
    ]
