# Generated by Django 4.2.30 on 2026-10-05 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AuthBillet', '0024_role_de_terminal_et_portefeuille'),
        ('QrcodeCashless', '0020_delete_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartecashless',
            name='wallet_ephemere',
            field=models.OneToOneField(blank=True, help_text='Wallet temporaire pour carte anonyme (avant identification user)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carte_ephemere', to='AuthBillet.wallet'),
        ),
        migrations.AlterField(
            model_name='cartecashless',
            name='number',
            field=models.CharField(db_index=True, editable=False, max_length=8, unique=True, verbose_name='Numéro'),
        ),
        migrations.AlterField(
            model_name='cartecashless',
            name='tag_id',
            field=models.CharField(db_index=True, editable=False, max_length=8, unique=True, verbose_name='Identifiant NFC'),
        ),
        migrations.AlterField(
            model_name='cartecashless',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur·ice'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='generation',
            field=models.SmallIntegerField(verbose_name='Génération'),
        ),
    ]
