# Generated by Django 4.2.28 on 2026-03-06 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QrcodeCashless', '0021_cartecashless_wallet_ephemere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartecashless',
            name='wallet_ephemere',
        ),
    ]
