# Generated by Django 4.2.30 on 2026-09-09 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('QrcodeCashless', '0021_cartecashless_wallet_ephemere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartecashless',
            name='number',
            field=models.CharField(db_index=True, editable=False, max_length=8, unique=True, verbose_name='Numéro'),
        ),
        migrations.AlterField(
            model_name='cartecashless',
            name='tag_id',
            field=models.CharField(db_index=True, editable=False, max_length=8, unique=True, verbose_name='Identifiant NFC'),
        ),
        migrations.AlterField(
            model_name='cartecashless',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur·ice'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='generation',
            field=models.SmallIntegerField(verbose_name='Génération'),
        ),
    ]
