# Generated by Django 4.2.28 on 2026-03-12 04:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('QrcodeCashless', '0021_cartecashless_wallet_ephemere'),
        ('BaseBillet', '0203_categorieproduct_membershipproduct_posproduct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (e.g. Indoor, Terrace, Bar).', max_length=200, unique=True, verbose_name='Name')),
                ('icon', models.CharField(blank=True, help_text='Icon name (e.g. Bootstrap Icons class).', max_length=50, null=True, verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Table category',
                'verbose_name_plural': 'Table categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Table name or number (e.g. Table 1, Bar 3).', max_length=200, unique=True, verbose_name='Name')),
                ('poids', models.SmallIntegerField(default=0, help_text='Lower values are displayed first.', verbose_name='Display order')),
                ('statut', models.CharField(choices=[('L', 'Free'), ('O', 'Occupied'), ('S', 'Served')], default='L', max_length=1, verbose_name='Status')),
                ('ephemere', models.BooleanField(default=False, help_text='Temporary table created for a single service.', verbose_name='Temporary')),
                ('archive', models.BooleanField(default=False, verbose_name='Archived')),
                ('position_top', models.IntegerField(blank=True, help_text='Vertical position in pixels on the floor plan.', null=True, verbose_name='Top position')),
                ('position_left', models.IntegerField(blank=True, help_text='Horizontal position in pixels on the floor plan.', null=True, verbose_name='Left position')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='laboutik.categorietable', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
                'ordering': ('poids', 'name'),
            },
        ),
        migrations.CreateModel(
            name='PointDeVente',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Point of sale name. Must be unique.', max_length=200, unique=True, verbose_name='Name')),
                ('icon', models.CharField(blank=True, help_text='Icon name (e.g. Bootstrap Icons class).', max_length=50, null=True, verbose_name='Icon')),
                ('comportement', models.CharField(choices=[('D', 'Direct'), ('K', 'Kiosk'), ('C', 'Cashless')], default='D', help_text='Operating mode: Direct (standard sale), Kiosk (self-service), Cashless (NFC only).', max_length=1, verbose_name='Behavior')),
                ('service_direct', models.BooleanField(default=True, help_text='If checked, orders are served immediately (no table service).', verbose_name='Direct service')),
                ('afficher_les_prix', models.BooleanField(default=True, help_text='Display prices on the POS interface.', verbose_name='Show prices')),
                ('accepte_especes', models.BooleanField(default=True, verbose_name='Accepts cash')),
                ('accepte_carte_bancaire', models.BooleanField(default=True, verbose_name='Accepts credit card')),
                ('accepte_cheque', models.BooleanField(default=False, verbose_name='Accepts check')),
                ('accepte_commandes', models.BooleanField(default=False, help_text='Enable table order management for this point of sale.', verbose_name='Accepts orders')),
                ('poid_liste', models.SmallIntegerField(default=0, help_text='Lower values are displayed first.', verbose_name='Display order')),
                ('hidden', models.BooleanField(default=False, help_text='Hide this point of sale from the selection screen.', verbose_name='Hidden')),
                ('categories', models.ManyToManyField(blank=True, help_text='Product categories available at this point of sale.', related_name='points_de_vente', to='BaseBillet.categorieproduct', verbose_name='Categories')),
                ('products', models.ManyToManyField(blank=True, help_text='Products available at this point of sale.', related_name='points_de_vente', to='BaseBillet.product', verbose_name='Products')),
            ],
            options={
                'verbose_name': 'Point of sale',
                'verbose_name_plural': 'Points of sale',
                'ordering': ('poid_liste', 'name'),
            },
        ),
        migrations.CreateModel(
            name='CartePrimaire',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('edit_mode', models.BooleanField(default=False, help_text='Allow this operator to modify products and prices from the POS interface.', verbose_name='Edit mode')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('carte', models.OneToOneField(help_text='Physical NFC card associated with this primary card.', on_delete=django.db.models.deletion.CASCADE, related_name='carte_primaire', to='QrcodeCashless.cartecashless', verbose_name='NFC card')),
                ('points_de_vente', models.ManyToManyField(blank=True, help_text='Points of sale this operator can access.', related_name='cartes_primaires', to='laboutik.pointdevente', verbose_name='Points of sale')),
            ],
            options={
                'verbose_name': 'Primary card',
                'verbose_name_plural': 'Primary cards',
            },
        ),
    ]
