# Generated by Django 4.2.29 on 2026-04-06 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('QrcodeCashless', '0021_cartecashless_wallet_ephemere'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BaseBillet', '0204_categorieproduct_futproduct_membershipproduct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (e.g. Indoor, Terrace, Bar).', max_length=200, unique=True, verbose_name='Name')),
                ('icon', models.CharField(blank=True, help_text='Icon name (e.g. Bootstrap Icons class).', max_length=50, null=True, verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Table category',
                'verbose_name_plural': 'Table categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ClotureCaisse',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('datetime_ouverture', models.DateTimeField(help_text='Start of the service period covered by this closure.', verbose_name='Service start')),
                ('datetime_cloture', models.DateTimeField(default=django.utils.timezone.now, help_text='Moment of the closure. Set explicitly, not auto_now_add.', verbose_name='Closure datetime')),
                ('total_especes', models.IntegerField(default=0, help_text='Total cash amount in cents.', verbose_name='Cash total (cents)')),
                ('total_carte_bancaire', models.IntegerField(default=0, help_text='Total credit card amount in cents.', verbose_name='Credit card total (cents)')),
                ('total_cashless', models.IntegerField(default=0, help_text='Total cashless/NFC amount in cents.', verbose_name='Cashless total (cents)')),
                ('total_general', models.IntegerField(default=0, help_text='Grand total in cents (cash + card + cashless).', verbose_name='Grand total (cents)')),
                ('nombre_transactions', models.IntegerField(default=0, help_text='Number of LigneArticle records in this period.', verbose_name='Transaction count')),
                ('niveau', models.CharField(choices=[('J', 'Daily'), ('H', 'Weekly'), ('M', 'Monthly'), ('A', 'Annual')], default='J', help_text='J = journaliere (caissier), M = mensuelle (auto), A = annuelle (auto). / J = daily (cashier), M = monthly (auto), A = annual (auto).', max_length=1, verbose_name='Closure level')),
                ('numero_sequentiel', models.PositiveIntegerField(default=0, help_text='Numero sequentiel par niveau de cloture. Sans trou. Global au tenant. / Sequential number per closure level. No gap. Global to tenant.', verbose_name='Sequential number')),
                ('total_perpetuel', models.IntegerField(default=0, help_text='Total cumule depuis la mise en service, snapshot au moment de cette cloture. / Cumulative total since first use, snapshot at this closure time.', verbose_name='Perpetual total (cents)')),
                ('hash_lignes', models.CharField(blank=True, default='', help_text='SHA-256 des LigneArticle couvertes. Filet de securite. / SHA-256 of covered LigneArticle. Safety net.', max_length=64, verbose_name='Lines integrity hash')),
                ('rapport_json', models.JSONField(blank=True, default=dict, help_text='Detailed report: par_categorie, par_produit, par_moyen_paiement, commandes.', verbose_name='JSON report')),
            ],
            options={
                'verbose_name': 'Cash register closure',
                'verbose_name_plural': 'Cash register closures',
                'ordering': ('-datetime_cloture',),
            },
        ),
        migrations.CreateModel(
            name='CompteComptable',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('numero_de_compte', models.CharField(help_text='Numero du compte PCG (ex: 7072000). / PCG account number (e.g. 7072000).', max_length=20, verbose_name='Account number')),
                ('libelle_du_compte', models.CharField(help_text='Libelle descriptif du compte (ex: Ventes de marchandises). / Descriptive account label (e.g. Merchandise sales).', max_length=200, verbose_name='Account label')),
                ('nature_du_compte', models.CharField(choices=[('VENTE', 'Sales (class 7)'), ('TVA', 'VAT (class 4457)'), ('TRESORERIE', 'Treasury (class 5)'), ('TIERS', 'Third-party (class 4)'), ('CHARGE', 'Expense (class 6)'), ('PRODUIT_EXCEPTIONNEL', 'Exceptional income (class 77)'), ('SPECIAL', 'Special')], help_text='Nature du compte : VENTE (classe 7), TVA (4457), TRESORERIE (5), etc. / Account nature: SALES (class 7), VAT (4457), TREASURY (5), etc.', max_length=30, verbose_name='Account nature')),
                ('taux_de_tva', models.DecimalField(blank=True, decimal_places=2, help_text='Taux de TVA en pourcentage (ex: 20.00, 10.00, 5.50). Renseigner uniquement pour les comptes VENTE et TVA. / VAT rate as percentage (e.g. 20.00, 10.00, 5.50). Only fill for SALES and VAT accounts.', max_digits=5, null=True, verbose_name='VAT rate (%)')),
                ('est_actif', models.BooleanField(default=True, help_text='Decocher pour desactiver le compte sans le supprimer. / Uncheck to deactivate the account without deleting it.', verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Accounting code',
                'verbose_name_plural': 'Accounting codes',
                'ordering': ['numero_de_compte'],
            },
        ),
        migrations.CreateModel(
            name='LaboutikConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taille_police_articles', models.SmallIntegerField(choices=[(18, '18'), (20, '20'), (22, '22'), (24, '24'), (26, '26'), (28, '28')], default=22, help_text="Taille de la police des noms d'articles sur l'interface caisse. / Font size for article names on the POS interface.", verbose_name='Article font size')),
                ('sunmi_app_id', models.CharField(blank=True, help_text="Identifiant de l'application Sunmi Cloud (stocke chiffre). / Sunmi Cloud application ID (stored encrypted).", max_length=200, null=True, verbose_name='Sunmi App ID (encrypted)')),
                ('sunmi_app_key', models.CharField(blank=True, help_text="Cle de l'application Sunmi Cloud (stockee chiffree). / Sunmi Cloud application key (stored encrypted).", max_length=200, null=True, verbose_name='Sunmi App Key (encrypted)')),
                ('hmac_key', models.CharField(blank=True, help_text="Cle HMAC pour le chainage d'integrite des donnees d'encaissement. Generee automatiquement, stockee chiffree Fernet. / HMAC key for POS data integrity chaining. Auto-generated, Fernet-encrypted.", max_length=200, null=True, verbose_name='HMAC key (encrypted)')),
                ('fond_de_caisse', models.IntegerField(default=0, help_text='Montant initial du tiroir-caisse en centimes. / Initial cash drawer amount in cents.', verbose_name='Cash float (cents)')),
                ('rapport_emails', models.JSONField(blank=True, default=list, help_text="Liste d'adresses email pour l'envoi automatique des rapports. / List of email addresses for automatic report sending.", verbose_name='Report email recipients')),
                ('rapport_periodicite', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='daily', help_text="Frequence d'envoi automatique des rapports comptables. / Automatic accounting report sending frequency.", max_length=10, verbose_name='Report frequency')),
                ('pied_ticket', models.TextField(blank=True, default='', help_text='Texte libre imprime en bas de chaque ticket de vente. / Custom text printed at the bottom of every receipt.', verbose_name='Receipt footer text')),
                ('total_perpetuel', models.IntegerField(default=0, help_text='Total cumule de toutes les clotures depuis la mise en service. Ne doit jamais etre remis a zero. / Cumulative total of all closures since first use. Must never be reset to zero.', verbose_name='Perpetual total (cents)')),
                ('compteur_tickets', models.PositiveIntegerField(default=0, help_text='Compteur sequentiel de tickets de vente. Incremente automatiquement a chaque impression. / Sequential receipt counter. Auto-incremented on each print.', verbose_name='Receipt counter')),
                ('mode_ecole', models.BooleanField(default=False, help_text='Active le mode ecole. Les ventes sont marquees comme fictives et exclues des rapports de production. / Enables training mode. Sales are marked as fictitious and excluded from production reports.', verbose_name='Training mode')),
            ],
            options={
                'verbose_name': 'LaBoutik Configuration',
            },
        ),
        migrations.CreateModel(
            name='PointDeVente',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Point of sale name. Must be unique.', max_length=200, unique=True, verbose_name='Name')),
                ('icon', models.CharField(blank=True, help_text='Icon name (e.g. Bootstrap Icons class).', max_length=50, null=True, verbose_name='Icon')),
                ('comportement', models.CharField(choices=[('D', 'Direct'), ('A', 'Memberships'), ('C', 'Cashless'), ('T', 'Ticketing'), ('V', 'Advanced'), ('I', 'Connected tap')], default='D', help_text='Determines how articles are loaded. Direct: M2M only. Memberships: auto-loads membership products. Cashless: auto-loads top-ups. Ticketing: builds from future events. Advanced: restaurant order mode.', max_length=1, verbose_name='POS type')),
                ('service_direct', models.BooleanField(default=True, help_text='If checked, orders are served immediately (no table service).', verbose_name='Direct service')),
                ('afficher_les_prix', models.BooleanField(default=True, help_text='Display prices on the POS interface.', verbose_name='Show prices')),
                ('accepte_especes', models.BooleanField(default=True, verbose_name='Accepts cash')),
                ('accepte_carte_bancaire', models.BooleanField(default=True, verbose_name='Accepts credit card')),
                ('accepte_cheque', models.BooleanField(default=False, verbose_name='Accepts check')),
                ('accepte_commandes', models.BooleanField(default=False, help_text='Enable table order management for this point of sale.', verbose_name='Accepts orders')),
                ('poid_liste', models.SmallIntegerField(default=0, help_text='Lower values are displayed first.', verbose_name='Display order')),
                ('hidden', models.BooleanField(default=False, help_text='Hide this point of sale from the selection screen.', verbose_name='Hidden')),
                ('categories', models.ManyToManyField(blank=True, help_text='Product categories available at this point of sale.', related_name='points_de_vente', to='BaseBillet.categorieproduct', verbose_name='Categories')),
            ],
            options={
                'verbose_name': 'Point of sale',
                'verbose_name_plural': 'Points of sale',
                'ordering': ('poid_liste', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Printer name (e.g. Kitchen, Bar, Main).', max_length=100, verbose_name='Name')),
                ('printer_type', models.CharField(choices=[('SC', 'Sunmi Cloud'), ('SI', 'Sunmi Inner'), ('LN', 'Sunmi LAN'), ('MK', 'Mock (console)')], default='SC', help_text='Sunmi Cloud: remote printer via HTTPS. Sunmi Inner: built-in printer on Sunmi tablet via WebSocket. Sunmi LAN: direct printing on local network (same subnet).', max_length=2, verbose_name='Printer type')),
                ('dots_per_line', models.SmallIntegerField(default=576, help_text='Number of dots per line. 576 for 80mm NT31x (kitchen cloud), 384 for 58mm NT21x, 240 for 57mm.', verbose_name='Dots per line')),
                ('sunmi_serial_number', models.CharField(blank=True, help_text='Serial number (SN) of the Sunmi Cloud printer. Not needed for Sunmi Inner.', max_length=100, null=True, verbose_name='Sunmi serial number')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address for LAN printing (same subnet). Not needed for Cloud or Inner.', null=True, verbose_name='IP address')),
                ('active', models.BooleanField(default=True, help_text='Uncheck to disable printing on this printer.', verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Printer',
                'verbose_name_plural': 'Printers',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Table name or number (e.g. Table 1, Bar 3).', max_length=200, unique=True, verbose_name='Name')),
                ('poids', models.SmallIntegerField(default=0, help_text='Lower values are displayed first.', verbose_name='Display order')),
                ('statut', models.CharField(choices=[('L', 'Free'), ('O', 'Occupied'), ('S', 'Served')], default='L', max_length=1, verbose_name='Status')),
                ('ephemere', models.BooleanField(default=False, help_text='Temporary table created for a single service.', verbose_name='Temporary')),
                ('archive', models.BooleanField(default=False, verbose_name='Archived')),
                ('position_top', models.IntegerField(blank=True, help_text='Vertical position in pixels on the floor plan.', null=True, verbose_name='Top position')),
                ('position_left', models.IntegerField(blank=True, help_text='Horizontal position in pixels on the floor plan.', null=True, verbose_name='Left position')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='laboutik.categorietable', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
                'ordering': ('poids', 'name'),
            },
        ),
        migrations.CreateModel(
            name='SortieCaisse',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Withdrawal date')),
                ('montant_total', models.IntegerField(help_text='Montant total retire en centimes. Recalcule cote serveur. / Total withdrawn amount in cents. Recalculated server-side.', verbose_name='Total amount (cents)')),
                ('ventilation', models.JSONField(default=dict, help_text='Ventilation par coupure. Cle = valeur en centimes, valeur = quantite. / Denomination breakdown. Key = value in cents, value = quantity.', verbose_name='Denomination breakdown')),
                ('note', models.TextField(blank=True, default='', help_text="Note libre sur le retrait d'especes. / Optional note about the cash withdrawal.", verbose_name='Note')),
                ('operateur', models.ForeignKey(blank=True, help_text="Caissier qui a effectue le retrait d'especes. / Cashier who performed the cash withdrawal.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sorties_caisse', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
                ('point_de_vente', models.ForeignKey(help_text="Point de vente depuis lequel le retrait d'especes est effectue. / Point of sale from which cash is withdrawn.", on_delete=django.db.models.deletion.PROTECT, related_name='sorties_caisse', to='laboutik.pointdevente', verbose_name='Point of sale')),
            ],
            options={
                'verbose_name': 'Cash withdrawal',
                'verbose_name_plural': 'Cash withdrawals',
                'ordering': ('-datetime',),
            },
        ),
        migrations.AddField(
            model_name='pointdevente',
            name='printer',
            field=models.ForeignKey(blank=True, help_text='Printer used for sale tickets at this point of sale.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_de_vente', to='laboutik.printer', verbose_name='Ticket printer'),
        ),
        migrations.AddField(
            model_name='pointdevente',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='Products available at this point of sale.', related_name='points_de_vente', to='BaseBillet.product', verbose_name='Products'),
        ),
        migrations.CreateModel(
            name='MappingMoyenDePaiement',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('moyen_de_paiement', models.CharField(help_text='Code du moyen de paiement (ex: CA = especes, CC = carte bancaire, CH = cheque). Doit correspondre aux codes PaymentMethod. / Payment method code (e.g. CA = cash, CC = credit card, CH = check). Must match PaymentMethod codes.', max_length=10, unique=True, verbose_name='Payment method code')),
                ('libelle_moyen', models.CharField(help_text='Libelle lisible (ex: Especes, Carte bancaire, Cheque). / Readable label (e.g. Cash, Credit card, Check).', max_length=100, verbose_name='Payment method label')),
                ('compte_de_tresorerie', models.ForeignKey(blank=True, help_text="Compte de tresorerie PCG associe (ex: 5311000 pour especes). Laisser vide pour ignorer ce moyen dans l'export comptable (ex: paiements NFC cashless, deja encaisses a la recharge). / PCG treasury account (e.g. 5311000 for cash). Leave blank to ignore this method in accounting export (e.g. NFC cashless payments, already collected at top-up).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moyens_de_paiement', to='laboutik.comptecomptable', verbose_name='Treasury account')),
            ],
            options={
                'verbose_name': 'Payment method mapping',
                'verbose_name_plural': 'Payment method mappings',
                'ordering': ['moyen_de_paiement'],
            },
        ),
        migrations.CreateModel(
            name='JournalOperation',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('type_operation', models.CharField(choices=[('ARCHIVAGE', 'Archiving'), ('VERIFICATION', 'Verification'), ('EXPORT_FISCAL', 'Fiscal export')], help_text="Type d'operation technique (archivage, verification, export fiscal). / Type of technical operation (archiving, verification, fiscal export).", max_length=20, verbose_name='Operation type')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Operation date')),
                ('details', models.JSONField(default=dict, help_text="Details de l'operation au format JSON. / Operation details in JSON format.", verbose_name='Details')),
                ('hmac_hash', models.CharField(blank=True, default='', help_text="Hash HMAC-SHA256 pour la verification d'integrite. / HMAC-SHA256 hash for integrity verification.", max_length=64, verbose_name='HMAC hash')),
                ('operateur', models.ForeignKey(blank=True, help_text="Utilisateur qui a declenche l'operation technique. / User who triggered the technical operation.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_journal', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
            ],
            options={
                'verbose_name': 'Operation log',
                'verbose_name_plural': 'Operation logs',
                'ordering': ('datetime',),
            },
        ),
        migrations.CreateModel(
            name='ImpressionLog',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Print datetime')),
                ('uuid_transaction', models.UUIDField(blank=True, db_index=True, help_text="Identifiant de transaction pour regrouper les lignes d'un meme ticket. / Transaction identifier to group lines of the same receipt.", null=True, verbose_name='Transaction UUID')),
                ('type_justificatif', models.CharField(choices=[('VENTE', 'Sale receipt'), ('CLOT', 'Closure report'), ('COMM', 'Order ticket'), ('BILL', 'Event ticket')], default='VENTE', help_text='Type de justificatif imprime : VENTE, CLOT, COMM ou BILL. / Type of printed receipt: VENTE, CLOT, COMM or BILL.', max_length=10, verbose_name='Receipt type')),
                ('is_duplicata', models.BooleanField(default=False, help_text='Cocher si cette impression est un duplicata (re-impression). / Check if this print is a duplicate (re-print).', verbose_name='Duplicate')),
                ('format_emission', models.CharField(choices=[('P', 'Paper'), ('E', 'Electronic')], default='P', help_text='P = papier (imprimante thermique), E = electronique (email/PDF). / P = paper (thermal printer), E = electronic (email/PDF).', max_length=1, verbose_name='Emission format')),
                ('cloture', models.ForeignKey(blank=True, help_text='Cloture de caisse concernee par cette impression. Null pour les tickets de vente et billets. / Cash register closure for this print. Null for sale tickets and event tickets.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='impressions', to='laboutik.cloturecaisse', verbose_name='Closure')),
                ('ligne_article', models.ForeignKey(blank=True, help_text="Ligne d'article concernee par cette impression. Null pour les clotures et billets. / Article line for this print. Null for closures and tickets.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='impressions', to='BaseBillet.lignearticle', verbose_name='Article line')),
                ('operateur', models.ForeignKey(blank=True, help_text="Caissier connecte au moment de l'impression. / Cashier who triggered this print.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impressions', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
                ('printer', models.ForeignKey(blank=True, help_text='Imprimante physique utilisee pour cette impression. Null pour les emissions electroniques. / Physical printer used for this print. Null for electronic receipts.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impressions', to='laboutik.printer', verbose_name='Printer')),
            ],
            options={
                'verbose_name': 'Print log',
                'verbose_name_plural': 'Print logs',
                'ordering': ('-datetime',),
            },
        ),
        migrations.CreateModel(
            name='HistoriqueFondDeCaisse',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Modification date')),
                ('ancien_montant', models.IntegerField(help_text='Ancien montant du fond de caisse en centimes. / Previous cash float amount in cents.', verbose_name='Previous amount (cents)')),
                ('nouveau_montant', models.IntegerField(help_text='Nouveau montant du fond de caisse en centimes. / New cash float amount in cents.', verbose_name='New amount (cents)')),
                ('raison', models.TextField(blank=True, default='', help_text='Raison du changement de fond de caisse. / Reason for the cash float change.', verbose_name='Reason')),
                ('operateur', models.ForeignKey(blank=True, help_text='Utilisateur qui a modifie le fond de caisse. / User who modified the cash float.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique_fond_de_caisse', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
                ('point_de_vente', models.ForeignKey(blank=True, help_text='Point de vente dont le fond de caisse a ete modifie. / Point of sale whose cash float was modified.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique_fond_de_caisse', to='laboutik.pointdevente', verbose_name='Point of sale')),
            ],
            options={
                'verbose_name': 'Cash float history',
                'verbose_name_plural': 'Cash float histories',
                'ordering': ('-datetime',),
            },
        ),
        migrations.CreateModel(
            name='CorrectionPaiement',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('ancien_moyen', models.CharField(help_text='Code du moyen de paiement avant correction (ex: CA, CC, CH). / Payment method code before correction.', max_length=10, verbose_name='Previous payment method')),
                ('nouveau_moyen', models.CharField(help_text='Code du moyen de paiement apres correction. / Payment method code after correction.', max_length=10, verbose_name='New payment method')),
                ('raison', models.TextField(help_text='Raison de la correction. Obligatoire pour la tracabilite. / Correction reason. Mandatory for traceability.', verbose_name='Reason')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Correction date')),
                ('ligne_article', models.ForeignKey(help_text="Ligne d'article dont le moyen de paiement a ete corrige. / Article line whose payment method was corrected.", on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='BaseBillet.lignearticle', verbose_name='Article line')),
                ('operateur', models.ForeignKey(blank=True, help_text='Caissier qui a effectue la correction. / Cashier who performed the correction.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections_paiement', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
            ],
            options={
                'verbose_name': 'Payment correction',
                'verbose_name_plural': 'Payment corrections',
                'ordering': ('-datetime',),
            },
        ),
        migrations.CreateModel(
            name='CommandeSauvegarde',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('service', models.UUIDField(blank=True, help_text='Service session identifier (UUID). Groups orders by work period.', null=True, verbose_name='Service')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('statut', models.CharField(choices=[('OP', 'Open'), ('SV', 'Served'), ('PA', 'Paid'), ('AN', 'Cancelled')], default='OP', max_length=2, verbose_name='Status')),
                ('commentaire', models.TextField(blank=True, default='', help_text='Kitchen notes or special requests.', verbose_name='Comment')),
                ('archive', models.BooleanField(default=False, verbose_name='Archived')),
                ('responsable', models.ForeignKey(blank=True, help_text='Cashier or waiter who created this order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_sauvegardees', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
                ('table', models.ForeignKey(blank=True, help_text='Restaurant table for this order. Null for takeaway.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='laboutik.table', verbose_name='Table')),
            ],
            options={
                'verbose_name': 'Saved order',
                'verbose_name_plural': 'Saved orders',
                'ordering': ('-datetime',),
            },
        ),
        migrations.AddField(
            model_name='cloturecaisse',
            name='point_de_vente',
            field=models.ForeignKey(blank=True, help_text='Point de vente depuis lequel la cloture a ete declenchee (informatif). La cloture couvre tout le tenant. / POS from which closure was triggered (informational). Closure covers the entire tenant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clotures', to='laboutik.pointdevente', verbose_name='Triggered from POS'),
        ),
        migrations.AddField(
            model_name='cloturecaisse',
            name='responsable',
            field=models.ForeignKey(blank=True, help_text='Cashier who performed the closure.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clotures_caisse', to=settings.AUTH_USER_MODEL, verbose_name='Operator'),
        ),
        migrations.CreateModel(
            name='CartePrimaire',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('edit_mode', models.BooleanField(default=False, help_text='Allow this operator to modify products and prices from the POS interface.', verbose_name='Edit mode')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('carte', models.OneToOneField(help_text='Physical NFC card associated with this primary card.', on_delete=django.db.models.deletion.CASCADE, related_name='carte_primaire', to='QrcodeCashless.cartecashless', verbose_name='NFC card')),
                ('points_de_vente', models.ManyToManyField(blank=True, help_text='Points of sale this operator can access.', related_name='cartes_primaires', to='laboutik.pointdevente', verbose_name='Points of sale')),
            ],
            options={
                'verbose_name': 'Primary card',
                'verbose_name_plural': 'Primary cards',
            },
        ),
        migrations.CreateModel(
            name='ArticleCommandeSauvegarde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.SmallIntegerField(default=1, verbose_name='Quantity')),
                ('reste_a_payer', models.IntegerField(default=0, help_text='Remaining amount in cents. 0 = not yet billed.', verbose_name='Remaining to pay (cents)')),
                ('reste_a_servir', models.SmallIntegerField(default=0, verbose_name='Remaining to serve')),
                ('statut', models.CharField(choices=[('AT', 'Waiting'), ('EC', 'In progress'), ('PR', 'Ready'), ('SV', 'Served'), ('AN', 'Cancelled')], default='AT', max_length=2, verbose_name='Status')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='laboutik.commandesauvegarde', verbose_name='Order')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles_commande', to='BaseBillet.price', verbose_name='Price')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles_commande', to='BaseBillet.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Order article',
                'verbose_name_plural': 'Order articles',
                'ordering': ('commande', 'product__name'),
            },
        ),
    ]
