# Generated by Django 4.2.28 on 2026-03-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboutik', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointdevente',
            name='comportement',
            field=models.CharField(choices=[('D', 'Direct'), ('K', 'Kiosk'), ('C', 'Cashless'), ('A', 'Membership')], default='D', help_text='Operating mode: Direct (standard sale), Kiosk (self-service), Cashless (NFC only), Membership (subscriptions and memberships).', max_length=1, verbose_name='Behavior'),
        ),
    ]
