# Generated by Django 4.2.30 on 2026-07-14 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('laboutik', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom')),
                ('stripe_id', models.CharField(blank=True, max_length=21, null=True, verbose_name='Identifiant Stripe')),
                ('is_primary_location', models.BooleanField(default=False, verbose_name='Location primaire')),
            ],
        ),
        migrations.RemoveField(
            model_name='pointdevente',
            name='printer',
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text="Nom de l'appareil, par exemple « Caisse bar 1 ».", max_length=200, null=True, verbose_name='Nom')),
                ('registration_code', models.CharField(blank=True, help_text='Code fourni par le TPE Stripe lors de son premier demarrage.', max_length=200, null=True, verbose_name="Code d'enregistrement du lecteur")),
                ('stripe_id', models.CharField(blank=True, max_length=21, null=True, verbose_name='Identifiant Stripe')),
                ('type', models.CharField(blank=True, choices=[('', 'Pas de TPE'), ('W', 'bbpos_wisepos_e')], default='', max_length=2, verbose_name='Type de TPE')),
                ('archived', models.BooleanField(default=False, verbose_name='Archive')),
                ('printer', models.ForeignKey(blank=True, help_text="Imprimante utilisee par ce terminal. Laisser vide si l'appareil n'imprime pas.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminaux', to='laboutik.printer', verbose_name='Imprimante')),
                ('term_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminal', to=settings.AUTH_USER_MODEL, verbose_name='Compte du terminal')),
            ],
            options={
                'verbose_name': 'Terminal',
                'verbose_name_plural': 'Terminaux',
                'ordering': ('name',),
            },
        ),
    ]
