# Generated by Django 4.2.28 on 2026-03-12 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BaseBillet', '0204_price_asset_product_besoin_tag_id_and_more'),
        ('laboutik', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandeSauvegarde',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('service', models.UUIDField(blank=True, help_text='Service session identifier (UUID). Groups orders by work period.', null=True, verbose_name='Service')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('statut', models.CharField(choices=[('OP', 'Open'), ('SV', 'Served'), ('PA', 'Paid'), ('AN', 'Cancelled')], default='OP', max_length=2, verbose_name='Status')),
                ('commentaire', models.TextField(blank=True, default='', help_text='Kitchen notes or special requests.', verbose_name='Comment')),
                ('archive', models.BooleanField(default=False, verbose_name='Archived')),
                ('responsable', models.ForeignKey(blank=True, help_text='Cashier or waiter who created this order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_sauvegardees', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
                ('table', models.ForeignKey(blank=True, help_text='Restaurant table for this order. Null for takeaway.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='laboutik.table', verbose_name='Table')),
            ],
            options={
                'verbose_name': 'Saved order',
                'verbose_name_plural': 'Saved orders',
                'ordering': ('-datetime',),
            },
        ),
        migrations.CreateModel(
            name='ArticleCommandeSauvegarde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.SmallIntegerField(default=1, verbose_name='Quantity')),
                ('reste_a_payer', models.IntegerField(default=0, help_text='Remaining amount in cents. 0 = not yet billed.', verbose_name='Remaining to pay (cents)')),
                ('reste_a_servir', models.SmallIntegerField(default=0, verbose_name='Remaining to serve')),
                ('statut', models.CharField(choices=[('AT', 'Waiting'), ('EC', 'In progress'), ('PR', 'Ready'), ('SV', 'Served'), ('AN', 'Cancelled')], default='AT', max_length=2, verbose_name='Status')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='laboutik.commandesauvegarde', verbose_name='Order')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles_commande', to='BaseBillet.price', verbose_name='Price')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles_commande', to='BaseBillet.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Order article',
                'verbose_name_plural': 'Order articles',
                'ordering': ('commande', 'product__name'),
            },
        ),
    ]
