# Generated by Django 4.2.30 on 2026-07-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboutik', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboutikconfiguration',
            name='mode_ecole',
            field=models.BooleanField(default=False, help_text="DESACTIVE — chantier de conformite LNE en cours. Ce reglage n'a aucun effet et n'est plus modifiable depuis l'administration. / DISABLED — LNE compliance work in progress. This setting has no effect and is no longer editable from the administration.", verbose_name='Training mode'),
        ),
    ]
