# Generated by Django 4.2.30 on 2026-09-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboutik', '0002_alter_laboutikconfiguration_mode_ecole'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloturecaisse',
            name='total_cheque',
            field=models.IntegerField(default=0, help_text='Total check amount in cents.', verbose_name='Check total (cents)'),
        ),
        migrations.AlterField(
            model_name='cloturecaisse',
            name='total_general',
            field=models.IntegerField(default=0, help_text='Grand total in cents (cash + card + cashless + check).', verbose_name='Grand total (cents)'),
        ),
    ]
