# Generated by Django 4.2.28 on 2026-03-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboutik', '0002_add_adhesion_comportement'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboutikConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taille_police_articles', models.SmallIntegerField(choices=[(18, '18'), (20, '20'), (22, '22'), (24, '24'), (26, '26'), (28, '28')], default=22, help_text="Taille de la police des noms d'articles sur l'interface caisse. / Font size for article names on the POS interface.", verbose_name='Article font size')),
            ],
            options={
                'verbose_name': 'LaBoutik Configuration',
            },
        ),
    ]
