# Generated by Django 4.2.28 on 2026-03-12 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('laboutik', '0002_commandesauvegarde_articlecommandesauvegarde'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClotureCaisse',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('datetime_ouverture', models.DateTimeField(help_text='Start of the service period covered by this closure.', verbose_name='Service start')),
                ('datetime_cloture', models.DateTimeField(auto_now_add=True, verbose_name='Closure datetime')),
                ('total_especes', models.IntegerField(default=0, help_text='Total cash amount in cents.', verbose_name='Cash total (cents)')),
                ('total_carte_bancaire', models.IntegerField(default=0, help_text='Total credit card amount in cents.', verbose_name='Credit card total (cents)')),
                ('total_cashless', models.IntegerField(default=0, help_text='Total cashless/NFC amount in cents.', verbose_name='Cashless total (cents)')),
                ('total_general', models.IntegerField(default=0, help_text='Grand total in cents (cash + card + cashless).', verbose_name='Grand total (cents)')),
                ('nombre_transactions', models.IntegerField(default=0, help_text='Number of LigneArticle records in this period.', verbose_name='Transaction count')),
                ('rapport_json', models.JSONField(blank=True, default=dict, help_text='Detailed report: par_categorie, par_produit, par_moyen_paiement, commandes.', verbose_name='JSON report')),
                ('point_de_vente', models.ForeignKey(help_text='Point of sale that triggered this closure.', on_delete=django.db.models.deletion.PROTECT, related_name='clotures', to='laboutik.pointdevente', verbose_name='Point of sale')),
                ('responsable', models.ForeignKey(blank=True, help_text='Cashier who performed the closure.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clotures_caisse', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
            ],
            options={
                'verbose_name': 'Cash register closure',
                'verbose_name_plural': 'Cash register closures',
                'ordering': ('-datetime_cloture',),
            },
        ),
    ]
