# Generated by Django 4.2.30 on 2026-07-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboutik', '0003_terminal_terminal_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminal',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archivé'),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='registration_code',
            field=models.CharField(blank=True, help_text='Code fourni par le TPE Stripe lors de son premier démarrage.', max_length=200, null=True, verbose_name="Code d'enregistrement du lecteur"),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=21, null=True, unique=True, verbose_name='Identifiant Stripe'),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='terminal_role',
            field=models.CharField(choices=[('LB', 'LaBoutik POS'), ('TI', 'Connected tap'), ('KI', 'Kiosk / self-service')], default='LB', help_text='Ce que cet appareil sait faire. Ne change plus une fois appairé.', max_length=2, verbose_name="Type d'appareil"),
        ),
    ]
