# Generated by Django 4.2.30 on 2026-09-10 11:23

from django.db import migrations


def dedupliquer(apps, schema_editor):
    Terminal = apps.get_model('laboutik', 'Terminal')
    vus = set()
    for obj in Terminal.objects.order_by('id'):
        if obj.name in vus:
            # stratégie au choix : suffixer, fusionner, supprimer...
            obj.name = f"{obj.name}-{obj.id}"
            obj.save(update_fields=['name'])
        else:
            vus.add(obj.name)

def reverse(apps, schema_editor):
    Terminal = apps.get_model('laboutik', 'Terminal')
    for obj in Terminal.objects.order_by('id'):
        suffixe = f"-{obj.id}"
        if obj.name.endswith(suffixe):
            obj.name = obj.name[:-len(suffixe)]
            obj.save(update_fields=['name'])

class Migration(migrations.Migration):

    dependencies = [
        ('laboutik', '0003_cloturecaisse_total_cheque_and_more'),
    ]

    operations = [
        migrations.RunPython(dedupliquer, reverse),
    ]
