# Generated by Django 4.2.30 on 2026-09-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboutik', '0004_auto_20260910_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminal',
            name='name',
            field=models.CharField(blank=True, help_text="Nom de l'appareil, par exemple « Caisse bar 1 ».", max_length=200, null=True, unique=True, verbose_name='Nom'),
        ),
    ]
