# Generated by Django 4.2.28 on 2026-03-24 20:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('laboutik', '0005_restaurer_types_pv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Printer name (e.g. Kitchen, Bar, Main).', max_length=100, verbose_name='Name')),
                ('printer_type', models.CharField(choices=[('SC', 'Sunmi Cloud'), ('SI', 'Sunmi Inner')], default='SC', help_text='Sunmi Cloud: remote printer via HTTPS. Sunmi Inner: built-in printer on Sunmi tablet via WebSocket.', max_length=2, verbose_name='Printer type')),
                ('paper_width', models.CharField(choices=[('80', '80mm (384 dots)'), ('57', '57mm (240 dots)')], default='80', help_text='Paper width. 80mm = 384 dots per line, 57mm = 240 dots.', max_length=2, verbose_name='Paper width')),
                ('sunmi_serial_number', models.CharField(blank=True, help_text='Serial number (SN) of the Sunmi Cloud printer. Not needed for Sunmi Inner.', max_length=100, null=True, verbose_name='Sunmi serial number')),
                ('active', models.BooleanField(default=True, help_text='Uncheck to disable printing on this printer.', verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Printer',
                'verbose_name_plural': 'Printers',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='laboutikconfiguration',
            name='sunmi_app_id',
            field=models.CharField(blank=True, help_text="Identifiant de l'application Sunmi Cloud (stocke chiffre). / Sunmi Cloud application ID (stored encrypted).", max_length=200, null=True, verbose_name='Sunmi App ID (encrypted)'),
        ),
        migrations.AddField(
            model_name='laboutikconfiguration',
            name='sunmi_app_key',
            field=models.CharField(blank=True, help_text="Cle de l'application Sunmi Cloud (stockee chiffree). / Sunmi Cloud application key (stored encrypted).", max_length=200, null=True, verbose_name='Sunmi App Key (encrypted)'),
        ),
        migrations.AddField(
            model_name='pointdevente',
            name='printer',
            field=models.ForeignKey(blank=True, help_text='Printer used for sale tickets at this point of sale.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_de_vente', to='laboutik.printer', verbose_name='Ticket printer'),
        ),
    ]
