# Generated by Django 4.2.30 on 2026-10-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboutik', '0006_icones_fontawesome_vers_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboutikconfiguration',
            name='show_membership_after_payment',
            field=models.BooleanField(default=False, verbose_name="Afficher les adhésions au retour d'un paiement"),
        ),
    ]
