# Generated by Django 4.2.28 on 2026-03-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboutik', '0006_printer_laboutikconfiguration_sunmi_app_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printer',
            name='paper_width',
        ),
        migrations.AddField(
            model_name='printer',
            name='dots_per_line',
            field=models.SmallIntegerField(default=576, help_text='Number of dots per line. 576 for 80mm NT31x (kitchen cloud), 384 for 58mm NT21x, 240 for 57mm.', verbose_name='Dots per line'),
        ),
        migrations.AddField(
            model_name='printer',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address for LAN printing (same subnet). Not needed for Cloud or Inner.', null=True, verbose_name='IP address'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='printer_type',
            field=models.CharField(choices=[('SC', 'Sunmi Cloud'), ('SI', 'Sunmi Inner'), ('LN', 'Sunmi LAN')], default='SC', help_text='Sunmi Cloud: remote printer via HTTPS. Sunmi Inner: built-in printer on Sunmi tablet via WebSocket. Sunmi LAN: direct printing on local network (same subnet).', max_length=2, verbose_name='Printer type'),
        ),
    ]
