# Generated by Django 4.2.30 on 2026-09-29 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0230_vente_reglement_montants_entiers'),
        ('laboutik', '0006_icones_fontawesome_vers_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandesauvegarde',
            name='vente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commandes_de_table', to='BaseBillet.vente', verbose_name='Vente'),
        ),
    ]
