# Generated by Django 4.2.28 on 2026-03-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboutik', '0007_remove_printer_paper_width_printer_dots_per_line_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='printer_type',
            field=models.CharField(choices=[('SC', 'Sunmi Cloud'), ('SI', 'Sunmi Inner'), ('LN', 'Sunmi LAN'), ('MK', 'Mock (console)')], default='SC', help_text='Sunmi Cloud: remote printer via HTTPS. Sunmi Inner: built-in printer on Sunmi tablet via WebSocket. Sunmi LAN: direct printing on local network (same subnet).', max_length=2, verbose_name='Printer type'),
        ),
    ]
