# Generated by Django 4.2.30 on 2026-10-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboutik', '0007_laboutikconfiguration_show_membership_after_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboutikconfiguration',
            name='show_membership_after_payment',
            field=models.BooleanField(default=False, help_text='Après un paiement via la caisse (en cashless), affiche les adhésions lié à la carte.', verbose_name="Afficher les adhésions au retour d'un paiement"),
        ),
    ]
