# Generated by Django 4.2.30 on 2026-10-02 20:26
"""
Migration de donnees : un seul compte par numero, avant la contrainte d'unicite (0009).
/ Data migration: one account per number, before the uniqueness constraint (0009).

LOCALISATION : laboutik/migrations/0008_dedoublonner_les_numeros_de_compte.py

Pour chaque numero porte par plusieurs comptes, on garde le premier par cle (`pk`).
Les categories de caisse et les correspondances des moyens de paiement des autres
comptes sont repointees sur lui, puis ces comptes sont supprimes. Le choix du compte
garde n'a pas d'autre effet : tous les liens finissent sur lui.
/ For each number held by several accounts, the first one by `pk` is kept. Links of
the other accounts are repointed to it, then those accounts are deleted.

DML seul : la contrainte (DDL) est dans la migration suivante (PIEGES 9.113).
/ DML only: the constraint (DDL) is in the next migration.
"""

from django.db import connection, migrations


def dedoublonner_les_numeros_de_compte(apps, schema_editor):
    """
    Garde un compte par numero et repointe les liens des doublons sur lui.
    / Keeps one account per number and repoints the duplicates' links to it.

    Les tables de `laboutik` n'existent pas dans le schema `public` : rien a faire.
    / laboutik tables do not exist in the public schema: nothing to do.
    """
    schema_courant = connection.schema_name
    if schema_courant == "public":
        return

    CompteComptable = apps.get_model("laboutik", "CompteComptable")
    MappingMoyenDePaiement = apps.get_model("laboutik", "MappingMoyenDePaiement")
    CategorieProduct = apps.get_model("BaseBillet", "CategorieProduct")

    compte_garde_par_numero = {}
    nombre_de_doublons_supprimes = 0

    tous_les_comptes = CompteComptable.objects.order_by("numero_de_compte", "pk")
    for compte in tous_les_comptes:
        numero = compte.numero_de_compte

        # Premier compte de ce numero : il est garde.
        # / First account with this number: it is kept.
        if numero not in compte_garde_par_numero:
            compte_garde_par_numero[numero] = compte
            continue

        # Un doublon : ses liens passent sur le compte garde, puis il est supprime.
        # / A duplicate: its links move to the kept account, then it is deleted.
        compte_garde = compte_garde_par_numero[numero]
        CategorieProduct.objects.filter(compte_comptable=compte).update(
            compte_comptable=compte_garde
        )
        MappingMoyenDePaiement.objects.filter(compte_de_tresorerie=compte).update(
            compte_de_tresorerie=compte_garde
        )
        compte.delete()
        nombre_de_doublons_supprimes += 1

    if nombre_de_doublons_supprimes:
        print(
            f"  -> [{schema_courant}] {nombre_de_doublons_supprimes} "
            f"compte(s) en double supprime(s)"
        )


class Migration(migrations.Migration):
    dependencies = [
        ("BaseBillet", "0231_product_consigne_remboursee"),
        ("laboutik", "0007_commandesauvegarde_vente"),
    ]

    operations = [
        migrations.RunPython(
            dedoublonner_les_numeros_de_compte,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
