# Generated by Django 4.2.30 on 2026-10-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboutik', '0008_dedoublonner_les_numeros_de_compte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comptecomptable',
            name='numero_de_compte',
            field=models.CharField(help_text='Numero du compte PCG (ex: 707000). / PCG account number (e.g. 707000).', max_length=20, unique=True, verbose_name='Account number'),
        ),
    ]
