# Generated by Django 4.2.28 on 2026-03-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboutik', '0008_alter_printer_printer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboutikconfiguration',
            name='fond_de_caisse',
            field=models.IntegerField(default=0, help_text='Montant initial du tiroir-caisse en centimes. / Initial cash drawer amount in cents.', verbose_name='Cash float (cents)'),
        ),
        migrations.AddField(
            model_name='laboutikconfiguration',
            name='hmac_key',
            field=models.CharField(blank=True, help_text="Cle HMAC pour le chainage d'integrite des donnees d'encaissement. Generee automatiquement, stockee chiffree Fernet. / HMAC key for POS data integrity chaining. Auto-generated, Fernet-encrypted.", max_length=200, null=True, verbose_name='HMAC key (encrypted)'),
        ),
        migrations.AddField(
            model_name='laboutikconfiguration',
            name='pied_ticket',
            field=models.TextField(blank=True, default='', help_text='Texte libre imprime en bas de chaque ticket de vente. / Custom text printed at the bottom of every receipt.', verbose_name='Receipt footer text'),
        ),
        migrations.AddField(
            model_name='laboutikconfiguration',
            name='rapport_emails',
            field=models.JSONField(blank=True, default=list, help_text="Liste d'adresses email pour l'envoi automatique des rapports. / List of email addresses for automatic report sending.", verbose_name='Report email recipients'),
        ),
        migrations.AddField(
            model_name='laboutikconfiguration',
            name='rapport_periodicite',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='daily', help_text="Frequence d'envoi automatique des rapports comptables. / Automatic accounting report sending frequency.", max_length=10, verbose_name='Report frequency'),
        ),
        migrations.AddField(
            model_name='laboutikconfiguration',
            name='total_perpetuel',
            field=models.IntegerField(default=0, help_text='Total cumule de toutes les clotures depuis la mise en service. Ne doit jamais etre remis a zero. / Cumulative total of all closures since first use. Must never be reset to zero.', verbose_name='Perpetual total (cents)'),
        ),
    ]
