# Generated by Django 4.2.30 on 2026-10-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboutik', '0008_alter_laboutikconfiguration_show_membership_after_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboutikconfiguration',
            name='taille_police_articles',
            field=models.SmallIntegerField(choices=[(18, '18'), (20, '20'), (22, '22'), (24, '24'), (26, '26'), (28, '28')], default=18, help_text="Taille de la police des noms d'articles sur l'interface caisse. / Font size for article names on the POS interface.", verbose_name='Article font size'),
        ),
    ]
