# Generated by Django 4.2.28 on 2026-03-30 09:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('laboutik', '0009_add_hmac_and_report_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloturecaisse',
            name='hash_lignes',
            field=models.CharField(blank=True, default='', help_text='SHA-256 des LigneArticle couvertes. Filet de securite. / SHA-256 of covered LigneArticle. Safety net.', max_length=64, verbose_name='Lines integrity hash'),
        ),
        migrations.AddField(
            model_name='cloturecaisse',
            name='niveau',
            field=models.CharField(choices=[('J', 'Daily'), ('M', 'Monthly'), ('A', 'Annual')], default='J', help_text='J = journaliere (caissier), M = mensuelle (auto), A = annuelle (auto). / J = daily (cashier), M = monthly (auto), A = annual (auto).', max_length=1, verbose_name='Closure level'),
        ),
        migrations.AddField(
            model_name='cloturecaisse',
            name='numero_sequentiel',
            field=models.PositiveIntegerField(default=0, help_text='Numero sequentiel par point de vente et par niveau. Sans trou. / Sequential number per POS and per level. No gap.', verbose_name='Sequential number'),
        ),
        migrations.AddField(
            model_name='cloturecaisse',
            name='total_perpetuel',
            field=models.IntegerField(default=0, help_text='Total cumule depuis la mise en service, snapshot au moment de cette cloture. / Cumulative total since first use, snapshot at this closure time.', verbose_name='Perpetual total (cents)'),
        ),
        migrations.AlterField(
            model_name='cloturecaisse',
            name='datetime_cloture',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Moment of the closure. Set explicitly, not auto_now_add.', verbose_name='Closure datetime'),
        ),
    ]
