# Generated by Django 4.2.30 on 2026-10-02 20:27
"""
Migration de donnees : charge le plan comptable par defaut dans tout lieu qui n'a
AUCUN compte.
/ Data migration: loads the default chart of accounts into every venue with NO account.

LOCALISATION : laboutik/migrations/0010_charger_le_plan_comptable_par_defaut.py

Elle couvre aussi les lieux crees plus tard : `Client.auto_create_schema = True`
rejoue toutes les migrations dans un schema neuf. Aucun autre crochet n'est utile.
/ It also covers venues created later: auto_create_schema replays every migration.

C'est la version « modeles historiques » (`apps.get_model`) du chargeur de
`laboutik/plan_comptable.py`. Elle n'importe que les DONNEES du plan
(`laboutik/plan_comptable_par_defaut.py`), jamais un modele vivant. Le lieu n'ayant
aucun compte, tout est cree d'un coup ; une correspondance de moyen deja presente
n'est pas touchee.
/ Historical-models version of the loader. Imports only the plan DATA.
"""

from django.db import connection, migrations

from laboutik.plan_comptable_par_defaut import (
    COMPTE_DES_CATEGORIES_CONNUES,
    COMPTES_DU_PLAN_PAR_DEFAUT,
    CORRESPONDANCES_DES_MOYENS_PAR_DEFAUT,
)


def charger_le_plan_si_aucun_compte(apps, schema_editor):
    """
    Charge le plan par defaut si le lieu n'a aucun compte. Sinon ne fait rien.
    / Loads the default plan if the venue has no account. Else does nothing.

    Les tables de `laboutik` n'existent pas dans le schema `public` : rien a faire.
    / laboutik tables do not exist in the public schema: nothing to do.
    """
    schema_courant = connection.schema_name
    if schema_courant == "public":
        return

    CompteComptable = apps.get_model("laboutik", "CompteComptable")
    MappingMoyenDePaiement = apps.get_model("laboutik", "MappingMoyenDePaiement")
    CategorieProduct = apps.get_model("BaseBillet", "CategorieProduct")

    le_lieu_a_deja_un_compte = CompteComptable.objects.exists()
    if le_lieu_a_deja_un_compte:
        return

    # 1. Les comptes / The accounts
    compte_par_numero = {}
    for entree in COMPTES_DU_PLAN_PAR_DEFAUT:
        compte_par_numero[entree["numero"]] = CompteComptable.objects.create(
            numero_de_compte=entree["numero"],
            libelle_du_compte=entree["libelle"],
            nature_du_compte=entree["nature"],
            taux_de_tva=entree["taux_de_tva"],
        )

    # 2. Les correspondances des moyens, seulement si le moyen n'en a aucune
    # / 2. The payment method mappings, only if the method has none
    for correspondance in CORRESPONDANCES_DES_MOYENS_PAR_DEFAUT:
        le_moyen_a_deja_une_correspondance = MappingMoyenDePaiement.objects.filter(
            moyen_de_paiement=correspondance["moyen"]
        ).exists()
        if le_moyen_a_deja_une_correspondance:
            continue
        MappingMoyenDePaiement.objects.create(
            moyen_de_paiement=correspondance["moyen"],
            libelle_moyen=correspondance["libelle"],
            compte_de_tresorerie=compte_par_numero[correspondance["numero"]],
        )

    # 3. Les categories connues, si elles existent et n'ont pas de compte
    # / 3. The known categories, if they exist and have no account
    for categorie_connue in COMPTE_DES_CATEGORIES_CONNUES:
        compte_de_la_categorie = compte_par_numero[categorie_connue["numero"]]
        categories_sans_compte = CategorieProduct.objects.filter(
            name=categorie_connue["nom_de_la_categorie"],
            compte_comptable__isnull=True,
        )
        for categorie in categories_sans_compte:
            categorie.compte_comptable = compte_de_la_categorie
            categorie.save(update_fields=["compte_comptable"])

    print(
        f"  -> [{schema_courant}] plan comptable par defaut charge "
        f"({len(COMPTES_DU_PLAN_PAR_DEFAUT)} comptes)"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("BaseBillet", "0231_product_consigne_remboursee"),
        ("laboutik", "0009_comptecomptable_numero_de_compte_unique"),
    ]

    operations = [
        migrations.RunPython(
            charger_le_plan_si_aucun_compte,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
