# Generated by Django 4.2.30 on 2026-10-02 21:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('laboutik', '0010_charger_le_plan_comptable_par_defaut'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointdevente',
            name='code_journal',
            field=models.CharField(blank=True, default='', help_text='Code du journal comptable de ce point de vente, 10 lettres majuscules au plus (ex. : BAR). Vide : dérivé du nom du point de vente.', max_length=10, validators=[django.core.validators.RegexValidator(message='Lettres majuscules seules, sans accent (ex. : BAR).', regex='^[A-Z]+$')], verbose_name='Code journal'),
        ),
        migrations.CreateModel(
            name='MappingMonnaie',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('asset_uuid', models.UUIDField(help_text='Identifiant de la monnaie (fedow_core ou ancien Fedow).', unique=True, verbose_name='Monnaie (uuid)')),
                ('compte_de_tresorerie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monnaies', to='laboutik.comptecomptable', verbose_name='Compte de la monnaie')),
            ],
            options={
                'verbose_name': "Compte d'une monnaie",
                'verbose_name_plural': 'Comptes des monnaies',
                'ordering': ['asset_uuid'],
            },
        ),
    ]
