# Generated by Django 4.2.28 on 2026-03-30 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboutik', '0010_cloture_enrichie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloturecaisse',
            name='numero_sequentiel',
            field=models.PositiveIntegerField(default=0, help_text='Numero sequentiel par niveau de cloture. Sans trou. Global au tenant. / Sequential number per closure level. No gap. Global to tenant.', verbose_name='Sequential number'),
        ),
        migrations.AlterField(
            model_name='cloturecaisse',
            name='point_de_vente',
            field=models.ForeignKey(blank=True, help_text='Point de vente depuis lequel la cloture a ete declenchee (informatif). La cloture couvre tout le tenant. / POS from which closure was triggered (informational). Closure covers the entire tenant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clotures', to='laboutik.pointdevente', verbose_name='Triggered from POS'),
        ),
    ]
