# Generated by Django 4.2.28 on 2026-03-30 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BaseBillet', '0209_add_point_de_vente_on_lignearticle'),
        ('laboutik', '0011_cloture_pv_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboutikconfiguration',
            name='compteur_tickets',
            field=models.PositiveIntegerField(default=0, help_text='Compteur sequentiel de tickets de vente. Incremente automatiquement a chaque impression. / Sequential receipt counter. Auto-incremented on each print.', verbose_name='Receipt counter'),
        ),
        migrations.CreateModel(
            name='ImpressionLog',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Print datetime')),
                ('uuid_transaction', models.UUIDField(blank=True, help_text="Identifiant de transaction pour regrouper les lignes d'un meme ticket. / Transaction identifier to group lines of the same receipt.", null=True, verbose_name='Transaction UUID')),
                ('type_justificatif', models.CharField(choices=[('VENTE', 'Sale receipt'), ('CLOT', 'Closure report'), ('COMM', 'Order ticket'), ('BILL', 'Event ticket')], default='VENTE', help_text='Type de justificatif imprime : VENTE, CLOT, COMM ou BILL. / Type of printed receipt: VENTE, CLOT, COMM or BILL.', max_length=10, verbose_name='Receipt type')),
                ('is_duplicata', models.BooleanField(default=False, help_text='Cocher si cette impression est un duplicata (re-impression). / Check if this print is a duplicate (re-print).', verbose_name='Duplicate')),
                ('format_emission', models.CharField(choices=[('P', 'Paper'), ('E', 'Electronic')], default='P', help_text='P = papier (imprimante thermique), E = electronique (email/PDF). / P = paper (thermal printer), E = electronic (email/PDF).', max_length=1, verbose_name='Emission format')),
                ('cloture', models.ForeignKey(blank=True, help_text='Cloture de caisse concernee par cette impression. Null pour les tickets de vente et billets. / Cash register closure for this print. Null for sale tickets and event tickets.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='impressions', to='laboutik.cloturecaisse', verbose_name='Closure')),
                ('ligne_article', models.ForeignKey(blank=True, help_text="Ligne d'article concernee par cette impression. Null pour les clotures et billets. / Article line for this print. Null for closures and tickets.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='impressions', to='BaseBillet.lignearticle', verbose_name='Article line')),
                ('operateur', models.ForeignKey(blank=True, help_text='Cashier who triggered this print.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impressions', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
                ('printer', models.ForeignKey(blank=True, help_text='Imprimante physique utilisee pour cette impression. Null pour les emissions electroniques. / Physical printer used for this print. Null for electronic receipts.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impressions', to='laboutik.printer', verbose_name='Printer')),
            ],
            options={
                'verbose_name': 'Print log',
                'verbose_name_plural': 'Print logs',
                'ordering': ('-datetime',),
            },
        ),
    ]
