# Generated by Django 4.2.28 on 2026-03-30 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('laboutik', '0012_impression_log_compteur_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impressionlog',
            name='operateur',
            field=models.ForeignKey(blank=True, help_text="Caissier connecte au moment de l'impression. / Cashier who triggered this print.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impressions', to=settings.AUTH_USER_MODEL, verbose_name='Operator'),
        ),
        migrations.AlterField(
            model_name='impressionlog',
            name='uuid_transaction',
            field=models.UUIDField(blank=True, db_index=True, help_text="Identifiant de transaction pour regrouper les lignes d'un meme ticket. / Transaction identifier to group lines of the same receipt.", null=True, verbose_name='Transaction UUID'),
        ),
    ]
