# Generated by Django 4.2.29 on 2026-03-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboutik', '0013_impression_log_uuid_transaction_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboutikconfiguration',
            name='mode_ecole',
            field=models.BooleanField(default=False, help_text='Active le mode ecole. Les ventes sont marquees comme fictives et exclues des rapports de production. / Enables training mode. Sales are marked as fictitious and excluded from production reports.', verbose_name='Training mode'),
        ),
    ]
