# Generated by Django 4.2.28 on 2026-04-01 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BaseBillet', '0210_prix_achat_product'),
        ('laboutik', '0014_mode_ecole'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortieCaisse',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Withdrawal date')),
                ('montant_total', models.IntegerField(help_text='Montant total retire en centimes. Recalcule cote serveur. / Total withdrawn amount in cents. Recalculated server-side.', verbose_name='Total amount (cents)')),
                ('ventilation', models.JSONField(default=dict, help_text='Ventilation par coupure. Cle = valeur en centimes, valeur = quantite. / Denomination breakdown. Key = value in cents, value = quantity.', verbose_name='Denomination breakdown')),
                ('note', models.TextField(blank=True, default='', help_text="Note libre sur le retrait d'especes. / Optional note about the cash withdrawal.", verbose_name='Note')),
                ('operateur', models.ForeignKey(blank=True, help_text="Caissier qui a effectue le retrait d'especes. / Cashier who performed the cash withdrawal.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sorties_caisse', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
                ('point_de_vente', models.ForeignKey(help_text="Point de vente depuis lequel le retrait d'especes est effectue. / Point of sale from which cash is withdrawn.", on_delete=django.db.models.deletion.PROTECT, related_name='sorties_caisse', to='laboutik.pointdevente', verbose_name='Point of sale')),
            ],
            options={
                'verbose_name': 'Cash withdrawal',
                'verbose_name_plural': 'Cash withdrawals',
                'ordering': ('-datetime',),
            },
        ),
        migrations.CreateModel(
            name='CorrectionPaiement',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('ancien_moyen', models.CharField(help_text='Code du moyen de paiement avant correction (ex: CA, CC, CH). / Payment method code before correction.', max_length=10, verbose_name='Previous payment method')),
                ('nouveau_moyen', models.CharField(help_text='Code du moyen de paiement apres correction. / Payment method code after correction.', max_length=10, verbose_name='New payment method')),
                ('raison', models.TextField(help_text='Raison de la correction. Obligatoire pour la tracabilite. / Correction reason. Mandatory for traceability.', verbose_name='Reason')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Correction date')),
                ('ligne_article', models.ForeignKey(help_text="Ligne d'article dont le moyen de paiement a ete corrige. / Article line whose payment method was corrected.", on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='BaseBillet.lignearticle', verbose_name='Article line')),
                ('operateur', models.ForeignKey(blank=True, help_text='Caissier qui a effectue la correction. / Cashier who performed the correction.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections_paiement', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
            ],
            options={
                'verbose_name': 'Payment correction',
                'verbose_name_plural': 'Payment corrections',
                'ordering': ('-datetime',),
            },
        ),
    ]
