# Generated by Django 4.2.30 on 2026-10-03 22:34
"""
Le journal des impressions (`ImpressionLog.cloture`) pointe vers la clôture unique du
lieu (`comptabilite.ClotureCaisse`) au lieu de l'ancienne clôture de caisse.
/ The print log now points to the venue's single closure.

LOCALISATION : laboutik/migrations/0015_impression_vers_la_cloture_unique.py

IRRÉVERSIBLE DÈS QU'UN Z EST TRACÉ : une impression liée à une clôture unique ne peut
pas revenir vers l'ancienne table (l'uuid n'y existe pas). Revenir en arrière demande
de vider d'abord ce lien, comme le fait 0014.
/ Irreversible once a Z is logged: the link must be emptied first, as 0014 does.

Spécification : TECH_DOC/SESSIONS/COMPTABILITE/CHANTIER-05-G-lecteurs.md (§2.1).
"""

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0005_cloture_unique_chainee'),
        ('laboutik', '0014_vider_le_lien_de_cloture_des_impressions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impressionlog',
            name='cloture',
            field=models.ForeignKey(blank=True, help_text='Cloture de caisse concernee par cette impression. Null pour les tickets de vente et billets. / Cash register closure for this print. Null for sale tickets and event tickets.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='impressions', to='comptabilite.cloturecaisse', verbose_name='Closure'),
        ),
    ]
