# Generated by Django 4.2.29 on 2026-04-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboutik', '0015_add_correction_paiement_and_sortie_caisse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloturecaisse',
            name='niveau',
            field=models.CharField(choices=[('J', 'Daily'), ('H', 'Weekly'), ('M', 'Monthly'), ('A', 'Annual')], default='J', help_text='J = journaliere (caissier), M = mensuelle (auto), A = annuelle (auto). / J = daily (cashier), M = monthly (auto), A = annual (auto).', max_length=1, verbose_name='Closure level'),
        ),
    ]
