# Generated by Django 4.2.29 on 2026-04-02 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('laboutik', '0016_add_hebdomadaire_closure_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalOperation',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('type_operation', models.CharField(choices=[('ARCHIVAGE', 'Archiving'), ('VERIFICATION', 'Verification'), ('EXPORT_FISCAL', 'Fiscal export')], help_text="Type d'operation technique (archivage, verification, export fiscal). / Type of technical operation (archiving, verification, fiscal export).", max_length=20, verbose_name='Operation type')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Operation date')),
                ('details', models.JSONField(default=dict, help_text="Details de l'operation au format JSON. / Operation details in JSON format.", verbose_name='Details')),
                ('hmac_hash', models.CharField(blank=True, default='', help_text="Hash HMAC-SHA256 pour la verification d'integrite. / HMAC-SHA256 hash for integrity verification.", max_length=64, verbose_name='HMAC hash')),
                ('operateur', models.ForeignKey(blank=True, help_text="Utilisateur qui a declenche l'operation technique. / User who triggered the technical operation.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_journal', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
            ],
            options={
                'verbose_name': 'Operation log',
                'verbose_name_plural': 'Operation logs',
                'ordering': ('datetime',),
            },
        ),
        migrations.CreateModel(
            name='HistoriqueFondDeCaisse',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Modification date')),
                ('ancien_montant', models.IntegerField(help_text='Ancien montant du fond de caisse en centimes. / Previous cash float amount in cents.', verbose_name='Previous amount (cents)')),
                ('nouveau_montant', models.IntegerField(help_text='Nouveau montant du fond de caisse en centimes. / New cash float amount in cents.', verbose_name='New amount (cents)')),
                ('raison', models.TextField(blank=True, default='', help_text='Raison du changement de fond de caisse. / Reason for the cash float change.', verbose_name='Reason')),
                ('operateur', models.ForeignKey(blank=True, help_text='Utilisateur qui a modifie le fond de caisse. / User who modified the cash float.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique_fond_de_caisse', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
                ('point_de_vente', models.ForeignKey(blank=True, help_text='Point de vente dont le fond de caisse a ete modifie. / Point of sale whose cash float was modified.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique_fond_de_caisse', to='laboutik.pointdevente', verbose_name='Point of sale')),
            ],
            options={
                'verbose_name': 'Cash float history',
                'verbose_name_plural': 'Cash float histories',
                'ordering': ('-datetime',),
            },
        ),
    ]
