# Generated by Django 4.2.29 on 2026-04-02 20:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('laboutik', '0017_journaloperation_historiquefondecaisse'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteComptable',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('numero_de_compte', models.CharField(help_text='Numero du compte PCG (ex: 7072000). / PCG account number (e.g. 7072000).', max_length=20, verbose_name='Account number')),
                ('libelle_du_compte', models.CharField(help_text='Libelle descriptif du compte (ex: Ventes de marchandises). / Descriptive account label (e.g. Merchandise sales).', max_length=200, verbose_name='Account label')),
                ('nature_du_compte', models.CharField(choices=[('VENTE', 'Sales (class 7)'), ('TVA', 'VAT (class 4457)'), ('TRESORERIE', 'Treasury (class 5)'), ('TIERS', 'Third-party (class 4)'), ('CHARGE', 'Expense (class 6)'), ('PRODUIT_EXCEPTIONNEL', 'Exceptional income (class 77)'), ('SPECIAL', 'Special')], help_text='Nature du compte : VENTE (classe 7), TVA (4457), TRESORERIE (5), etc. / Account nature: SALES (class 7), VAT (4457), TREASURY (5), etc.', max_length=30, verbose_name='Account nature')),
                ('taux_de_tva', models.DecimalField(blank=True, decimal_places=2, help_text='Taux de TVA en pourcentage (ex: 20.00, 10.00, 5.50). Renseigner uniquement pour les comptes VENTE et TVA. / VAT rate as percentage (e.g. 20.00, 10.00, 5.50). Only fill for SALES and VAT accounts.', max_digits=5, null=True, verbose_name='VAT rate (%)')),
                ('est_actif', models.BooleanField(default=True, help_text='Decocher pour desactiver le compte sans le supprimer. / Uncheck to deactivate the account without deleting it.', verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Accounting code',
                'verbose_name_plural': 'Accounting codes',
                'ordering': ['numero_de_compte'],
            },
        ),
        migrations.CreateModel(
            name='MappingMoyenDePaiement',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('moyen_de_paiement', models.CharField(help_text='Code du moyen de paiement (ex: CA = especes, CC = carte bancaire, CH = cheque). Doit correspondre aux codes PaymentMethod. / Payment method code (e.g. CA = cash, CC = credit card, CH = check). Must match PaymentMethod codes.', max_length=10, unique=True, verbose_name='Payment method code')),
                ('libelle_moyen', models.CharField(help_text='Libelle lisible (ex: Especes, Carte bancaire, Cheque). / Readable label (e.g. Cash, Credit card, Check).', max_length=100, verbose_name='Payment method label')),
                ('compte_de_tresorerie', models.ForeignKey(blank=True, help_text="Compte de tresorerie PCG associe (ex: 5311000 pour especes). Laisser vide pour ignorer ce moyen dans l'export comptable (ex: paiements NFC cashless, deja encaisses a la recharge). / PCG treasury account (e.g. 5311000 for cash). Leave blank to ignore this method in accounting export (e.g. NFC cashless payments, already collected at top-up).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moyens_de_paiement', to='laboutik.comptecomptable', verbose_name='Treasury account')),
            ],
            options={
                'verbose_name': 'Payment method mapping',
                'verbose_name_plural': 'Payment method mappings',
                'ordering': ['moyen_de_paiement'],
            },
        ),
    ]
