# Generated by Django 4.2.29 on 2026-04-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboutik', '0018_comptecomptable_mappingmoyendepaiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointdevente',
            name='comportement',
            field=models.CharField(choices=[('D', 'Direct'), ('A', 'Memberships'), ('C', 'Cashless'), ('T', 'Ticketing'), ('V', 'Advanced'), ('I', 'Connected tap')], default='D', help_text='Determines how articles are loaded. Direct: M2M only. Memberships: auto-loads membership products. Cashless: auto-loads top-ups. Ticketing: builds from future events. Advanced: restaurant order mode.', max_length=1, verbose_name='POS type'),
        ),
    ]
