# Generated by Django 4.2.30 on 2026-07-18 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BaseBillet', '0222_commande_resourceproduct'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Calendar',
                'verbose_name_plural': 'Calendars',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ResourceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('image', models.URLField(blank=True, default='', verbose_name='Image URL')),
            ],
            options={
                'verbose_name': 'Resource group',
                'verbose_name_plural': 'Resource groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Weekly opening',
                'verbose_name_plural': 'Weekly openings',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Displayed only for membership/subscription products.', null=True, verbose_name='Long description')),
                ('capacity', models.PositiveIntegerField(default=1, help_text='Maximum simultaneous bookings per slot. 1 = exclusive use.', verbose_name='Capacity')),
                ('cancellation_deadline_hours', models.PositiveIntegerField(default=24, help_text='Hours before slot start within which cancellation is allowed.', verbose_name='Cancellation deadline (hours)')),
                ('booking_horizon_days', models.PositiveIntegerField(default=28, help_text='How far ahead a member can book.', verbose_name='Booking horizon (days)')),
                ('slot_type', models.CharField(choices=[('H', "à l'heure"), ('D', 'à la journée')], default='H', max_length=1, verbose_name='Type de réservation')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='booking.calendar', verbose_name='Calendar')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='booking.resourcegroup', verbose_name='Group')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='BaseBillet.product', verbose_name='Produit')),
                ('weekly_opening', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='booking.weeklyopening', verbose_name='Weekly opening')),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
            },
        ),
        migrations.CreateModel(
            name='OpeningEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='Weekday')),
                ('start_time', models.TimeField(verbose_name='Start time')),
                ('slot_duration_minutes', models.PositiveIntegerField(verbose_name='Slot duration (minutes)')),
                ('slot_count', models.PositiveIntegerField(verbose_name='Slot count')),
                ('weekly_opening', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_entries', to='booking.weeklyopening', verbose_name='Weekly opening')),
            ],
            options={
                'verbose_name': "Période d'ouverture",
                'verbose_name_plural': "Périodes d'ouvertures",
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ClosedPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(blank=True, help_text='Same as start date: single-day closure. Later than start date: multi-day closure. Leave empty: endless closure.', null=True, verbose_name='End date')),
                ('label', models.CharField(blank=True, default='', help_text='e.g. "Summer closure", "Public holiday"', max_length=200, verbose_name='Label')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='closed_periods', to='booking.calendar', verbose_name='Calendar')),
            ],
            options={
                'verbose_name': 'Closed period',
                'verbose_name_plural': 'Closed periods',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='Slot begining')),
                ('slot_duration_minutes', models.PositiveIntegerField(verbose_name='Slot duration (minutes)')),
                ('slot_count', models.PositiveIntegerField(verbose_name='Slot count')),
                ('end_datetime', models.DateTimeField(editable=False, verbose_name='Slot end')),
                ('status', models.CharField(choices=[('WP', 'Waiting for payment'), ('CA', 'Cancelled'), ('WA', 'Waiting for admin validation'), ('VA', 'Confirmed by admin, waiting for payment'), ('PA', 'Paid by user'), ('AU', 'Confirmed by system'), ('FR', 'Email verification still pending'), ('FU', 'Email verified'), ('UC', 'Canceled by user')], default='WP', max_length=2, verbose_name='Status')),
                ('booked_at', models.DateTimeField(auto_now_add=True, verbose_name='Booked at')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Last name')),
                ('commande', models.ForeignKey(blank=True, help_text='Renseignée uniquement si la réservation a été créée via un panier multi-items. / Only set if the booking was created via a multi-item cart.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='BaseBillet.commande', verbose_name='Order')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='booking.resource', verbose_name='Resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['start_datetime'],
            },
        ),
        migrations.AddConstraint(
            model_name='closedperiod',
            constraint=models.CheckConstraint(check=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='closed_period_end_date_gte_start_date'),
        ),
    ]
