# Generated by Django 4.2.29 on 2026-04-08 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Calendar',
                'verbose_name_plural': 'Calendars',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ResourceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('image', models.URLField(blank=True, default='', verbose_name='Image URL')),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of labels, e.g. ["salle", "machine"]', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Resource group',
                'verbose_name_plural': 'Resource groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Weekly opening',
                'verbose_name_plural': 'Weekly openings',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('capacity', models.PositiveIntegerField(default=1, help_text='Maximum simultaneous bookings per slot. 1 = exclusive use.', verbose_name='Capacity')),
                ('cancellation_deadline_hours', models.PositiveIntegerField(default=24, help_text='Hours before slot start within which cancellation is allowed.', verbose_name='Cancellation deadline (hours)')),
                ('booking_horizon_days', models.PositiveIntegerField(default=28, help_text='How far ahead a member can book.', verbose_name='Booking horizon (days)')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('image', models.URLField(blank=True, default='', verbose_name='Image URL')),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of labels, e.g. ["salle", "machine"]', verbose_name='Tags')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='booking.calendar', verbose_name='Calendar')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='booking.resourcegroup', verbose_name='Group')),
                ('weekly_opening', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='booking.weeklyopening', verbose_name='Weekly opening')),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OpeningEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='Weekday')),
                ('start_time', models.TimeField(verbose_name='Start time')),
                ('slot_duration_minutes', models.PositiveIntegerField(verbose_name='Slot duration (minutes)')),
                ('slot_count', models.PositiveIntegerField(verbose_name='Slot count')),
                ('weekly_opening', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_entries', to='booking.weeklyopening', verbose_name='Weekly opening')),
            ],
            options={
                'verbose_name': 'Opening entry',
                'verbose_name_plural': 'Opening entries',
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ClosedPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(blank=True, help_text='Leave empty for an endless closure.', null=True, verbose_name='End date')),
                ('label', models.CharField(blank=True, default='', help_text='e.g. "Summer closure", "Public holiday"', max_length=200, verbose_name='Label')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='closed_periods', to='booking.calendar', verbose_name='Calendar')),
            ],
            options={
                'verbose_name': 'Closed period',
                'verbose_name_plural': 'Closed periods',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='Slot begining')),
                ('slot_duration_minutes', models.PositiveIntegerField(verbose_name='Slot duration (minutes)')),
                ('slot_count', models.PositiveIntegerField(verbose_name='Slot count')),
                ('status', models.CharField(choices=[('new', 'New — in basket'), ('validated', 'Validated — pending payment'), ('confirmed', 'Confirmed — payment done')], default='new', max_length=20, verbose_name='Status')),
                ('booked_at', models.DateTimeField(auto_now_add=True, verbose_name='Booked at')),
                ('payment_ref', models.CharField(blank=True, max_length=200, null=True, verbose_name='Payment reference')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='booking.resource', verbose_name='Resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['start_datetime'],
            },
        ),
    ]
