# Generated by Django 4.2.29 on 2026-04-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closedperiod',
            name='end_date',
            field=models.DateField(blank=True, help_text='Same as start date: single-day closure. Later than start date: multi-day closure. Leave empty: endless closure.', null=True, verbose_name='End date'),
        ),
        migrations.AddConstraint(
            model_name='closedperiod',
            constraint=models.CheckConstraint(check=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='closed_period_end_date_gte_start_date'),
        ),
    ]
