# Generated by Django 4.2.30 on 2026-09-29 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0229_paymentmethod_non_monetaire'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='product',
            field=models.ForeignKey(limit_choices_to={'categorie_article': 'C'}, on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='BaseBillet.resourceproduct', verbose_name='Produit'),
        ),
    ]
