# Generated by Django 4.2.30 on 2026-06-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='booking_horizon_days',
            field=models.PositiveIntegerField(default=28, help_text='How far ahead a member can book.', verbose_name='Booking horizon (days)'),
        ),
    ]
