# Generated by Django 4.2.30 on 2026-10-06 16:09

from django.db import migrations



def create_default_groupe(apps, schema_editor):
    ResourceGroup = apps.get_model("booking", "ResourceGroup")
    ResourceGroup.objects.create(name="Ressource")
    ResourceGroup.objects.create(name="Espace")

class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_resource_group'),
    ]

    operations = [
        migrations.RunPython(create_default_groupe),
    ]
