# Generated by Django 4.2.29 on 2026-04-27 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_closed_period_end_date_constraint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='resourcegroup',
            name='tags',
        ),
    ]
