# Generated by Django 4.2.30 on 2026-06-29 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0220_resourceproduct_alter_product_categorie_article_and_more'),
        ('booking', '0002_resource_booking_horizon_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='name',
            field=models.CharField(default='test', max_length=200, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resource',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='BaseBillet.resourceproduct', verbose_name='Product'),
        ),
    ]
