# Generated by Django 4.2.30 on 2026-06-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0220_resourceproduct_alter_product_categorie_article_and_more'),
        ('booking', '0003_resource_name_alter_resource_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['name'], 'verbose_name': 'Resource', 'verbose_name_plural': 'Resources'},
        ),
        migrations.RemoveField(
            model_name='resource',
            name='product',
        ),
        migrations.AddField(
            model_name='resource',
            name='prices',
            field=models.ManyToManyField(related_name='resources', to='BaseBillet.price', verbose_name='Prices'),
        ),
    ]
