# Generated by Django 4.2.30 on 2026-06-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_resource_options_remove_resource_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('WP', 'Waiting for payment'), ('CA', 'Cancelled'), ('WA', 'Waiting for admin validation'), ('VA', 'Confirmed by admin, waiting for payment'), ('PA', 'Paid by user'), ('AU', 'Confirmed by system')], default='WP', max_length=2, verbose_name='Status'),
        ),
    ]
