# Generated by Django 4.2.29 on 2026-04-27 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_add_end_datetime_to_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed')], default='confirmed', max_length=20, verbose_name='Status'),
        ),
    ]
