# Generated by Django 4.2.30 on 2026-06-30 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0221_lignearticle_booking'),
        ('booking', '0005_alter_booking_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'verbose_name': 'Resource', 'verbose_name_plural': 'Resources'},
        ),
        migrations.RemoveField(
            model_name='resource',
            name='name',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='prices',
        ),
        migrations.AddField(
            model_name='resource',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product', to='BaseBillet.product', verbose_name='Produit'),
        ),
    ]
