# Generated by Django 4.2.30 on 2026-06-30 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0221_lignearticle_booking'),
        ('booking', '0006_alter_resource_options_remove_resource_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='BaseBillet.product', verbose_name='Produit'),
        ),
    ]
