# Generated by Django 4.2.30 on 2026-07-02 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0221_lignearticle_booking'),
        ('booking', '0007_alter_resource_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='commande',
            field=models.ForeignKey(blank=True, help_text='Renseignée uniquement si la réservation a été créée via un panier multi-items. / Only set if the booking was created via a multi-item cart.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_commande', to='BaseBillet.commande', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('WP', 'Waiting for payment'), ('CA', 'Cancelled'), ('WA', 'Waiting for admin validation'), ('VA', 'Confirmed by admin, waiting for payment'), ('PA', 'Paid by user'), ('AU', 'Confirmed by system'), ('UC', 'Canceled by user')], default='WP', max_length=2, verbose_name='Status'),
        ),
    ]
