# Generated by Django 4.2.30 on 2026-07-07 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_booking_commande_alter_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='payment_ref',
        ),
    ]
