# Generated by Django 4.2.30 on 2026-07-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_remove_booking_payment_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('WP', 'Waiting for payment'), ('CA', 'Cancelled'), ('WA', 'Waiting for admin validation'), ('VA', 'Confirmed by admin, waiting for payment'), ('PA', 'Paid by user'), ('AU', 'Confirmed by system'), ('FR', 'Email verification still pending'), ('FU', 'Email verified'), ('UC', 'Canceled by user')], default='WP', max_length=2, verbose_name='Status'),
        ),
    ]
