# Generated by Django 4.2.30 on 2026-07-09 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0226_alter_paiement_stripe_status'),
        ('booking', '0010_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='commande',
            field=models.ForeignKey(blank=True, help_text='Renseignée uniquement si la réservation a été créée via un panier multi-items. / Only set if the booking was created via a multi-item cart.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='BaseBillet.commande', verbose_name='Order'),
        ),
    ]
