# Generated by Django 4.2.30 on 2026-07-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_alter_booking_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='booking',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Last name'),
        ),
    ]
