# Generated by Django 4.2.30 on 2026-07-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_booking_first_name_booking_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='slot_type',
            field=models.CharField(choices=[('H', "à l'heure"), ('D', 'à la journée')], default='H', max_length=1, verbose_name='Type de réservation'),
        ),
    ]
