# Generated by Django 4.2.30 on 2026-07-16 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0226_alter_paiement_stripe_status'),
        ('booking', '0013_resource_slot_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='BaseBillet.product', verbose_name='Produit'),
        ),
    ]
