# Generated by Django 4.2.30 on 2026-07-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_alter_resource_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
