# Generated by Django 4.2.30 on 2026-07-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_resource_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True, help_text='Displayed only for membership/subscription products.', null=True, verbose_name='Long description'),
        ),
    ]
