# Generated by Django 4.2.30 on 2026-06-20 12:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BaseBillet', '0220_categorieproduct_price_asset_price_contenance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('type_mouvement', models.CharField(choices=[('VE', 'Vente'), ('RE', 'Réception'), ('AJ', 'Ajustement'), ('OF', 'Offert'), ('PE', 'Perte/casse'), ('DM', 'Débit mètre')], help_text='Nature du mouvement de stock', max_length=2, verbose_name='Type de mouvement')),
                ('quantite', models.IntegerField(help_text='Variation signée du stock (négatif = sortie, positif = entrée)', verbose_name='Quantité (delta)')),
                ('quantite_avant', models.IntegerField(help_text='Niveau de stock avant ce mouvement', verbose_name='Quantité avant')),
                ('motif', models.CharField(blank=True, default='', help_text='Raison du mouvement (optionnel)', max_length=200, verbose_name='Motif')),
                ('cree_le', models.DateTimeField(auto_now_add=True, help_text='Date et heure de création du mouvement', verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('quantite', models.IntegerField(default=0, help_text='Quantité actuelle en stock (peut être négative)', verbose_name='Quantité')),
                ('unite', models.CharField(choices=[('UN', 'Pièces'), ('CL', 'Centilitres'), ('GR', 'Grammes')], default='UN', help_text='Unité de mesure du stock', max_length=2, verbose_name='Unité')),
                ('seuil_alerte', models.PositiveIntegerField(blank=True, help_text="Alerte quand le stock descend sous ce seuil (vide = pas d'alerte)", null=True, verbose_name="Seuil d'alerte")),
                ('autoriser_vente_hors_stock', models.BooleanField(default=True, help_text='Si coché, la vente reste possible même en rupture de stock', verbose_name='Autoriser vente hors stock')),
                ('product', models.OneToOneField(help_text='Le produit POS associé à ce stock', on_delete=django.db.models.deletion.CASCADE, related_name='stock_inventaire', to='BaseBillet.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
            },
        ),
    ]
