# Generated by Django 4.2.29 on 2026-04-03 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("BaseBillet", "0212_ticket_scanned_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("laboutik", "0018_comptecomptable_mappingmoyendepaiement"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "quantite",
                    models.IntegerField(
                        default=0,
                        help_text="Quantité actuelle en stock (peut être négative) / Current stock quantity (can be negative)",
                        verbose_name="Quantité / Quantity",
                    ),
                ),
                (
                    "unite",
                    models.CharField(
                        choices=[
                            ("UN", "Pièces / Units"),
                            ("CL", "Centilitres"),
                            ("GR", "Grammes / Grams"),
                        ],
                        default="UN",
                        help_text="Unité de mesure du stock / Stock measurement unit",
                        max_length=2,
                        verbose_name="Unité / Unit",
                    ),
                ),
                (
                    "seuil_alerte",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Alerte quand le stock descend sous ce seuil (vide = pas d'alerte) / Alert when stock drops below this threshold (empty = no alert)",
                        null=True,
                        verbose_name="Seuil d'alerte / Alert threshold",
                    ),
                ),
                (
                    "autoriser_vente_hors_stock",
                    models.BooleanField(
                        default=True,
                        help_text="Si coché, la vente reste possible même en rupture de stock / If checked, sales remain possible even when out of stock",
                        verbose_name="Autoriser vente hors stock / Allow out-of-stock sales",
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        help_text="Le produit POS associé à ce stock / The POS product linked to this stock",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_inventaire",
                        to="BaseBillet.product",
                        verbose_name="Produit / Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock",
                "verbose_name_plural": "Stocks",
            },
        ),
        migrations.CreateModel(
            name="MouvementStock",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "type_mouvement",
                    models.CharField(
                        choices=[
                            ("VE", "Vente / Sale"),
                            ("RE", "Réception / Reception"),
                            ("AJ", "Ajustement / Adjustment"),
                            ("OF", "Offert / Offered"),
                            ("PE", "Perte/casse / Loss/breakage"),
                            ("DM", "Débit mètre / Meter debit"),
                        ],
                        help_text="Nature du mouvement de stock / Nature of the stock movement",
                        max_length=2,
                        verbose_name="Type de mouvement / Movement type",
                    ),
                ),
                (
                    "quantite",
                    models.IntegerField(
                        help_text="Variation signée du stock (négatif = sortie, positif = entrée) / Signed stock change (negative = outgoing, positive = incoming)",
                        verbose_name="Quantité (delta) / Quantity (delta)",
                    ),
                ),
                (
                    "quantite_avant",
                    models.IntegerField(
                        help_text="Niveau de stock avant ce mouvement / Stock level before this movement",
                        verbose_name="Quantité avant / Quantity before",
                    ),
                ),
                (
                    "motif",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Raison du mouvement (optionnel) / Reason for the movement (optional)",
                        max_length=200,
                        verbose_name="Motif / Reason",
                    ),
                ),
                (
                    "cree_le",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date et heure de création du mouvement / Movement creation date and time",
                        verbose_name="Créé le / Created at",
                    ),
                ),
                (
                    "cloture",
                    models.ForeignKey(
                        blank=True,
                        help_text="Clôture pendant laquelle ce mouvement a eu lieu / Closure during which this movement occurred",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mouvements_stock",
                        to="laboutik.cloturecaisse",
                        verbose_name="Clôture de caisse / Cash register closure",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        help_text="Utilisateur ayant effectué ce mouvement / User who performed this movement",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mouvements_stock_crees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par / Created by",
                    ),
                ),
                (
                    "ligne_article",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ligne de vente liée (si vente) / Related sale line (if sale)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mouvements_stock",
                        to="BaseBillet.lignearticle",
                        verbose_name="Ligne article / Order line",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        help_text="Le stock concerné par ce mouvement / The stock affected by this movement",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mouvements",
                        to="inventaire.stock",
                        verbose_name="Stock",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mouvement de stock / Stock movement",
                "verbose_name_plural": "Mouvements de stock / Stock movements",
                "ordering": ["-cree_le"],
                "indexes": [
                    models.Index(fields=["-cree_le"], name="idx_mvt_cree_le"),
                    models.Index(fields=["type_mouvement"], name="idx_mvt_type"),
                ],
            },
        ),
    ]
