# Generated by Django 4.2.30 on 2026-06-20 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laboutik', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventaire', '0001_initial'),
        ('BaseBillet', '0221_categorieproduct_compte_comptable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementstock',
            name='cloture',
            field=models.ForeignKey(blank=True, help_text='Clôture pendant laquelle ce mouvement a eu lieu', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to='laboutik.cloturecaisse', verbose_name='Clôture de caisse'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='cree_par',
            field=models.ForeignKey(blank=True, help_text='Utilisateur ayant effectué ce mouvement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='ligne_article',
            field=models.ForeignKey(blank=True, help_text='Ligne de vente liée (si vente)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to='BaseBillet.lignearticle', verbose_name='Ligne article'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='stock',
            field=models.ForeignKey(help_text='Le stock concerné par ce mouvement', on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='inventaire.stock', verbose_name='Stock'),
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['-cree_le'], name='idx_mvt_cree_le'),
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['type_mouvement'], name='idx_mvt_type'),
        ),
    ]
