# Generated by Django 3.2 on 2022-04-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='contact@tibillet.re', max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
