# Generated by Django 3.2 on 2022-05-19 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0002_alter_client_categorie'),
        ('MetaBillet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDirectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('event_uuid', models.UUIDField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist', to='Customers.client')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place', to='Customers.client')),
            ],
        ),
        migrations.DeleteModel(
            name='Configuration',
        ),
    ]
