# Generated by Django 3.2 on 2022-06-25 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0002_alter_client_categorie'),
        ('MetaBillet', '0002_auto_20220519_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDirectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_sold_stripe_id', models.CharField(blank=True, max_length=30, null=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_place', to='Customers.client')),
            ],
        ),
    ]
