# Generated by Django 4.2 on 2024-08-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetaBillet', '0004_waitingconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitingconfiguration',
            name='id_acc_connect',
            field=models.CharField(blank=True, max_length=21, null=True, verbose_name='Id stripe connect'),
        ),
        migrations.AddField(
            model_name='waitingconfiguration',
            name='laboutik_wanted',
            field=models.BooleanField(default=False),
        ),
    ]
