# Generated by Django 4.2 on 2024-08-31 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetaBillet', '0005_waitingconfiguration_id_acc_connect_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitingconfiguration',
            name='dns_choice',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Choix du nom de domaine'),
        ),
    ]
