# Generated by Django 4.2.17 on 2025-02-16 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MetaBillet', '0006_waitingconfiguration_dns_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitingconfiguration',
            name='stripe_connect_account',
        ),
    ]
