# Generated by Django 4.2.17 on 2025-02-26 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0002_alter_client_categorie'),
        ('MetaBillet', '0007_remove_waitingconfiguration_stripe_connect_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitingconfiguration',
            name='created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='waitingconfiguration',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waiting_config', to='Customers.client', verbose_name='Tenant'),
        ),
    ]
