# Generated by Django 4.2.17 on 2025-03-02 10:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MetaBillet', '0008_waitingconfiguration_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitingconfiguration',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waitingconfiguration',
            name='onboard_stripe_finished',
            field=models.BooleanField(default=False),
        ),
    ]
