# Generated by Django 4.2.17 on 2025-03-13 09:05

from django.db import migrations, models
import stdimage.models
import stdimage.validators


class Migration(migrations.Migration):

    dependencies = [
        ('MetaBillet', '0009_waitingconfiguration_datetime_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waitingconfiguration',
            options={'verbose_name': 'Settings', 'verbose_name_plural': 'Settings'},
        ),
        migrations.AlterField(
            model_name='waitingconfiguration',
            name='adress',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='waitingconfiguration',
            name='carte_restaurant',
            field=stdimage.models.JPEGField(blank=True, force_min_size=False, null=True, upload_to='images/', validators=[stdimage.validators.MaxSizeValidator(1920, 1920)], variations={'fhd': (1920, 1920), 'hdr': (720, 720), 'med': (480, 480), 'thumbnail': (150, 90)}, verbose_name='Restaurant menu'),
        ),
        migrations.AlterField(
            model_name='waitingconfiguration',
            name='categorie',
            field=models.CharField(choices=[('A', 'Artist'), ('S', 'Scene'), ('F', 'Festival'), ('T', 'Tour operator'), ('P', 'Producer'), ('M', 'Event aggregator'), ('R', 'Root public tenant')], default='S', max_length=3, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='waitingconfiguration',
            name='city',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='waitingconfiguration',
            name='dns_choice',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Domain name choice'),
        ),
        migrations.AlterField(
            model_name='waitingconfiguration',
            name='id_acc_connect',
            field=models.CharField(blank=True, max_length=21, null=True, verbose_name='Stripe connect ID'),
        ),
        migrations.AlterField(
            model_name='waitingconfiguration',
            name='legal_documents',
            field=models.URLField(blank=True, null=True, verbose_name='By-laws'),
        ),
        migrations.AlterField(
            model_name='waitingconfiguration',
            name='long_description',
            field=models.TextField(blank=True, null=True, verbose_name='Long description'),
        ),
        migrations.AlterField(
            model_name='waitingconfiguration',
            name='map_img',
            field=stdimage.models.JPEGField(blank=True, force_min_size=False, null=True, upload_to='images/', validators=[stdimage.validators.MaxSizeValidator(1920, 1920)], variations={'fhd': (1920, 1920), 'hdr': (720, 720), 'med': (480, 480), 'thumbnail': (150, 90)}, verbose_name='Geographical map'),
        ),
        migrations.AlterField(
            model_name='waitingconfiguration',
            name='organisation',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Collective name'),
        ),
        migrations.AlterField(
            model_name='waitingconfiguration',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='waitingconfiguration',
            name='postal_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Zip code'),
        ),
        migrations.AlterField(
            model_name='waitingconfiguration',
            name='short_description',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Short description'),
        ),
    ]
