# Generated by Django 4.2.17 on 2025-05-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetaBillet', '0011_waitingconfiguration_payment_wanted'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitingconfiguration',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
