# Generated by Django 4.2.30 on 2026-05-15 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboard', '0001_initial'),
        ('MetaBillet', '0012_waitingconfiguration_email_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitingconfiguration',
            name='address_country',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='waitingconfiguration',
            name='address_locality',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='waitingconfiguration',
            name='current_step',
            field=models.CharField(choices=[('identity', 'Identity'), ('verify', 'Verify email'), ('place', 'Place location'), ('descriptions', 'Descriptions'), ('events', 'Events'), ('launch', 'Launch')], default='identity', help_text='Current step the user is on in the wizard.', max_length=20, verbose_name='Current wizard step'),
        ),
        migrations.AddField(
            model_name='waitingconfiguration',
            name='error_message',
            field=models.TextField(blank=True, default='', help_text='Error message captured by the async tenant-creation task, if any.', verbose_name='Async task error'),
        ),
        migrations.AddField(
            model_name='waitingconfiguration',
            name='events_draft',
            field=models.JSONField(blank=True, default=list, verbose_name='Events draft'),
        ),
        migrations.AddField(
            model_name='waitingconfiguration',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='waitingconfiguration',
            name='invitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_by_drafts', to='onboard.onboardinvitation', verbose_name='Invitation used'),
        ),
        migrations.AddField(
            model_name='waitingconfiguration',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Last name'),
        ),
        migrations.AddField(
            model_name='waitingconfiguration',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='waitingconfiguration',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='waitingconfiguration',
            name='otp_attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='OTP wrong attempts'),
        ),
        migrations.AddField(
            model_name='waitingconfiguration',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, help_text='Expiration of the OTP, usually 10 minutes after issuance.', null=True, verbose_name='OTP expires at'),
        ),
        migrations.AddField(
            model_name='waitingconfiguration',
            name='otp_hash',
            field=models.CharField(blank=True, default='', help_text='PBKDF2 hash of the one-time password. Never stored in plain text.', max_length=128, verbose_name='OTP hash'),
        ),
        migrations.AddField(
            model_name='waitingconfiguration',
            name='otp_resend_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='OTP resend count'),
        ),
        migrations.AddField(
            model_name='waitingconfiguration',
            name='street_address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Street address'),
        ),
        migrations.AlterField(
            model_name='waitingconfiguration',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Zip code'),
        ),
    ]
