# Generated by Django 4.2.30 on 2026-05-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetaBillet', '0012_waitingconfiguration_email_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitingconfiguration',
            name='address_country',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='waitingconfiguration',
            name='address_locality',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='waitingconfiguration',
            name='current_step',
            field=models.CharField(choices=[('identity', 'Identity'), ('verify', 'Verify email'), ('place', 'Place location'), ('descriptions', 'Descriptions'), ('events', 'Events'), ('launch', 'Launch')], default='identity', max_length=20, verbose_name='Current wizard step'),
        ),
        migrations.AddField(
            model_name='waitingconfiguration',
            name='error_message',
            field=models.TextField(blank=True, default='', verbose_name='Async task error'),
        ),
        migrations.AddField(
            model_name='waitingconfiguration',
            name='events_draft',
            field=models.JSONField(blank=True, default=list, verbose_name='Events draft'),
        ),
        migrations.AddField(
            model_name='waitingconfiguration',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='waitingconfiguration',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Last name'),
        ),
        migrations.AddField(
            model_name='waitingconfiguration',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='waitingconfiguration',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='waitingconfiguration',
            name='otp_attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='OTP wrong attempts'),
        ),
        migrations.AddField(
            model_name='waitingconfiguration',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='OTP expires at'),
        ),
        migrations.AddField(
            model_name='waitingconfiguration',
            name='otp_hash',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='OTP bcrypt hash'),
        ),
        migrations.AddField(
            model_name='waitingconfiguration',
            name='otp_resend_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='OTP resend count'),
        ),
        migrations.AddField(
            model_name='waitingconfiguration',
            name='street_address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Street address'),
        ),
    ]
