# Generated by Django 4.2.30 on 2026-05-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetaBillet', '0013_waitingconfiguration_address_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitingconfiguration',
            name='otp_sent_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last OTP send (used for cooldown).', null=True, verbose_name='OTP last sent at'),
        ),
    ]
