# Generated by Django 4.2.30 on 2026-05-14 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboard', '0001_initial'),
        ('MetaBillet', '0013_waitingconfiguration_address_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitingconfiguration',
            name='invitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_by_drafts', to='onboard.onboardinvitation', verbose_name='Invitation used'),
        ),
        migrations.AlterField(
            model_name='waitingconfiguration',
            name='current_step',
            field=models.CharField(choices=[('identity', 'Identity'), ('verify', 'Verify email'), ('place', 'Place location'), ('descriptions', 'Descriptions'), ('events', 'Events'), ('launch', 'Launch')], default='identity', help_text='Current step the user is on in the wizard.', max_length=20, verbose_name='Current wizard step'),
        ),
        migrations.AlterField(
            model_name='waitingconfiguration',
            name='error_message',
            field=models.TextField(blank=True, default='', help_text='Error message captured by the async tenant-creation task, if any.', verbose_name='Async task error'),
        ),
        migrations.AlterField(
            model_name='waitingconfiguration',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, help_text='Expiration of the OTP, usually 10 minutes after issuance.', null=True, verbose_name='OTP expires at'),
        ),
        migrations.AlterField(
            model_name='waitingconfiguration',
            name='otp_hash',
            field=models.CharField(blank=True, default='', help_text='Bcrypt hash of the one-time password. Never stored in plain text.', max_length=100, verbose_name='OTP bcrypt hash'),
        ),
    ]
