# Generated by Django 4.2.30 on 2026-05-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetaBillet', '0014_waitingconfiguration_invitation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitingconfiguration',
            name='otp_hash',
            field=models.CharField(blank=True, default='', help_text='PBKDF2 hash of the one-time password. Never stored in plain text.', max_length=128, verbose_name='OTP hash'),
        ),
    ]
