# Generated by Django 4.2.30 on 2026-05-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetaBillet', '0014_waitingconfiguration_otp_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitingconfiguration',
            name='events_creation_warnings',
            field=models.TextField(blank=True, default='', help_text='Non-blocking warnings from event draft processing during tenant creation.', verbose_name='Events creation warnings'),
        ),
    ]
