# Generated by Django 4.2.30 on 2026-05-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetaBillet', '0015_waitingconfiguration_events_creation_warnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitingconfiguration',
            name='language',
            field=models.CharField(blank=True, default='', help_text='BCP47 language code captured during the onboarding wizard.', max_length=10, verbose_name='Preferred language'),
        ),
    ]
