# Generated by Django 4.2.30 on 2026-05-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetaBillet', '0015_alter_waitingconfiguration_otp_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitingconfiguration',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Zip code'),
        ),
    ]
