# Generated by Django 4.2.30 on 2026-06-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetaBillet', '0016_add_wc_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitingconfiguration',
            name='current_step',
            field=models.CharField(choices=[('identity', 'Identity'), ('verify', 'Verify email'), ('venue', 'Your venue'), ('place', 'Address'), ('descriptions', 'Descriptions'), ('events', 'Events'), ('launch', 'Launch')], default='identity', help_text='Current step the user is on in the wizard.', max_length=20, verbose_name='Current wizard step'),
        ),
    ]
