# Generated by Django 4.2.30 on 2026-09-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetaBillet', '0017_alter_waitingconfiguration_current_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitingconfiguration',
            name='created',
            field=models.BooleanField(default=False, verbose_name='Créée le'),
        ),
        migrations.AlterField(
            model_name='waitingconfiguration',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date et heure'),
        ),
        migrations.AlterField(
            model_name='waitingconfiguration',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Adresse e-mail'),
        ),
        migrations.AlterField(
            model_name='waitingconfiguration',
            name='email_confirmed',
            field=models.BooleanField(default=False, verbose_name='Adresse e-mail confirmée'),
        ),
        migrations.AlterField(
            model_name='waitingconfiguration',
            name='laboutik_wanted',
            field=models.BooleanField(default=False, verbose_name='LaBoutik souhaité'),
        ),
        migrations.AlterField(
            model_name='waitingconfiguration',
            name='payment_wanted',
            field=models.BooleanField(default=False, verbose_name='Paiement souhaité'),
        ),
        migrations.AlterField(
            model_name='waitingconfiguration',
            name='site_web',
            field=models.URLField(blank=True, null=True, verbose_name='Site web'),
        ),
    ]
