# Generated by Django 4.2.30 on 2026-09-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetaBillet', '0018_verbose_name_fr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitingconfiguration',
            name='created',
            field=models.BooleanField(default=False, verbose_name='Instance créée'),
        ),
    ]
