# Generated by Django 4.2.28 on 2026-02-28 17:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customers', '0004_alter_client_categorie_alter_client_on_trial'),
        ('AuthBillet', '0024_wallet_name_wallet_public_pem'),
        ('QrcodeCashless', '0021_cartecashless_wallet_ephemere'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name="Nom de l'asset")),
                ('currency_code', models.CharField(help_text='Code devise sur 3 caracteres : EUR, TMP, PTS, etc.', max_length=3, verbose_name='Code devise')),
                ('category', models.CharField(choices=[('TLF', 'Token local fiduciaire'), ('TNF', 'Token local cadeau'), ('FED', 'Fiduciaire federee'), ('TIM', 'Monnaie temps'), ('FID', 'Points de fidelite')], max_length=3, verbose_name='Categorie')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
                ('archive', models.BooleanField(default=False, verbose_name='Archive')),
                ('id_price_stripe', models.CharField(blank=True, help_text='Identifiant Stripe du Price pour recharge (categorie FED uniquement)', max_length=100, null=True, verbose_name='Stripe Price ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('tenant_origin', models.ForeignKey(help_text='Lieu ou organisation qui a cree cet asset', on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='Customers.client', verbose_name='Tenant createur')),
                ('wallet_origin', models.ForeignKey(help_text='Wallet du lieu ou de la personne qui a cree cet asset', on_delete=django.db.models.deletion.PROTECT, related_name='fedow_core_assets', to='AuthBillet.wallet', verbose_name='Wallet createur')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.IntegerField(default=0, help_text='Solde en centimes. 1500 = 15,00 EUR.', verbose_name='Solde')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tokens', to='fedow_core.asset', verbose_name='Asset')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tokens', to='AuthBillet.wallet', verbose_name='Wallet')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
            },
        ),
        migrations.CreateModel(
            name='Federation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('assets', models.ManyToManyField(blank=True, related_name='federations', to='fedow_core.asset', verbose_name='Assets partages')),
                ('tenants', models.ManyToManyField(blank=True, related_name='federations', to='Customers.client', verbose_name='Tenants membres')),
            ],
            options={
                'verbose_name': 'Federation',
                'verbose_name_plural': 'Federations',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text="Identifiant unique conserve pour les imports depuis l'ancien Fedow", unique=True, verbose_name='UUID')),
                ('hash', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Hash SHA256')),
                ('migrated', models.BooleanField(default=False, verbose_name='Transaction migree')),
                ('amount', models.PositiveIntegerField(help_text='Montant en centimes. 350 = 3,50 EUR.', verbose_name='Montant')),
                ('action', models.CharField(choices=[('FST', 'Genesis'), ('CRE', 'Creation'), ('RFL', 'Recharge'), ('SAL', 'Vente'), ('QRS', 'Vente QR'), ('FUS', 'Fusion'), ('RFD', 'Remboursement'), ('VOI', 'Annulation'), ('DEP', 'Depot bancaire'), ('TRF', 'Virement')], max_length=3, verbose_name='Action')),
                ('datetime', models.DateTimeField(verbose_name='Date et heure')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Commentaire')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadonnees')),
                ('subscription_type', models.CharField(blank=True, max_length=50, null=True, verbose_name="Type d'abonnement (legacy)")),
                ('subscription_start_datetime', models.DateTimeField(blank=True, null=True, verbose_name="Debut d'abonnement (legacy)")),
                ('checkout_stripe', models.UUIDField(blank=True, help_text='UUID du Paiement_stripe associe (pas de FK cross-schema)', null=True, verbose_name='Paiement Stripe')),
                ('ip', models.GenericIPAddressField(default='0.0.0.0', verbose_name='Adresse IP')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='fedow_core.asset', verbose_name='Asset')),
                ('card', models.ForeignKey(blank=True, help_text='Carte NFC utilisee pour cette transaction', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='QrcodeCashless.cartecashless', verbose_name='Carte cashless')),
                ('primary_card', models.ForeignKey(blank=True, help_text='Carte maitresse du point de vente (terminal/caissier)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_as_primary', to='QrcodeCashless.cartecashless', verbose_name='Carte maitresse')),
                ('receiver', models.ForeignKey(blank=True, help_text='Wallet credite (qui recoit). Nullable pour VOID/REFUND.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_received', to='AuthBillet.wallet', verbose_name='Destinataire')),
                ('sender', models.ForeignKey(help_text='Wallet debite (qui paye)', on_delete=django.db.models.deletion.PROTECT, related_name='transactions_sent', to='AuthBillet.wallet', verbose_name='Emetteur')),
                ('tenant', models.ForeignKey(help_text='Lieu concerne — TOUJOURS filtrer par ce champ dans les vues', on_delete=django.db.models.deletion.PROTECT, related_name='fedow_transactions', to='Customers.client', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['tenant', 'datetime'], name='fedow_core__tenant__317d26_idx'), models.Index(fields=['sender', 'datetime'], name='fedow_core__sender__f18800_idx'), models.Index(fields=['receiver', 'datetime'], name='fedow_core__receive_7081b2_idx'), models.Index(fields=['asset', 'datetime'], name='fedow_core__asset_i_521230_idx'), models.Index(fields=['action'], name='fedow_core__action_77f255_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='token',
            constraint=models.UniqueConstraint(fields=('wallet', 'asset'), name='unique_token_per_wallet_asset'),
        ),
    ]
