# Generated by Django 4.2.28 on 2026-02-28 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0004_alter_client_categorie_alter_client_on_trial'),
        ('fedow_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='federation',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Le lieu qui a cree cette federation. Lui seul peut envoyer des invitations.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='federations_created', to='Customers.client', verbose_name='Cree par'),
        ),
        migrations.AddField(
            model_name='federation',
            name='pending_tenants',
            field=models.ManyToManyField(blank=True, help_text="Lieux invites a rejoindre cette federation. Ils verront l'invitation dans leur admin et pourront accepter.", related_name='federation_invitations_pending', to='Customers.client', verbose_name='Invitations en attente'),
        ),
        migrations.AlterField(
            model_name='federation',
            name='tenants',
            field=models.ManyToManyField(blank=True, help_text='Lieux qui ont accepte de rejoindre cette federation.', related_name='federations', to='Customers.client', verbose_name='Tenants membres'),
        ),
    ]
