# Generated by Django 4.2.30 on 2026-04-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fedow_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='action',
            field=models.CharField(choices=[('FST', 'Genesis'), ('CRE', 'Creation'), ('RFL', 'Recharge'), ('SAL', 'Vente'), ('QRS', 'Vente QR'), ('FUS', 'Fusion'), ('RFD', 'Remboursement'), ('VOI', 'Annulation'), ('DEP', 'Depot bancaire'), ('TRF', 'Virement'), ('BTR', 'Virement bancaire pot central')], max_length=3, verbose_name='Action'),
        ),
    ]
