# Generated by Django 4.2.28 on 2026-02-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0004_alter_client_categorie_alter_client_on_trial'),
        ('fedow_core', '0002_add_federation_invitation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='federated_with',
            field=models.ManyToManyField(blank=True, help_text='Lieux qui ont accepte de partager cet asset.', related_name='assets_federated', to='Customers.client', verbose_name='Lieux federes'),
        ),
        migrations.AddField(
            model_name='asset',
            name='pending_invitations',
            field=models.ManyToManyField(blank=True, help_text="Lieux invites a partager cet asset. Ils verront l'invitation dans leur admin et pourront accepter.", related_name='asset_invitations_pending', to='Customers.client', verbose_name='Invitations en attente'),
        ),
    ]
