# Generated by Django 4.2.10 on 2024-02-15 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RsaKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_pem', models.CharField(editable=False, max_length=2048)),
                ('public_pem', models.CharField(editable=False, max_length=512)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FedowConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fedow_place_uuid', models.UUIDField(blank=True, editable=False, null=True)),
                ('fedow_place_wallet_uuid', models.UUIDField(blank=True, editable=False, null=True)),
                ('fedow_place_admin_apikey', models.CharField(blank=True, editable=False, max_length=41, null=True)),
                ('fedow_place_wallet_public_pem', models.CharField(blank=True, editable=False, max_length=500, null=True)),
                ('rsa_key', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fedow_connect.rsakey')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
