# Generated by Django 4.2.11 on 2024-04-18 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AuthBillet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FedowConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fedow_place_uuid', models.UUIDField(blank=True, editable=False, null=True)),
                ('fedow_place_admin_apikey', models.CharField(blank=True, editable=False, max_length=200, null=True)),
                ('fedow_place_wallet_uuid', models.UUIDField(blank=True, editable=False, null=True)),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place', to='AuthBillet.wallet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
