# Generated by Django 4.2.10 on 2024-02-15 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fedow_connect', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fedowconfig',
            name='rsa_key',
        ),
        migrations.DeleteModel(
            name='RsaKey',
        ),
    ]
