# Generated by Django 4.2.11 on 2024-05-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fedow_connect', '0005_fedowconfig_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='fedowconfig',
            name='json_key_to_cashless',
            field=models.CharField(blank=True, editable=False, max_length=500, null=True),
        ),
    ]
