# Generated by Django 4.2 on 2024-10-31 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fedow_connect', '0006_fedowconfig_json_key_to_cashless'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fedowconfig',
            name='json_key_to_cashless',
        ),
    ]
