# Generated by Django 4.2.23 on 2025-08-24 11:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('AuthBillet', '0021_alter_tibilletuser_offre'),
        ('fedow_connect', '0007_remove_fedowconfig_json_key_to_cashless'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('currency_code', models.CharField(max_length=3)),
                ('archive', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name="Dernière modification des informations de l'asset")),
                ('comment', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('TLF', 'Fiduciaire'), ('TNF', 'Cadeau'), ('FED', 'Fiduciaire fédérée'), ('TIM', 'Monnaie temps'), ('FID', 'Points de fidélité'), ('BDG', 'Badgeuse/Pointeuse'), ('SUB', 'Adhésion ou abonnement')], max_length=3)),
                ('id_price_stripe', models.CharField(blank=True, editable=False, max_length=30, null=True)),
                ('wallet_origin', models.ForeignKey(help_text="Lieu ou configuration d'origine", on_delete=django.db.models.deletion.PROTECT, related_name='assets_created', to='AuthBillet.wallet')),
            ],
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(condition=models.Q(('category', 'FED')), fields=('category',), name='unique_stripe_primary_asset'),
        ),
    ]
