# Generated by Django 4.2.24 on 2025-09-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0004_alter_client_categorie_alter_client_on_trial'),
        ('fedow_connect', '0008_asset_asset_unique_stripe_primary_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='active',
            field=models.BooleanField(default=False, help_text='Un lieux vous a peut être invité à partager cet actif ? Validez en cochant la case et sauvegardez.', verbose_name='Activer cet actif'),
        ),
        migrations.AddField(
            model_name='asset',
            name='federated_with',
            field=models.ManyToManyField(blank=True, help_text='Lieux fédérés', related_name='federated_assets', to='Customers.client', verbose_name='Lieux fédérés'),
        ),
        migrations.AddField(
            model_name='asset',
            name='invitation_to_federated_with',
            field=models.ManyToManyField(blank=True, help_text='Ajoutez un lieux a partager cet actif, il recevra un mail de confirmation. Une fois validé, il disparaitra de cette liste pour aller dans celle ci dessous', related_name='invitation_to_federated_with', to='Customers.client', verbose_name='Inviter un lieux à partager cet actif'),
        ),
    ]
