# Generated by Django 4.2.24 on 2025-09-25 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fedow_connect', '0009_asset_active_asset_federated_with_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asset',
        ),
    ]
