# Generated by Django 4.2.11 on 2024-04-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RootConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuseau_horaire', models.CharField(choices=[('Indian/Reunion', 'Indian/Reunion'), ('Europe/Paris', 'Europe/Paris')], default='Indian/Reunion', max_length=50)),
                ('stripe_api_key', models.CharField(blank=True, max_length=110, null=True)),
                ('stripe_test_api_key', models.CharField(blank=True, max_length=110, null=True)),
                ('stripe_mode_test', models.BooleanField(default=True)),
                ('fedow_domain', models.URLField(blank=True, editable=False, null=True)),
                ('fedow_ip', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('fedow_create_place_apikey', models.CharField(blank=True, editable=False, max_length=200, null=True)),
                ('fedow_primary_pub_pem', models.CharField(blank=True, editable=False, max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
