# Generated by Django 4.2.10 on 2024-02-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_billet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rootconfiguration',
            name='fedow_domain',
            field=models.URLField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='rootconfiguration',
            name='fedow_ip',
            field=models.GenericIPAddressField(blank=True, editable=False, null=True),
        ),
    ]
