# Generated by Django 4.2.10 on 2024-02-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_billet', '0002_rootconfiguration_fedow_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rootconfiguration',
            name='fedow_create_place_apikey',
            field=models.CharField(blank=True, editable=False, max_length=110, null=True),
        ),
    ]
