# Generated by Django 4.2.10 on 2024-02-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_billet', '0003_rootconfiguration_fedow_create_place_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='rootconfiguration',
            name='fedow_primary_pub_pem',
            field=models.CharField(blank=True, editable=False, max_length=500, null=True),
        ),
    ]
