# Generated by Django 4.2.11 on 2024-05-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_billet', '0005_alter_rootconfiguration_fedow_create_place_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rootconfiguration',
            name='stripe_api_key',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='rootconfiguration',
            name='stripe_test_api_key',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
