# Generated by Django 4.2.30 on 2026-07-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_billet', '0006_alter_rootconfiguration_stripe_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rootconfiguration',
            name='domaines_embed_autorises',
            field=models.TextField(blank=True, default='', help_text='Un domaine par ligne (ex. newsletter.ghost.io). Ces hotes seuls peuvent etre integres dans un bloc « Contenu integre libre ».', verbose_name="Domaines d'integration autorises (iframe)"),
        ),
    ]
