# Generated by Django 3.2 on 2022-05-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='categorie',
            field=models.CharField(choices=[('A', 'Artiste'), ('S', 'Lieu de spectacle vivant'), ('F', 'Festival'), ('T', 'Tourneur'), ('P', 'Producteur'), ('M', 'Agenda culturel'), ('R', 'Tenant public root')], default='S', max_length=3, verbose_name='Categorie'),
        ),
    ]
