# Generated by Django 4.2.17 on 2025-03-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0002_alter_client_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='categorie',
            field=models.CharField(choices=[('A', 'Artist'), ('S', 'Scene'), ('F', 'Festival'), ('T', 'Tour operator'), ('P', 'Producer'), ('M', 'Event aggregator'), ('R', 'Root public tenant')], default='S', max_length=3, verbose_name='Category'),
        ),
    ]
