# Generated by Django 4.2.21 on 2025-06-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0003_alter_client_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='categorie',
            field=models.CharField(choices=[('A', 'Artist'), ('S', 'Scene'), ('F', 'Festival'), ('T', 'Tour operator'), ('P', 'Producer'), ('M', 'Event aggregator'), ('W', 'Waiting configuration'), ('R', 'Root public tenant')], default='S', max_length=3, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='client',
            name='on_trial',
            field=models.BooleanField(default=False),
        ),
    ]
