# Generated by Django 4.2.30 on 2026-04-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0004_alter_client_categorie_alter_client_on_trial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='categorie',
            field=models.CharField(choices=[('A', 'Artist'), ('S', 'Scene'), ('F', 'Festival'), ('T', 'Tour operator'), ('P', 'Producer'), ('M', 'Event aggregator'), ('W', 'Waiting configuration'), ('R', 'Root public tenant'), ('E', 'Federation currency')], default='S', max_length=3, verbose_name='Category'),
        ),
    ]
