# Generated by Django 4.2.30 on 2026-09-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0004_alter_client_categorie_alter_client_on_trial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='created_on',
            field=models.DateField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Nom du lieu'),
        ),
    ]
