# Generated by Django 2.2 on 2021-06-23 09:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('Customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TibilletUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('espece', models.CharField(choices=[('TE', 'Terminal'), ('AN', 'Android'), ('HU', 'Humain')], default='HU', max_length=2)),
                ('offre', models.CharField(choices=[('PU', 'Public'), ('FR', 'Gratuit'), ('PR', 'Premium'), ('EN', 'Entreprise'), ('CU', 'Custom')], default='PU', max_length=2)),
                ('client_achat', models.ManyToManyField(blank=True, related_name='user_achats', to='Customers.Client')),
                ('client_admin', models.ManyToManyField(blank=True, related_name='user_admin', to='Customers.Client')),
                ('client_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_principal', to='Customers.Client', verbose_name='Inscription depuis')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HumanUser',
            fields=[
            ],
            options={
                'verbose_name': 'Utilisateur',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('AuthBillet.tibilletuser',),
        ),
        migrations.CreateModel(
            name='SuperHumanUser',
            fields=[
            ],
            options={
                'verbose_name': 'Administrateur',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('AuthBillet.tibilletuser',),
        ),
        migrations.CreateModel(
            name='TermUser',
            fields=[
            ],
            options={
                'verbose_name': 'Terminal',
                'verbose_name_plural': 'Terminaux',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('AuthBillet.tibilletuser',),
        ),
    ]
