# Generated by Django 2.2 on 2021-06-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthBillet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tibilletuser',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
