# Generated by Django 2.2 on 2021-06-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthBillet', '0002_tibilletuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tibilletuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
