# Generated by Django 3.2 on 2022-02-20 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthBillet', '0002_alter_membership_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
