# Generated by Django 2.2 on 2021-10-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthBillet', '0002_auto_20211022_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tibilletuser',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
