# Generated by Django 2.2 on 2021-11-11 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0001_initial'),
        ('AuthBillet', '0003_auto_20211022_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='tibilletuser',
            name='accept_newsletter',
            field=models.BooleanField(default=True, verbose_name="J'accepte de recevoir la newsletter"),
        ),
        migrations.AddField(
            model_name='tibilletuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tibilletuser',
            name='last_see',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tibilletuser',
            name='postal_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('first_contribution', models.DateField(blank=True, null=True)),
                ('last_contribution', models.DateField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Customers.Client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
