# Generated by Django 2.2 on 2021-11-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthBillet', '0004_auto_20211111_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tibilletuser',
            name='first_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tibilletuser',
            name='last_name',
            field=models.CharField(max_length=200),
        ),
    ]
