# Generated by Django 2.2 on 2021-11-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthBillet', '0005_auto_20211112_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tibilletuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tibilletuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
