# Generated by Django 2.2 on 2021-11-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthBillet', '0006_auto_20211112_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='contribution_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
