# Generated by Django 4.2.29 on 2026-05-15 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClotureCaisse',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('niveau', models.CharField(choices=[('J', 'Daily'), ('H', 'Weekly'), ('M', 'Monthly'), ('A', 'Yearly')], default='J', help_text='Daily closure aggregates one day. Weekly/monthly/yearly aggregate the matching daily closures.', max_length=1, verbose_name='Periodicity')),
                ('numero_sequentiel', models.PositiveIntegerField(help_text='Continuous global counter per tenant (LNE compliance). Shared across all periodicities (daily, weekly, monthly, yearly).', unique=True, verbose_name='Sequential number')),
                ('datetime_debut', models.DateTimeField(verbose_name='Period start')),
                ('datetime_fin', models.DateTimeField(verbose_name='Period end')),
                ('total_general', models.IntegerField(default=0, verbose_name='Total TTC (cents)')),
                ('total_ht', models.IntegerField(default=0, verbose_name='Total HT (cents)')),
                ('total_tva', models.IntegerField(default=0, verbose_name='Total VAT (cents)')),
                ('nombre_transactions', models.IntegerField(default=0, verbose_name='Number of transactions')),
                ('total_perpetuel', models.IntegerField(default=0, help_text='Sum of total_general of all daily closures since tenant creation. Safety check against retroactive modification.', verbose_name='Perpetual total (cents)')),
                ('hash_lignes', models.CharField(blank=True, help_text='SHA-256 of sorted (pk, amount, qty, status) tuples of every LigneArticle covered. Changes if any line is altered post-closure.', max_length=64, verbose_name='Lines hash')),
                ('rapport_json', models.JSONField(default=dict, help_text='Full report sections (totals by payment method, sales by category, VAT breakdown, memberships, tickets, refunds, synthesis, legal info).', verbose_name='Report payload')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.ForeignKey(blank=True, help_text='User who triggered a manual closure. Null if Celery auto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clotures_caisse', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
            ],
            options={
                'verbose_name': 'Cash closure',
                'verbose_name_plural': 'Cash closures',
                'ordering': ['-datetime_fin', '-numero_sequentiel'],
                'indexes': [models.Index(fields=['niveau', '-datetime_fin'], name='comptabilit_niveau_465d61_idx'), models.Index(fields=['-numero_sequentiel'], name='comptabilit_numero__439893_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='cloturecaisse',
            constraint=models.UniqueConstraint(fields=('niveau', 'datetime_debut', 'datetime_fin'), name='unique_cloture_periode'),
        ),
    ]
