# Generated by Django 4.2.30 on 2026-05-15 16:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


def _seed_comptes_et_mappings(apps, schema_editor):
    """
    Seed initial : 9 comptes PCG francais + 13 mappings PaymentMethod.
    / Initial seed: 9 French PCG accounts + 13 PaymentMethod mappings.

    IMPORTANT : modeles TENANT_APP. La table n'existe pas dans le schema public.
    On retourne immediatement si on est dans public.
    / IMPORTANT: TENANT_APP models. Tables don't exist in public schema. Return if public.
    """
    from django.db import connection
    if connection.schema_name == "public":
        return

    CompteComptable = apps.get_model("comptabilite", "CompteComptable")
    MappingMoyenDePaiement = apps.get_model("comptabilite", "MappingMoyenDePaiement")

    # --- 9 comptes par defaut (plan comptable francais PCG)
    # / 9 default accounts (French PCG)
    comptes_seed = [
        ("411000", "Clients", "C"),
        ("512000", "Banque", "B"),
        ("530000", "Caisse (especes)", "B"),
        ("511000", "Cheques a encaisser", "B"),
        ("4457100", "TVA collectee 5.5%", "T"),
        ("4457200", "TVA collectee 10%", "T"),
        ("4457300", "TVA collectee 20%", "T"),
        ("706000", "Prestations de services (billets)", "V"),
        ("756000", "Cotisations (adhesions)", "V"),
    ]
    comptes_par_numero = {}
    for numero, libelle, type_compte in comptes_seed:
        compte, _ = CompteComptable.objects.get_or_create(
            numero=numero,
            defaults={"libelle": libelle, "type_compte": type_compte},
        )
        comptes_par_numero[numero] = compte

    # --- 13 mappings PaymentMethod -> compte de tresorerie/client
    # / 13 PaymentMethod -> treasury/client account mappings
    mappings_seed = [
        ("CC", "512000"),   # CB TPE
        ("CA", "530000"),   # Especes
        ("CH", "511000"),   # Cheque
        ("TR", "512000"),   # Virement
        ("SF", "512000"),   # Stripe federe
        ("SN", "512000"),   # Stripe NoFedow
        ("SP", "512000"),   # Stripe SEPA
        ("SR", "512000"),   # Stripe recurrent
        ("QR", "512000"),   # QR / NFC
        ("LE", "411000"),   # Asset local euro
        ("LG", "411000"),   # Asset local gift
        ("NA", "512000"),   # Offert (place-holder, jamais utilise pour ventilation)
        ("UK", "512000"),   # Inconnu
    ]
    for payment_method, numero_compte in mappings_seed:
        compte = comptes_par_numero.get(numero_compte)
        if compte:
            MappingMoyenDePaiement.objects.get_or_create(
                payment_method=payment_method,
                defaults={"compte": compte},
            )


def _reverse_seed(apps, schema_editor):
    """No-op : on ne supprime pas les comptes a la migration reverse."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteComptable',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=12, unique=True, verbose_name='Account number')),
                ('libelle', models.CharField(max_length=120, verbose_name='Label')),
                ('type_compte', models.CharField(choices=[('V', 'Sales'), ('T', 'VAT collected'), ('B', 'Cash / Bank'), ('C', 'Customers'), ('X', 'Other')], max_length=1, verbose_name='Account type')),
                ('actif', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Accounting account',
                'verbose_name_plural': 'Accounting accounts',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='MappingMoyenDePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(help_text='PaymentMethod code from BaseBillet (CC, CA, CH, TR, SF, ...)', max_length=2, unique=True, verbose_name='Payment method')),
                ('compte', models.ForeignKey(limit_choices_to={'type_compte__in': ['B', 'C']}, on_delete=django.db.models.deletion.PROTECT, to='comptabilite.comptecomptable', verbose_name='Accounting account')),
            ],
            options={
                'verbose_name': 'Payment method mapping',
                'verbose_name_plural': 'Payment method mappings',
                'ordering': ['payment_method'],
            },
        ),
        migrations.RunPython(_seed_comptes_et_mappings, reverse_code=_reverse_seed),
    ]
