# Generated by Django 4.2.30 on 2026-05-19 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comptabilite', '0002_comptecomptable_mappingmoyendepaiement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cloturecaisse',
            options={'ordering': ['-datetime_fin', '-numero_sequentiel'], 'verbose_name': 'Clôture de caisse', 'verbose_name_plural': 'Clôtures de caisse'},
        ),
        migrations.AlterModelOptions(
            name='comptecomptable',
            options={'ordering': ['numero'], 'verbose_name': 'Compte comptable', 'verbose_name_plural': 'Comptes comptables'},
        ),
        migrations.AlterModelOptions(
            name='mappingmoyendepaiement',
            options={'ordering': ['payment_method'], 'verbose_name': 'Mapping moyen de paiement', 'verbose_name_plural': 'Mappings moyens de paiement'},
        ),
        migrations.AlterField(
            model_name='cloturecaisse',
            name='datetime_debut',
            field=models.DateTimeField(verbose_name='Début de la période'),
        ),
        migrations.AlterField(
            model_name='cloturecaisse',
            name='datetime_fin',
            field=models.DateTimeField(verbose_name='Fin de la période'),
        ),
        migrations.AlterField(
            model_name='cloturecaisse',
            name='hash_lignes',
            field=models.CharField(blank=True, help_text='SHA-256 des tuples (pk, montant, qte, statut) triés de chaque LigneArticle couverte. Change si une ligne est altérée après clôture.', max_length=64, verbose_name='Empreinte des lignes'),
        ),
        migrations.AlterField(
            model_name='cloturecaisse',
            name='niveau',
            field=models.CharField(choices=[('J', 'Journalière'), ('H', 'Hebdomadaire'), ('M', 'Mensuelle'), ('A', 'Annuelle')], default='J', help_text='La clôture journalière agrège une journée. Les clôtures hebdomadaire, mensuelle et annuelle agrègent les clôtures journalières correspondantes.', max_length=1, verbose_name='Périodicité'),
        ),
        migrations.AlterField(
            model_name='cloturecaisse',
            name='nombre_transactions',
            field=models.IntegerField(default=0, verbose_name='Nombre de transactions'),
        ),
        migrations.AlterField(
            model_name='cloturecaisse',
            name='numero_sequentiel',
            field=models.PositiveIntegerField(help_text='Compteur continu global par tenant (conformité LNE). Partagé entre toutes les périodicités (journalière, hebdomadaire, mensuelle, annuelle).', unique=True, verbose_name='Numéro séquentiel'),
        ),
        migrations.AlterField(
            model_name='cloturecaisse',
            name='rapport_json',
            field=models.JSONField(default=dict, help_text='Sections complètes du rapport (totaux par moyen de paiement, ventes par catégorie, ventilation TVA, adhésions, billets, remboursements, synthèse, informations légales).', verbose_name='Contenu du rapport'),
        ),
        migrations.AlterField(
            model_name='cloturecaisse',
            name='responsable',
            field=models.ForeignKey(blank=True, help_text='Utilisateur ayant déclenché une clôture manuelle. Vide si déclenchement automatique par Celery.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clotures_caisse', to=settings.AUTH_USER_MODEL, verbose_name='Opérateur'),
        ),
        migrations.AlterField(
            model_name='cloturecaisse',
            name='total_general',
            field=models.IntegerField(default=0, verbose_name='Total TTC (centimes)'),
        ),
        migrations.AlterField(
            model_name='cloturecaisse',
            name='total_ht',
            field=models.IntegerField(default=0, verbose_name='Total HT (centimes)'),
        ),
        migrations.AlterField(
            model_name='cloturecaisse',
            name='total_perpetuel',
            field=models.IntegerField(default=0, help_text='Somme des total_general de toutes les clôtures journalières depuis la création du tenant. Filet de sécurité contre toute modification rétroactive.', verbose_name='Total perpétuel (centimes)'),
        ),
        migrations.AlterField(
            model_name='cloturecaisse',
            name='total_tva',
            field=models.IntegerField(default=0, verbose_name='Total TVA (centimes)'),
        ),
        migrations.AlterField(
            model_name='comptecomptable',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='comptecomptable',
            name='libelle',
            field=models.CharField(max_length=120, verbose_name='Libellé'),
        ),
        migrations.AlterField(
            model_name='comptecomptable',
            name='numero',
            field=models.CharField(max_length=12, unique=True, verbose_name='Numéro de compte'),
        ),
        migrations.AlterField(
            model_name='comptecomptable',
            name='type_compte',
            field=models.CharField(choices=[('V', 'Ventes'), ('T', 'TVA collectée'), ('B', 'Trésorerie (banque / caisse)'), ('C', 'Clients'), ('X', 'Autre')], max_length=1, verbose_name='Type de compte'),
        ),
        migrations.AlterField(
            model_name='mappingmoyendepaiement',
            name='compte',
            field=models.ForeignKey(limit_choices_to={'type_compte__in': ['B', 'C']}, on_delete=django.db.models.deletion.PROTECT, to='comptabilite.comptecomptable', verbose_name='Compte comptable'),
        ),
        migrations.AlterField(
            model_name='mappingmoyendepaiement',
            name='payment_method',
            field=models.CharField(help_text='Code PaymentMethod de BaseBillet (CC, CA, CH, TR, SF, ...)', max_length=2, unique=True, verbose_name='Moyen de paiement'),
        ),
    ]
