# Generated by Django 4.2.30 on 2026-10-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0003_alter_cloturecaisse_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappingmoyendepaiement',
            name='compte',
        ),
        migrations.RemoveField(
            model_name='cloturecaisse',
            name='hash_lignes',
        ),
        migrations.AddField(
            model_name='cloturecaisse',
            name='hmac_hash',
            field=models.CharField(blank=True, default='', help_text='Empreinte HMAC de la clôture, chaînée avec la clôture précédente.', max_length=64, verbose_name='Empreinte'),
        ),
        migrations.AddField(
            model_name='cloturecaisse',
            name='nombre_ventes_perpetuel',
            field=models.IntegerField(default=0, help_text='Somme des nombres de ventes de toutes les clôtures journalières depuis la mise en service.', verbose_name='Nombre de ventes perpétuel'),
        ),
        migrations.AddField(
            model_name='cloturecaisse',
            name='numero_derniere_vente',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Numéro de la dernière vente'),
        ),
        migrations.AddField(
            model_name='cloturecaisse',
            name='numero_premiere_vente',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Numéro de la première vente'),
        ),
    ]
