# Generated by Django 4.2.30 on 2026-10-02 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0003_alter_cloturecaisse_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappingmoyendepaiement',
            name='compte',
        ),
        migrations.DeleteModel(
            name='CompteComptable',
        ),
        migrations.DeleteModel(
            name='MappingMoyenDePaiement',
        ),
    ]
