# Generated by Django 4.2.30 on 2026-10-03 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboutik', '0013_ranger_les_crowds_dans_le_financement_participatif'),
        ('comptabilite', '0004_retirer_l_ancien_plan_comptable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloturecaisse',
            name='hash_lignes',
        ),
        migrations.AddField(
            model_name='cloturecaisse',
            name='hmac_hash',
            field=models.CharField(blank=True, default='', help_text='Empreinte HMAC de la clôture, chaînée avec la clôture précédente.', max_length=64, verbose_name='Empreinte'),
        ),
        migrations.AddField(
            model_name='cloturecaisse',
            name='nombre_ventes_perpetuel',
            field=models.IntegerField(default=0, help_text='Somme des nombres de ventes de toutes les clôtures journalières depuis la mise en service.', verbose_name='Nombre de ventes perpétuel'),
        ),
        migrations.AddField(
            model_name='cloturecaisse',
            name='numero_derniere_vente',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Numéro de la dernière vente'),
        ),
        migrations.AddField(
            model_name='cloturecaisse',
            name='numero_premiere_vente',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Numéro de la première vente'),
        ),
        migrations.AddField(
            model_name='cloturecaisse',
            name='point_de_vente',
            field=models.ForeignKey(blank=True, help_text='Poste depuis lequel la clôture a été lancée (pour information).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clotures_comptables', to='laboutik.pointdevente', verbose_name='Point de vente'),
        ),
        migrations.AddField(
            model_name='cloturecaisse',
            name='previous_hmac',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Empreinte précédente'),
        ),
        migrations.AddField(
            model_name='cloturecaisse',
            name='total_argent_recu',
            field=models.IntegerField(default=0, help_text="Tout l'argent entré moins tout l'argent sorti sur la période.", verbose_name='Argent reçu (centimes)'),
        ),
        migrations.AlterField(
            model_name='cloturecaisse',
            name='niveau',
            field=models.CharField(choices=[('J', 'Journalière'), ('H', 'Hebdomadaire'), ('M', 'Mensuelle'), ('A', 'Annuelle')], default='J', help_text="La clôture journalière va de la clôture journalière précédente à la fin du service. Les clôtures hebdomadaire, mensuelle et annuelle comptent les ventes de la semaine, du mois ou de l'année, en heure locale du lieu.", max_length=1, verbose_name='Périodicité'),
        ),
        migrations.AlterField(
            model_name='cloturecaisse',
            name='nombre_transactions',
            field=models.IntegerField(default=0, verbose_name='Nombre de ventes'),
        ),
        migrations.AlterField(
            model_name='cloturecaisse',
            name='rapport_json',
            field=models.JSONField(default=dict, help_text='Toutes les sections du rapport des ventes, figées au moment de la clôture.', verbose_name='Contenu du rapport'),
        ),
        migrations.AlterField(
            model_name='cloturecaisse',
            name='total_general',
            field=models.IntegerField(default=0, help_text="Chiffre d'affaires TTC de la période.", verbose_name='Total TTC (centimes)'),
        ),
        migrations.AlterField(
            model_name='cloturecaisse',
            name='total_perpetuel',
            field=models.IntegerField(default=0, help_text='Somme des totaux TTC de toutes les clôtures journalières depuis la mise en service. Jamais remis à zéro.', verbose_name='Total perpétuel (centimes)'),
        ),
    ]
