# Generated by Django 4.2.29 on 2026-03-20 05:12

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(help_text='UID hex sans espaces', max_length=32, unique=True)),
                ('label', models.CharField(blank=True, max_length=100, verbose_name='Nom carte')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Valide depuis')),
                ('valid_to', models.DateTimeField(blank=True, null=True, verbose_name='Fin de validité')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Solde en unité (ex: patate)', max_digits=12)),
            ],
            options={
                'verbose_name': 'Carte',
                'verbose_name_plural': 'Cartes',
            },
        ),
        migrations.CreateModel(
            name='CarteMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(help_text='UID hex sans espaces', max_length=32, unique=True, verbose_name='UID')),
                ('label', models.CharField(blank=True, max_length=100, verbose_name='Nom')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('produit', models.CharField(blank=True, help_text='Ex : Eau, Désinfectant, Alcool isopropylique…', max_length=100, verbose_name='Produit de nettoyage')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Carte maintenance',
                'verbose_name_plural': 'Cartes maintenance',
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_self_register', models.BooleanField(default=False, help_text="Activez temporairement pour qu'un nouveau Pi puisse s'enregistrer automatiquement au démarrage. Désactivez après l'enregistrement.", verbose_name="Autoriser l'auto-enregistrement des Pi")),
            ],
            options={
                'verbose_name': 'Configuration serveur',
                'verbose_name_plural': 'Configuration serveur',
            },
        ),
        migrations.CreateModel(
            name='Debimetre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Modèle du débitmètre (ex: YF-S201, FS300A)', max_length=100, verbose_name='Modèle')),
                ('flow_calibration_factor', models.FloatField(default=6.5, help_text='Facteur de calibration (Hz par L/min) — 1 L = facteur × 60 impulsions', verbose_name='Facteur de calibration')),
            ],
            options={
                'verbose_name': 'Débitmètre',
                'verbose_name_plural': 'Débitmètres',
            },
        ),
        migrations.CreateModel(
            name='Fut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la bière')),
                ('brasseur', models.CharField(blank=True, max_length=100, verbose_name='Brasseur')),
                ('type_biere', models.CharField(choices=[('blonde', 'Blonde'), ('brune', 'Brune'), ('ambree', 'Ambrée'), ('blanche', 'Blanche'), ('ipa', 'IPA'), ('stout', 'Stout'), ('lager', 'Lager'), ('autre', 'Autre')], default='blonde', max_length=20, verbose_name='Type')),
                ('degre_alcool', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4, verbose_name="Degré d'alcool (%)")),
                ('volume_fut_l', models.DecimalField(decimal_places=1, default=Decimal('30.0'), max_digits=6, verbose_name='Volume du fût (L)')),
                ('quantite_stock', models.PositiveIntegerField(default=0, verbose_name='Quantité en stock')),
                ('prix_achat', models.DecimalField(blank=True, decimal_places=2, help_text="Prix d'achat du fût (facultatif)", max_digits=8, null=True, verbose_name="Prix d'achat (€)")),
                ('prix_litre', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Prix de vente par litre pour ce fût', max_digits=8, verbose_name='Prix au litre (€)')),
            ],
            options={
                'verbose_name': 'Fût',
                'verbose_name_plural': 'Fûts',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='TireuseBec',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_tireuse', models.CharField(help_text="Nom affiché: ex. 'Bière', 'Soft'", max_length=50)),
                ('enabled', models.BooleanField(default=True, verbose_name='En service')),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('nom_boisson', models.CharField(default='Liquide', help_text='Nom affiché du liquide', max_length=100)),
                ('monnaie', models.CharField(default='patate', help_text="Nom de l'unité de solde (ex: patate)", max_length=20)),
                ('prix_litre_override', models.DecimalField(blank=True, decimal_places=2, help_text='Laisser vide pour utiliser le prix du fût. Renseigner pour forcer un prix sur cette tireuse (réservé admin).', max_digits=8, null=True, verbose_name='Prix au litre (override)')),
                ('reservoir_ml', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Volume courant en ml (décrémenté en temps réel)', max_digits=10, verbose_name='Volume restant')),
                ('seuil_mini_ml', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Seuil bas en ml (on réserve ce volume)', max_digits=10)),
                ('appliquer_reserve', models.BooleanField(default=True, help_text='Appliquer la réserve (stock - seuil)')),
                ('debimetre', models.ForeignKey(blank=True, help_text='Débitmètre associé (détermine le facteur de calibration)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tireuses', to='controlvanne.debimetre')),
                ('fut_actif', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tireuses_actives', to='controlvanne.fut', verbose_name='Fût en service')),
            ],
            options={
                'verbose_name': 'Tireuse',
                'verbose_name_plural': 'Tireuses',
            },
        ),
        migrations.CreateModel(
            name='RfidSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(db_index=True, max_length=32)),
                ('label_snapshot', models.CharField(blank=True, help_text='Copie du label au début', max_length=100, verbose_name='Nom carte')),
                ('authorized', models.BooleanField(default=False, verbose_name='En service')),
                ('liquid_label_snapshot', models.CharField(blank=True, help_text='Copie du nom du liquide au début', max_length=100, verbose_name='Nom boisson')),
                ('unit_label_snapshot', models.CharField(blank=True, default='', max_length=20)),
                ('unit_ml_snapshot', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=8)),
                ('allowed_ml_session', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('charged_units', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Début')),
                ('ended_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Fin')),
                ('volume_start_ml', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('volume_end_ml', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('volume_delta_ml', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('dernier_volume_ml', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_maintenance', models.BooleanField(default=False, verbose_name='Session maintenance')),
                ('is_calibration', models.BooleanField(default=False, verbose_name='Session calibration')),
                ('volume_reel_ml', models.DecimalField(blank=True, decimal_places=2, help_text='Volume mesuré physiquement dans un verre gradué', max_digits=10, null=True, verbose_name='Volume réel (ml)')),
                ('produit_maintenance_snapshot', models.CharField(blank=True, max_length=100, verbose_name='Produit utilisé')),
                ('balance_avant', models.DecimalField(blank=True, decimal_places=2, help_text='Solde de la carte au début de la session', max_digits=12, null=True, verbose_name='Solde avant')),
                ('balance_apres', models.DecimalField(blank=True, decimal_places=2, help_text='Solde de la carte après facturation', max_digits=12, null=True, verbose_name='Solde après')),
                ('last_message', models.TextField(blank=True, default='')),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='controlvanne.card')),
                ('carte_maintenance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='controlvanne.cartemaintenance', verbose_name='Carte maintenance')),
                ('tireuse_bec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='controlvanne.tireusebec', verbose_name='Nom tireuse')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueFut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mis_en_service_le', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Mis en service le')),
                ('retire_le', models.DateTimeField(blank=True, null=True, verbose_name='Retiré le')),
                ('volume_initial_ml', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Volume initial (ml)')),
                ('volume_final_ml', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Volume final (ml)')),
                ('fut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='controlvanne.fut', verbose_name='Fût')),
                ('tireuse_bec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_futs', to='controlvanne.tireusebec', verbose_name='Tireuse')),
            ],
            options={
                'verbose_name': 'Historique fût',
                'verbose_name_plural': 'Historique fûts',
                'ordering': ['-mis_en_service_le'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueCarte',
            fields=[
            ],
            options={
                'verbose_name': 'Historique carte',
                'verbose_name_plural': 'Historique cartes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('controlvanne.rfidsession',),
        ),
        migrations.CreateModel(
            name='HistoriqueMaintenance',
            fields=[
            ],
            options={
                'verbose_name': 'Historique maintenance',
                'verbose_name_plural': 'Historique maintenances',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('controlvanne.rfidsession',),
        ),
        migrations.CreateModel(
            name='HistoriqueTireuse',
            fields=[
            ],
            options={
                'verbose_name': 'Historique tireuse',
                'verbose_name_plural': 'Historique tireuses',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('controlvanne.rfidsession',),
        ),
        migrations.CreateModel(
            name='SessionCalibration',
            fields=[
            ],
            options={
                'verbose_name': 'Session calibration',
                'verbose_name_plural': 'Sessions calibration',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('controlvanne.rfidsession',),
        ),
    ]
