# Generated by Django 6.0.3 on 2026-03-30 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlvanne', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tireusebec',
            name='nom_boisson',
        ),
    ]
