# Generated by Django 4.2.29 on 2026-04-06 08:20

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('QrcodeCashless', '0021_cartecashless_wallet_ephemere'),
        ('BaseBillet', '0205_lignearticle_point_de_vente_and_more'),
        ('discovery', '0002_alter_pairingdevice_pin_code'),
        ('laboutik', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarteMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.CharField(blank=True, max_length=100, verbose_name='Cleaning product')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('carte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carte_maintenance', to='QrcodeCashless.cartecashless', verbose_name='NFC card')),
            ],
            options={
                'verbose_name': 'Maintenance card',
                'verbose_name_plural': 'Maintenance cards',
            },
        ),
        migrations.CreateModel(
            name='ConfigurationTireuse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Tap module configuration',
                'verbose_name_plural': 'Tap module configuration',
            },
        ),
        migrations.CreateModel(
            name='Debimetre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Flow meter model (e.g. YF-S201, FS300A)', max_length=100, verbose_name='Model')),
                ('flow_calibration_factor', models.FloatField(default=6.5, help_text='Calibration factor (Hz per L/min) — 1 L = factor × 60 pulses', verbose_name='Calibration factor')),
            ],
            options={
                'verbose_name': 'Flow meter',
                'verbose_name_plural': 'Flow meters',
            },
        ),
        migrations.CreateModel(
            name='TireuseAPIKey',
            fields=[
                ('id', models.CharField(editable=False, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('prefix', models.CharField(editable=False, max_length=8, unique=True)),
                ('hashed_key', models.CharField(editable=False, max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('name', models.CharField(default=None, help_text='A free-form name for the API key. Need not be unique. 50 characters max.', max_length=50)),
                ('revoked', models.BooleanField(blank=True, default=False, help_text='If the API key is revoked, clients cannot use it anymore. (This cannot be undone.)')),
                ('expiry_date', models.DateTimeField(blank=True, help_text='Once API key expires, clients cannot use it anymore.', null=True, verbose_name='Expires')),
            ],
            options={
                'verbose_name': 'Tap API Key',
                'verbose_name_plural': 'Tap API Keys',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='TireuseBec',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_tireuse', models.CharField(help_text="Display name: e.g. 'Beer', 'Soft drink'", max_length=50, verbose_name='Tap name')),
                ('enabled', models.BooleanField(default=True, verbose_name='In service')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Notes')),
                ('reservoir_ml', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current volume in ml (decremented in real time).', max_digits=10, verbose_name='Remaining volume')),
                ('seuil_mini_ml', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Low threshold in ml (this volume is reserved).', max_digits=10, verbose_name='Minimum threshold')),
                ('appliquer_reserve', models.BooleanField(default=True, help_text='Apply reserve (stock - threshold).', verbose_name='Apply reserve')),
                ('debimetre', models.ForeignKey(blank=True, help_text='Associated flow meter (determines calibration factor).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tireuses', to='controlvanne.debimetre', verbose_name='Flow meter')),
                ('fut_actif', models.ForeignKey(blank=True, help_text='Product of type FUT currently on this tap.', limit_choices_to={'categorie_article': 'U'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tireuses_actives', to='BaseBillet.product', verbose_name='Active keg')),
                ('pairing_device', models.ForeignKey(blank=True, help_text='Raspberry Pi or ESP32 controlling this tap.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tireuses', to='discovery.pairingdevice', verbose_name='Pairing device')),
                ('point_de_vente', models.OneToOneField(blank=True, help_text='POS linked to this tap (auto-created or manually assigned).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tireuse', to='laboutik.pointdevente', verbose_name='Point of sale')),
            ],
            options={
                'verbose_name': 'Tap',
                'verbose_name_plural': 'Taps',
            },
        ),
        migrations.CreateModel(
            name='RfidSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(db_index=True, max_length=32, verbose_name='Card UID')),
                ('label_snapshot', models.CharField(blank=True, help_text='Copy of the card label at session start.', max_length=100, verbose_name='Card name')),
                ('authorized', models.BooleanField(default=False, verbose_name='Authorized')),
                ('liquid_label_snapshot', models.CharField(blank=True, help_text='Copy of the liquid name at session start.', max_length=100, verbose_name='Beverage name')),
                ('allowed_ml_session', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Maximum volume allowed for this session (ml).', max_digits=12, verbose_name='Allowed ml')),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Start')),
                ('ended_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='End')),
                ('volume_start_ml', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Volume start (ml)')),
                ('volume_end_ml', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Volume end (ml)')),
                ('volume_delta_ml', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Volume served (ml)')),
                ('dernier_volume_ml', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Last volume (ml)')),
                ('is_maintenance', models.BooleanField(default=False, verbose_name='Maintenance session')),
                ('is_calibration', models.BooleanField(default=False, verbose_name='Calibration session')),
                ('volume_reel_ml', models.DecimalField(blank=True, decimal_places=2, help_text='Volume physically measured in a graduated glass.', max_digits=10, null=True, verbose_name='Actual volume (ml)')),
                ('produit_maintenance_snapshot', models.CharField(blank=True, max_length=100, verbose_name='Cleaning product used')),
                ('last_message', models.TextField(blank=True, default='', verbose_name='Last message')),
                ('carte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfid_sessions', to='QrcodeCashless.cartecashless', verbose_name='NFC card')),
                ('carte_maintenance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='controlvanne.cartemaintenance', verbose_name='Maintenance card')),
                ('ligne_article', models.ForeignKey(blank=True, help_text='POS sale line created for this session.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfid_sessions', to='BaseBillet.lignearticle', verbose_name='Sale line')),
                ('tireuse_bec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='controlvanne.tireusebec', verbose_name='Tap')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='cartemaintenance',
            name='tireuses',
            field=models.ManyToManyField(blank=True, help_text='Leave empty for all taps.', related_name='cartes_maintenance', to='controlvanne.tireusebec', verbose_name='Authorized taps'),
        ),
        migrations.CreateModel(
            name='HistoriqueCarte',
            fields=[
            ],
            options={
                'verbose_name': 'Card history',
                'verbose_name_plural': 'Card history',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('controlvanne.rfidsession',),
        ),
        migrations.CreateModel(
            name='HistoriqueMaintenance',
            fields=[
            ],
            options={
                'verbose_name': 'Maintenance history',
                'verbose_name_plural': 'Maintenance history',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('controlvanne.rfidsession',),
        ),
        migrations.CreateModel(
            name='HistoriqueTireuse',
            fields=[
            ],
            options={
                'verbose_name': 'Tap history',
                'verbose_name_plural': 'Tap history',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('controlvanne.rfidsession',),
        ),
        migrations.CreateModel(
            name='SessionCalibration',
            fields=[
            ],
            options={
                'verbose_name': 'Calibration session',
                'verbose_name_plural': 'Calibration sessions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('controlvanne.rfidsession',),
        ),
    ]
