# Generated by Django 4.2.29 on 2026-04-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlvanne', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tireusebec',
            name='nom_tireuse',
            field=models.CharField(help_text="Display name: e.g. 'Beer', 'Soft drink'", max_length=50, unique=True, verbose_name='Tap name'),
        ),
    ]
