# Generated by Django 4.2.30 on 2026-09-26 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0228_alter_brevoconfig_last_log_and_more'),
        ('controlvanne', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tireusebec',
            name='fut_actif',
            field=models.ForeignKey(blank=True, help_text='Product of type FUT currently on this tap.', limit_choices_to={'categorie_article': 'U'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tireuses_actives', to='BaseBillet.futproduct', verbose_name='Active keg'),
        ),
    ]
