# Generated by Django 4.2.29 on 2026-04-09 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlvanne', '0002_nom_tireuse_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tireusebec',
            name='appliquer_reserve',
        ),
        migrations.RemoveField(
            model_name='tireusebec',
            name='seuil_mini_ml',
        ),
    ]
