# Generated by Django 4.2.30 on 2026-07-06 11:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlvanne', '0003_remove_seuil_mini_appliquer_reserve'),
    ]

    operations = [
        migrations.AddField(
            model_name='tireusebec',
            name='reservoir_illimite',
            field=models.BooleanField(default=True, help_text='If checked, the empty-keg check is bypassed (no volume tracking).', verbose_name='Unlimited reservoir'),
        ),
        migrations.AlterField(
            model_name='tireusebec',
            name='reservoir_ml',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current volume in ml (decremented in real time). Ignored if unlimited.', max_digits=10, verbose_name='Remaining volume'),
        ),
    ]
