# Generated by Django 4.2.30 on 2026-07-14 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboutik', '0002_stripelocation_remove_pointdevente_printer_terminal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('controlvanne', '0004_tireusebec_reservoir_illimite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tireusebec',
            name='pairing_device',
        ),
        migrations.AddField(
            model_name='tireuseapikey',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tireuse_api_key', to=settings.AUTH_USER_MODEL, verbose_name='Compte du terminal'),
        ),
        migrations.AddField(
            model_name='tireusebec',
            name='terminal',
            field=models.OneToOneField(blank=True, help_text='Le Raspberry Pi qui pilote cette tireuse, une fois appaire.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tireuse', to='laboutik.terminal', verbose_name='Terminal appaire'),
        ),
    ]
