# Generated by Django 4.2.30 on 2026-07-21 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboutik', '0005_remove_terminal_registration_code_and_more'),
        ('controlvanne', '0005_remove_tireusebec_pairing_device_tireuseapikey_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tireusebec',
            name='terminal',
            field=models.OneToOneField(blank=True, help_text='Le Raspberry Pi qui pilote cette tireuse.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tireuse', to='laboutik.terminal', verbose_name='Terminal (Raspberry Pi)'),
        ),
    ]
