# Generated by Django 3.2 on 2022-11-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RootConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuseau_horaire', models.CharField(choices=[('Indian/Reunion', 'Indian/Reunion'), ('Europe/Paris', 'Europe/Paris')], default='Indian/Reunion', max_length=50)),
                ('stripe_api_key', models.CharField(blank=True, max_length=110, null=True)),
                ('stripe_test_api_key', models.CharField(blank=True, max_length=110, null=True)),
                ('stripe_mode_test', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
