# Generated by Django 4.2.24 on 2025-10-26 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fedow_public', '0003_assetfedowpublic_archive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrowdConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nom du projet')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.URLField(blank=True, null=True, verbose_name='Image (URL)')),
                ('funding_goal', models.PositiveIntegerField(verbose_name='Objectif (centimes)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('funding_mode', models.CharField(choices=[('cascade', 'Contribution en cascade'), ('adaptative', 'Contribution adaptative')], default='adaptative', max_length=20)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='fedow_public.assetfedowpublic')),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField(verbose_name='Montant (centimes)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to=settings.AUTH_USER_MODEL)),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='crowds.initiative')),
            ],
        ),
    ]
