# Generated by Django 4.2.24 on 2025-10-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='budget_contributif',
            field=models.BooleanField(default=False, help_text="Permettez a votre communauté de proposer des actions qui s'inscrivent dans un budget contributif : https://movilab.org/wiki/Coremuneration_et_budget_contributif", verbose_name='Budget contributif'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='currency',
            field=models.CharField(default='€', help_text='Changez la valeur de la contribution : Comptez en €, monnaie locale, monnaie temps, bonbons ?', max_length=250, verbose_name='Valeur'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='direct_debit',
            field=models.BooleanField(default=False, help_text='Réclamer le paiement de la contribution financière en ligne. Cela redirigera la personne sur Stripe pour un paiement.', verbose_name='Paiement direct'),
        ),
    ]
