# Generated by Django 4.2.24 on 2025-10-31 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='currency',
            field=models.CharField(default='€', help_text='Changez la valeur de la contribution : Comptez en €, monnaie locale, monnaie temps, bonbons ?', max_length=250, verbose_name='Devise'),
        ),
    ]
