# Generated by Django 4.2.24 on 2025-10-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowds', '0002_initiative_budget_contributif_initiative_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowdconfig',
            name='active',
            field=models.BooleanField(default=True, help_text='Vous pouvez activer ou desactiver cette fonction pour la faire apparaitre dans le menu général.', verbose_name='Activer Crowds'),
        ),
        migrations.AlterField(
            model_name='crowdconfig',
            name='description',
            field=models.TextField(blank=True, default='Découvrez les projets à financer et les budgets contributifs'),
        ),
        migrations.AlterField(
            model_name='crowdconfig',
            name='title',
            field=models.CharField(blank=True, default='Contribuez', max_length=255, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='crowdconfig',
            name='vote_button_name',
            field=models.CharField(blank=True, default="Ça m'intérèsse !", max_length=255, verbose_name='Nom du bouton de vote'),
        ),
    ]
