# Generated by Django 4.2.24 on 2025-11-05 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crowds', '0002_alter_initiative_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowdconfig',
            name='name_contributions',
            field=models.CharField(blank=True, default='Contributions', help_text='Sera affiché en face de la somme et sur le detail', max_length=255, verbose_name="Mot pour 'Contributions'"),
        ),
        migrations.AddField(
            model_name='crowdconfig',
            name='name_funding_goal',
            field=models.CharField(blank=True, default='Objectif', help_text='Sera affiché en face de la somme', max_length=255, verbose_name="Mot pour 'Objectif'"),
        ),
        migrations.AddField(
            model_name='crowdconfig',
            name='name_participations',
            field=models.CharField(blank=True, default='Participations', help_text='Sera affiché en face de la somme et sur le detail', max_length=255, verbose_name="Mot pour 'Participations'"),
        ),
        migrations.AddField(
            model_name='initiative',
            name='adaptative_funding_goal_on_participation',
            field=models.BooleanField(default=False, help_text="Si activé, l'objectif à financer augmentera en fonction des demandes de participations au budget contributif validées.", verbose_name='Objectif lié aux demandes de participation'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='archived',
            field=models.BooleanField(default=False, help_text='Archived initiatives are not displayed in the main page.', verbose_name='Archived'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='contributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to=settings.AUTH_USER_MODEL),
        ),
    ]
