# Generated by Django 4.2.24 on 2025-11-26 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crowds', '0003_crowdconfig_name_contributions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crowdconfig',
            name='name_contributions',
        ),
        migrations.RemoveField(
            model_name='crowdconfig',
            name='name_funding_goal',
        ),
        migrations.RemoveField(
            model_name='initiative',
            name='funding_goal',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='requested_amount_cents',
        ),
        migrations.AddField(
            model_name='crowdconfig',
            name='name_funding',
            field=models.CharField(blank=True, default='Financement', help_text="C'est le nom par defaut que vous pouvez changer ici. Vous pouvez aussi le changer dans chaque initiative.", max_length=255, verbose_name="Mot pour 'Financement'"),
        ),
        migrations.AddField(
            model_name='crowdconfig',
            name='name_goal',
            field=models.CharField(blank=True, default='Objectif', help_text="C'est le nom par defaut que vous pouvez changer ici. Vous pouvez aussi le changer dans chaque initiative.", max_length=255, verbose_name="Mot pour 'Objectif'"),
        ),
        migrations.AddField(
            model_name='initiative',
            name='name_funding',
            field=models.CharField(blank=True, default='Financement', help_text="C'est le nom par defaut que vous pouvez changer ici uniquement pour cet initiative. Vous pouvez aussi le changer celui par default pour tous dans la configuration.", max_length=255, verbose_name="Mot pour 'Financement'"),
        ),
        migrations.AddField(
            model_name='initiative',
            name='name_goal',
            field=models.CharField(blank=True, default='Objectif', help_text="C'est le nom par defaut que vous pouvez changer ici uniquement pour cet initiative. Vous pouvez aussi le changer celui par default pour tous dans la configuration.", max_length=255, verbose_name="Mot pour 'Objectif'"),
        ),
        migrations.AddField(
            model_name='initiative',
            name='name_participations',
            field=models.CharField(blank=True, default='Participations', help_text="C'est le nom par defaut que vous pouvez changer ici uniquement pour cet initiative. Vous pouvez aussi le changer celui par default pour tous dans la configuration.", max_length=255, verbose_name="Mot pour 'Participations'"),
        ),
        migrations.AddField(
            model_name='initiative',
            name='vote',
            field=models.BooleanField(default=False, help_text='Les utilisateurs peuvent voter pour les initiatives qui leur plaisent.', verbose_name='Activer les votes'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='vote_button_name',
            field=models.CharField(blank=True, default="Ça m'intérèsse !", help_text="C'est le nom par defaut que vous pouvez changer ici uniquement pour cet initiative. Vous pouvez aussi le changer celui par default pour tous dans la configuration.", max_length=255, verbose_name='Nom du bouton de vote'),
        ),
        migrations.AddField(
            model_name='participation',
            name='amount',
            field=models.PositiveIntegerField(blank=True, help_text='Part du budget sollicité.', null=True),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='crowdconfig',
            name='name_participations',
            field=models.CharField(blank=True, default='Participations', help_text="C'est le nom par defaut que vous pouvez changer ici. Vous pouvez aussi le changer dans chaque initiative.", max_length=255, verbose_name="Mot pour 'Participations'"),
        ),
        migrations.AlterField(
            model_name='crowdconfig',
            name='vote_button_name',
            field=models.CharField(blank=True, default="Ça m'intérèsse !", help_text="C'est le nom par defaut que vous pouvez changer ici. Vous pouvez aussi le changer dans chaque initiative.", max_length=255, verbose_name='Nom du bouton de vote'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='state',
            field=models.CharField(choices=[('requested', 'Demande formulée'), ('rejected', 'Demande rejetée'), ('approved_admin', 'Demande validée par un·e admin'), ('completed_user', "Participation indiquée comme terminée par l'utilisateur·ice"), ('validated_admin', 'Participation validée par un·e admin')], default='requested', help_text="Statut de l'action (schema.org/ActionStatusType)", max_length=32),
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, verbose_name="Decrivez l'objectif à financer.")),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='Montant')),
                ('state', models.CharField(choices=[('requested', 'Proposition formulée'), ('rejected', 'Rejetée'), ('approved', 'Validée')], default='requested', max_length=32, verbose_name='Statut')),
                ('contributor', models.ForeignKey(help_text='Qui à porté la proposition', on_delete=django.db.models.deletion.PROTECT, related_name='budget_items_contributor', to=settings.AUTH_USER_MODEL, verbose_name='Qui porte')),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_items', to='crowds.initiative')),
                ('validator', models.ForeignKey(blank=True, help_text='Qui à validé la proposition', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_items_validator', to=settings.AUTH_USER_MODEL, verbose_name='Qui valide')),
            ],
        ),
    ]
