# Generated by Django 4.2.24 on 2025-11-23 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crowds', '0003_crowdconfig_name_contributions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='vote',
            field=models.BooleanField(default=False, help_text='Les utilisateurs peuvent voter pour les initiatives qui leur plaisent.', verbose_name='Activer les votes'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='requested_amount_cents',
            field=models.PositiveIntegerField(blank=True, help_text='Part du budget sollicité en centimes (schema.org/MonetaryAmount)', null=True),
        ),
        migrations.AlterField(
            model_name='participation',
            name='state',
            field=models.CharField(choices=[('requested', 'Demande formulée'), ('rejected', 'Demande rejetée'), ('approved_admin', 'Demande validée par un·e admin'), ('completed_user', "Participation indiquée comme terminée par l'utilisateur·ice"), ('validated_admin', 'Participation validée par un·e admin')], default='requested', help_text="Statut de l'action (schema.org/ActionStatusType)", max_length=32),
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, verbose_name="Decrivez l'objectif à financer.")),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant (décimal)')),
                ('state', models.CharField(choices=[('requested', 'Proposition formulée'), ('rejected', 'Rejetée'), ('approved', 'Validée')], default='requested', max_length=32, verbose_name='Statut')),
                ('contributor', models.ForeignKey(help_text='Qui à porté la proposition', on_delete=django.db.models.deletion.PROTECT, related_name='budget_items_contributor', to=settings.AUTH_USER_MODEL, verbose_name='Qui porte')),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_items', to='crowds.initiative')),
                ('validator', models.ForeignKey(blank=True, help_text='Qui à validé la proposition', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_items_validator', to=settings.AUTH_USER_MODEL, verbose_name='Qui valide')),
            ],
        ),
    ]
