# Generated by Django 4.2.27 on 2026-01-30 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0193_externalapikey_membership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crowds', '0004_remove_crowdconfig_name_contributions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowdconfig',
            name='contributor_covenant',
            field=models.URLField(blank=True, help_text='Si vide : https://movilab.org/wiki/Coremuneration_et_budget_contributif', null=True, verbose_name='Lien vers le code de contribution à valider à chaque participation'),
        ),
        migrations.AddField(
            model_name='crowdconfig',
            name='global_funding_button',
            field=models.BooleanField(default=False, verbose_name="Bouton de financement global sur la page d'accueil Crowds"),
        ),
        migrations.AddField(
            model_name='crowdconfig',
            name='global_funding_button_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Texte du bouton 'Je finance'"),
        ),
        migrations.AddField(
            model_name='crowdconfig',
            name='pro_bono_name',
            field=models.CharField(blank=True, help_text="Si vide : Pro-bono. C'est le nom par defaut que vous pouvez changer ici. Ex : Bénévolat, Mécénat de compétence...", max_length=255, verbose_name="Mot pour 'Pro-bono'"),
        ),
        migrations.CreateModel(
            name='GlobalFunding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('amount_funded', models.PositiveIntegerField(default=0, verbose_name='Montant du financement')),
                ('amount_to_be_included', models.PositiveIntegerField(default=0, verbose_name='Montant à répartir')),
                ('contributor_name', models.CharField(blank=True, help_text="Nom affiché de l'origine de la contribution", max_length=255, null=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name="Decrivez ce que vous attendez de la contribution, ou envoyez un messages sympa à l'équipe !")),
                ('ligne_article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BaseBillet.lignearticle', verbose_name='Ligne comptable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
        ),
    ]
