# Generated by Django 4.2.24 on 2025-11-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowds', '0004_initiative_vote_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crowdconfig',
            name='name_contributions',
        ),
        migrations.AddField(
            model_name='crowdconfig',
            name='name_funding',
            field=models.CharField(blank=True, default='Financement', help_text="C'est le nom par defaut que vous pouvez changer ici. Vous pouvez aussi le changer dans chaque initiative.", max_length=255, verbose_name="Mot pour 'Financement'"),
        ),
        migrations.AlterField(
            model_name='crowdconfig',
            name='name_funding_goal',
            field=models.CharField(blank=True, default='Objectif', help_text="C'est le nom par defaut que vous pouvez changer ici. Vous pouvez aussi le changer dans chaque initiative.", max_length=255, verbose_name="Mot pour 'Objectif'"),
        ),
        migrations.AlterField(
            model_name='crowdconfig',
            name='name_participations',
            field=models.CharField(blank=True, default='Participations', help_text="C'est le nom par defaut que vous pouvez changer ici. Vous pouvez aussi le changer dans chaque initiative.", max_length=255, verbose_name="Mot pour 'Participations'"),
        ),
        migrations.AlterField(
            model_name='crowdconfig',
            name='vote_button_name',
            field=models.CharField(blank=True, default="Ça m'intérèsse !", help_text="C'est le nom par defaut que vous pouvez changer ici. Vous pouvez aussi le changer dans chaque initiative.", max_length=255, verbose_name='Nom du bouton de vote'),
        ),
    ]
