# Generated by Django 4.2.24 on 2025-11-26 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowds', '0005_remove_crowdconfig_name_contributions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crowdconfig',
            old_name='name_funding_goal',
            new_name='name_goal',
        ),
    ]
