# Generated by Django 4.2.27 on 2026-02-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowds', '0005_crowdconfig_contributor_covenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='closed',
            field=models.BooleanField(default=False, help_text="Clôturer une initiative empêche toute modification mais elle reste visible avec le badge 'Clôturé'.", verbose_name='Clôturée'),
        ),
    ]
