# Generated by Django 4.2.24 on 2025-11-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowds', '0006_rename_name_funding_goal_crowdconfig_name_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='name_funding',
            field=models.CharField(blank=True, default='Financement', help_text="C'est le nom par defaut que vous pouvez changer ici uniquement pour cet initiative. Vous pouvez aussi le changer celui par default pour tous dans la configuration.", max_length=255, verbose_name="Mot pour 'Financement'"),
        ),
        migrations.AddField(
            model_name='initiative',
            name='name_goal',
            field=models.CharField(blank=True, default='Objectif', help_text="C'est le nom par defaut que vous pouvez changer ici uniquement pour cet initiative. Vous pouvez aussi le changer celui par default pour tous dans la configuration.", max_length=255, verbose_name="Mot pour 'Objectif'"),
        ),
        migrations.AddField(
            model_name='initiative',
            name='name_participations',
            field=models.CharField(blank=True, default='Participations', help_text="C'est le nom par defaut que vous pouvez changer ici uniquement pour cet initiative. Vous pouvez aussi le changer celui par default pour tous dans la configuration.", max_length=255, verbose_name="Mot pour 'Participations'"),
        ),
        migrations.AddField(
            model_name='initiative',
            name='vote_button_name',
            field=models.CharField(blank=True, default="Ça m'intérèsse !", help_text="C'est le nom par defaut que vous pouvez changer ici uniquement pour cet initiative. Vous pouvez aussi le changer celui par default pour tous dans la configuration.", max_length=255, verbose_name='Nom du bouton de vote'),
        ),
    ]
