# Generated by Django 4.2.27 on 2026-02-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowds', '0006_initiative_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowdconfig',
            name='active',
            field=models.BooleanField(default=True, help_text='Vous pouvez activer ou desactiver cette fonction pour la faire apparaitre dans le menu général.', verbose_name='Activer'),
        ),
    ]
