# Generated by Django 4.2.24 on 2025-11-26 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowds', '0007_initiative_name_funding_initiative_name_goal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initiative',
            name='funding_goal',
        ),
    ]
