# Generated by Django 4.2.28 on 2026-03-15 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseBillet', '0202_remove_price_adhesion_obligatoire_event_thematique_and_more'),
        ('crowds', '0007_alter_crowdconfig_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='ligne_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions_crowds', to='BaseBillet.lignearticle', verbose_name='Ligne comptable'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='paiement_stripe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions_crowds', to='BaseBillet.paiement_stripe', verbose_name='Paiement Stripe'),
        ),
    ]
