# Generated by Django 4.2.24 on 2025-11-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowds', '0008_remove_initiative_funding_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetitem',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='requested_amount_cents',
            field=models.PositiveIntegerField(blank=True, help_text='Part du budget sollicité.', null=True),
        ),
    ]
