# Generated by Django 4.2.30 on 2026-09-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowds', '0008_contribution_ligne_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowdconfig',
            name='description',
            field=models.TextField(blank=True, default='Découvrez les projets à financer et les budgets contributifs', verbose_name='Description'),
        ),
    ]
