# Generated by Django 4.2.24 on 2025-11-26 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowds', '0009_alter_budgetitem_amount_alter_contribution_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participation',
            old_name='requested_amount_cents',
            new_name='amount',
        ),
    ]
