# Generated by Django 4.2.27 on 2026-02-25 12:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customers', '0004_alter_client_categorie_alter_client_on_trial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PairingDevice',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Name of the device to pair, e.g. 'Cash register 1'", max_length=100, verbose_name='Device name')),
                ('pin_code', models.PositiveIntegerField(help_text='6-digit pairing code', unique=True, verbose_name='PIN code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('claimed_at', models.DateTimeField(blank=True, help_text='Set when a device claims this PIN', null=True, verbose_name='Claimed at')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairing_devices', to='Customers.client', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Pairing device',
                'verbose_name_plural': 'Pairing devices',
                'ordering': ['-created_at'],
            },
        ),
    ]
