# Generated by Django 4.2.27 on 2026-02-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairingdevice',
            name='pin_code',
            field=models.PositiveIntegerField(blank=True, help_text='6-digit pairing code, cleared after claim', null=True, unique=True, verbose_name='PIN code'),
        ),
    ]
