# Generated by Django 4.2.30 on 2026-04-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0002_alter_pairingdevice_pin_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairingdevice',
            name='terminal_role',
            field=models.CharField(choices=[('LB', 'LaBoutik POS'), ('TI', 'Connected tap'), ('KI', 'Kiosk / self-service')], default='LB', help_text='Type of hardware role being paired', max_length=2, verbose_name='Terminal role'),
        ),
    ]
