# Generated by Django 4.2.30 on 2026-07-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0003_pairingdevice_terminal_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairingdevice',
            name='cible_uuid',
            field=models.UUIDField(blank=True, help_text="Identifiant de l'objet que cet appairage doit rattacher (une tireuse). Vide apres l'appairage.", null=True, verbose_name='Objet a rattacher'),
        ),
    ]
