# Generated by Django 4.2.30 on 2026-07-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0004_pairingdevice_cible_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairingdevice',
            name='cible_uuid',
            field=models.UUIDField(blank=True, help_text="Identifiant de l'objet que cet appairage doit rattacher (une tireuse). Vide après l'appairage.", null=True, verbose_name='Objet à rattacher'),
        ),
    ]
