# Generated by Django 3.2 on 2022-01-31 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='categorie',
            field=models.CharField(choices=[('A', 'Artiste'), ('S', 'Salle de spectacle'), ('F', 'Festival'), ('T', 'Tourneur'), ('P', 'Producteur')], default='S', max_length=3, verbose_name='Categorie'),
        ),
    ]
