# Generated by Django 4.2.30 on 2026-04-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seocache',
            name='cache_type',
            field=models.CharField(choices=[('tenant_summary', 'Tenant summary (config, stats, domain)'), ('tenant_events', 'Published events for tenant'), ('tenant_memberships', 'Published memberships for tenant'), ('aggregate_events', 'Aggregated events for network (ROOT)'), ('aggregate_memberships', 'Aggregated memberships for network (ROOT)'), ('aggregate_lieux', 'Aggregated active venues (ROOT)'), ('sitemap_index', 'Cross-tenant sitemap index (ROOT)'), ('global_counts', 'Global counts: events, memberships, initiatives (ROOT)')], db_index=True, max_length=30, verbose_name='Cache type'),
        ),
    ]
