# Generated by Django 4.2.30 on 2026-07-03 10:16

from django.db import migrations, models


def supprimer_les_doublons_seocache(apps, schema_editor):
    """
    Supprime les doublons SEOCache avant de poser les contraintes uniques.
    / Removes duplicate SEOCache rows before adding the unique constraints.

    Pourquoi des doublons existent : unique_together ne protegeait pas les
    lignes tenant=None (PostgreSQL considere les NULL comme distincts), et
    deux rebuilds concurrents pouvaient donc creer la meme ligne d'agregat.
    On garde la ligne la plus recente (updated_at) de chaque groupe — c'est
    du cache, il se recalcule tout seul.
    / Why duplicates exist: unique_together did not protect tenant=None rows
    (PostgreSQL treats NULLs as distinct), so concurrent rebuilds could create
    the same aggregate row. We keep the most recent row of each group — it is
    a cache, it rebuilds itself.
    """
    SEOCache = apps.get_model("seo", "SEOCache")

    groupes_en_double = (
        SEOCache.objects.values("cache_type", "tenant_id")
        .annotate(nombre=models.Count("id"))
        .filter(nombre__gt=1)
    )

    for groupe in groupes_en_double:
        lignes_du_groupe = SEOCache.objects.filter(
            cache_type=groupe["cache_type"],
            tenant_id=groupe["tenant_id"],
        ).order_by("-updated_at")

        ligne_a_garder = lignes_du_groupe.first()
        nombre_supprime = 0
        for ligne in lignes_du_groupe.exclude(pk=ligne_a_garder.pk):
            ligne.delete()
            nombre_supprime += 1

        if nombre_supprime:
            print(
                f"  -> SEOCache {groupe['cache_type']} "
                f"(tenant={groupe['tenant_id']}) : "
                f"{nombre_supprime} doublon(s) supprime(s)"
            )


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0004_alter_seocache_cache_type'),
    ]

    operations = [
        # 1. Nettoyage des doublons existants (sinon AddConstraint echoue).
        # / 1. Clean existing duplicates (otherwise AddConstraint fails).
        migrations.RunPython(
            supprimer_les_doublons_seocache,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterUniqueTogether(
            name='seocache',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='seocache',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', False)), fields=('cache_type', 'tenant'), name='seo_cache_unique_type_par_tenant'),
        ),
        migrations.AddConstraint(
            model_name='seocache',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', True)), fields=('cache_type',), name='seo_cache_unique_type_global'),
        ),
    ]
