# Generated by Django 4.2.30 on 2026-10-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0005_dedoublonner_seocache'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seocache',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='seocache',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', False)), fields=('cache_type', 'tenant'), name='seo_cache_unique_type_par_tenant'),
        ),
        migrations.AddConstraint(
            model_name='seocache',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', True)), fields=('cache_type',), name='seo_cache_unique_type_global'),
        ),
    ]
