# Generated by Django 4.2.30 on 2026-05-14 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import onboard.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Customers', '0004_alter_client_categorie_alter_client_on_trial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, default=onboard.models._generate_invitation_code, max_length=40, unique=True, verbose_name='Invitation code')),
                ('email_invited', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Invited email (optional)')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Used at')),
                ('expires_at', models.DateTimeField(default=onboard.models._default_expires_at, verbose_name='Expires at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by_tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboard_invitations_sent', to='Customers.client', verbose_name='Invited by tenant')),
                ('invited_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboard_invitations_sent', to=settings.AUTH_USER_MODEL, verbose_name='Invited by user')),
            ],
            options={
                'verbose_name': 'Onboard invitation',
                'verbose_name_plural': 'Onboard invitations',
            },
        ),
    ]
