# Generated by Django 4.2.30 on 2026-09-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardinvitation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créée le'),
        ),
    ]
