FROM python:3.8-bullseye

## UPDATE
RUN apt-get update 
RUN apt-get upgrade -y
RUN apt install -y python3-pip

RUN pip install pip --upgrade

## PYTHON
RUN pip install django==3.2
# RUN pip install django-admin-sortable2==1.0.2
RUN pip install djangorestframework
# RUN pip install django-jet
RUN pip install requests
RUN pip install gunicorn
# RUN pip install django-admin-rangefilter
RUN pip install sentry-sdk
RUN pip install python-dateutil
RUN pip install django-solo
# RUN pip install admin-totals
RUN pip install django-tenants
RUN pip install markdown       # Markdown support for the browsable API.
# RUN pip install django-filter  # Filtering support
# RUN pip install djoser
RUN pip install djangorestframework_simplejwt
# RUN pip install django-allauth

## PYTHON FOR DEV
RUN pip install ipython
RUN pip install ipdb
# RUN pip install django_debug_toolbar
RUN pip install Werkzeug==2.0.3
RUN pip install django-extensions


## POSTGRES CLIENT
RUN pip install psycopg2-binary==2.8.6
RUN mkdir -p /usr/share/man/man1
RUN mkdir -p /usr/share/man/man7
RUN apt-get install -y --no-install-recommends postgresql-client


## LATER ?
# RUN pip install mailchimp3
# RUN apt install cron -y
# RUN apt install curl -y
RUN apt install borgbackup -y
# RUN pip install inotify
# RUN pip install django-silk
# RUN apt install openssh-client -y
# RUN pip install beautifulsoup4
RUN pip install Pillow
RUN pip install django-stdimage
# RUN pip install django-crispy-forms
# RUN pip install reportlab

# RUN pip install -U social-auth-app-django
# RUN pip install -U django-templated-mail

RUN pip install stripe


RUN apt install -y python3-cffi
RUN apt install -y python3-brotli
RUN apt install -y libpango-1.0-0
RUN apt install -y libpangoft2-1.0-0
RUN pip install django-weasyprint


RUN pip install celery
RUN pip install redis
RUN pip install tenant-schemas-celery

RUN pip install segno
RUN pip install python-barcode

RUN pip install django-cors-headers

RUN python -m pip install -U channels
RUN python -m pip install -U channels_redis

RUN pip install mailjet_rest
RUN pip install authlib

RUN pip install djangorestframework-api-key
RUN pip install flower

RUN apt-get -y clean

RUN python --version
RUN django-admin --version
RUN pip freeze

# docker build -t registry.3peaks.re/tibillet_ticket:2022-09-27 .
# docker push registry.3peaks.re/tibillet_ticket:2022-09-27
