# Generated by Django 4.2.30 on 2026-10-05 15:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laboutik', '0001_initial'),
        ('QrcodeCashless', '0021_portefeuille_ephemere_de_la_carte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borne',
            fields=[
            ],
            options={
                'verbose_name': 'Borne',
                'verbose_name_plural': 'Bornes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('laboutik.terminal',),
        ),
        migrations.CreateModel(
            name='ReglagesBorne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recharge_active', models.BooleanField(default=True, verbose_name='Recharge de carte active')),
                ('terminal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reglages_borne', to='laboutik.terminal', verbose_name='Borne')),
            ],
            options={
                'verbose_name': 'Réglages de la borne',
                'verbose_name_plural': 'Réglages des bornes',
            },
        ),
        migrations.CreateModel(
            name='PaymentsIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField(verbose_name='Montant')),
                ('payment_intent_stripe_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='Paiement intent stripe id')),
                ('reader_stripe_id', models.CharField(blank=True, max_length=21, null=True, verbose_name='Lecteur utilisé (Stripe)')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure')),
                ('status', models.CharField(choices=[('R', 'requires_payment_method'), ('P', 'in_progress'), ('A', 'Paiement autorisé, mais pas encore capturé'), ('S', 'Succes'), ('C', 'Canceled')], default='R', max_length=2, verbose_name='Status')),
                ('solde_avant_centimes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Solde avant recharge (centimes)')),
                ('carte_creditee_le', models.DateTimeField(blank=True, null=True, verbose_name='Carte créditée le')),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments_intents', to='QrcodeCashless.cartecashless', verbose_name='Carte cashless')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='laboutik.terminal', verbose_name='Borne')),
            ],
        ),
    ]
