# Generated by Django 4.2.30 on 2026-07-06 19:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StripeLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom')),
                ('stripe_id', models.CharField(blank=True, max_length=21, null=True, verbose_name='Stripe ID')),
                ('is_primary_location', models.BooleanField(default=False, verbose_name='Primary Asset Location')),
            ],
        ),
    ]
