# Generated by Django 4.2.30 on 2026-07-06 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kiosk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom')),
                ('registration_code', models.CharField(blank=True, max_length=200, null=True, verbose_name="Code d'enregistrement du lecteur")),
                ('stripe_id', models.CharField(blank=True, max_length=21, null=True, verbose_name='Stripe ID')),
                ('type', models.CharField(choices=[('W', 'bbpos_wisepos_e')], default='W', max_length=2, verbose_name='Type')),
                ('archived', models.BooleanField(default=False)),
                ('term_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminal', to=settings.AUTH_USER_MODEL, verbose_name='Borne (terminal appairé)')),
            ],
        ),
    ]
