# Generated by Django 4.2.30 on 2026-09-28 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboutik', '0006_icones_fontawesome_vers_material'),
        ('kiosk', '0002_verbose_name_fr'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsintent',
            name='solde_avant_centimes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Solde avant recharge (centimes)'),
        ),
        migrations.CreateModel(
            name='ReglagesBorne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recharge_active', models.BooleanField(default=True, verbose_name='Recharge de carte active')),
                ('terminal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reglages_borne', to='laboutik.terminal', verbose_name='Borne')),
            ],
            options={
                'verbose_name': 'Réglages de la borne',
                'verbose_name_plural': 'Réglages des bornes',
            },
        ),
    ]
