# Generated by Django 4.2.30 on 2026-07-06 21:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('QrcodeCashless', '0021_cartecashless_wallet_ephemere'),
        ('kiosk', '0002_terminal'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentsIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField()),
                ('payment_intent_stripe_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='Paiement intent stripe id')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('R', 'requires_payment_method'), ('P', 'in_progress'), ('A', 'Paiement autorisé, mais pas encore capturé'), ('S', 'Succes'), ('C', 'Canceled')], default='R', max_length=2, verbose_name='Status')),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments_intents', to='QrcodeCashless.cartecashless', verbose_name='Carte cashless')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kiosk.terminal', verbose_name='TPE')),
            ],
        ),
    ]
