# Generated by Django 4.2.30 on 2026-09-29 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboutik', '0006_icones_fontawesome_vers_material'),
        ('kiosk', '0003_refonte_ecrans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borne',
            fields=[
            ],
            options={
                'verbose_name': 'Borne',
                'verbose_name_plural': 'Bornes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('laboutik.terminal',),
        ),
    ]
