# Generated by Django 4.2.30 on 2026-07-09 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0003_paymentsintent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='terminal',
            options={'verbose_name': 'TPE Bancaire', 'verbose_name_plural': 'TPE Bancaires'},
        ),
    ]
