# Generated by Django 4.2.30 on 2026-09-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0004_borne'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsintent',
            name='carte_creditee_le',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Carte créditée le'),
        ),
    ]
