# Generated by Django 4.2.30 on 2026-07-14 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboutik', '0005_remove_terminal_registration_code_and_more'),
        ('kiosk', '0005_delete_stripelocation_alter_paymentsintent_terminal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsintent',
            name='reader_stripe_id',
            field=models.CharField(blank=True, max_length=21, null=True, verbose_name='Lecteur utilisé (Stripe)'),
        ),
        migrations.AlterField(
            model_name='paymentsintent',
            name='terminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='laboutik.terminal', verbose_name='Borne'),
        ),
    ]
